--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            837151129                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = 63.889400
datum1 = 60.318474
local datum2 = {field3 = 0x3C}
datum4 = "2"
datum5 = 31

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return nil
local func6 = function (a0, a1, a2, a3)
  v27, v29, v31, v33 = -21, -95.182139, 1, a0
  local v35, v37, v39 = 44, "5", "10"
  a3 = tostring(math.floor(a0))
  for i=5,19,3 do
      v27 = math.floor(a3 + 1) + math.floor(26.022337) or -(math.floor(a0))
  end
  if datum4 ~= "10" then
      a3 = a3
      v27 = math.floor(146.115800) or 34 + -(math.floor(138.793201))
      a0 = math.tan(v27) + -(math.pi)
  end
  a3 = a3
  return true ~= "id do cillum" == a1 == "eiusmod culpa" == a2 == "proident" == a3 == false == not false
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @return boolean
function func11(a0, a1, a2, a3)
  local v41, v43, v45, v47 = "reprehenderit irure in", "tempor in ea", a2, a0
  v49, v51, v53, v55 = a3, false, 20.255645, v41
  local cond57 = 9
  while cond57 < 30 do
      a3 = a3
      cond57 = cond57 + 2
  end
  v43 = "in commodo amet"
  if a3 == "ipsum sunt tempor" then
      a0 = true ~= not true ~= a1
  else
      v41 = "enim eu Duis"
      a2 = "10"
  end
  v41 = "exercitation nisi"
  return false ~= a0 ~= true == a1 == "voluptate do" ~= a2 ~= "Excepteur" ~= a3 ~= "sed reprehenderit qui eu" == v41 ~= not "officia fugiat laborum" ~= v43
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 int
-- @return nil
function datum2:m16(a0, a1, a2, ...)
  local v62, v64, v66 = "3", -32, datum5
  local v68, v70, v72, v74 = "1", v62, 37.251424, a0
  if a2 == -58 then
      v64 = a2 or -(math.floor(a1))
  end
  local cond76 = 7
  while cond76 < 0x19 do
      v64 = math.floor(185.793138) or 0x62 + - math.floor(6.118896e+01)
      v62 = tostring(math.floor(116.883568))
      a0 = false == not false
      cond76 = cond76 + 2
  end
  if datum1 == 55.392797 then
      v62 = "4"
      v64 = -16 or -58 - -(46)
      a2 = tonumber(v62) or tonumber(v62) + - -58
  end
  a0 = false == true ~= true == not false == false
  return a0 ~= false == false ~= "consequat incididunt" == v62 == not false
end

-- @param a0 boolean
-- @return float
function datum2:m20(a0, ...)
  local v77, v79, v81 = "velit et elit", "6", "magna cupidatat"
  local v83, v85, v87 = datum4, a0, datum0
  v79 = v79
  local cond89 = false
  while cond89 ~= false do
      v77 = "laboris officia magna labore"
      v79 = "2"
      cond89 = true
  end
  v77 = "amet incididunt"
  if a0 ~= false then
      v77 = "consequat"
      v79 = "5"
  else
      v79 = [[10]]
      v79 = "9"
  end
  for i=10,4,2 do
      v79 = tostring(37)
      a0 = true ~= [[ullamco
mollit
laboris]] ~= v79 == not "Ut aliquip elit" ~= v77
      v79 = "7"
  end
  return 37.744674 + 36.480420 - -(math.pi)
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 int
-- @return nil
function datum2:m22(a0, a1, a2, a3)
  v91, v93 = a2, false
  v95, v97, v99, v101 = a2, datum0, datum5, v91
  a0 = tostring(-91)
  local cond103 = true
  repeat
      a0 = "9"
      a1 = "enim dolore ex"
      v91 = "1"
      cond103 = false
  until cond103 ~= true
  if datum0 == -40.939387 then
      a1 = "nostrud ea"
  else
      v91 = "6"
  end
  local cond106 = true
  repeat
      v91 = "9"
      a1 = a1
      v91 = "4"
      cond106 = false
  until cond106 ~= true
  return "velit in sed" ~= a0 ~= "laboris Ut nostrud consectetur" ~= a1 ~= "cillum commodo aliquip" == a2 ~= true == "aliqua" == v91 ~= not false == v93
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func6_a0 = 92.037750
local func6_a1 = "6"
local func6_a2 = "qui dolore in"
local func6_a3 = "8"
local r_func6_0 = func6(func6_a0, func6_a1, func6_a2, func6_a3)
local func11_a0 = false
local func11_a1 = false
local func11_a2 = "3"
local func11_a3 = "do cillum"
local r_func11_0 = func11(func11_a0, func11_a1, func11_a2, func11_a3)
local m16_a0 = false
local m16_a1 = 0x1.20b8bc780f05ep+2
local m16_a2 = 30
local m16_vararg0 = true
local m16_vararg1 = 95.922248
local m16_vararg2 = false
local r_m16_0 = datum2:m16(m16_a0, m16_a1, m16_a2, m16_vararg0, m16_vararg1, m16_vararg2)
local m20_a0 = true
local m20_vararg0 = 55
local m20_vararg1 = "officia occaecat"
local r_m20_0 = datum2:m20(m20_a0, m20_vararg0, m20_vararg1)
local m22_a0 = "4"
local m22_a1 = [[nostrud
sunt]]
local m22_a2 = "3"
local m22_a3 = -19
local r_m22_0 = datum2:m22(m22_a0, m22_a1, m22_a2, m22_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = math.floor(datum0)
local res_datum1 = math.floor(datum1)
local res_datum2 = #(datum2)
local res_datum4 = math.floor(datum4 + 0)
local res_datum5 = datum5
local res_r_func6_0 = 1
local res_r_func11_0 = r_func11_0 and 0x1 or 0
local res_r_m16_0 = 1
local res_r_m20_0 = math.floor(r_m20_0)
local res_r_m22_0 = 0x1
RESULT = res_r_m22_0 - res_r_m20_0 - res_r_m16_0 + res_r_func11_0 + res_r_func6_0 - res_datum5 + res_datum4 - res_datum2 + res_datum1 + res_datum0
print(math.floor(RESULT))