--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            715831888                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
local datum0 = {field1 = false}
datum2 = 47.098027
local datum3 = true
datum4 = "2"
local datum5 = false
datum6 = "esse irure in"
local datum7 = false
datum8 = true
local datum9 = {field10 = true}
local datum11 = "ullamco Duis minim"

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 float
-- @return function
function func12(a0, a1, a2, a3)
  local v27, v29, v31 = datum2, [[3]], datum4
  local v33, v35, v37, v39 = datum4, -93, "8", datum7
  local cond41 = 3
  while cond41 <= 24 do
      v27 = math.tan(a0) + 97.134361 + -(math.pi)
      cond41 = cond41 + 2
  end
  v29 = tostring(10)
  for _, _ in ipairs(datum9) do
      a0 = 72.716097 + -(math.abs(a0))
  end
  if a0 > 7.316115 then
      a3 = math.sin(a0) - math.pi - -(4.725185e+01)
      v27 = math.cos(85.870593) + math.pi - -(8.904968)
  else
      v29 = tostring(math.floor(a0))
      a3 = 82.754417 - -(math.pi)
      a1 = "veniam aliquip elit dolore" == "sint deserunt mollit" ~= not a1
  end
  return nil
end

-- @param a0 string
-- @return function
function func17(a0)
  v43, v45, v47 = -19, 49, 28.651597
  local v49, v51, v53 = datum4, false, true
  v55, v57, v59 = "2", "4", datum2
  v45 = #("ea Excepteur est eiusmod") + math.floor(1.044806e+02) or - -86
  local cond61 = 125
  while cond61 > 0x3a do
      v45 = math.floor(v47) + -(-41)
      cond61 = cond61 - 3
  end
  local cond62 = 0x79
  repeat
      a0 = "6"
      v47 = math.cos(v43) + math.cos(v45) + -(0.591783)
      a0 = tostring(math.floor(v47))
      cond62 = cond62 - 2
  until cond62 >= 71
  return nil
end

-- @return string
function func19()
  local v63, v65 = datum4, datum6
  v67, v69, v71 = -44.435147, true, -0.861133
  v73, v75, v77, v79 = datum6, "non consectetur incididunt", 39.730634, true
  for i=5,16,0x3 do
      v65 = "laborum amet non Duis"
  end
  local cond82 = 1
  while cond82 < 35 do
      v65 = "dolore"
      v65 = "adipiscing cillum quis ad"
      v63 = v63
      cond82 = cond82 + 2
  end
  v65 = 60.343134
  if v67 == -73.631857 then
      v67 = math.pi - math.pi + -(math.sin(-23))
      v63 = [[3]]
  else
      v65 = [[non]]
      v67 = math.tan(-53) + 1.319956 - -(math.abs(v67))
      v63 = tostring(-35)
  end
  return v63
end

-- @param a0 string
-- @param a1 string
-- @return string
local func20 = function (a0, a1)
  v86, v88, v90, v92 = datum2, a0, a1, 45
  local v94, v96, v98 = 65.930501, 47, v86
  local cond100 = 1
  while cond100 <= 32 do
      v88 = "8"
      a0 = tostring(math.floor(v86))
      cond100 = cond100 + 3
  end
  local cond101 = 4
  while cond101 < 32 do
      a1 = "Excepteur sunt"
      a1 = "id proident velit"
      a0 = "10"
      cond101 = cond101 + 2
  end
  local cond103 = 2
  while cond103 <= 43 do
      v86 = math.abs(0x1.a221b175f3f1bp+5) + math.abs(-96) - -(5.058578e+01)
      a0 = tostring(-54)
      cond103 = cond103 + 3
  end
  return "id aute adipiscing"
end

-- @param a0 boolean
-- @return function
function datum9:m23(a0)
  local v104, v106, v108, v110 = -18.528936, datum4, "1", 0x1.35f361459e3fcp+4
  local v112, v114, v116 = datum11, datum6, datum4
  local v118, v120, v122 = datum11, datum2, datum4
  v108 = tostring(math.floor(v104))
  local cond124 = 0
  repeat
      v104 = math.sin(0x1.8a3c526d49ef7p+5) + math.pi + -(math.sin(v104))
      cond124 = cond124 + 0x2
  until cond124 <= 35
  v106 = "8"
  v108 = "5"
  return nil
end

-- @return string
function datum9:m25(...)
  v125, v127, v129, v131 = 72, 88.007804, datum4, datum7
  local v133, v135, v137, v139 = v125, v125, datum6, "2"
  if v125 ~= -100 then
      v125 = -17 + -76 + -(math.floor(183.021178))
  end
  v127 = 26.235576 - math.cos(19.994056) - -(6.642861e+01)
  for i=4,14,2 do
      v127 = 6.960872e+01 + -(0x1.042e2d02b19c4p+5)
  end
  v127 = math.tan(0x3b) - 6.864224 + -(math.sin(v127))
  for i, _ in ipairs(datum0) do
      v127 = math.pi + -(math.tan(v127))
      v127 = math.cos(0x21) + math.sin(v127) - -(math.pi)
      v127 = math.tan(66.907018) - -(math.pi)
  end
  local cond143 = true
  repeat
      v125 = -15 - -(math.floor(0x1.0e7ace360b6bcp+5))
      v125 = 49 + math.floor(v127) or -(-65)
      v125 = -24 or - v125
      cond143 = false
  until cond143 == false
  return tostring(v125)
end

-- @return function
local func26 = function ()
  v144, v146 = "2", -42.402591
  v148, v150, v152, v154 = 32, -70, 70.111291, false
  local v156, v158, v160, v162 = true, v146, 78, datum2
  if v146 > 0x1.3d521f69bc17cp+6 then
      v144 = "10"
  end
  local cond164 = true
  repeat
      v148 = v148 - math.floor(91.771221) or -(string.len("quis mollit pariatur mollit"))
      v146 = math.pi + -(math.abs(-90))
      v144 = tostring(math.floor(v146))
      cond164 = false
  until cond164 ~= true
  v148 = math.floor(v146) + math.floor(v146) or -(math.floor(83.441489))
  v146 = math.cos(v148) + -(81.874572)
  if v144 == "10" then
      v146 = math.cos(0x27) - math.abs(v146) - -(math.abs(73.407202))
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func12_a0 = 6.472538
local func12_a1 = true
local func12_a2 = 99.117378
local func12_a3 = 76.261193
local r_func12_0 = func12(func12_a0, func12_a1, func12_a2, func12_a3)
local func17_a0 = "7"
local r_func17_0 = func17(func17_a0)
local r_func19_0 = func19()
local func20_a0 = "9"
local func20_a1 = "consequat cupidatat"
local r_func20_0 = func20(func20_a0, func20_a1)
local m23_a0 = false
local r_m23_0 = datum9:m23(m23_a0)
local m25_vararg0 = -58
local m25_vararg1 = -22
local m25_vararg2 = "minim Lorem"
local r_m25_0 = datum9:m25(m25_vararg0, m25_vararg1, m25_vararg2)
local r_func26_0 = func26()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = datum3 and 1 or 0
local res_datum4 = tonumber(datum4)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = #(datum6)
local res_datum7 = datum7 and 0x1 or 0
local res_datum8 = datum8 and 1 or 0
local res_datum9 = #(datum9)
local res_datum11 = string.len(datum11)
local res_r_func12_0 = 1
local res_r_func17_0 = 0x1
local res_r_func19_0 = tonumber(r_func19_0)
local res_r_func20_0 = string.len(r_func20_0)
local res_r_m23_0 = 1
local res_r_m25_0 = tonumber(r_m25_0)
local res_r_func26_0 = 0x1
RESULT = res_r_func26_0 - res_r_m25_0 + res_r_m23_0 - res_r_func20_0 + res_r_func19_0 - res_r_func17_0 - res_r_func12_0 - res_datum11 + res_datum9 + res_datum8 - res_datum7 + res_datum6 + res_datum5 - res_datum4 + res_datum3 + res_datum2 - res_datum0
print(math.floor(RESULT))