--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            718036104                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = {field1 = "occaecat voluptate ullamco Lorem"}
local datum2 = -74
datum3 = {field4 = true}
datum5 = true
local datum6 = {field7 = 84}
local datum8 = {field9 = 199.339805}
local datum10 = {field11 = -98}
datum12 = -84
datum13 = "eu Excepteur"
datum14 = {field15 = 71.043622}

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @return float
function func16(a0)
  v40, v42, v44 = datum5, "ex", 27.066627
  v46, v48, v50 = datum2, -18.976448, "4"
  v52, v54, v56 = false, -77, -84
  if v42 ~= "id pariatur do" then
      a0 = "9"
      v40 = true == true ~= not true
      v40 = "in aute in" ~= a0 == false == true ~= not false
  end
  local cond58 = 102
  while cond58 > 61 do
      v40 = v40 ~= false ~= not false
      a0 = tostring(math.floor(v44))
      cond58 = cond58 - 3
  end
  v42 = "esse dolore Duis"
  local cond59 = 4
  while cond59 <= 29 do
      v42 = "sunt aute amet"
      v40 = false == not "aute cupidatat" == v42
      v40 = v40 ~= not false ~= false
      cond59 = cond59 + 1
  end
  return math.pi - math.pi + 41.680456 + -(math.sin(v44))
end

-- @param a0 string
-- @param a1 string
-- @return table
function datum0:m18(a0, a1)
  local v61, v63, v65 = 99, "reprehenderit", 6
  v67, v69, v71 = datum2, datum2, true
  v73, v75 = -5.770003e+01, v61
  v65 = #("ullamco Ut") + -(math.floor(0x1.035619106e38fp+7))
  for _, v in pairs(datum6) do
      a0 = "2"
      v65 = -93 + 89 - -(math.floor(0x1.0605d38d87b9ep+6))
      a0 = tostring(-53)
  end
  v65 = -72 + v65 or - string.len("in reprehenderit ut")
  v63 = [[est
Excepteur
aliquip]]
  a0 = "8"
  a0 = a1
  return {t79 = a0}
end

-- @param a0 int
-- @return float
local func21 = function (a0)
  v81, v83 = datum12, 54.315803
  local v85, v87, v89, v91 = 0x1.2ea9b6a25f01p+4, datum2, 12.947588, -39
  if a0 == -26 then
      v83 = math.tan(v83) - math.tan(a0) - -(math.tan(v83))
      v81 = -76 + 8 or -(math.floor(v83))
      a0 = math.floor(17.230121) or -47 or -(math.floor(137.745725))
  end
  for i, v in pairs(datum10) do
      v81 = #("incididunt id nisi dolor") + #("id enim") or -(60)
  end
  if v81 == 32 then
      a0 = string.len("dolore amet in in") or -(-99)
      a0 = v81 or 53 + -(94)
  else
      a0 = a0 or - 0x3f
      v83 = math.tan(-85) + -(math.sin(62))
  end
  v83 = math.tan(a0) - -(math.cos(a0))
  if datum8 ~= {} then
      a0 = -2 + -(63)
  else
      a0 = math.floor(v83) + math.floor(193.246202) or -(v81)
  end
  for i=20,5 do
      a0 = 64 or -(9)
      v83 = math.pi + -(math.sin(v81))
      a0 = v81 - - 48
  end
  return math.abs(a0) - math.abs(v81) - -(math.abs(v83))
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 int
-- @param a3 boolean
-- @return string
function datum3:m23(a0, a1, a2, a3)
  local v96, v98, v100, v102 = a2, 43.600274, -26, 97
  v104, v106 = true, 27.991648
  a0 = "mollit id" == "anim commodo ea" ~= false ~= not true
  for _, v in pairs(datum6) do
      v98 = math.tan(v98) + math.tan(v96) + -(math.sin(-60))
      a3 = false == true == not true
  end
  for i=18,4 do
      v96 = math.floor(171.723203) + math.floor(112.803272) - -(math.floor(1.723518e+02))
  end
  a3 = false == not false
  local cond110 = false
  repeat
      v96 = string.len("nisi veniam") or -(0)
      cond110 = true
  until cond110 ~= false
  return "3"
end

-- @return string
function datum8:m28()
  v111, v113, v115 = -32.122748, 30, 75.152882
  local v117, v119, v121, v123 = 0x1.6cd82f7891cb4p+4, "10", [[non
in
irure
voluptate]], "4"
  local v125, v127 = 33, datum13
  if v115 < 81.707775 then
      v111 = math.tan(v113) + math.cos(v115) + -(math.pi)
      v115 = math.cos(71.231073) + -(46.227256)
      v113 = 39 + 0x62 + - math.floor(v115)
  else
      v113 = math.floor(159.641786) + - -28
  end
  v115 = math.sin(v111) - math.cos(v113) + -(math.cos(v115))
  v111 = math.sin(0) - 10.084069 + -(math.pi)
  if datum5 == true then
      v111 = math.pi - math.abs(55.509372) - -(93.122983)
  else
      v113 = 74 + math.floor(60.936196) or -(math.floor(v115))
  end
  v113 = #("eu sed") + -(-77)
  v111 = math.tan(v113) - math.tan(v115) - -(math.tan(141.343409))
  return v111
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 string
-- @param a4 string
-- @return function
function func29(a0, a1, a2, a3, a4)
  local v130, v132 = 90, datum12
  local v134, v136, v138, v140 = "8", datum12, "8", "2"
  if v132 ~= 93 then
      a4 = tostring(math.floor(1.510221e+01))
      v130 = -76 + tonumber(a3) or -(#("do ut"))
      a3 = tostring(math.floor(107.436357))
  else
      a1 = false == not true
      a2 = math.pi - math.pi + -(52.903695)
  end
  local cond142 = false
  while cond142 == true do
      a2 = 14.493360 + math.tan(0) - -(math.tan(3))
      a0 = math.pi + -(math.pi)
      v132 = -93 - -(0x38)
      cond142 = true
  end
  v132 = 65 - 0x5e - - tonumber(a4)
  return nil
end

-- @param a0 int
-- @param a1 string
-- @param a2 string
-- @return float
function datum14:m35(a0, a1, a2)
  local v143, v145, v147 = a0, "incididunt qui qui", false
  v149, v151, v153 = "in nisi", true, -44.569609
  local cond155 = 111
  repeat
      v143 = -71 + -(-35)
      v143 = -74 or -(#(a1))
      a2 = [[consequat
occaecat]]
      cond155 = cond155 - 1
  until cond155 >= 50
  v145 = "incididunt et amet nulla"
  if datum10 == {} then
      v145 = "velit aliquip nisi mollit"
      v145 = "dolor minim deserunt"
      a2 = a1
  else
      a0 = 14 or math.floor(11.849018) + -(#([[ad
Ut]]))
      a0 = 20 + #("non") or -(5)
  end
  for i, _ in ipairs(datum0) do
      a1 = "Ut ut dolor"
  end
  return math.abs(a0) - 12.789929 - 0x1.f2421ea748ba4p+5 + math.tan(v143) - -(math.pi)
end

-- @return table
function datum3:m39()
  v163, v165, v167 = true, "amet in", -27.010339
  v169, v171, v173, v175 = "tempor enim", datum5, v163, "9"
  v177, v179, v181, v183 = "2", 15.944186, 95, -29.089714
  v167 = math.abs(-46) - 76.740419 + -(34.309078)
  for _, _ in pairs(datum8) do
      v165 = "Excepteur est eu"
  end
  if v165 ~= "in sunt sint" then
      v165 = "pariatur elit ullamco"
  end
  if v165 ~= "mollit deserunt eiusmod Lorem" then
      v163 = false == false ~= not true ~= v163
      v167 = math.pi + 38.806174 - -(math.tan(1))
  else
      v167 = math.pi - -(math.abs(0x1.c6f3c753c43c5p+6))
  end
  for i=1,0xb,0x2 do
      v165 = "voluptate"
      v163 = true ~= not "qui non" ~= "ex ut labore sit"
      v163 = false ~= not "dolore pariatur sit" ~= v165
  end
  v167 = math.sin(v167) - -(69.684698)
  return {3}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func16_a0 = "10"
local r_func16_0 = func16(func16_a0)
local m18_a0 = "6"
local m18_a1 = "1"
local r_m18_0 = datum0:m18(m18_a0, m18_a1)
local func21_a0 = -82
local r_func21_0 = func21(func21_a0)
local m23_a0 = true
local m23_a1 = false
local m23_a2 = 14
local m23_a3 = true
local r_m23_0 = datum3:m23(m23_a0, m23_a1, m23_a2, m23_a3)
local r_m28_0 = datum8:m28()
local func29_a0 = 22.689751
local func29_a1 = true
local func29_a2 = 42.750375
local func29_a3 = "6"
local func29_a4 = "10"
local r_func29_0 = func29(func29_a0, func29_a1, func29_a2, func29_a3, func29_a4)
local m35_a0 = -60
local m35_a1 = "reprehenderit ad commodo"
local m35_a2 = "et ad fugiat reprehenderit"
local r_m35_0 = datum14:m35(m35_a0, m35_a1, m35_a2)
local r_m39_0 = datum3:m39()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = datum2
local res_datum3 = #(datum3)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = #(datum6)
local res_datum8 = #(datum8)
local res_datum10 = #(datum10)
local res_datum12 = datum12
local res_datum13 = #(datum13)
local res_datum14 = ms.table_to_int(datum14)
local res_r_func16_0 = math.floor(r_func16_0)
local res_r_m18_0 = #(r_m18_0)
local res_r_func21_0 = math.floor(r_func21_0)
local res_r_m23_0 = tonumber(r_m23_0)
local res_r_m28_0 = string.len(r_m28_0)
local res_r_func29_0 = 1
local res_r_m35_0 = math.floor(r_m35_0)
local res_r_m39_0 = #(r_m39_0)
RESULT = res_r_m39_0 - res_r_m35_0 - res_r_func29_0 + res_r_m28_0 + res_r_m23_0 - res_r_func21_0 - res_r_m18_0 + res_r_func16_0 + res_datum14 - res_datum13 + res_datum12 - res_datum10 + res_datum8 + res_datum6 + res_datum5 - res_datum3 + res_datum2 + res_datum0
print(math.floor(RESULT))