--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:           1015938308                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  9 statements)         --
--------------------------------------------------------
datum0 = {field1 = 1.536697e+02}
datum2 = {field3 = "incididunt qui"}
datum4 = {field5 = true}
local datum6 = 75.391990
local datum7 = {field8 = false}
datum9 = 40.641260
local datum10 = true
local datum11 = {field12 = true}
datum13 = {field14 = 36.509347}

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 int
-- @param a2 string
-- @param a3 string
-- @return string
function func15(a0, a1, a2, a3, ...)
  local v35, v37, v39 = a1, a1, 0
  v41, v43 = "2", false
  v45, v47 = true, a3
  for i=16,0,0x3 do
      a3 = tostring(26)
  end
  local cond49 = false
  while cond49 ~= false do
      v37 = v35 - -(math.floor(a0))
      cond49 = true
  end
  local cond50 = 10
  while cond50 <= 0x30 do
      a0 = math.sin(v35) - -(math.sin(v35))
      cond50 = cond50 + 0x2
  end
  v37 = 65 + - -57
  return "commodo mollit sunt sint"
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 boolean
-- @return string
function datum4:m20(a0, a1, a2, a3)
  local v52, v54, v56 = a3, a1, a3
  local v58, v60, v62, v64 = a3, "aute sunt", false, "2"
  local cond66 = true
  while cond66 == false do
      a3 = "consectetur quis Lorem" == [[labore
nisi
sint]] ~= true == not false
      v54 = "4"
      a3 = true ~= false == "sed tempor ad laborum" ~= "irure qui dolor" ~= not a3
      cond66 = false
  end
  local cond67 = false
  while cond67 == true do
      v54 = tostring(-84)
      v52 = "do" == a2 ~= "magna" == a0 == not true
      cond67 = true
  end
  local cond68 = 0
  repeat
      a1 = "8"
      v52 = "sint veniam in" ~= "velit aliquip cillum consequat" ~= not false
      cond68 = cond68 + 3
  until cond68 < 32
  return "1"
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @return float
function func25(a0, a1, a2)
  v69, v71, v73, v75 = 10, a2, 52.209863, -45
  local v77, v79, v81, v83 = a0, a2, a1, 35
  v69 = -8 + -33 or -(string.len(v71))
  a0 = "Duis" == "sed sunt" ~= not false
  if a1 ~= "7" then
      a2 = "anim amet sint"
      a2 = "officia sunt"
      a2 = a2
  else
      v69 = -52 + -10 + -(v69)
  end
  local cond87 = 9
  while cond87 < 0x27 do
      v69 = -49 or - string.len("consequat qui")
      v71 = 65.516645
      v69 = math.floor(174.582142) or - math.floor(22.619420)
      cond87 = cond87 + 2
  end
  return 20.657522 - 27.920331 + math.pi + math.cos(v69) - -(math.pi)
end

-- @param a0 boolean
-- @param a1 string
-- @return function
local func29 = function (a0, a1)
  local v88, v90 = 17, -11.863934
  local v92, v94, v96 = -82, -63, datum6
  for i=17,0,2 do
      a0 = false ~= a0 == not "Lorem Duis elit anim" == "dolore"
  end
  a1 = "1"
  for _, _ in ipairs(datum0) do
      v90 = math.pi - math.pi - -(math.sin(v90))
  end
  if v88 >= 0x18 then
      a1 = tostring(0x30)
  end
  v88 = string.len("nisi Ut magna") + 49 + - 0x44
  local cond99 = true
  while cond99 == false do
      a1 = "8"
      v90 = math.pi - math.pi + -(math.pi)
      cond99 = false
  end
  return nil
end

-- @return string
function datum2:m32()
  v100, v102 = -75, 99
  v104, v106 = "minim incididunt dolore est", "2"
  v100 = string.len("eu consequat cupidatat") or - 55
  v100 = v102 + -(v102)
  if v100 < -96 then
      v100 = #("laboris occaecat do") - 34 or -(60)
      v102 = v100 or math.floor(99.271653) or - math.floor(112.499309)
  end
  local cond108 = true
  while cond108 == false do
      v100 = 59 or 0x19 + -(42)
      cond108 = false
  end
  return "deserunt voluptate aute"
end

-- @param a0 string
-- @return string
function datum7:m33(a0)
  local v110, v112, v114 = datum9, [[6]], datum10
  v116, v118, v120, v122 = "officia labore ea", "8", [[cupidatat
Lorem
voluptate
dolor]], 53
  local v124, v126 = false, "dolor consectetur fugiat"
  for i=13,5 do
      a0 = a0
      a0 = "elit fugiat"
  end
  for _, v in ipairs(datum13) do
      v112 = [[10]]
      v114 = "id tempor" ~= "deserunt pariatur" == true == not "aute magna cupidatat" == "non commodo"
      v112 = "10"
  end
  local cond131 = true
  repeat
      v112 = tostring(-3)
      cond131 = false
  until cond131 == false
  if a0 == "est ea fugiat" then
      a0 = v110
      v110 = math.tan(v110) + math.abs(-33) - -(math.pi)
      v114 = "labore qui id" ~= "reprehenderit tempor" ~= true == true ~= not true ~= false
  end
  v114 = false == "dolore" ~= v112 ~= not true
  return "3"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func15_a0 = 0x1.3449e9199fc87p+6
local func15_a1 = 3
local func15_a2 = "9"
local func15_a3 = "3"
local func15_vararg0 = 81.719857
local r_func15_0 = func15(func15_a0, func15_a1, func15_a2, func15_a3, func15_vararg0)
local m20_a0 = "pariatur"
local m20_a1 = "3"
local m20_a2 = "5"
local m20_a3 = false
local r_m20_0 = datum4:m20(m20_a0, m20_a1, m20_a2, m20_a3)
local func25_a0 = false
local func25_a1 = "5"
local func25_a2 = [[anim
dolore]]
local r_func25_0 = func25(func25_a0, func25_a1, func25_a2)
local func29_a0 = true
local func29_a1 = "5"
local r_func29_0 = func29(func29_a0, func29_a1)
local r_m32_0 = datum2:m32()
local m33_a0 = "exercitation eiusmod"
local r_m33_0 = datum7:m33(m33_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = math.floor(datum9)
local res_datum10 = datum10 and 1 or 0
local res_datum11 = ms.table_to_int(datum11)
local res_datum13 = #(datum13)
local res_r_func15_0 = #(r_func15_0)
local res_r_m20_0 = tonumber(r_m20_0)
local res_r_func25_0 = math.floor(r_func25_0)
local res_r_func29_0 = 1
local res_r_m32_0 = string.len(r_m32_0)
local res_r_m33_0 = tonumber(r_m33_0)
RESULT = res_r_m33_0 + res_r_m32_0 - res_r_func29_0 + res_r_func25_0 - res_r_m20_0 - res_r_func15_0 - res_datum13 + res_datum11 - res_datum10 - res_datum9 - res_datum7 - res_datum6 + res_datum4 + res_datum2 - res_datum0
print(math.floor(RESULT))