--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            463121809                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = "ullamco"
local datum1 = "mollit enim"
local datum2 = {field3 = true}
datum4 = {field5 = -26}
datum6 = {field7 = -32}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @return string
function datum2:m8(a0, a1, a2)
  local v19, v21, v23 = -30.278510, 6.128440e+01, false
  v25, v27, v29, v31 = 98, a2, 69.098310, -69
  v33, v35, v37 = "2", -4.218013, false
  for i, v in pairs(datum2) do
      a1 = tostring(math.floor(v21))
      v23 = v23 ~= not "dolore in" ~= a0
  end
  if a0 ~= "5" then
      a0 = [[1]]
  else
      a1 = "10"
  end
  a2 = true == not true ~= a2
  v23 = true ~= false ~= "in" ~= "labore sint enim ea" == not false
  a1 = "3"
  return "irure Excepteur ea exercitation"
end

-- @param a0 string
-- @return string
function func12(a0)
  v43, v45, v47, v49 = a0, a0, -90, true
  v51, v53, v55, v57 = 86, -92.354091, "1", datum1
  local cond59 = false
  while cond59 == true do
      v43 = "10"
      cond59 = true
  end
  local cond60 = 0
  repeat
      a0 = tostring(math.floor(52.022543))
      v45 = v43
      cond60 = cond60 + 2
  until cond60 <= 0x31
  return "culpa fugiat ut est"
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @return nil
function func14(a0, a1, a2)
  local v61, v63 = a1, [[5]]
  local v65, v67 = -46.423517, 38
  local v69, v71 = "10", [[1]]
  if v61 == true then
      v63 = tostring(0x28)
      a2 = 39.309942 - math.pi - -(math.pi)
      v63 = tostring(83)
  else
      v63 = tostring(math.floor(134.622452))
  end
  v61 = "laborum sunt et" ~= "reprehenderit" ~= false ~= not false
  local cond73 = 0x6f
  repeat
      v63 = "5"
      v61 = "mollit cillum consectetur" ~= "aliqua cupidatat nulla amet" == not false == true
      cond73 = cond73 - 3
  until cond73 >= 61
  return true == false == a1 ~= false == false ~= v61 == "amet" ~= v63 ~= not true
end

-- @return function
local func18 = function ()
  v74, v76 = -2.730959, "aliqua laborum"
  v78, v80 = datum1, true
  if v74 == 0x1.95722e2d7579p+3 then
      v74 = math.pi - math.sin(-48) - -(math.pi)
  else
      v76 = v74
  end
  if datum4 ~= {} then
      v76 = "ipsum adipiscing"
  else
      v74 = math.sin(114.566744) + -(math.cos(90))
  end
  if datum6 == {} then
      v74 = math.abs(11) + math.abs(v74) + -(math.abs(91.926651))
  else
      v74 = math.tan(-81) - -(math.pi)
      v76 = "est"
      v76 = "mollit pariatur cupidatat exercitation"
  end
  v76 = "anim nulla"
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m8_a0 = "2"
local m8_a1 = "7"
local m8_a2 = true
local r_m8_0 = datum2:m8(m8_a0, m8_a1, m8_a2)
local func12_a0 = "5"
local r_func12_0 = func12(func12_a0)
local func14_a0 = 52.353477
local func14_a1 = false
local func14_a2 = 97.209218
local r_func14_0 = func14(func14_a0, func14_a1, func14_a2)
local r_func18_0 = func18()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = string.len(datum1)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = #(datum6)
local res_r_m8_0 = #(r_m8_0)
local res_r_func12_0 = #(r_func12_0)
local res_r_func14_0 = 0x1
local res_r_func18_0 = 1
RESULT = res_r_func18_0 + res_r_func14_0 - res_r_func12_0 - res_r_m8_0 + res_datum6 + res_datum4 - res_datum2 + res_datum1 + res_datum0
print(math.floor(RESULT))