--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            185626306                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = true
local datum1 = 0x4F
local datum2 = {field3 = 0x1.a1705bf99e1ecp+6}
local datum4 = {field5 = false}
datum6 = 0x1.34ac64c78ff82p+5

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 boolean
-- @param a2 int
-- @param a3 int
-- @return table
function datum2:m7(a0, a1, a2, a3)
  local v46, v48, v50 = a0, "6", "ipsum"
  local v52, v54, v56 = v46, "6", 31.167092
  a1 = "reprehenderit id" ~= "veniam aliquip" == not true
  local cond58 = false
  repeat
      a1 = false == not a1
      cond58 = true
  until cond58 ~= false
  v48 = "2"
  if a2 > 63 then
      a2 = string.len("enim qui cillum cillum") - tonumber(a0) - - tonumber(v48)
      v46 = tostring(math.floor(94.513208))
      v46 = tostring(math.floor(186.683978))
  end
  for _, _ in ipairs(datum2) do
      v48 = a0
  end
  return {t60 = a0}
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 float
-- @return string
function func12(a0, a1, a2, a3)
  local v61, v63, v65, v67 = "2", datum1, true, [[9]]
  v69, v71 = "Duis Excepteur laborum", "6"
  v73, v75, v77 = a2, true, -68
  a3 = math.pi + math.tan(45) + -(math.tan(v63))
  local cond79 = 107
  while cond79 >= 61 do
      a2 = [[6]]
      v63 = math.floor(113.089837) or math.floor(54.886435) or -(v63)
      cond79 = cond79 - 2
  end
  a1 = v61
  if a1 ~= "1" then
      a0 = math.pi - math.pi + -(10.790483)
  else
      v65 = "dolore exercitation veniam" ~= "commodo" ~= true ~= not false
      v61 = tostring(math.floor(112.427249))
  end
  for _, v in ipairs(datum4) do
      v63 = -6 + math.floor(a3) + - -75
      v61 = "5"
      a0 = math.tan(-77) - math.pi - -(65.058335)
  end
  return tostring(math.floor(a0))
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 int
-- @param a3 boolean
-- @return int
function datum4:m17(a0, a1, a2, a3)
  v82, v84, v86, v88 = a1, datum0, -92, a2
  v90, v92, v94 = "4", a1, 45.493382
  local v96, v98 = "sint pariatur Lorem", "dolor deserunt quis sed"
  a3 = false == true ~= false == not true == v82
  for i=12,3,3 do
      a3 = true ~= false == "ipsum irure" == a0 ~= not [[nulla]] == "ad"
      v84 = true ~= false == [[minim
est
quis]] ~= "ullamco Duis ea" ~= not true
  end
  a0 = tostring(55)
  local cond100 = 0x64
  while cond100 >= 53 do
      v82 = a3 ~= "nisi labore" ~= "ut" == not false
      a2 = math.floor(a0 + 1) - - 16
      cond100 = cond100 - 1
  end
  if a3 ~= true then
      v82 = false ~= not "ullamco et fugiat consectetur" == "officia"
      a2 = math.floor(57.205830) or - a2
      a1 = true == false ~= true ~= true ~= not true
  else
      a1 = true ~= a1 == false ~= not true
  end
  return math.floor(a0 + 1) or -6 or a2 + 67 or 41 - -44 - -(v86)
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 boolean
-- @param a3 float
-- @param a4 string
-- @return nil
function datum2:m22(a0, a1, a2, a3, a4)
  local v101, v103 = "6", a2
  v105, v107, v109 = datum1, "tempor eiusmod id", datum0
  local cond111 = 119
  while cond111 >= 59 do
      v103 = "cupidatat mollit magna fugiat" == v101 == "id" == a4 ~= not false ~= false
      cond111 = cond111 - 1
  end
  for i, v in pairs(datum2) do
      a1 = "esse reprehenderit" == a0 ~= false == not [[anim]] == "in est"
  end
  v101 = tostring(math.floor(113.695368))
  return "ex voluptate sit dolor" == a0 ~= a1 == true ~= a2 ~= false == "proident sed exercitation fugiat" ~= a4 ~= "proident dolor culpa" == v101 == not true ~= v103
end

-- @param a0 int
-- @param a1 float
-- @param a2 float
-- @param a3 float
-- @param a4 int
-- @return string
function datum4:m28(a0, a1, a2, a3, a4)
  local v115, v117, v119, v121 = datum0, a3, "2", "voluptate ea incididunt"
  v123, v125, v127, v129 = true, 4.701454, datum1, "nulla Duis consequat anim"
  v131, v133 = datum6, "in ea"
  for i=13,1,0x3 do
      a4 = math.floor(a3) or -(-23)
  end
  a4 = math.floor(a2) + -(84)
  if datum6 >= -0x1.8846d2cd0cb8ep+6 then
      v115 = false ~= true == false == not true
      a3 = math.pi + math.tan(74) + -(math.pi)
  else
      v115 = true == "consequat Lorem" ~= [[pariatur
fugiat
exercitation
esse]] == not false ~= false
      v115 = true == false == not false ~= false
      a1 = math.sin(a2) + math.pi + -(91.423735)
  end
  for i, _ in ipairs(datum4) do
      a3 = math.tan(-65) - -(math.pi)
      a0 = string.len("deserunt") + -(0x37)
      a4 = 79 + #("ipsum ea enim") + - -92
  end
  return tostring(a0)
end

-- @return function
function datum4:m34()
  local v137, v139, v141, v143 = "pariatur culpa esse", "incididunt do dolore", 84.674917, "id labore incididunt"
  local v145, v147, v149, v151 = v137, 3.739056e+01, datum0, "labore"
  local v153, v155 = "in deserunt voluptate id", "ad exercitation"
  v139 = "deserunt irure"
  if v141 <= 23.385350 then
      v137 = "aute in"
      v139 = "incididunt ea"
  else
      v137 = 47.791683
  end
  if v137 ~= "do ea consectetur eiusmod" then
      v139 = 61.720346
      v139 = "dolor Ut"
  else
      v139 = "cupidatat Excepteur ea dolor"
      v137 = "ad est sunt eu"
  end
  if v139 ~= "proident in" then
      v139 = "fugiat cillum"
  end
  return nil
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @param a3 string
-- @return int
function datum4:m35(a0, a1, a2, a3)
  v166, v168, v170, v172 = a1, "7", true, a3
  local v174, v176, v178 = "cupidatat quis", 74.713642, "sunt ex in culpa"
  if a2 < 90.112612 then
      a1 = "deserunt occaecat proident Duis"
  else
      a0 = "1"
      a2 = math.cos(78.609847) - math.pi - -(math.tan(-9))
  end
  a2 = 70.594309 + math.tan(97) + -(math.abs(163.206393))
  v168 = "6"
  local cond180 = false
  repeat
      a0 = "1"
      v168 = tostring(math.floor(146.375611))
      a2 = math.tan(128.246302) - math.pi + -(math.sin(43.767180))
      cond180 = true
  until cond180 ~= false
  a1 = [[ad
id
et
Ut]]
  return tonumber(a0) or #(a1) or math.floor(a2) or tonumber(a3) + string.len(v166) - - math.floor(v168 + 3)
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 float
-- @param a4 int
-- @return float
function datum2:m40(a0, a1, a2, a3, a4)
  local v182, v184, v186, v188 = "10", a1, "occaecat cillum", datum0
  v190, v192 = datum0, a1
  for i=4,20,2 do
      a3 = math.tan(174.320596) + math.pi + -(math.pi)
      a4 = a4 - -(0x36)
  end
  if a3 > 45.378391 then
      a2 = v184
      a0 = math.cos(a0) + -(math.pi)
  end
  a4 = 19 + -(math.floor(5.495927e+01))
  a2 = "10"
  for i=11,4,2 do
      v184 = tostring(63)
  end
  return math.sin(a0) + math.pi + math.pi - math.abs(a3) + math.abs(a4) + math.pi + -(math.pi)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m7_a0 = "10"
local m7_a1 = false
local m7_a2 = 66
local m7_a3 = 0x36
local r_m7_0 = datum2:m7(m7_a0, m7_a1, m7_a2, m7_a3)
local func12_a0 = 30.628445
local func12_a1 = "4"
local func12_a2 = "7"
local func12_a3 = 40.355586
local r_func12_0 = func12(func12_a0, func12_a1, func12_a2, func12_a3)
local m17_a0 = "4"
local m17_a1 = false
local m17_a2 = -91
local m17_a3 = false
local r_m17_0 = datum4:m17(m17_a0, m17_a1, m17_a2, m17_a3)
local m22_a0 = [[7]]
local m22_a1 = false
local m22_a2 = false
local m22_a3 = 1.688568
local m22_a4 = [[9]]
local r_m22_0 = datum2:m22(m22_a0, m22_a1, m22_a2, m22_a3, m22_a4)
local m28_a0 = 0
local m28_a1 = 35.592008
local m28_a2 = 85.341029
local m28_a3 = 31.410327
local m28_a4 = -63
local r_m28_0 = datum4:m28(m28_a0, m28_a1, m28_a2, m28_a3, m28_a4)
local r_m34_0 = datum4:m34()
local m35_a0 = "3"
local m35_a1 = "ut sint ullamco in"
local m35_a2 = 10.185207
local m35_a3 = "8"
local r_m35_0 = datum4:m35(m35_a0, m35_a1, m35_a2, m35_a3)
local m40_a0 = 91.232450
local m40_a1 = "1"
local m40_a2 = "5"
local m40_a3 = 68.632060
local m40_a4 = 1
local r_m40_0 = datum2:m40(m40_a0, m40_a1, m40_a2, m40_a3, m40_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0 and 1 or 0
local res_datum1 = datum1
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = math.floor(datum6)
local res_r_m7_0 = #(r_m7_0)
local res_r_func12_0 = math.floor(r_func12_0 + 1)
local res_r_m17_0 = r_m17_0
local res_r_m22_0 = 1
local res_r_m28_0 = math.floor(r_m28_0 + 0)
local res_r_m34_0 = 1
local res_r_m35_0 = r_m35_0
local res_r_m40_0 = math.floor(r_m40_0)
RESULT = res_r_m40_0 - res_r_m35_0 + res_r_m34_0 - res_r_m28_0 - res_r_m22_0 - res_r_m17_0 + res_r_func12_0 + res_r_m7_0 + res_datum6 - res_datum4 - res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))