--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            999366000                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = "1"
local datum1 = {field2 = 93}
datum3 = {field4 = 0x1.5e5f70e9b4893p+7}
datum5 = "9"
local datum6 = {field7 = 172.860011}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 int
-- @param a2 string
-- @param a3 float
-- @return string
function func8(a0, a1, a2, a3)
  v22, v24, v26, v28 = a2, "10", a3, datum5
  local v30, v32, v34 = 60, 96, a2
  local cond36 = true
  while cond36 == false do
      v24 = "9"
      a1 = a0 or 61 - - math.floor(v24 + 1)
      v22 = "sed ad"
      cond36 = false
  end
  a3 = 81.109066 - math.tan(-4) - -(42.725731)
  a1 = #(a2) or tonumber(v24) or -(88)
  return tostring(a0)
end

-- @param a0 string
-- @param a1 int
-- @return table
function datum1:m13(a0, a1)
  v37, v39 = false, -37.795494
  v41, v43, v45, v47 = "2", "8", v37, "cillum exercitation"
  local v49, v51 = -0x1.78e88d7dd9c7p+2, a1
  v37 = true == false == v37 ~= not false ~= false
  v39 = 84.373167 + math.sin(174.143900) + -(math.tan(143.842286))
  v37 = true == not false
  a1 = a1 + -40 or - 45
  local cond53 = false
  repeat
      v37 = false == "cupidatat occaecat elit tempor" == "occaecat in" ~= not true
      v39 = math.pi - -(60.658483)
      cond53 = true
  until cond53 ~= false
  return {0}
end

-- @return float
function datum1:m16()
  v54, v56, v58, v60 = 6.297439, 53.763543, -9.639620, "veniam commodo"
  local v62, v64, v66, v68 = "2", 8.892133, 0x3F, false
  local v70, v72 = "cupidatat laborum", true
  local cond74 = 111
  repeat
      v58 = math.abs(133.829085) - -(32.828570)
      v58 = math.pi - -(49.131781)
      v58 = 10.061061 + math.sin(29.021470) - -(math.tan(v56))
      cond74 = cond74 - 1
  until cond74 >= 71
  for i, _ in pairs(datum1) do
      v54 = math.tan(-84) - -(math.pi)
  end
  if v54 <= 5.729581 then
      v56 = math.pi + math.tan(v58) - -(math.abs(50))
      v56 = math.sin(v56) - -(math.cos(v58))
      v54 = math.pi + math.pi + -(math.sin(-78))
  end
  return math.cos(v54) + math.abs(v56) + -(math.tan(v58))
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @param a3 float
-- @return string
function func17(a0, a1, a2, a3)
  v77, v79 = "labore aute nostrud", 82
  v81, v83, v85, v87 = 36.647129, -66, false, 7
  local v89, v91 = false, true
  a3 = math.abs(v79) + math.sin(81) + -(math.tan(-97))
  v77 = 12.653531
  for i=19,0x1,2 do
      a3 = math.cos(103.293491) + math.cos(1.422236e+02) - -(61.009274)
      a3 = math.abs(126.660065) - math.pi + -(math.pi)
      v77 = "qui amet"
  end
  if a1 == false then
      v77 = "veniam velit"
      a3 = 94.546431 + -(11.866840)
      a3 = 50.531511 + math.pi + -(17.894368)
  end
  local cond94 = 10
  repeat
      a2 = "5"
      a3 = math.sin(0x1.8d04979a386cp+4) - -(math.sin(a3))
      cond94 = cond94 + 2
  until cond94 <= 40
  return "5"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = -2
local func8_a1 = -19
local func8_a2 = "aute"
local func8_a3 = 68.975460
local r_func8_0 = func8(func8_a0, func8_a1, func8_a2, func8_a3)
local m13_a0 = [[6]]
local m13_a1 = -27
local r_m13_0 = datum1:m13(m13_a0, m13_a1)
local r_m16_0 = datum1:m16()
local func17_a0 = "tempor sint"
local func17_a1 = false
local func17_a2 = "5"
local func17_a3 = 88.420766
local r_func17_0 = func17(func17_a0, func17_a1, func17_a2, func17_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = #(datum1)
local res_datum3 = #(datum3)
local res_datum5 = tonumber(datum5)
local res_datum6 = #(datum6)
local res_r_func8_0 = tonumber(r_func8_0)
local res_r_m13_0 = #(r_m13_0)
local res_r_m16_0 = math.floor(r_m16_0)
local res_r_func17_0 = tonumber(r_func17_0)
RESULT = res_r_func17_0 + res_r_m16_0 + res_r_m13_0 + res_r_func8_0 + res_datum6 + res_datum5 + res_datum3 + res_datum1 + res_datum0
print(math.floor(RESULT))