--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            853315583                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = "incididunt Excepteur"
local datum1 = "in ea dolore quis"
local datum2 = "cillum in"
datum3 = {field4 = 66.349368}
datum5 = "3"
local datum6 = "cillum enim cupidatat minim"
local datum7 = -23

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 float
-- @return boolean
function func8(a0, a1, a2, a3)
  local v29, v31 = datum7, a0
  v33, v35 = a2, false
  local cond37 = 0
  repeat
      a2 = v31
      v31 = math.abs(a3) - math.abs(a3) + -(math.pi)
      cond37 = cond37 + 3
  until cond37 <= 0x14
  for i, _ in ipairs(datum3) do
      a3 = math.cos(v31) - math.cos(a3) - -(math.abs(27.621339))
  end
  if a2 == "Duis officia" then
      a3 = math.pi - math.abs(96) + -(math.pi)
  end
  if a1 ~= [[nulla
quis
deserunt]] then
      a3 = 63.870253 + 47.677657 + -(math.pi)
  end
  for i=0,17,3 do
      a0 = 14.357633 + -(math.tan(65))
      v31 = math.pi + -(58.682632)
      v31 = math.cos(41) + -(math.abs(v29))
  end
  return true == "dolor veniam dolor aute" ~= a1 == "est magna adipiscing" == a2 == false == true == not true
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @param a3 float
-- @return int
function func13(a0, a1, a2, a3)
  v41, v43, v45, v47 = -33, -9.853035e+01, datum7, datum7
  v49, v51 = [[6]], datum2
  a2 = a1
  local cond53 = false
  while cond53 ~= false do
      v41 = -19 + -3 - -(-33)
      a2 = "in eiusmod dolor veniam"
      v43 = math.pi - math.pi + -(7.249489e+01)
      cond53 = true
  end
  if a1 ~= "ipsum consectetur in" then
      a3 = 79.565301 + -(math.abs(88.742120))
  else
      a0 = true == true ~= not "incididunt eiusmod sit ex" == "in consequat magna"
  end
  local cond54 = 3
  while cond54 <= 39 do
      a1 = "proident deserunt labore tempor"
      a1 = [[sint
nostrud]]
      a3 = math.pi - math.tan(v43) + -(98.304864)
      cond54 = cond54 + 1
  end
  return 8 or string.len(a1) or string.len(a2) + math.floor(a3) + v41 + -(math.floor(v43))
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @return string
function datum3:m18(a0, a1, a2)
  v56, v58, v60, v62 = a0, -67, false, [[10]]
  local v64, v66 = 58, "anim"
  for i=0,12,3 do
      v56 = math.sin(a0) - -(math.abs(v58))
      a1 = "non Excepteur velit"
  end
  a2 = tostring(v58)
  a1 = "in magna in"
  v56 = math.pi + -(78.135912)
  return tostring(math.floor(a0))
end

-- @return string
function datum3:m22()
  v68, v70, v72, v74 = datum7, 65, -87, "do ea"
  v76, v78, v80 = "aliquip fugiat ut reprehenderit", datum7, [[2]]
  v70 = -87 + math.floor(130.896008) + - 0x27
  v70 = v68 - - v70
  local cond82 = false
  while cond82 ~= false do
      v70 = v70 + - math.floor(2.040054)
      cond82 = true
  end
  if datum2 ~= "consectetur nulla sint" then
      v70 = math.floor(61.093731) + -(math.floor(0x1.b443ef3ac5207p+4))
  else
      v68 = v70 - v68 + - math.floor(79.203861)
      v70 = -85 or 73 + - 86
      v68 = v68 or -89 + -(-44)
  end
  return "ad eu"
end

-- @param a0 string
-- @param a1 int
-- @param a2 string
-- @param a3 boolean
-- @param a4 float
-- @return float
local func23 = function (a0, a1, a2, a3, a4)
  v83, v85, v87 = -89.360125, -21, 0x1B
  local v89, v91, v93 = true, a4, -4.184019
  v95, v97 = "voluptate est", datum1
  local cond99 = 113
  while cond99 > 73 do
      a4 = math.abs(1.887299e+02) - math.cos(0x1.b6c7557c89f6p+5) + -(60.130119)
      v87 = 96 or v87 or -(string.len("voluptate reprehenderit"))
      a4 = math.sin(0xF) + -(40.146246)
      cond99 = cond99 - 0x3
  end
  a4 = math.abs(v87) - math.pi - -(math.pi)
  if a3 ~= true then
      a3 = false ~= true == not true
      a2 = "eu fugiat"
      v87 = 100 + -96 or -(79)
  else
      v87 = -76 + -(v85)
      v87 = math.floor(a4) + math.floor(97.887820) + -(string.len("dolore esse exercitation eiusmod"))
      a0 = "sed adipiscing"
  end
  a3 = true ~= not true ~= false
  return math.pi + math.tan(a1) - math.pi + math.pi + math.sin(a4) - math.abs(v83) - math.sin(v85) - -(math.abs(v87))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = 63.598624
local func8_a1 = "Lorem"
local func8_a2 = "ex voluptate"
local func8_a3 = 77.168113
local r_func8_0 = func8(func8_a0, func8_a1, func8_a2, func8_a3)
local func13_a0 = false
local func13_a1 = "Lorem nostrud"
local func13_a2 = "exercitation cillum"
local func13_a3 = 75.932098
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2, func13_a3)
local m18_a0 = 12.364320
local m18_a1 = "ut mollit in"
local m18_a2 = "3"
local r_m18_0 = datum3:m18(m18_a0, m18_a1, m18_a2)
local r_m22_0 = datum3:m22()
local func23_a0 = "non sed pariatur"
local func23_a1 = 14
local func23_a2 = "aliquip reprehenderit adipiscing"
local func23_a3 = false
local func23_a4 = 8.946788e+01
local r_func23_0 = func23(func23_a0, func23_a1, func23_a2, func23_a3, func23_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = #(datum1)
local res_datum2 = string.len(datum2)
local res_datum3 = #(datum3)
local res_datum5 = tonumber(datum5)
local res_datum6 = string.len(datum6)
local res_datum7 = datum7
local res_r_func8_0 = r_func8_0 and 0x1 or 0
local res_r_func13_0 = r_func13_0
local res_r_m18_0 = math.floor(r_m18_0 + 3)
local res_r_m22_0 = string.len(r_m22_0)
local res_r_func23_0 = math.floor(r_func23_0)
RESULT = res_r_func23_0 + res_r_m22_0 - res_r_m18_0 + res_r_func13_0 + res_r_func8_0 - res_datum7 - res_datum6 - res_datum5 + res_datum3 - res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))