--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            481350649                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = {field1 = "ut mollit sunt"}
datum2 = {field3 = true}
local datum4 = {field5 = -29}
datum6 = "cupidatat dolore adipiscing"
local datum7 = {field8 = true}
datum9 = 83.310304
local datum10 = {field11 = 56}
datum12 = "occaecat proident"
local datum13 = 9.203684
local datum14 = 56

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 float
-- @param a2 int
-- @return string
function datum10:m15(a0, a1, a2)
  v51, v53 = datum6, a1
  v55, v57 = a0, false
  v59, v61, v63, v65 = true, v53, true, "6"
  v51 = "in velit dolore"
  a2 = -47 - string.len([[incididunt
Duis
fugiat]]) or - 88
  a0 = 0x1c + a2 + -(string.len("aliquip magna"))
  a2 = v55 + -(75)
  for i=13,5 do
      v53 = math.tan(-71) + -(math.sin(a2))
      a1 = math.abs(6) + math.pi + -(83.778073)
      v51 = "fugiat aliquip sunt"
  end
  v51 = "reprehenderit esse"
  return tostring(a0)
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 int
-- @return int
function datum4:m19(a0, a1, a2, a3)
  local v69, v71, v73, v75 = [[elit
mollit
fugiat
eu]], a0, 3.754904e+01, datum14
  local v77, v79 = -17, true
  local cond81 = 2
  while cond81 <= 0x2b do
      v71 = tostring(a3)
      cond81 = cond81 + 1
  end
  local cond82 = true
  while cond82 ~= true do
      a0 = "4"
      a0 = tostring(4)
      cond82 = false
  end
  for i, v in ipairs(datum4) do
      a2 = "in qui"
      a2 = "labore eiusmod aliquip"
      a3 = 76 or - string.len(v69)
  end
  for _, v in pairs(datum10) do
      a2 = "cillum Duis"
      a1 = "velit"
  end
  return math.floor(a0 + 0x2) or #(a1) + string.len(a2) - a3 or string.len(v69) + - math.floor(v71 + 1)
end

-- @return nil
function datum2:m24()
  local v91, v93 = true, "5"
  local v95, v97, v99 = v91, 72.444054, datum12
  local v101, v103, v105 = datum14, "4", true
  for i=20,0 do
      v93 = "4"
      v91 = false == true == not false
      v93 = "4"
  end
  local cond107 = 121
  while cond107 > 69 do
      v95 = "sed ullamco ullamco" == [[elit
Duis]] == not false
      v95 = true ~= v91 == not "Excepteur" ~= "reprehenderit do non"
      v93 = "7"
      cond107 = cond107 - 3
  end
  if datum6 ~= "velit ea" then
      v93 = v93
  else
      v93 = "8"
      v95 = "Duis dolor" == v93 == false == not true
  end
  if datum6 == "deserunt adipiscing" then
      v91 = true == "laborum ipsum ut" == "in cillum" == not true
      v95 = false == not true ~= false
      v93 = "5"
  end
  return false == v91 == "officia dolor id" == v93 ~= not v95
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @return boolean
function datum2:m25(a0, a1, a2, ...)
  local v108, v110, v112, v114 = a0, a2, 72.274336, a1
  v116, v118 = -11, a2
  a2 = "10"
  if datum9 ~= -57.297589 then
      v110 = a0
      v110 = v108
      a1 = [[voluptate
amet
in]] == v110 ~= "consectetur" ~= a2 == not true == a1
  end
  for i, _ in pairs(datum10) do
      v108 = "5"
      a0 = a0
  end
  a1 = true ~= not true
  for i=4,12 do
      a2 = tostring(math.floor(75.124400))
  end
  return "ipsum" == a0 == a1 ~= "voluptate" ~= a2 ~= "minim consectetur exercitation enim" ~= v108 ~= not "ut elit non" == v110
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @param a4 string
-- @return boolean
function datum10:m29(a0, a1, a2, a3, a4)
  local v122, v124, v126, v128 = 69, datum13, false, datum13
  v130, v132, v134 = -47.588364, true, v122
  v136, v138, v140, v142 = datum13, false, false, false
  v122 = string.len("minim id") + - 59
  v122 = math.floor(83.670190) or - math.floor(0x1.4c5fd7591802p+7)
  for _, _ in ipairs(datum0) do
      v122 = -41 + math.floor(a0 + 2) or -(-56)
      a4 = "2"
  end
  local cond145 = true
  repeat
      v122 = -86 - math.floor(a1 + 3) or -(-97)
      a4 = "9"
      cond145 = false
  until cond145 ~= true
  a1 = "5"
  return "ex laborum" == a0 ~= "nostrud eu quis" ~= a1 == "consectetur consectetur enim est" ~= a2 == "officia non" == a3 == "eu fugiat commodo" ~= a4 == true ~= true ~= not true == v126
end

-- @param a0 float
-- @param a1 string
-- @param a2 boolean
-- @param a3 boolean
-- @return float
local func35 = function (a0, a1, a2, a3, ...)
  v146, v148, v150 = 49.151417, 79.600197, "10"
  v152, v154, v156, v158 = "4", -52, a1, v146
  v148 = math.tan(v148) - -(math.abs(a0))
  v148 = math.pi - -(math.cos(a0))
  local cond160 = 0x3
  repeat
      a2 = true ~= false ~= not [[do
veniam]] ~= a1
      a3 = true == a2 ~= false ~= not true
      a2 = "nulla in" == a1 == not true
      cond160 = cond160 + 2
  until cond160 < 34
  return math.sin(a0) - math.pi - math.pi - math.pi - math.tan(v146) + -(math.tan(v148))
end

-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @param a3 float
-- @return string
function datum4:m40(a0, a1, a2, a3)
  local v161, v163, v165, v167 = a1, -26, "9", datum6
  local v169, v171 = datum14, v161
  a0 = "Lorem sint mollit"
  v161 = v161
  local cond173 = false
  repeat
      a0 = "aute eu ut anim"
      v161 = [[6]]
      v161 = tostring(3)
      cond173 = true
  until cond173 ~= false
  local cond175 = true
  while cond175 == false do
      v161 = "10"
      v163 = 24 + 90 or - 0x31
      v161 = tostring(-61)
      cond175 = false
  end
  return "3"
end

-- @param a0 string
-- @param a1 int
-- @param a2 boolean
-- @param a3 string
-- @param a4 string
-- @return int
function func45(a0, a1, a2, a3, a4, ...)
  v176, v178 = datum13, "2"
  v180, v182, v184 = v176, -17, v176
  a3 = "proident ullamco pariatur"
  local cond186 = true
  repeat
      a4 = "culpa ad"
      cond186 = false
  until cond186 == false
  if datum12 == "qui" then
      a3 = "in et"
      a4 = "qui"
  else
      a2 = false == "voluptate nisi" ~= "in aliquip fugiat" ~= not true == a2
      a0 = tostring(44)
  end
  return math.floor(a0 + 0) or a1 + 57 + string.len(a3) + #(a4) + math.floor(v176) + - math.floor(v178 + 2)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m15_a0 = -88
local m15_a1 = 14.973850
local m15_a2 = -99
local r_m15_0 = datum10:m15(m15_a0, m15_a1, m15_a2)
local m19_a0 = "10"
local m19_a1 = "in elit cupidatat"
local m19_a2 = "ut amet"
local m19_a3 = 17
local r_m19_0 = datum4:m19(m19_a0, m19_a1, m19_a2, m19_a3)
local r_m24_0 = datum2:m24()
local m25_a0 = "7"
local m25_a1 = true
local m25_a2 = "6"
local m25_vararg0 = -84
local m25_vararg1 = -22
local m25_vararg2 = false
local r_m25_0 = datum2:m25(m25_a0, m25_a1, m25_a2, m25_vararg0, m25_vararg1, m25_vararg2)
local m29_a0 = [[2]]
local m29_a1 = "6"
local m29_a2 = "sit culpa"
local m29_a3 = "ut ex ut ea"
local m29_a4 = "4"
local r_m29_0 = datum10:m29(m29_a0, m29_a1, m29_a2, m29_a3, m29_a4)
local func35_a0 = 55.770004
local func35_a1 = "3"
local func35_a2 = false
local func35_a3 = false
local func35_vararg0 = false
local func35_vararg1 = true
local r_func35_0 = func35(func35_a0, func35_a1, func35_a2, func35_a3, func35_vararg0, func35_vararg1)
local m40_a0 = "id labore consectetur nisi"
local m40_a1 = [[5]]
local m40_a2 = true
local m40_a3 = 76.301010
local r_m40_0 = datum4:m40(m40_a0, m40_a1, m40_a2, m40_a3)
local func45_a0 = "1"
local func45_a1 = -47
local func45_a2 = false
local func45_a3 = "ut qui laborum cupidatat"
local func45_a4 = "irure do"
local func45_vararg0 = false
local r_func45_0 = func45(func45_a0, func45_a1, func45_a2, func45_a3, func45_a4, func45_vararg0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = #(datum2)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = #(datum6)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = math.floor(datum9)
local res_datum10 = #(datum10)
local res_datum12 = string.len(datum12)
local res_datum13 = math.floor(datum13)
local res_datum14 = datum14
local res_r_m15_0 = math.floor(r_m15_0 + 1)
local res_r_m19_0 = r_m19_0
local res_r_m24_0 = 1
local res_r_m25_0 = r_m25_0 and 1 or 0
local res_r_m29_0 = r_m29_0 and 1 or 0
local res_r_func35_0 = math.floor(r_func35_0)
local res_r_m40_0 = math.floor(r_m40_0 + 3)
local res_r_func45_0 = r_func45_0
RESULT = res_r_func45_0 - res_r_m40_0 + res_r_func35_0 - res_r_m29_0 + res_r_m25_0 + res_r_m24_0 + res_r_m19_0 - res_r_m15_0 - res_datum14 - res_datum13 + res_datum12 - res_datum10 + res_datum9 - res_datum7 - res_datum6 - res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))