--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            132955934                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = {field1 = false}
datum2 = {field3 = 27}
local datum4 = "7"
local datum5 = {field6 = "veniam elit"}
datum7 = {field8 = 97.628086}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 int
-- @return float
local func9 = function (a0, a1)
  local v29, v31, v33, v35 = "non exercitation Excepteur", 74.801833, false, [[9]]
  v37, v39 = v29, -1.123495e+01
  v41, v43 = v29, false
  v29 = "magna"
  v33 = false ~= not "anim nulla" == "dolore enim"
  v29 = "anim Lorem cupidatat Lorem"
  if datum0 ~= {} then
      a1 = a1 - 62 or - 57
      a0 = false == v33 == not true
  else
      a0 = false == not "deserunt Duis laborum consectetur" == v29
      v29 = "aliquip"
  end
  return 71.182145 + math.tan(a1) - 91.775160 - math.sin(v31) + -(7.288523e+01)
end

-- @param a0 string
-- @param a1 boolean
-- @return string
function func12(a0, a1)
  local v47, v49, v51 = -26, "aliquip dolore", 0x1.248c57e587de2p+6
  local v53, v55, v57 = "5", -23, [[ut
Duis
pariatur
nisi]]
  local v59, v61, v63 = -37, -46, -0x1.bce130fb3616p+3
  local cond65 = 0
  while cond65 <= 39 do
      v47 = 74 or -(#("cupidatat aliquip"))
      cond65 = cond65 + 1
  end
  if v49 ~= [[in
elit
officia]] then
      v47 = -7 + -(8)
      a1 = false == not true
  end
  for i, _ in ipairs(datum7) do
      v51 = math.cos(-73) + -(math.pi)
  end
  if datum0 == {} then
      v47 = 0x40 or -55 or - math.floor(49.146820)
      a0 = v49
  end
  return "6"
end

-- @param a0 string
-- @param a1 string
-- @param a2 int
-- @param a3 string
-- @param a4 int
-- @return table
function func15(a0, a1, a2, a3, a4)
  local v69, v71 = "amet", a3
  v73, v75 = true, 74
  for i=15,0x5 do
      v71 = "5"
      v71 = tostring(-98)
  end
  for i=5,0xb do
      a0 = "dolor Ut Ut"
      a1 = "1"
  end
  for i, _ in ipairs(datum5) do
      a0 = "in consequat"
      v69 = "laborum"
      a4 = 92 or -(-46)
  end
  if v69 == "proident nostrud" then
      a0 = v69
      a0 = "sed sed aliquip sit"
  end
  return {0x4}
end

-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 boolean
-- @return boolean
function datum7:m21(a0, a1, a2, a3)
  v82, v84, v86 = true, "1", a3
  v88, v90, v92 = -21, a1, 36.277533
  v84 = "2"
  if v82 == true then
      a1 = math.pi + math.cos(142.740743) - -(math.pi)
  end
  if a0 == "1" then
      a0 = tostring(math.floor(a1))
      a0 = "10"
  else
      v84 = "8"
      v84 = "5"
      a2 = "aute non consectetur"
  end
  a2 = [[laboris
quis
eiusmod]]
  for i, _ in pairs(datum0) do
      a3 = true ~= not true
      v84 = [[5]]
      v84 = "6"
  end
  v84 = "10"
  return "quis amet proident et" ~= a0 == false ~= "proident" == a2 ~= a3 == false == v82 == not "dolore" ~= v84
end

-- @param a0 int
-- @param a1 int
-- @return table
function datum5:m26(a0, a1)
  v97, v99, v101, v103 = "Ut cillum amet", "7", "3", "sed voluptate"
  v105, v107, v109 = "5", 35, a1
  local v111, v113, v115 = v99, true, v99
  a1 = string.len([[qui
ea]]) or -35 + -(41)
  if v99 ~= "5" then
      v99 = tostring(a0)
      v99 = "4"
  end
  local cond117 = true
  while cond117 ~= true do
      a1 = -87 + tonumber(v99) or -(28)
      v99 = "1"
      cond117 = false
  end
  local cond118 = false
  while cond118 ~= false do
      v101 = v101
      a0 = -58 - - math.floor(16.640187)
      a1 = math.floor(44.746680) or -(tonumber(v101))
      cond118 = true
  end
  return {a0}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func9_a0 = false
local func9_a1 = -54
local r_func9_0 = func9(func9_a0, func9_a1)
local func12_a0 = "dolore veniam"
local func12_a1 = false
local r_func12_0 = func12(func12_a0, func12_a1)
local func15_a0 = "qui dolore in"
local func15_a1 = "10"
local func15_a2 = 40
local func15_a3 = "8"
local func15_a4 = -2
local r_func15_0 = func15(func15_a0, func15_a1, func15_a2, func15_a3, func15_a4)
local m21_a0 = "1"
local m21_a1 = 66.277011
local m21_a2 = "quis minim"
local m21_a3 = false
local r_m21_0 = datum7:m21(m21_a0, m21_a1, m21_a2, m21_a3)
local m26_a0 = -6
local m26_a1 = -57
local r_m26_0 = datum5:m26(m26_a0, m26_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = #(datum2)
local res_datum4 = math.floor(datum4 + 3)
local res_datum5 = #(datum5)
local res_datum7 = #(datum7)
local res_r_func9_0 = math.floor(r_func9_0)
local res_r_func12_0 = tonumber(r_func12_0)
local res_r_func15_0 = #(r_func15_0)
local res_r_m21_0 = r_m21_0 and 0x1 or 0
local res_r_m26_0 = ms.table_to_int(r_m26_0)
RESULT = res_r_m26_0 - res_r_m21_0 - res_r_func15_0 + res_r_func12_0 - res_r_func9_0 + res_datum7 - res_datum5 + res_datum4 + res_datum2 + res_datum0
print(math.floor(RESULT))