--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            763532200                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = 59}
local datum2 = -49
datum3 = false
local datum4 = true
datum5 = {field6 = false}
local datum7 = {field8 = true}
local datum9 = "8"

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @return float
function func10()
  local v39, v41, v43, v45 = datum9, "laboris mollit consequat cillum", datum3, datum2
  local v47, v49, v51, v53 = datum3, -88.539274, "ad cillum", true
  local cond55 = 111
  while cond55 >= 74 do
      v39 = "10"
      v41 = "ipsum cillum"
      cond55 = cond55 - 0x2
  end
  v41 = v41
  v39 = v39
  for i, _ in pairs(datum5) do
      v39 = tostring(math.floor(34.298986))
      v41 = "exercitation"
  end
  v39 = v39
  return 54.094378 + -(math.pi)
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 string
-- @return nil
function datum5:m11(a0, a1, a2)
  local v61, v63, v65 = datum2, "proident dolor", a2
  local v67, v69 = a1, v61
  a0 = math.pi + math.sin(37) + -(9.247305e+01)
  if v63 == "Excepteur culpa Duis ipsum" then
      a0 = 91.128462 - math.cos(7) - -(19.171042)
  else
      v63 = string.reverse(v63)
      a2 = tostring(math.floor(143.680240))
  end
  a2 = tostring(math.floor(a0))
  v63 = "ut"
  return false ~= a1 == "sint reprehenderit irure" ~= a2 == false ~= not "amet minim" == v63
end

-- @param a0 string
-- @return function
function func15(a0)
  v72, v74, v76 = "ullamco cupidatat do", true, 51
  local v78, v80 = false, a0
  for _, v in pairs(datum5) do
      v72 = "qui"
      v72 = "sed consectetur quis"
      a0 = "1"
  end
  for i, _ in pairs(datum5) do
      v72 = v72
  end
  a0 = "6"
  if a0 ~= "6" then
      v72 = 41.545760
      v74 = true ~= true ~= false ~= not true
      v72 = "irure dolore ut"
  else
      v74 = true ~= not false
      v72 = "cillum dolore occaecat tempor"
      a0 = "10"
  end
  v74 = "eu ex" ~= [[sit]] ~= not "non ullamco id" ~= "consequat aute"
  local cond91 = 0x7
  while cond91 <= 34 do
      v72 = "ea commodo"
      cond91 = cond91 + 0x1
  end
  return nil
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 int
-- @return string
function func17(a0, a1, a2)
  v92, v94, v96 = 56, "nisi est enim", "dolore dolore enim"
  local v98, v100 = a1, "aute sint nisi"
  local v102, v104 = true, -5.779139e+00
  v92 = #("velit minim et") - #("veniam veniam") or - math.floor(1.924798e+02)
  local cond106 = false
  repeat
      v94 = "sint irure id"
      v92 = -6 or math.floor(130.062885) - - -58
      cond106 = true
  until cond106 ~= false
  a1 = true ~= not true == true
  a0 = a0
  a2 = math.floor(90.813851) or - 0x5A
  return a0
end

-- @param a0 string
-- @param a1 string
-- @return string
function datum7:m21(a0, a1)
  local v108, v110 = true, "consectetur minim"
  v112, v114, v116, v118 = a0, -35.991926, -9, datum2
  v110 = "eu aliqua Ut"
  local cond120 = 119
  repeat
      v110 = "cupidatat qui"
      a0 = "9"
      a1 = "minim consequat"
      cond120 = cond120 - 1
  until cond120 >= 51
  for _, _ in pairs(datum0) do
      v108 = false == not "Excepteur" ~= a1
      v110 = v110
      a0 = a0
  end
  return "minim anim"
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @return boolean
function datum0:m24(a0, a1, a2)
  local v124, v126 = 3.353504, datum9
  v128, v130 = "incididunt mollit irure", 33
  if v126 == "6" then
      a1 = "aliquip velit magna"
      a1 = "magna quis deserunt"
      v124 = 22.801334 + -(math.pi)
  end
  local cond134 = 0
  while cond134 < 29 do
      v126 = tostring(-92)
      a1 = "exercitation est"
      v124 = math.pi + -(57.194622)
      cond134 = cond134 + 1
  end
  if datum9 ~= "3" then
      v124 = math.cos(68) + -(math.pi)
      a1 = "aliquip dolor ipsum consequat"
  else
      a0 = tostring(math.floor(a2))
      a2 = math.abs(138.971078) + -(5.851019)
      v124 = math.pi - math.pi + -(math.sin(-46))
  end
  a0 = "2"
  a2 = 4.952359 + 0x1.4de0f6a7adc1p+6 + -(18.027539)
  return "Excepteur consequat tempor ad" == a0 == "do mollit aute ea" ~= a1 == true == true ~= not "culpa do amet" == v126
end

-- @param a0 float
-- @param a1 int
-- @param a2 string
-- @param a3 float
-- @param a4 boolean
-- @return float
function datum7:m28(a0, a1, a2, a3, a4)
  local v136, v138 = 62.048026, a0
  v140, v142 = -31.674087, -54.682198
  local v144, v146 = -43.847857, "nostrud"
  v136 = math.abs(11.420091) + math.cos(v136) - -(math.abs(v136))
  if datum4 ~= true then
      a1 = string.len("et in ex amet") or math.floor(0x1.231ae303b4eeep+7) or - math.floor(97.951466)
      a2 = tostring(math.floor(v140))
  end
  v140 = math.abs(73.554673) + -(math.cos(39.437558))
  if datum7 ~= {} then
      a1 = math.floor(a3) - 0x35 or - math.floor(v140)
  else
      v138 = math.tan(a3) - -(math.abs(a3))
      a2 = "6"
      a0 = math.pi - -(55.725878)
  end
  if datum0 ~= {} then
      a0 = 64.384548 + math.pi + -(math.tan(184.204311))
      v140 = math.cos(187.915064) - math.sin(a1) + -(math.pi)
  else
      v138 = math.tan(3.270511) + -(math.pi)
      a4 = true ~= not true == true
      v138 = 0x1.3ce04d77bc19ep+3 + 32.528230 + -(math.pi)
  end
  local cond148 = 7
  while cond148 <= 46 do
      v136 = math.pi - math.tan(0x42) - -(math.sin(v140))
      cond148 = cond148 + 3
  end
  return math.sin(a0) - math.sin(a1) + 10.183862 - math.sin(a3) - 55.224806 + math.cos(v136) + math.tan(v138) + -(math.sin(v140))
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return nil
function func34(a0, a1, a2, a3)
  v149, v151, v153 = "enim Excepteur", datum2, -0.081700
  local v155, v157, v159, v161 = 26, datum3, "sed deserunt ea culpa", "2"
  local cond163 = true
  while cond163 ~= true do
      a1 = [[labore
dolor
labore]]
      cond163 = false
  end
  if v151 <= -17 then
      a3 = 115.820659
  else
      a0 = false ~= false == not "fugiat consequat aliqua culpa" ~= "laborum occaecat esse irure"
      a0 = true ~= true ~= not false
      a1 = "eiusmod adipiscing"
  end
  a1 = a2
  for i=0x11,4,2 do
      a2 = "Duis sint"
  end
  local cond165 = 0x76
  repeat
      a0 = true == not true
      a0 = false == not false
      a1 = a1
      cond165 = cond165 - 2
  until cond165 >= 51
  return false ~= a0 ~= "dolor in do" ~= a1 ~= [[officia
ut]] ~= a2 == "deserunt" == a3 == "culpa dolore ullamco" == v149 ~= not false
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_func10_0 = func10()
local m11_a0 = 1.160952
local m11_a1 = false
local m11_a2 = "1"
local r_m11_0 = datum5:m11(m11_a0, m11_a1, m11_a2)
local func15_a0 = "2"
local r_func15_0 = func15(func15_a0)
local func17_a0 = "6"
local func17_a1 = true
local func17_a2 = -95
local r_func17_0 = func17(func17_a0, func17_a1, func17_a2)
local m21_a0 = "6"
local m21_a1 = "qui nulla ut"
local r_m21_0 = datum7:m21(m21_a0, m21_a1)
local m24_a0 = "8"
local m24_a1 = "in magna"
local m24_a2 = 0x1.523a75576c5cep+5
local r_m24_0 = datum0:m24(m24_a0, m24_a1, m24_a2)
local m28_a0 = 0x1.2e2b8bb5e37bbp+6
local m28_a1 = 0
local m28_a2 = "3"
local m28_a3 = 0x1.90f6ee7922c0bp+4
local m28_a4 = true
local r_m28_0 = datum7:m28(m28_a0, m28_a1, m28_a2, m28_a3, m28_a4)
local func34_a0 = false
local func34_a1 = "officia mollit"
local func34_a2 = "Duis quis"
local func34_a3 = "ea ullamco elit nisi"
local r_func34_0 = func34(func34_a0, func34_a1, func34_a2, func34_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = datum2
local res_datum3 = datum3 and 0x1 or 0
local res_datum4 = datum4 and 1 or 0
local res_datum5 = #(datum5)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = math.floor(datum9 + 2)
local res_r_func10_0 = math.floor(r_func10_0)
local res_r_m11_0 = 1
local res_r_func15_0 = 1
local res_r_func17_0 = math.floor(r_func17_0 + 0)
local res_r_m21_0 = string.len(r_m21_0)
local res_r_m24_0 = r_m24_0 and 1 or 0
local res_r_m28_0 = math.floor(r_m28_0)
local res_r_func34_0 = 1
RESULT = res_r_func34_0 + res_r_m28_0 - res_r_m24_0 + res_r_m21_0 + res_r_func17_0 + res_r_func15_0 + res_r_m11_0 - res_r_func10_0 - res_datum9 - res_datum7 + res_datum5 + res_datum4 - res_datum3 + res_datum2 + res_datum0
print(math.floor(RESULT))