--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            987549888                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
local datum0 = {field1 = true}
local datum2 = 23.748620
local datum3 = [[2]]
datum4 = {field5 = true}
datum6 = 3.591490e+01
datum7 = {field8 = "dolore Ut"}
datum9 = {field10 = true}
datum11 = 50.199607

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @return table
function datum7:m12(a0, a1, a2)
  v36, v38, v40 = true, -65, "7"
  local v42, v44 = false, "officia Duis"
  if datum6 >= 58.449839 then
      a2 = "3"
      a0 = a2
  else
      a2 = "9"
  end
  local cond46 = false
  repeat
      a1 = "deserunt ad ad Lorem"
      v36 = "laboris tempor consequat et" == a0 ~= "pariatur incididunt officia" ~= a0 ~= not [[aliquip
incididunt]] == "elit id Excepteur proident"
      a0 = tostring(v38)
      cond46 = true
  until cond46 == true
  for i=5,13,3 do
      v36 = true == false == true ~= not false
      a0 = "6"
  end
  a0 = tostring(math.floor(187.541363))
  for _, v in ipairs(datum4) do
      a0 = a0
      v36 = "Duis incididunt culpa laborum" == a1 ~= not true
      v36 = true ~= v36 == "ullamco ex" ~= a0 ~= not v36
  end
  return {-6}
end

-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @return table
function func16(a0, a1, a2, a3)
  v52, v54 = "6", datum3
  v56, v58 = -71, a3
  local v60, v62, v64, v66 = 76.358072, "dolor eiusmod", "9", datum3
  for i=0x14,0 do
      v52 = "6"
      v52 = "10"
  end
  if datum11 ~= 2.697815 then
      v52 = v54
      a1 = math.sin(-12) + 17.535734 - -(math.cos(-5))
      a3 = "7"
  else
      a2 = tostring(-87)
  end
  if datum11 > 91.425698 then
      v56 = 49 or math.floor(170.543573) - -(20)
  else
      a1 = math.cos(-43) - math.abs(44) + -(9.601748e+01)
  end
  for i=5,13,3 do
      a2 = "2"
      a1 = 28.568436 - math.pi - -(0x1.6fad5e12af89p+6)
  end
  for _, _ in pairs(datum7) do
      v54 = tostring(33)
      a3 = "9"
  end
  if a1 <= 59.408345 then
      v56 = math.floor(a3 + 0x1) + - 43
  end
  return {t69 = a0}
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 boolean
-- @param a3 string
-- @param a4 float
-- @return function
function datum0:m21(a0, a1, a2, a3, a4, ...)
  local v71, v73 = -58, 3
  local v75, v77, v79, v81 = false, -17, "non ea Excepteur et", false
  v83, v85, v87 = [[incididunt
aute
ad
Lorem]], true, "Ut labore pariatur pariatur"
  v73 = tonumber(a3) + - string.len("laborum ut ut")
  if a4 ~= -0x1.acf2d04a4d758p+3 then
      a2 = true ~= not v75
  else
      a0 = "enim non" ~= "ut" ~= not true
      v73 = math.floor(a3 + 1) + - -28
      a3 = "3"
  end
  for i=17,0,2 do
      v73 = v71 + -(-38)
      a1 = 41.563850 + math.cos(49) + -(3.863879)
      a4 = math.pi - -(4.522671e+01)
  end
  for i=0,14 do
      a0 = true ~= false == "irure reprehenderit Ut" == a3 ~= not true
      v75 = "Excepteur cupidatat exercitation" == "aute consequat" == not true
      v75 = true == [[ut
in
anim
veniam]] == "elit nisi eiusmod" == not false
  end
  a4 = math.cos(-49) - -(math.pi)
  a4 = math.pi - -(math.sin(89))
  return nil
end

-- @param a0 int
-- @param a1 string
-- @param a2 int
-- @param a3 float
-- @param a4 boolean
-- @return int
function func27(a0, a1, a2, a3, a4)
  v89, v91, v93 = a3, a3, a4
  v95, v97, v99, v101 = a4, datum3, 71.906957, datum6
  if v89 == 26.443719 then
      v89 = math.pi + -(53.289283)
  end
  if a3 <= 1.335901 then
      v91 = 0x1.b1e05bd02b8bdp+5 + -(77.751952)
      a0 = -14 + -93 or - string.len([[in
et
cillum]])
  else
      a2 = math.floor(v91) or -(a2)
  end
  a3 = math.pi + -(math.sin(89))
  if a0 >= -17 then
      a1 = "1"
      a2 = math.floor(122.535949) or string.len("minim exercitation") or -(math.floor(90.716992))
      a1 = "1"
  else
      a2 = string.len("aute magna velit adipiscing") + - #("labore aliquip aute mollit")
  end
  return a0 or math.floor(a1 + 0) + a2 or math.floor(a3) or 88 + math.floor(v89) + - math.floor(v91)
end

-- @param a0 float
-- @param a1 int
-- @return function
local func33 = function (a0, a1)
  local v103, v105 = "cupidatat", datum6
  local v107, v109, v111 = -43, "Duis laboris ipsum", v103
  if v105 >= -43.065067 then
      a0 = math.pi - -(math.pi)
  end
  a1 = math.floor(129.874574) or - math.floor(a0)
  if datum4 ~= {} then
      v105 = math.abs(a1) - -(math.cos(7.827889))
  end
  a0 = math.pi - -(math.cos(a0))
  local cond113 = false
  while cond113 == true do
      a0 = math.pi + 52.408292 - -(math.sin(a0))
      v103 = [[eu
elit
commodo]]
      cond113 = true
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m12_a0 = [[1]]
local m12_a1 = [[ea
occaecat]]
local m12_a2 = "4"
local r_m12_0 = datum7:m12(m12_a0, m12_a1, m12_a2)
local func16_a0 = "Lorem"
local func16_a1 = 46.574623
local func16_a2 = "3"
local func16_a3 = "5"
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3)
local m21_a0 = true
local m21_a1 = 44.015809
local m21_a2 = true
local m21_a3 = "5"
local m21_a4 = 22.465058
local m21_vararg0 = true
local m21_vararg1 = 63.624569
local m21_vararg2 = -52
local r_m21_0 = datum0:m21(m21_a0, m21_a1, m21_a2, m21_a3, m21_a4, m21_vararg0, m21_vararg1, m21_vararg2)
local func27_a0 = -78
local func27_a1 = [[6]]
local func27_a2 = -81
local func27_a3 = 73.773405
local func27_a4 = true
local r_func27_0 = func27(func27_a0, func27_a1, func27_a2, func27_a3, func27_a4)
local func33_a0 = 82.013010
local func33_a1 = 86
local r_func33_0 = func33(func33_a0, func33_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = math.floor(datum3 + 2)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = math.floor(datum6)
local res_datum7 = #(datum7)
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = math.floor(datum11)
local res_r_m12_0 = #(r_m12_0)
local res_r_func16_0 = ms.table_to_int(r_func16_0)
local res_r_m21_0 = 1
local res_r_func27_0 = r_func27_0
local res_r_func33_0 = 0x1
RESULT = res_r_func33_0 + res_r_func27_0 - res_r_m21_0 + res_r_func16_0 - res_r_m12_0 + res_datum11 - res_datum9 + res_datum7 - res_datum6 + res_datum4 - res_datum3 - res_datum2 - res_datum0
print(math.floor(RESULT))