--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            734938972                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = {field1 = false}
local datum2 = {field3 = 1.324758e+02}
datum4 = {field5 = 9.578368}
local datum6 = 35.189709
datum7 = {field8 = -81}
datum9 = true
local datum10 = {field11 = 74}
local datum12 = "10"
datum13 = [[cupidatat
mollit]]
datum14 = {field15 = 166.335635}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @param a3 string
-- @param a4 float
-- @return function
local func16 = function (a0, a1, a2, a3, a4, ...)
  v36, v38, v40 = a4, false, datum13
  local v42, v44, v46 = a2, datum13, "3"
  local v48, v50, v52 = datum9, -9, a2
  local cond54 = true
  while cond54 == false do
      a0 = tostring(0)
      v36 = math.pi - 5.173073e+01 - -(math.abs(a4))
      cond54 = false
  end
  a1 = [[aliquip
amet]]
  v38 = [[ex
veniam
minim]] == "elit magna" ~= "proident tempor" ~= a1 == not true == true
  return nil
end

-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 float
-- @param a4 boolean
-- @return int
local func22 = function (a0, a1, a2, a3, a4)
  local v55, v57, v59 = "10", 63, [[Lorem
voluptate
minim]]
  local v61, v63 = "2", a0
  local cond65 = false
  while cond65 ~= false do
      a3 = math.pi - -(math.cos(83.712872))
      cond65 = true
  end
  a3 = math.abs(a1) + math.cos(-99) - -(17.192227)
  if v55 ~= "3" then
      a4 = a4 == not [[minim
in
dolor
in]] == a0
      a0 = "voluptate ut do pariatur"
      a3 = math.abs(9.706892) + -(math.pi)
  end
  if a1 > 38.394289 then
      a3 = math.abs(-18) - math.pi + -(math.sin(73))
  else
      a4 = true == not true
      a1 = math.pi - math.abs(a1) - -(math.abs(-42))
  end
  local cond67 = false
  while cond67 == true do
      v55 = "5"
      v55 = tostring(-83)
      cond67 = true
  end
  return #(a0) or math.floor(a1) + #(a2) + math.floor(a3) + -19 + tonumber(v55) + -(v57)
end

-- @param a0 string
-- @param a1 boolean
-- @return function
local func28 = function (a0, a1)
  local v68, v70 = 0x2b, -52
  v72, v74, v76 = datum9, "fugiat in", -86.991496
  local cond78 = true
  repeat
      a1 = false ~= false ~= not false == true
      v68 = 33 + -(string.len("cupidatat est ut cupidatat"))
      v68 = -64 - 21 or - -29
      cond78 = false
  until cond78 == false
  for _, _ in ipairs(datum0) do
      a0 = tostring(-48)
  end
  a0 = tostring(v70)
  local cond80 = 10
  repeat
      v68 = 80 + - v70
      cond80 = cond80 + 3
  until cond80 <= 22
  return nil
end

-- @param a0 int
-- @param a1 int
-- @param a2 float
-- @param a3 float
-- @return string
local func31 = function (a0, a1, a2, a3)
  local v81, v83, v85, v87 = "ipsum", datum13, 86, a3
  v89, v91, v93 = datum12, datum9, true
  if a3 > -88.876868 then
      a2 = math.sin(18.937784) + math.pi - -(math.pi)
  end
  a1 = math.floor(a3) + 80 or -(math.floor(a2))
  a1 = #(v81) + -(#("proident aliquip"))
  for _, _ in pairs(datum2) do
      a3 = math.cos(a0) + math.cos(-95) - -(math.pi)
      a0 = math.floor(197.827106) - string.len(v81) - - math.floor(a3)
  end
  a0 = #(v81) + -(string.len("ullamco in"))
  return "tempor"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func16_a0 = "2"
local func16_a1 = "adipiscing"
local func16_a2 = true
local func16_a3 = "dolore"
local func16_a4 = 9.686566
local func16_vararg0 = [[elit]]
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3, func16_a4, func16_vararg0)
local func22_a0 = "Excepteur nulla do"
local func22_a1 = 98.097429
local func22_a2 = [[eu]]
local func22_a3 = 44.995239
local func22_a4 = true
local r_func22_0 = func22(func22_a0, func22_a1, func22_a2, func22_a3, func22_a4)
local func28_a0 = "6"
local func28_a1 = true
local r_func28_0 = func28(func28_a0, func28_a1)
local func31_a0 = -77
local func31_a1 = 97
local func31_a2 = 5.354050
local func31_a3 = 7.655449
local r_func31_0 = func31(func31_a0, func31_a1, func31_a2, func31_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = datum9 and 1 or 0
local res_datum10 = #(datum10)
local res_datum12 = tonumber(datum12)
local res_datum13 = string.len(datum13)
local res_datum14 = #(datum14)
local res_r_func16_0 = 1
local res_r_func22_0 = r_func22_0
local res_r_func28_0 = 1
local res_r_func31_0 = #(r_func31_0)
RESULT = res_r_func31_0 + res_r_func28_0 - res_r_func22_0 + res_r_func16_0 - res_datum14 - res_datum13 + res_datum12 + res_datum10 + res_datum9 + res_datum7 - res_datum6 + res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))