--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            470754862                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
datum0 = -53
local datum1 = {field2 = -37}
datum3 = {field4 = "sunt consequat officia"}
datum5 = {field6 = true}
datum7 = {field8 = 28}
datum9 = 44.836517

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 float
-- @return boolean
function func10(a0, a1, ...)
  v26, v28 = 87, "1"
  v30, v32, v34 = false, "labore deserunt enim", -64
  local cond36 = false
  repeat
      a0 = true == true ~= "mollit ullamco commodo Ut" ~= "elit ut reprehenderit fugiat" ~= not "Duis elit elit" ~= v28
      a0 = true ~= true == not false
      cond36 = true
  until cond36 == true
  local cond37 = 6
  repeat
      a0 = a0 ~= not true
      cond37 = cond37 + 2
  until cond37 < 23
  if a1 >= 9.279279 then
      a1 = 9.907672 + -(0x1.866c6cc1502b8p+5)
  end
  if datum3 ~= {} then
      a0 = "ipsum Lorem ex" == v28 == not false
      v28 = tostring(math.floor(160.788738))
  end
  return a0 ~= false == true == not "ut laborum dolore" ~= v28
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return boolean
local func13 = function (a0, a1, a2, a3)
  v38, v40 = datum0, "et dolore"
  v42, v44, v46, v48 = a0, -72.432733, "4", true
  v50, v52 = false, -19.366907
  if datum5 == {} then
      a2 = a2
  end
  for i=10,3,2 do
      a2 = "4"
      v40 = "quis deserunt pariatur"
      a3 = tostring(math.floor(17.550430))
  end
  local cond54 = 4
  while cond54 <= 0x2C do
      a1 = "8"
      v38 = string.len(v42) + math.floor(a2 + 0x2) - - 96
      a1 = "10"
      cond54 = cond54 + 0x1
  end
  v40 = a0
  if v40 == "officia dolore" then
      v42 = "ut"
      v42 = "Ut dolor"
  end
  return "cupidatat qui irure" == a0 == "non adipiscing ut aute" ~= a1 ~= "fugiat consectetur" == a2 ~= "dolor id in" == a3 == true == "do nisi consequat" == v40 == not "in aliqua" ~= v42
end

-- @param a0 boolean
-- @return float
function func18(a0)
  local v58, v60 = "fugiat", false
  local v62, v64, v66, v68 = false, 27, a0, datum0
  v70, v72, v74, v76 = v58, datum0, -21.180794, "2"
  if v60 == true then
      a0 = true == true ~= not "veniam in magna" ~= "dolore consequat est"
  else
      v60 = true == "adipiscing dolor do dolore" == "irure irure Duis" ~= not false ~= v60
  end
  for i, v in pairs(datum5) do
      v60 = false ~= v60 == not false
      a0 = true ~= a0 ~= not "elit elit proident" ~= "officia ipsum pariatur culpa"
      a0 = true == true == false == not "id adipiscing veniam nulla" ~= v58
  end
  local cond81 = 9
  repeat
      v58 = "cillum nulla"
      a0 = false == true ~= true == not false
      a0 = "adipiscing dolore" ~= v58 ~= true == not false ~= a0
      cond81 = cond81 + 0x1
  until cond81 < 29
  v58 = [[reprehenderit
aute]]
  return 6.411082e+00 + math.pi - 83.922691 + -(34.101466)
end

-- @param a0 string
-- @return boolean
function func20(a0)
  local v82, v84, v86 = 74, "3", -87
  local v88, v90 = datum0, "Ut adipiscing"
  for _, _ in ipairs(datum5) do
      a0 = "ut ex"
  end
  local cond93 = 105
  while cond93 > 69 do
      v82 = 0x63 - - #(a0)
      cond93 = cond93 - 1
  end
  v82 = 85 + - #(a0)
  return "deserunt amet laboris" == a0 == false ~= not "quis enim laboris" ~= v84
end

-- @return boolean
function func22(...)
  v94, v96, v98 = "ad occaecat dolore", 80, false
  v100, v102, v104 = false, 62, "10"
  for _, _ in pairs(datum1) do
      v96 = math.floor(74.442138) - - #(v94)
      v94 = "amet ut"
      v96 = 61 or -(0x35)
  end
  v94 = "et dolor"
  for _, _ in pairs(datum7) do
      v94 = v94
      v96 = math.floor(178.094127) or -(v96)
      v94 = "occaecat magna in"
  end
  if datum5 ~= {} then
      v96 = v96 + -(v96)
      v94 = "consectetur esse Duis aliqua"
      v94 = "laboris"
  end
  return "esse sunt dolore dolore" == v94 ~= not true
end

-- @param a0 string
-- @param a1 float
-- @return function
local func23 = function (a0, a1)
  v113, v115, v117, v119 = -37.633084, "10", datum9, a0
  local v121, v123, v125 = a1, false, true
  local cond127 = 112
  repeat
      v115 = "6"
      v113 = math.tan(a1) - -(8.087999)
      cond127 = cond127 - 1
  until cond127 > 0x37
  v115 = "1"
  for i=20,0x3,3 do
      v115 = v115
      a0 = a0
  end
  for i=2,0xf,2 do
      a1 = math.cos(125.496573) + 78.575513 + -(math.abs(45))
  end
  if v115 ~= "3" then
      v115 = [[4]]
      a1 = 92.546933 - -(math.cos(40))
      a0 = "dolore est"
  else
      a1 = math.cos(-41) - -(math.pi)
      v113 = math.pi + -(math.pi)
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = true
local func10_a1 = 65.888856
local func10_vararg0 = true
local func10_vararg1 = false
local r_func10_0 = func10(func10_a0, func10_a1, func10_vararg0, func10_vararg1)
local func13_a0 = "et ipsum nisi"
local func13_a1 = "1"
local func13_a2 = "9"
local func13_a3 = "10"
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2, func13_a3)
local func18_a0 = true
local r_func18_0 = func18(func18_a0)
local func20_a0 = "pariatur reprehenderit nisi"
local r_func20_0 = func20(func20_a0)
local func22_vararg0 = "anim laboris"
local r_func22_0 = func22(func22_vararg0)
local func23_a0 = "do magna"
local func23_a1 = 70.069166
local r_func23_0 = func23(func23_a0, func23_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0
local res_datum1 = #(datum1)
local res_datum3 = ms.table_to_int(datum3)
local res_datum5 = #(datum5)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = math.floor(datum9)
local res_r_func10_0 = r_func10_0 and 1 or 0
local res_r_func13_0 = r_func13_0 and 1 or 0
local res_r_func18_0 = math.floor(r_func18_0)
local res_r_func20_0 = r_func20_0 and 0x1 or 0
local res_r_func22_0 = r_func22_0 and 1 or 0
local res_r_func23_0 = 1
RESULT = res_r_func23_0 + res_r_func22_0 - res_r_func20_0 - res_r_func18_0 + res_r_func13_0 - res_r_func10_0 - res_datum9 - res_datum7 - res_datum5 - res_datum3 - res_datum1 + res_datum0
print(math.floor(RESULT))