--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             47355123                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
datum0 = {field1 = true}
local datum2 = true
local datum3 = {field4 = false}
local datum5 = 64
local datum6 = "9"
datum7 = -100
datum8 = {field9 = "esse"}
local datum10 = 72

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @return int
function datum8:m11(a0, a1, a2)
  local v29, v31 = datum2, a0
  v33, v35, v37 = false, [[Ut]], "10"
  v39, v41, v43, v45 = v29, -6.190459e+01, 88, v29
  if a1 ~= "ut in consequat" then
      v29 = false ~= not "labore" ~= "eiusmod"
      a2 = 21.857344
      a1 = 176.529442
  else
      v33 = false ~= false ~= not "dolore quis ex" ~= "sint amet laborum"
  end
  local cond48 = 0
  while cond48 <= 38 do
      a0 = "9"
      a2 = "ut"
      cond48 = cond48 + 0x3
  end
  a2 = "enim elit sit"
  local cond50 = 6
  repeat
      a2 = "commodo in incididunt"
      a1 = "ex sint Excepteur"
      cond50 = cond50 + 0x2
  until cond50 < 37
  return math.floor(a0 + 0x3) or string.len(a1) - #(a2) or 3 - math.floor(v31 + 0x1) or -(-65)
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @param a3 boolean
-- @return table
local func15 = function (a0, a1, a2, a3)
  local v52, v54, v56, v58 = a2, "qui", "sit incididunt", datum6
  v60, v62 = -11, -14.525786
  v54 = "exercitation in dolore"
  a3 = "ut id culpa" ~= v52 ~= not a0
  for _, _ in pairs(datum8) do
      a2 = "occaecat consequat"
  end
  if a3 ~= false then
      a0 = a3 == "deserunt" == a1 == not false
  end
  a0 = false == not "et labore ex ipsum" == a2
  local cond67 = 8
  while cond67 < 36 do
      a0 = "nostrud ipsum" == v54 ~= true ~= not true
      v54 = "qui dolor dolor"
      cond67 = cond67 + 3
  end
  return {-2}
end

-- @return table
function func20()
  local v71, v73, v75, v77 = datum2, false, "Lorem reprehenderit ullamco", "proident in laborum"
  local v79, v81, v83 = "qui ex occaecat", "6", datum6
  v73 = true ~= v71 == not true
  v71 = true == v71 == not true ~= v71
  if v71 ~= false then
      v73 = false == false == v73 == not true
      v71 = [[dolor
deserunt
Lorem]] ~= "aliquip esse" ~= true ~= true == not v71
      v73 = v71 ~= not true
  end
  if datum10 < -92 then
      v73 = true ~= not false
  else
      v73 = true == true ~= not false
  end
  local cond85 = 4
  repeat
      v71 = true == v71 == not true == v73
      v73 = false ~= false ~= not false
      v73 = false ~= not false
      cond85 = cond85 + 2
  until cond85 < 33
  return {t86 = v71}
end

-- @param a0 int
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @param a4 string
-- @return float
function func21(a0, a1, a2, a3, a4)
  v88, v90, v92 = a4, true, "non ullamco occaecat"
  local v94, v96, v98, v100 = 52.606126, -18, a1, "et adipiscing"
  local v102, v104, v106 = v88, datum6, a2
  local cond108 = false
  repeat
      a0 = 48 or math.floor(a1) + -(37)
      a2 = "1"
      cond108 = true
  until cond108 == true
  a2 = "7"
  local cond109 = true
  repeat
      a3 = "6"
      v88 = "reprehenderit"
      cond109 = false
  until cond109 == false
  a2 = "2"
  return math.abs(a0) + math.cos(a1) + 56.817579 - math.pi + 73.002920 - 90.057264 - 97.643025 - -(math.pi)
end

-- @param a0 string
-- @return function
local func27 = function (a0)
  local v110, v112, v114, v116 = true, "10", a0, datum10
  local v118, v120, v122, v124 = datum6, "5", datum6, "9"
  local v126, v128, v130, v132 = "officia aliqua", datum5, true, v110
  for i=10,0,0x2 do
      v110 = false ~= v110 ~= not "commodo" ~= v112
  end
  v110 = "commodo sint enim" ~= v112 ~= true ~= not false
  local cond134 = false
  while cond134 ~= false do
      v110 = v110 ~= "do aliqua" ~= a0 ~= not false == false
      v110 = true ~= true ~= not false
      cond134 = true
  end
  v114 = "nisi officia"
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m11_a0 = "9"
local m11_a1 = "in commodo cupidatat"
local m11_a2 = "sint in fugiat"
local r_m11_0 = datum8:m11(m11_a0, m11_a1, m11_a2)
local func15_a0 = true
local func15_a1 = "2"
local func15_a2 = "nulla elit"
local func15_a3 = false
local r_func15_0 = func15(func15_a0, func15_a1, func15_a2, func15_a3)
local r_func20_0 = func20()
local func21_a0 = 25
local func21_a1 = 26.037549
local func21_a2 = "7"
local func21_a3 = "2"
local func21_a4 = "sit"
local r_func21_0 = func21(func21_a0, func21_a1, func21_a2, func21_a3, func21_a4)
local func27_a0 = [[occaecat
magna
enim
in]]
local r_func27_0 = func27(func27_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = datum2 and 1 or 0
local res_datum3 = #(datum3)
local res_datum5 = datum5
local res_datum6 = math.floor(datum6 + 2)
local res_datum7 = datum7
local res_datum8 = ms.table_to_int(datum8)
local res_datum10 = datum10
local res_r_m11_0 = r_m11_0
local res_r_func15_0 = ms.table_to_int(r_func15_0)
local res_r_func20_0 = #(r_func20_0)
local res_r_func21_0 = math.floor(r_func21_0)
local res_r_func27_0 = 1
RESULT = res_r_func27_0 + res_r_func21_0 - res_r_func20_0 + res_r_func15_0 - res_r_m11_0 - res_datum10 - res_datum8 - res_datum7 - res_datum6 - res_datum5 - res_datum3 + res_datum2 - res_datum0
print(math.floor(RESULT))