--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             44426272                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  9 statements)         --
--------------------------------------------------------
datum0 = {field1 = "et"}
local datum2 = {field3 = 118.803567}
local datum4 = {field5 = -82}
datum6 = -3
datum7 = "ut eu ad"
local datum8 = 69
local datum9 = true
datum10 = 79
datum11 = 68

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @return string
function datum2:m12()
  local v28, v30, v32 = [[5]], datum7, datum10
  local v34, v36, v38 = v28, false, -83.983947
  for _, _ in ipairs(datum4) do
      v28 = tostring(math.floor(108.206133))
      v30 = "pariatur eu nisi"
  end
  local cond42 = false
  repeat
      v28 = "3"
      cond42 = true
  until cond42 ~= false
  v28 = tostring(0xE)
  if v30 ~= "nulla sed Excepteur ex" then
      v30 = "Ut sint"
      v30 = "Lorem velit amet"
      v30 = "adipiscing ut aute"
  end
  local cond46 = 4
  while cond46 < 23 do
      v30 = v30
      v28 = v28
      cond46 = cond46 + 1
  end
  return "sint non ex"
end

-- @param a0 float
-- @return function
local func13 = function (a0)
  v48, v50, v52 = datum7, true, -33.823987
  v54, v56, v58 = true, "7", 36
  v60, v62, v64, v66 = "9", "non quis", v50, datum9
  a0 = math.abs(-13) - -(math.cos(13))
  local cond68 = true
  while cond68 ~= true do
      a0 = math.cos(v52) + math.pi + -(math.pi)
      v52 = math.pi + math.sin(a0) + -(math.tan(v52))
      cond68 = false
  end
  if a0 >= -15.373320 then
      v48 = "laborum Lorem"
  else
      v48 = "labore sit consectetur"
      a0 = 0x1.9154d1e628f12p+5 + -(math.abs(54))
  end
  return nil
end

-- @param a0 float
-- @return boolean
function datum4:m15(a0)
  local v70, v72 = datum9, "8"
  local v74, v76 = "minim in", -26.657283
  v72 = tostring(-41)
  if v70 ~= true then
      v70 = true ~= true ~= not "labore cupidatat esse" ~= "incididunt ut in"
      a0 = math.pi + 30.637057 + -(math.pi)
      a0 = math.pi - -(math.pi)
  end
  if a0 ~= 98.725537 then
      v72 = "4"
      v70 = false == not false == true
      a0 = math.abs(a0) - math.pi + -(62.662037)
  end
  a0 = math.pi - -(math.pi)
  if a0 >= -35.995470 then
      v72 = tostring(26)
      v72 = "8"
      v70 = "fugiat tempor sunt" == "in do" == not true
  else
      v70 = false == not [[non]] == v72
      v70 = false == "sint deserunt elit" ~= "in" == not [[qui
Lorem
magna
pariatur]] == v72
      a0 = 49.432524 - math.pi + -(64.732477)
  end
  return true ~= v70 == not "reprehenderit" == v72
end

-- @return int
function func17()
  v78, v80 = 47.243288, -43.923134
  v82, v84 = "1", false
  local v86, v88, v90 = "aute adipiscing", "9", datum7
  local cond92 = 7
  while cond92 <= 32 do
      v78 = math.sin(v80) + -(math.pi)
      v78 = 0.947888 + 74.432463 - -(math.abs(v80))
      cond92 = cond92 + 0x2
  end
  if v78 >= -83.033940 then
      v82 = v82
      v82 = "1"
  else
      v78 = 6.473243 - -(math.abs(v78))
      v80 = math.sin(v80) + -(math.pi)
  end
  if v80 <= -7.085861e+01 then
      v78 = math.sin(v80) - math.pi + -(math.sin(v80))
      v82 = tostring(math.floor(v80))
      v80 = 29.869772 - math.pi + -(math.cos(v78))
  else
      v78 = math.sin(25.072793) - -(math.pi)
  end
  if v80 == 0x1.1eeaee6c5ebap+6 then
      v78 = math.pi - math.cos(v80) + -(62.351290)
      v78 = math.sin(v80) + math.abs(7.729030e+00) - -(math.pi)
      v78 = math.tan(v80) + math.cos(v78) + -(24.672844)
  else
      v78 = math.sin(-97) + math.pi + -(math.cos(v78))
      v80 = 32.586537 + math.tan(11.679647) + -(36.196477)
      v80 = math.cos(v78) + math.cos(v80) - -(math.abs(-67))
  end
  return math.floor(v78) + math.floor(v80) or - math.floor(v82 + 1)
end

-- @param a0 int
-- @return function
function datum4:m18(a0)
  local v93, v95, v97 = -71, true, false
  local v99, v101, v103, v105 = -30.801432, "10", -60, "sunt elit eiusmod voluptate"
  local v107, v109 = true, "10"
  local cond111 = false
  repeat
      v97 = true ~= not false
      cond111 = true
  until cond111 ~= false
  if a0 >= 14 then
      v97 = false == not false
  end
  v95 = false == false == not true
  if v97 == false then
      v93 = a0 or - a0
      a0 = string.len([[veniam
esse
occaecat]]) + -(string.len("consectetur"))
      v93 = 34 - math.floor(176.567887) + - string.len("nisi Lorem do")
  end
  return nil
end

-- @return function
local func20 = function ()
  local v112, v114, v116 = 20.703539, false, "4"
  local v118, v120 = "ullamco aliqua", "3"
  for i=14,2 do
      v112 = math.pi + -(math.tan(v112))
      v112 = math.pi + -(math.abs(72.620021))
      v112 = math.pi + -(math.pi)
  end
  v112 = math.cos(77) - -(70.127350)
  if v114 ~= false then
      v114 = false == not false
  end
  local cond122 = 125
  while cond122 >= 0x39 do
      v112 = math.pi + 45.561172 - -(math.abs(v112))
      cond122 = cond122 - 2
  end
  return nil
end

-- @param a0 int
-- @param a1 int
-- @return nil
function datum4:m21(a0, a1)
  v123, v125, v127 = 24.010944, true, -25.600352
  local v129, v131 = 11, datum9
  local cond133 = 100
  repeat
      a0 = math.floor(v123) - 92 - -(98)
      v123 = math.pi + -(math.sin(0x1.86b71dfcff8ecp+6))
      cond133 = cond133 - 1
  until cond133 >= 0x47
  if v123 >= 86.510542 then
      v123 = math.sin(-85) + 71.969442 + -(82.884923)
      v125 = true == false ~= not false
  else
      v123 = 90.089520 + -(math.cos(41.155174))
      v123 = math.pi - math.pi + -(math.sin(a1))
      v125 = true ~= "sed reprehenderit" == [[anim
occaecat]] ~= not false
  end
  if datum6 >= -79 then
      a0 = 34 - - -44
  else
      v125 = "velit ullamco voluptate" ~= "consequat ullamco dolore" ~= true == not v125
      a1 = -52 + -1 or -(math.floor(0x1.c3d630c583037p+6))
  end
  for i, _ in pairs(datum4) do
      a1 = string.len("ut deserunt id") + math.floor(120.913789) + - #([[sint
dolore
enim]])
  end
  return true ~= false ~= true ~= not v125
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @return string
local func24 = function (a0, a1, a2)
  local v136, v138, v140 = datum7, [[3]], -3
  local v142, v144 = 88.948580, a1
  a1 = "labore" == a0 ~= not false ~= false
  if datum0 == {} then
      a0 = "1"
      a0 = "7"
      v136 = 144.643380
  else
      v138 = "6"
      v138 = "3"
      v138 = "10"
  end
  if a1 ~= true then
      a0 = "7"
      v136 = "voluptate"
      v138 = "6"
  else
      v138 = "8"
      v138 = [[9]]
      v136 = [[in
culpa]]
  end
  a1 = "consectetur ad" ~= "et Ut dolore" ~= "ut" == v138 ~= not false
  return "qui"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_m12_0 = datum2:m12()
local func13_a0 = 36.231142
local r_func13_0 = func13(func13_a0)
local m15_a0 = 73.899556
local r_m15_0 = datum4:m15(m15_a0)
local r_func17_0 = func17()
local m18_a0 = -11
local r_m18_0 = datum4:m18(m18_a0)
local r_func20_0 = func20()
local m21_a0 = 0x3b
local m21_a1 = -46
local r_m21_0 = datum4:m21(m21_a0, m21_a1)
local func24_a0 = [[10]]
local func24_a1 = true
local func24_a2 = "dolor"
local r_func24_0 = func24(func24_a0, func24_a1, func24_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = datum6
local res_datum7 = string.len(datum7)
local res_datum8 = datum8
local res_datum9 = datum9 and 1 or 0
local res_datum10 = datum10
local res_datum11 = datum11
local res_r_m12_0 = string.len(r_m12_0)
local res_r_func13_0 = 0x1
local res_r_m15_0 = r_m15_0 and 1 or 0
local res_r_func17_0 = r_func17_0
local res_r_m18_0 = 0x1
local res_r_func20_0 = 1
local res_r_m21_0 = 1
local res_r_func24_0 = #(r_func24_0)
RESULT = res_r_func24_0 - res_r_m21_0 + res_r_func20_0 + res_r_m18_0 + res_r_func17_0 + res_r_m15_0 - res_r_func13_0 - res_r_m12_0 - res_datum11 - res_datum10 - res_datum9 - res_datum8 + res_datum7 - res_datum6 - res_datum4 - res_datum2 - res_datum0
print(math.floor(RESULT))