--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             85493992                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = [[do
voluptate
ea]]}
datum2 = "8"
local datum3 = 0x1.d036f3bdeffap+4
local datum4 = "ut ipsum occaecat sint"
local datum5 = false
datum6 = {field7 = false}
local datum8 = "4"

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 float
-- @return float
function func9(a0, a1)
  local v32, v34 = -79, false
  local v36, v38 = datum5, true
  local v40, v42, v44 = a1, 3.085057e+01, 56.968072
  for i=0xe,1,3 do
      a0 = "enim anim elit"
      a1 = math.cos(v32) + math.pi + -(math.tan(185.187106))
  end
  if v34 == true then
      v36 = false ~= v34 ~= false ~= not false
  else
      a1 = 64.297927 - math.sin(a1) + -(math.pi)
  end
  if a0 ~= "exercitation" then
      a1 = math.pi + -(math.cos(158.044253))
      v34 = true == true ~= not true
      v32 = #("sunt laboris") + -(9)
  end
  a0 = 0x1.0d69f3cef1497p+7
  local cond48 = 118
  while cond48 > 0x46 do
      a0 = "Duis pariatur ut"
      cond48 = cond48 - 0x3
  end
  return math.pi + math.tan(a1) + math.abs(v32) - math.pi + -(math.pi)
end

-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @return string
function datum6:m12(a0, a1, a2, ...)
  v50, v52, v54, v56 = "in aliquip", true, -38, -79
  v58, v60 = datum5, v50
  if a1 == 51.445343 then
      a0 = "9"
      a2 = "3"
  end
  local cond62 = true
  while cond62 ~= true do
      v52 = true == v52 ~= not true
      v52 = [[sed
enim
occaecat]] == v50 ~= not true == true
      cond62 = false
  end
  if v50 == "occaecat non laborum ipsum" then
      v50 = 71.873345
  else
      a1 = math.pi - math.tan(97.383942) + -(math.cos(155.584406))
      v52 = v52 == not "ad aliqua mollit consectetur" == "pariatur"
  end
  v52 = false ~= false == not false
  return a0
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return boolean
function datum6:m16(a0, a1, a2, a3)
  local v64, v66, v68, v70 = 99.074973, -97, 58.283266, datum3
  v72, v74, v76 = -67, "dolor non quis sunt", -88
  v64 = math.tan(v64) + math.pi - -(0x1.7c069e86a1d53p+3)
  local cond78 = true
  while cond78 ~= true do
      a3 = "8"
      a2 = a3
      cond78 = false
  end
  for i=0x3,16,3 do
      a2 = tostring(math.floor(0x1.13b6e97187a53p+2))
  end
  return true ~= "ex" == a1 == "aliquip incididunt tempor non" ~= a2 == "reprehenderit eu laboris" ~= a3 ~= false == not false
end

-- @param a0 float
-- @param a1 string
-- @param a2 float
-- @return string
function func21(a0, a1, a2)
  v79, v81 = datum4, datum3
  local v83, v85, v87, v89 = [[ullamco
anim
pariatur
mollit]], "4", 0, 86.950467
  v91, v93 = 39, datum2
  for i, v in pairs(datum0) do
      v79 = v83
      a2 = math.pi - -(math.cos(117.395456))
      a2 = 69.939164 + -(40.991784)
  end
  v81 = math.sin(-76) - -(math.abs(81.948903))
  if datum2 ~= "4" then
      v79 = "voluptate Excepteur"
  end
  for i, v in pairs(datum0) do
      a2 = 5.702877 - math.pi - -(47.777988)
      a1 = "ut laborum"
  end
  for _, v in ipairs(datum0) do
      a1 = "sit fugiat in"
      v81 = math.cos(77.316309) + -(math.sin(v81))
  end
  return "elit Excepteur irure"
end

-- @param a0 int
-- @return float
function func25(a0)
  local v107, v109, v111, v113 = "2", a0, false, "2"
  local v115, v117, v119, v121 = 57, a0, v107, datum2
  for _, _ in pairs(datum6) do
      v107 = tostring(-96)
      v109 = -86 + string.len("minim dolore eu eu") or - -48
      v107 = tostring(a0)
  end
  for i=0x13,1,2 do
      v109 = a0 or 99 - -(#("exercitation ad"))
  end
  if a0 ~= -43 then
      a0 = a0 - - math.floor(v107 + 1)
  end
  v109 = tonumber(v107) or -13 - -(a0)
  return math.tan(a0) - math.pi - -(math.cos(v109))
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @return nil
local func27 = function (a0, a1, a2, a3)
  v124, v126, v128 = a1, 69.844395, -49
  v130, v132, v134 = datum8, true, datum4
  local v136, v138, v140, v142 = a0, 1.814391e+01, "9", "consectetur laborum"
  a1 = math.abs(v126) + math.pi + -(math.pi)
  a0 = a0 ~= not false
  v128 = -40 - -37 - - math.floor(v124)
  for i, _ in pairs(datum0) do
      a1 = 98.187354 + math.pi + -(math.pi)
  end
  return true ~= a0 == false == "amet dolor nostrud in" == a2 ~= "est Lorem" == a3 == true ~= false ~= not false
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func9_a0 = "sunt magna velit sit"
local func9_a1 = 48.759072
local r_func9_0 = func9(func9_a0, func9_a1)
local m12_a0 = [[7]]
local m12_a1 = 64.444728
local m12_a2 = "3"
local m12_vararg0 = 0x15
local r_m12_0 = datum6:m12(m12_a0, m12_a1, m12_a2, m12_vararg0)
local m16_a0 = 89.291744
local m16_a1 = "ipsum in"
local m16_a2 = "7"
local m16_a3 = [[7]]
local r_m16_0 = datum6:m16(m16_a0, m16_a1, m16_a2, m16_a3)
local func21_a0 = 71.047525
local func21_a1 = "in tempor ad cillum"
local func21_a2 = 9.686190
local r_func21_0 = func21(func21_a0, func21_a1, func21_a2)
local func25_a0 = 40
local r_func25_0 = func25(func25_a0)
local func27_a0 = false
local func27_a1 = 64.124975
local func27_a2 = "deserunt do Ut"
local func27_a3 = "10"
local r_func27_0 = func27(func27_a0, func27_a1, func27_a2, func27_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = tonumber(datum2)
local res_datum3 = math.floor(datum3)
local res_datum4 = #(datum4)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = #(datum6)
local res_datum8 = tonumber(datum8)
local res_r_func9_0 = math.floor(r_func9_0)
local res_r_m12_0 = math.floor(r_m12_0 + 2)
local res_r_m16_0 = r_m16_0 and 0x1 or 0
local res_r_func21_0 = #(r_func21_0)
local res_r_func25_0 = math.floor(r_func25_0)
local res_r_func27_0 = 1
RESULT = res_r_func27_0 + res_r_func25_0 - res_r_func21_0 + res_r_m16_0 - res_r_m12_0 + res_r_func9_0 + res_datum8 - res_datum6 - res_datum5 + res_datum4 + res_datum3 - res_datum2 + res_datum0
print(math.floor(RESULT))