--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:           1017476036                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
local datum0 = "irure laborum laboris"
local datum1 = -96
datum2 = true
datum3 = 36
datum4 = "sint nisi minim est"
local datum5 = true
local datum6 = true
datum7 = "dolor commodo"

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @return string
local func8 = function (a0)
  v35, v37, v39 = datum5, [[7]], 94.278705
  local v41, v43 = datum6, a0
  local v45, v47 = v37, 59
  if v35 ~= false then
      a0 = "ut amet reprehenderit"
      a0 = a0
      a0 = "culpa dolor tempor"
  else
      a0 = "et sunt"
  end
  local cond52 = false
  while cond52 ~= false do
      v37 = tostring(math.floor(v39))
      v35 = "amet deserunt Duis sunt" == "incididunt magna" == not false == false
      a0 = "ea enim"
      cond52 = true
  end
  if v37 == "6" then
      a0 = "esse culpa"
      v35 = v35 == true == not "aliquip pariatur laborum" ~= a0
      a0 = "irure Duis"
  end
  v37 = tostring(math.floor(59.559992))
  for i, v in pairs({}) do
      v35 = true == true ~= false == v35 == not false ~= false
      a0 = "quis ea"
  end
  return "4"
end

-- @param a0 float
-- @return nil
local func10 = function (a0)
  local v59, v61 = [[exercitation]], [[2]]
  local v63, v65 = false, 59
  local cond67 = 114
  while cond67 >= 70 do
      v61 = "2"
      v59 = "aute laboris mollit quis"
      cond67 = cond67 - 0x1
  end
  v59 = v59
  a0 = math.pi - -(34.911524)
  return true ~= "culpa non" ~= v59 ~= not "anim" == v61
end

-- @param a0 float
-- @param a1 string
-- @param a2 int
-- @param a3 float
-- @param a4 int
-- @return string
local func12 = function (a0, a1, a2, a3, a4, ...)
  local v68, v70, v72 = 57, false, "in"
  local v74, v76, v78, v80 = "consectetur consectetur", "3", 15.193634, a3
  v82, v84 = "incididunt nostrud est", v70
  local cond86 = false
  while cond86 == true do
      v68 = -26 + 30 or -(a2)
      a3 = math.pi - math.pi - -(math.tan(198.466222))
      cond86 = true
  end
  for i, _ in pairs({}) do
      a3 = 39.162364 + -(math.pi)
  end
  local cond89 = true
  while cond89 ~= true do
      v70 = false == not true == v70
      a1 = tostring(math.floor(15.336331))
      cond89 = false
  end
  local cond90 = 110
  repeat
      a1 = "8"
      v72 = "ut laborum"
      cond90 = cond90 - 3
  until cond90 > 50
  return tostring(math.floor(a0))
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 int
-- @param a3 float
-- @return boolean
function func18(a0, a1, a2, a3)
  local v91, v93, v95 = 22, "5", true
  local v97, v99 = 66.664873, "labore dolor minim"
  local cond101 = false
  repeat
      v93 = tostring(math.floor(125.026840))
      a1 = false == "consequat laborum" == "quis" ~= not true
      cond101 = true
  until cond101 == true
  if a1 == false then
      a2 = #("nostrud fugiat") + - 18
      a0 = math.pi + math.tan(a3) - -(95.357599)
      a0 = math.pi + -(math.sin(189.984703))
  else
      v93 = "2"
  end
  local cond102 = 5
  repeat
      a1 = false == not true
      v91 = #([[Lorem]]) + - -46
      cond102 = cond102 + 3
  until cond102 < 32
  return false ~= a1 == false ~= true == false == not "exercitation officia consectetur" == v93
end

-- @param a0 float
-- @return string
local func23 = function (a0, ...)
  v103, v105 = 48.495616, "1"
  v107, v109, v111, v113 = true, "5", datum3, "9"
  v115, v117 = true, -89.821845
  for _, v in ipairs({}) do
      v103 = 44.601875 + -(math.pi)
      v105 = "10"
  end
  v107 = true == not false
  local cond121 = true
  repeat
      a0 = math.pi + -(math.sin(v103))
      a0 = math.sin(0x1.53d8cd5608e7cp+2) - math.abs(-68) - -(math.abs(a0))
      cond121 = false
  until cond121 == false
  if v105 ~= "10" then
      v107 = true ~= not false == v107
      a0 = math.cos(a0) + math.cos(170.037074) - -(math.cos(-88))
  else
      a0 = 18.664042 - -(85.905481)
      v103 = 1.306662 - -(math.tan(a0))
      v103 = math.pi + -(24.193591)
  end
  v107 = true == true == false ~= not "ad" == "consectetur ad do"
  return tostring(math.floor(a0))
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 float
-- @param a3 float
-- @param a4 string
-- @return float
local func25 = function (a0, a1, a2, a3, a4)
  local v122, v124, v126, v128 = a1, datum2, a2, -88
  v130, v132, v134, v136 = 86, a2, v122, 55.779644
  v138, v140, v142, v144 = -25.802451, a3, datum4, a2
  a3 = 36.924568 + 49.015227 + -(math.pi)
  local cond146 = 0x6c
  repeat
      a4 = "minim ea sint quis"
      cond146 = cond146 - 2
  until cond146 > 64
  a0 = "ea in" ~= "nostrud" == false == not true
  return math.pi + math.pi - math.cos(a2) - math.abs(a3) - 17.279194 + math.pi + math.pi + -(math.cos(v126))
end

-- @param a0 boolean
-- @param a1 float
-- @return table
function func31(a0, a1)
  local v148, v150 = 33, datum4
  v152, v154, v156 = datum1, "deserunt sit Excepteur dolore", a0
  local v158, v160, v162 = 36.655380, -3.774162, 17
  if a1 >= 97.179196 then
      v150 = "nulla ut quis"
  end
  for _, v in pairs({}) do
      v148 = math.floor(73.544508) or -(-47)
      a0 = true == true ~= false ~= not false
      a1 = 47.869237 - -(math.abs(56))
  end
  v152 = 57 + - 19
  if a1 > -87.355547 then
      a1 = math.sin(a1) - math.pi - -(math.pi)
  end
  for i=1,11,2 do
      v152 = -6 or #("sit laboris aute") or -(65)
      a1 = math.pi - -(math.abs(-57))
      a1 = math.cos(20.022882) + -(math.cos(99))
  end
  local cond166 = true
  while cond166 ~= true do
      v150 = "qui et aute officia"
      a0 = true == false == not false
      cond166 = false
  end
  return {-9}
end

-- @return table
local func34 = function ()
  v169, v171 = "4", "laboris deserunt"
  local v173, v175, v177, v179 = 71.195915, 88.126476, 75.281431, -67.773681
  v181, v183, v185 = "2", datum2, datum5
  if v173 < -84.986995 then
      v169 = v169
      v173 = math.pi + -(44.864081)
      v171 = "aute laborum consectetur"
  else
      v171 = "deserunt Lorem ea"
      v169 = "7"
      v173 = math.cos(0x1.5a4f49608d682p+7) + math.pi + -(math.pi)
  end
  local cond188 = false
  repeat
      v171 = "nostrud ea dolore"
      cond188 = true
  until cond188 ~= false
  local cond190 = 0
  repeat
      v169 = "3"
      cond190 = cond190 + 1
  until cond190 <= 0x17
  if v173 >= -5.709589 then
      v173 = 15.565249 + -(math.pi)
      v169 = "5"
      v171 = "ut in"
  end
  return {0}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = "consectetur do"
local r_func8_0 = func8(func8_a0)
local func10_a0 = 2.670590
local r_func10_0 = func10(func10_a0)
local func12_a0 = 73.525301
local func12_a1 = "9"
local func12_a2 = -96
local func12_a3 = 90.766513
local func12_a4 = 91
local func12_vararg0 = -72
local func12_vararg1 = "dolor"
local r_func12_0 = func12(func12_a0, func12_a1, func12_a2, func12_a3, func12_a4, func12_vararg0, func12_vararg1)
local func18_a0 = 1.284587e+00
local func18_a1 = true
local func18_a2 = 31
local func18_a3 = 1.014916
local r_func18_0 = func18(func18_a0, func18_a1, func18_a2, func18_a3)
local func23_a0 = 22.099716
local func23_vararg0 = "ad aute"
local func23_vararg1 = 65.323952
local r_func23_0 = func23(func23_a0, func23_vararg0, func23_vararg1)
local func25_a0 = true
local func25_a1 = "6"
local func25_a2 = 5.083335e+01
local func25_a3 = 84.422832
local func25_a4 = [[enim]]
local r_func25_0 = func25(func25_a0, func25_a1, func25_a2, func25_a3, func25_a4)
local func31_a0 = true
local func31_a1 = 96.126537
local r_func31_0 = func31(func31_a0, func31_a1)
local r_func34_0 = func34()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = string.len(datum0)
local res_datum1 = datum1
local res_datum2 = datum2 and 1 or 0
local res_datum3 = datum3
local res_datum4 = #(datum4)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = datum6 and 1 or 0
local res_datum7 = #(datum7)
local res_r_func8_0 = tonumber(r_func8_0)
local res_r_func10_0 = 1
local res_r_func12_0 = math.floor(r_func12_0 + 3)
local res_r_func18_0 = r_func18_0 and 1 or 0
local res_r_func23_0 = tonumber(r_func23_0)
local res_r_func25_0 = math.floor(r_func25_0)
local res_r_func31_0 = ms.table_to_int(r_func31_0)
local res_r_func34_0 = #(r_func34_0)
RESULT = res_r_func34_0 - res_r_func31_0 + res_r_func25_0 + res_r_func23_0 + res_r_func18_0 + res_r_func12_0 - res_r_func10_0 - res_r_func8_0 - res_datum7 + res_datum6 + res_datum5 + res_datum4 - res_datum3 + res_datum2 - res_datum1 - res_datum0
print(math.floor(RESULT))