--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            890861070                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = {field1 = 40.595347}
datum2 = [[6]]
local datum3 = 18.069168
local datum4 = 6.564920e+01
datum5 = {field6 = true}
local datum7 = {field8 = 85.914536}
local datum9 = {field10 = -56}
local datum11 = true
datum12 = "id Duis occaecat"
local datum13 = {field14 = 1.383001e+02}

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @return float
function datum9:m15(a0)
  local v32, v34, v36 = -75, 10, datum4
  local v38, v40 = "amet ullamco irure", datum3
  a0 = 90.101754
  local cond43 = false
  while cond43 ~= false do
      a0 = "commodo ipsum in"
      a0 = "incididunt magna aute"
      cond43 = true
  end
  if datum2 ~= "5" then
      v34 = v32 + - #("proident")
      v34 = -69 + - #("tempor id")
      v32 = string.len("ut esse ex") - -(48)
  else
      v34 = -49 or 1 + - math.floor(4.958603)
  end
  local cond45 = 0
  while cond45 <= 40 do
      v34 = #("ullamco ullamco") or math.floor(80.142524) or -(-11)
      cond45 = cond45 + 2
  end
  return 58.752381 + math.abs(v32) - -(math.abs(v34))
end

-- @param a0 int
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @param a4 float
-- @return table
local func17 = function (a0, a1, a2, a3, a4)
  local v46, v48, v50, v52 = datum11, 20.743978, a4, true
  local v54, v56, v58 = datum11, datum11, [[non
et
enim
aute]]
  local v60, v62 = -95, a2
  if datum5 == {} then
      a0 = string.len(a2) or -(math.floor(v50))
  end
  v48 = math.abs(85) - -(0x1.76a70beed829cp+4)
  if v46 == false then
      a3 = tostring(math.floor(v50))
  else
      a0 = #([[sed]]) + 44 or -(tonumber(a3))
  end
  a2 = "enim amet eiusmod"
  a4 = math.pi - math.abs(a4) - -(math.sin(178.601065))
  return {3}
end

-- @return string
local func23 = function ()
  local v67, v69, v71, v73 = datum4, datum11, false, [[2]]
  local v75, v77, v79, v81 = -50, "sint", "1", -19
  for i=2,19 do
      v67 = math.sin(v67) - -(math.cos(0x1.607d5518224abp+7))
      v67 = 46.823382 - 21.264146 + -(math.abs(6.430558))
  end
  if v67 < 54.688149 then
      v69 = v69 == false ~= v69 ~= not v69
      v67 = math.pi - -(math.cos(-89))
  else
      v69 = false ~= false == v69 ~= not false
  end
  v69 = "incididunt pariatur est" ~= "culpa ad" ~= true == true ~= not true ~= true
  local cond83 = true
  repeat
      v67 = math.sin(8.864707e+01) - -(math.cos(v67))
      v69 = true ~= not false
      v69 = false ~= true == false ~= not true
      cond83 = false
  until cond83 ~= true
  return [[proident
enim]]
end

-- @return int
function func24()
  v85, v87, v89 = "10", datum11, "7"
  v91, v93 = -26, -12
  local cond95 = false
  repeat
      v85 = v85
      v87 = "ullamco voluptate voluptate" == "eiusmod Duis tempor" ~= not false == true
      v87 = "sed anim deserunt" ~= [[et
id
ipsum]] == not false
      cond95 = true
  until cond95 ~= false
  if datum3 ~= -2.090593 then
      v85 = "6"
      v85 = "6"
      v87 = false ~= false == "sit Excepteur" == "eu in mollit" == not "pariatur" ~= v85
  end
  v87 = true ~= true ~= not false
  local cond96 = true
  repeat
      v85 = "5"
      cond96 = false
  until cond96 ~= true
  return tonumber(v85) or -(-31)
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @return string
function datum13:m25(a0, a1, a2, a3)
  v97, v99 = -42, a3
  local v101, v103, v105, v107 = -4.215194, "1", a0, a3
  v99 = "8"
  a0 = math.floor(v99 + 0) + -(-18)
  v97 = -18 + math.floor(v99 + 2) or - string.len("nulla eu nostrud")
  a2 = "labore"
  for _, _ in ipairs(datum5) do
      v99 = "10"
      a2 = a2
  end
  for i, _ in ipairs(datum9) do
      v99 = tostring(math.floor(32.083574))
  end
  return "in eu proident"
end

-- @param a0 int
-- @return table
function func30(a0)
  v115, v117 = -21.874968, [[laborum
labore]]
  v119, v121, v123 = true, false, datum4
  local v125, v127 = true, "3"
  if v117 == "id laboris incididunt" then
      v117 = "veniam reprehenderit"
  end
  local cond129 = 115
  repeat
      v119 = [[sint
est]] == [[Excepteur
nulla]] ~= not false
      cond129 = cond129 - 3
  until cond129 >= 57
  a0 = -42 or - -88
  local cond130 = 9
  repeat
      a0 = math.floor(25.268928) or #("est laborum") or - 0x4
      cond130 = cond130 + 3
  until cond130 < 25
  return {a0}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m15_a0 = "laboris occaecat"
local r_m15_0 = datum9:m15(m15_a0)
local func17_a0 = 0x35
local func17_a1 = "10"
local func17_a2 = "ea esse do"
local func17_a3 = "9"
local func17_a4 = 25.255821
local r_func17_0 = func17(func17_a0, func17_a1, func17_a2, func17_a3, func17_a4)
local r_func23_0 = func23()
local r_func24_0 = func24()
local m25_a0 = -36
local m25_a1 = true
local m25_a2 = "anim laborum laboris"
local m25_a3 = "5"
local r_m25_0 = datum13:m25(m25_a0, m25_a1, m25_a2, m25_a3)
local func30_a0 = -59
local r_func30_0 = func30(func30_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = tonumber(datum2)
local res_datum3 = math.floor(datum3)
local res_datum4 = math.floor(datum4)
local res_datum5 = ms.table_to_int(datum5)
local res_datum7 = #(datum7)
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = datum11 and 1 or 0
local res_datum12 = string.len(datum12)
local res_datum13 = ms.table_to_int(datum13)
local res_r_m15_0 = math.floor(r_m15_0)
local res_r_func17_0 = ms.table_to_int(r_func17_0)
local res_r_func23_0 = string.len(r_func23_0)
local res_r_func24_0 = r_func24_0
local res_r_m25_0 = #(r_m25_0)
local res_r_func30_0 = ms.table_to_int(r_func30_0)
RESULT = res_r_func30_0 - res_r_m25_0 - res_r_func24_0 + res_r_func23_0 + res_r_func17_0 - res_r_m15_0 - res_datum13 - res_datum12 + res_datum11 + res_datum9 - res_datum7 - res_datum5 - res_datum4 - res_datum3 + res_datum2 - res_datum0
print(math.floor(RESULT))