--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            983279979                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = 0x1.7a47cfa76aa9ep+7}
local datum2 = {field3 = "nulla consequat magna"}
local datum4 = {field5 = "do et ut in"}
datum6 = "6"
local datum7 = {field8 = 96}
datum9 = false
local datum10 = 96.418291

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 float
-- @param a2 string
-- @param a3 float
-- @param a4 string
-- @return table
function func11(a0, a1, a2, a3, a4, ...)
  local v37, v39, v41, v43 = datum10, "5", -87.330005, datum9
  local v45, v47 = "4", a1
  v49, v51 = -69, "id cillum pariatur"
  local cond53 = true
  while cond53 ~= true do
      a4 = v39
      v39 = "8"
      cond53 = false
  end
  if a0 == false then
      a4 = tostring(math.floor(24.348712))
      a1 = 40.905335 - math.cos(a3) - -(math.abs(a3))
      a1 = 0.303601 - math.pi + -(math.pi)
  else
      a2 = tostring(math.floor(172.299685))
  end
  a1 = math.abs(160.310290) + -(16.890784)
  return {t54 = a0}
end

-- @param a0 float
-- @param a1 string
-- @param a2 float
-- @param a3 float
-- @param a4 int
-- @return table
function datum4:m17(a0, a1, a2, a3, a4)
  v56, v58, v60 = datum6, -30, 0x1B
  local v62, v64, v66, v68 = datum10, a1, datum10, "magna labore aliquip do"
  v70, v72 = datum10, datum10
  if a4 >= 62 then
      a4 = v60 or - a4
  end
  local cond74 = 3
  repeat
      v56 = tostring(math.floor(30.495290))
      cond74 = cond74 + 3
  until cond74 <= 28
  a1 = "voluptate veniam"
  return {a0}
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 string
-- @param a3 boolean
-- @return string
local func23 = function (a0, a1, a2, a3, ...)
  v76, v78, v80, v82 = a2, -64, 55, datum10
  local v84, v86 = "5", v76
  v88, v90 = a1, 50
  a2 = "8"
  local cond92 = false
  while cond92 ~= false do
      a2 = tostring(v78)
      cond92 = true
  end
  local cond93 = 113
  repeat
      a0 = v80 or - math.floor(a2 + 0)
      a3 = false == not false
      v80 = math.floor(0x1.27a998421bacbp+7) + v80 - -(-49)
      cond93 = cond93 - 0x3
  until cond93 > 70
  return tostring(a0)
end

-- @param a0 boolean
-- @param a1 int
-- @param a2 int
-- @return boolean
function datum4:m28(a0, a1, a2)
  v94, v96 = 2, a0
  v98, v100, v102, v104 = 34, "7", a0, datum10
  v106, v108 = -26.662132, 21
  local cond110 = 1
  while cond110 <= 49 do
      a0 = false == false ~= false == true == not a0
      v98 = math.floor(50.595969) or -1 or -(math.floor(126.190758))
      a2 = -49 or - -61
      cond110 = cond110 + 1
  end
  local cond111 = true
  while cond111 == false do
      a0 = true == true ~= v96 == not false
      cond111 = false
  end
  return a0 ~= true == false == false ~= false == v96 == not true
end

-- @param a0 boolean
-- @param a1 string
-- @return float
function datum2:m32(a0, a1)
  local v112, v114, v116 = "consequat dolor aliquip", [[sint]], datum9
  local v118, v120, v122, v124 = datum6, "ullamco dolor dolor", -24, datum10
  v126, v128 = v112, 66
  if v112 == "ut pariatur" then
      v114 = 101.826197
  else
      v114 = [[magna
magna]]
      v112 = "qui"
      a1 = tostring(29)
  end
  if a1 ~= "9" then
      v112 = "adipiscing nostrud pariatur ut"
      v114 = "voluptate"
      v114 = "aliquip culpa sunt"
  else
      a1 = tostring(math.floor(130.179167))
      v116 = false == v116 == not true
  end
  for i=3,0xC,2 do
      v116 = "pariatur Duis" == a1 ~= not false == true
      v114 = "adipiscing fugiat"
      a1 = tostring(-18)
  end
  if a1 == "10" then
      v116 = "consectetur magna occaecat" == v112 == not true == a0
      a1 = "7"
  else
      v112 = "adipiscing tempor"
  end
  return 30.381703 - math.pi + 18.804559 - math.pi - -(math.pi)
end

-- @return boolean
function func35()
  local v136, v138, v140, v142 = true, "1", "3", 81
  v144, v146, v148, v150 = "cupidatat", 96, "5", "in aliqua laboris velit"
  v152, v154, v156 = false, false, -35
  v136 = "deserunt nisi" ~= v138 == not false
  v136 = [[velit
occaecat
sunt]] ~= v138 == true ~= true ~= not [[tempor
in
ullamco
aliquip]] == v138
  v138 = tostring(4)
  local cond158 = 119
  repeat
      v140 = "6"
      cond158 = cond158 - 0x1
  until cond158 > 63
  return v136 == "anim aute" == v138 == not "elit" ~= v140
end

-- @return table
function datum2:m36()
  v159, v161, v163, v165 = 45, "sit deserunt reprehenderit fugiat", [[ut
eiusmod
consequat
velit]], -41.445650
  local v167, v169 = v159, -94.797884
  v161 = "consequat sed consectetur"
  if v161 == "commodo esse in" then
      v159 = -70 - 21 or - #("est mollit")
      v159 = -21 or -(string.len("dolore incididunt fugiat"))
      v161 = "aliquip exercitation fugiat"
  else
      v161 = [[proident
ut]]
  end
  v159 = -90 or - math.floor(147.292819)
  for i=15,3,2 do
      v161 = "dolor aute"
  end
  for i, _ in pairs(datum7) do
      v161 = "velit"
      v159 = v159 or string.len("dolor occaecat ullamco") or - 61
      v161 = "sunt magna amet"
  end
  local cond177 = false
  repeat
      v159 = 0x28 - -(20)
      v159 = -85 or #(v161) or -(string.len("proident culpa enim"))
      v159 = #("labore do consequat") + -83 or -(string.len(v161))
      cond177 = true
  until cond177 == true
  return {v159}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func11_a0 = false
local func11_a1 = 75.798684
local func11_a2 = "1"
local func11_a3 = 37.014183
local func11_a4 = "7"
local func11_vararg0 = "ipsum ut"
local func11_vararg1 = 24
local r_func11_0 = func11(func11_a0, func11_a1, func11_a2, func11_a3, func11_a4, func11_vararg0, func11_vararg1)
local m17_a0 = 6.997161e+01
local m17_a1 = "deserunt deserunt tempor ad"
local m17_a2 = 0x1.309dcacf1277cp+6
local m17_a3 = 44.960813
local m17_a4 = 83
local r_m17_0 = datum4:m17(m17_a0, m17_a1, m17_a2, m17_a3, m17_a4)
local func23_a0 = -26
local func23_a1 = false
local func23_a2 = "8"
local func23_a3 = true
local func23_vararg0 = 4.981601
local func23_vararg1 = "cupidatat"
local func23_vararg2 = 89
local r_func23_0 = func23(func23_a0, func23_a1, func23_a2, func23_a3, func23_vararg0, func23_vararg1, func23_vararg2)
local m28_a0 = true
local m28_a1 = -68
local m28_a2 = -41
local r_m28_0 = datum4:m28(m28_a0, m28_a1, m28_a2)
local m32_a0 = true
local m32_a1 = [[3]]
local r_m32_0 = datum2:m32(m32_a0, m32_a1)
local r_func35_0 = func35()
local r_m36_0 = datum2:m36()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6 + 2)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = datum9 and 1 or 0
local res_datum10 = math.floor(datum10)
local res_r_func11_0 = ms.table_to_int(r_func11_0)
local res_r_m17_0 = #(r_m17_0)
local res_r_func23_0 = math.floor(r_func23_0 + 0)
local res_r_m28_0 = r_m28_0 and 0x1 or 0
local res_r_m32_0 = math.floor(r_m32_0)
local res_r_func35_0 = r_func35_0 and 1 or 0
local res_r_m36_0 = #(r_m36_0)
RESULT = res_r_m36_0 + res_r_func35_0 - res_r_m32_0 - res_r_m28_0 + res_r_func23_0 - res_r_m17_0 - res_r_func11_0 - res_datum10 + res_datum9 - res_datum7 + res_datum6 - res_datum4 - res_datum2 - res_datum0
print(math.floor(RESULT))