--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            779078582                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
datum0 = false
datum1 = false
local datum2 = false
local datum3 = -38
datum4 = "10"
datum5 = {field6 = 114.616773}
local datum7 = "7"
local datum8 = "8"

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 float
-- @return string
function datum5:m9(a0, a1, ...)
  v31, v33, v35 = "dolor", a1, -41.209680
  local v37, v39 = [[esse
nulla]], "voluptate Excepteur in incididunt"
  local v41, v43, v45, v47 = -84, true, -21, "4"
  local cond49 = false
  while cond49 ~= false do
      a0 = "2"
      a1 = 9.945381e+01 + math.abs(-69) + -(58.691194)
      a0 = [[7]]
      cond49 = true
  end
  if v31 == "reprehenderit eiusmod sit" then
      v33 = math.sin(165.346893) - math.cos(14.810724) + -(math.sin(10))
      v31 = "aute"
  end
  a1 = math.cos(v33) + -(48.949071)
  v33 = math.pi - -(math.sin(177.347351))
  for i=3,13 do
      a0 = tostring(math.floor(a1))
      v31 = v35
  end
  return a0
end

-- @param a0 boolean
-- @param a1 string
-- @return string
local func12 = function (a0, a1)
  local v51, v53, v55, v57 = a1, a0, datum2, false
  local v59, v61, v63, v65 = -7, a0, -29, -48
  local cond67 = 117
  while cond67 > 57 do
      v53 = false == false ~= not false ~= a0
      v51 = [[3]]
      cond67 = cond67 - 1
  end
  for i, _ in ipairs(datum5) do
      v51 = tostring(7)
      a1 = "4"
  end
  local cond70 = 3
  while cond70 <= 23 do
      a1 = "9"
      v53 = "proident irure ad" == "quis ut" ~= false == not true
      cond70 = cond70 + 1
  end
  return "4"
end

-- @param a0 float
-- @param a1 string
-- @return string
function datum5:m15(a0, a1)
  local v71, v73, v75, v77 = datum3, datum7, -9.826336e+01, false
  v79, v81, v83, v85 = -14.098956, "elit in sint dolore", "id", 73
  local v87, v89, v91, v93 = true, "3", -1.055358e+01, true
  if datum3 <= -55 then
      a0 = math.abs(v71) + math.abs(88) + -(math.abs(74))
      v71 = math.floor(0x1.5ab227394caf3p+5) - 40 or -(-99)
      v71 = math.floor(105.020983) or - math.floor(a1 + 0x2)
  else
      a1 = tostring(-52)
  end
  for i=4,18 do
      v75 = math.sin(95.217458) - -(49.551147)
      a1 = "7"
      v75 = math.pi - -(math.pi)
  end
  local cond95 = true
  repeat
      v71 = math.floor(192.829794) or math.floor(a0) + - #("esse est")
      cond95 = false
  until cond95 == false
  a1 = "2"
  return tostring(math.floor(a0))
end

-- @param a0 float
-- @return table
local func18 = function (a0, ...)
  local v96, v98, v100, v102 = datum8, a0, 19.693393, datum4
  local v104, v106, v108 = -34, datum3, "dolore"
  v110, v112, v114, v116 = "magna", 8.996810e+01, "1", v96
  v98 = math.pi - 85.916187 - -(37.614648)
  if v98 > 21.675834 then
      a0 = 50.673608 + -(30.357173)
      v98 = math.pi + -(5.914119e+01)
      v96 = v96
  else
      v98 = math.cos(v98) - math.pi - -(math.tan(191.242692))
      a0 = math.pi + math.pi + -(math.cos(v98))
  end
  v96 = "5"
  v98 = math.sin(-42) - 55.412095 + -(math.tan(a0))
  local cond118 = true
  repeat
      a0 = math.abs(v98) - -(math.pi)
      cond118 = false
  until cond118 ~= true
  return {a0}
end

-- @param a0 boolean
-- @param a1 int
-- @param a2 string
-- @param a3 float
-- @return string
function datum5:m20(a0, a1, a2, a3, ...)
  v120, v122, v124 = a3, datum2, a0
  local v126, v128, v130, v132 = "7", false, 94.194525, a2
  local v134, v136 = datum7, -33.811339
  v124 = true ~= not a0
  v124 = true == true ~= false == false == not a0
  a2 = 175.847057
  a0 = true == not true
  local cond139 = true
  repeat
      v120 = math.tan(19.230011) - math.pi - -(math.pi)
      a1 = 75 + math.floor(145.214913) or -(string.len("sed do Excepteur dolor"))
      v124 = false ~= not false
      cond139 = false
  until cond139 ~= true
  return "3"
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @param a4 string
-- @return string
function datum5:m25(a0, a1, a2, a3, a4)
  v140, v142, v144 = "5", datum0, a1
  local v146, v148 = datum1, datum1
  if a3 == "10" then
      a3 = "5"
      a1 = "officia ad" ~= a3 == not "anim in" ~= "esse"
  else
      a0 = "3"
  end
  for i=12,1 do
      a2 = "eiusmod anim"
      a4 = "9"
  end
  if a1 == true then
      a0 = tostring(math.floor(9.332350))
  end
  if a1 == false then
      a2 = "culpa pariatur culpa"
      v142 = "eu enim qui quis" == v140 == not "cillum et qui" ~= v140
      a2 = "ad tempor"
  else
      a0 = v140
  end
  a4 = a3
  return "ullamco dolore in"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m9_a0 = "1"
local m9_a1 = 55.602866
local r_m9_0 = datum5:m9(m9_a0, m9_a1)
local func12_a0 = false
local func12_a1 = "9"
local r_func12_0 = func12(func12_a0, func12_a1)
local m15_a0 = 47.646461
local m15_a1 = "8"
local r_m15_0 = datum5:m15(m15_a0, m15_a1)
local func18_a0 = 51.508808
local func18_vararg0 = 0x18
local func18_vararg1 = -77
local r_func18_0 = func18(func18_a0, func18_vararg0, func18_vararg1)
local m20_a0 = false
local m20_a1 = -47
local m20_a2 = "adipiscing enim proident"
local m20_a3 = 86.641922
local m20_vararg0 = -51
local r_m20_0 = datum5:m20(m20_a0, m20_a1, m20_a2, m20_a3, m20_vararg0)
local m25_a0 = "1"
local m25_a1 = false
local m25_a2 = "voluptate nulla aute"
local m25_a3 = "3"
local m25_a4 = "5"
local r_m25_0 = datum5:m25(m25_a0, m25_a1, m25_a2, m25_a3, m25_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0 and 1 or 0
local res_datum1 = datum1 and 0x1 or 0
local res_datum2 = datum2 and 1 or 0
local res_datum3 = datum3
local res_datum4 = tonumber(datum4)
local res_datum5 = ms.table_to_int(datum5)
local res_datum7 = tonumber(datum7)
local res_datum8 = math.floor(datum8 + 1)
local res_r_m9_0 = math.floor(r_m9_0 + 0)
local res_r_func12_0 = math.floor(r_func12_0 + 0)
local res_r_m15_0 = math.floor(r_m15_0 + 2)
local res_r_func18_0 = #(r_func18_0)
local res_r_m20_0 = tonumber(r_m20_0)
local res_r_m25_0 = #(r_m25_0)
RESULT = res_r_m25_0 - res_r_m20_0 - res_r_func18_0 + res_r_m15_0 + res_r_func12_0 + res_r_m9_0 + res_datum8 + res_datum7 + res_datum5 + res_datum4 + res_datum3 - res_datum2 - res_datum1 - res_datum0
print(math.floor(RESULT))