--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            217109446                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  9 statements)         --
--------------------------------------------------------
datum0 = {field1 = 0x1.13df83b360d5dp+6}
datum2 = {field3 = "aute"}
local datum4 = "4"
local datum5 = 5.638174
datum6 = -89
datum7 = true
local datum8 = "1"
local datum9 = "3"
datum10 = 0x1.c16d786ca6127p+5

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 float
-- @param a2 boolean
-- @param a3 string
-- @param a4 boolean
-- @return float
function func11(a0, a1, a2, a3, a4, ...)
  local v35, v37 = "velit do Ut", 55.836457
  local v39, v41, v43 = "6", "velit", a1
  a1 = 43.859045 - math.pi - -(47.626004)
  if datum6 == 73 then
      a3 = tostring(8)
      v37 = math.sin(0x1.f1b921c93f197p+6) - -(math.tan(77))
  else
      a0 = 82 or - string.len(v35)
  end
  if a4 == false then
      v37 = 69.284974 - -(4.767325e+01)
      a0 = 69 - 70 + - math.floor(110.087583)
  end
  for i=11,3,3 do
      a2 = true == not true
      v37 = math.pi + 28.443249 - -(math.pi)
  end
  a2 = true ~= false == not false
  a0 = 37 or math.floor(54.253662) or -(-91)
  return math.cos(a0) - math.tan(a1) + 36.989861 + 65.291460 - 74.463391 + math.pi + -(math.abs(v37))
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @return int
function datum0:m17(a0, a1, a2)
  local v45, v47, v49, v51 = true, a0, "tempor sed", false
  v53, v55, v57 = [[quis
enim]], "commodo", v45
  v59, v61 = datum6, "4"
  local cond63 = 8
  repeat
      v47 = "5"
      v49 = "adipiscing nulla"
      cond63 = cond63 + 3
  until cond63 < 34
  a2 = math.tan(-80) - -(math.pi)
  a2 = math.cos(129.003852) - math.pi + -(math.cos(45.179390))
  if a2 <= -54.546878 then
      v49 = "dolore"
      v47 = a0
      v47 = v47
  else
      v47 = "9"
      a0 = "10"
      v49 = "amet et minim dolore"
  end
  v45 = "in qui" == v47 == not true
  return math.floor(a0 + 0) - math.floor(a1 + 3) + math.floor(a2) - 0x51 + tonumber(v47) + - string.len(v49)
end

-- @param a0 string
-- @param a1 int
-- @param a2 string
-- @return function
function datum2:m21(a0, a1, a2)
  v67, v69, v71 = datum4, datum10, datum4
  local v73, v75, v77, v79 = "ad pariatur ex", a1, "ut", "adipiscing ullamco"
  a2 = "labore voluptate exercitation"
  v67 = "1"
  a2 = "et dolore eu"
  local cond82 = 9
  while cond82 <= 35 do
      a1 = -34 or -51 or -(a1)
      a1 = tonumber(v67) + -79 + -(99)
      cond82 = cond82 + 3
  end
  return nil
end

-- @param a0 string
-- @return nil
function func25(a0)
  v83, v85, v87 = "eiusmod labore cupidatat", datum8, datum8
  local v89, v91, v93 = v83, true, "4"
  v83 = a0
  if a0 ~= "est culpa" then
      v85 = "3"
  end
  for i=3,18 do
      v83 = [[dolor]]
      v85 = v85
  end
  local cond96 = false
  while cond96 == true do
      a0 = "id sunt"
      a0 = a0
      cond96 = true
  end
  return "ut dolor laboris" == a0 ~= "voluptate non ut" ~= v83 == not "in sunt proident est" ~= v85
end

-- @param a0 int
-- @param a1 string
-- @return table
function datum2:m27(a0, a1, ...)
  v97, v99, v101, v103 = -94.007153, a0, "6", a0
  local v105, v107, v109 = 88, "in ut sint occaecat", a1
  a1 = "magna Excepteur esse"
  local cond112 = false
  repeat
      a0 = 20 or 43 + - a0
      cond112 = true
  until cond112 == true
  for i=17,3 do
      a0 = v99 - math.floor(v97) + - -5
      v97 = 6.412812 + -(math.cos(v99))
      a1 = "in dolor"
  end
  v97 = math.pi - -(math.pi)
  return {a0}
end

-- @param a0 float
-- @param a1 int
-- @param a2 string
-- @return function
local func30 = function (a0, a1, a2)
  local v114, v116, v118 = datum5, "ullamco in", "ad in"
  v120, v122, v124 = a0, datum7, a1
  v114 = math.pi - -(94.649121)
  for i, _ in pairs(datum0) do
      a1 = math.floor(144.990369) or - 20
      a0 = 14.800245 - -(11.374896)
      a1 = -1 - -(math.floor(a0))
  end
  local cond128 = true
  while cond128 ~= true do
      v116 = "in"
      a2 = "6"
      cond128 = false
  end
  v116 = v116
  return nil
end

-- @return int
function datum2:m34()
  v130, v132, v134 = datum7, "est fugiat anim", "9"
  v136, v138, v140, v142 = "in sint", datum6, [[ipsum
aliquip
magna]], -38.834355
  v132 = "laboris do"
  if datum5 >= 94.079872 then
      v130 = true ~= not true
  else
      v130 = "dolor" ~= v132 ~= [[Lorem
magna
in]] == v132 == not "veniam elit in dolore" ~= v132
      v130 = false ~= true ~= not "magna enim" == "non Excepteur aute est"
  end
  for i=3,11,2 do
      v130 = v130 == false ~= not false
      v132 = "aliquip consequat aute"
      v132 = "aute"
  end
  for i=1,0x11,2 do
      v132 = v132
      v132 = "Ut deserunt"
      v132 = "nisi"
  end
  v132 = "nostrud nisi officia"
  for i=0,14 do
      v132 = [[irure
ut]]
      v132 = v132
      v132 = "laboris incididunt id"
  end
  return 62 - -(#(v132))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func11_a0 = -90
local func11_a1 = 9.415295
local func11_a2 = true
local func11_a3 = "1"
local func11_a4 = true
local func11_vararg0 = 10.935537
local r_func11_0 = func11(func11_a0, func11_a1, func11_a2, func11_a3, func11_a4, func11_vararg0)
local m17_a0 = "5"
local m17_a1 = "6"
local m17_a2 = 13.568026
local r_m17_0 = datum0:m17(m17_a0, m17_a1, m17_a2)
local m21_a0 = "in exercitation"
local m21_a1 = -36
local m21_a2 = "eiusmod"
local r_m21_0 = datum2:m21(m21_a0, m21_a1, m21_a2)
local func25_a0 = "sit Ut in"
local r_func25_0 = func25(func25_a0)
local m27_a0 = 29
local m27_a1 = "irure nisi velit"
local m27_vararg0 = true
local m27_vararg1 = 49.064737
local m27_vararg2 = -44
local r_m27_0 = datum2:m27(m27_a0, m27_a1, m27_vararg0, m27_vararg1, m27_vararg2)
local func30_a0 = 38.339164
local func30_a1 = 7
local func30_a2 = "5"
local r_func30_0 = func30(func30_a0, func30_a1, func30_a2)
local r_m34_0 = datum2:m34()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = math.floor(datum4 + 2)
local res_datum5 = math.floor(datum5)
local res_datum6 = datum6
local res_datum7 = datum7 and 1 or 0
local res_datum8 = math.floor(datum8 + 0x2)
local res_datum9 = tonumber(datum9)
local res_datum10 = math.floor(datum10)
local res_r_func11_0 = math.floor(r_func11_0)
local res_r_m17_0 = r_m17_0
local res_r_m21_0 = 1
local res_r_func25_0 = 1
local res_r_m27_0 = #(r_m27_0)
local res_r_func30_0 = 1
local res_r_m34_0 = r_m34_0
RESULT = res_r_m34_0 - res_r_func30_0 + res_r_m27_0 - res_r_func25_0 + res_r_m21_0 - res_r_m17_0 + res_r_func11_0 - res_datum10 + res_datum9 - res_datum8 + res_datum7 - res_datum6 + res_datum5 + res_datum4 + res_datum2 - res_datum0
print(math.floor(RESULT))