--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            185436769                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
local datum0 = {field1 = -46}
datum2 = -24
datum3 = {field4 = -84}
datum5 = "2"
local datum6 = {field7 = 45.089053}
local datum8 = "voluptate consectetur enim ipsum"
local datum9 = {field10 = false}
local datum11 = {field12 = true}
datum13 = {field14 = 26}
datum15 = [[9]]

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 string
-- @param a2 int
-- @param a3 string
-- @return boolean
function datum3:m16(a0, a1, a2, a3)
  local v40, v42, v44, v46 = -31.738290, false, a3, false
  local v48, v50, v52, v54 = false, a3, 54.090385, true
  v56, v58, v60 = "esse est officia", datum2, 0x1.0a72a954be926p+6
  if a0 >= 48.854621 then
      a1 = tostring(math.floor(89.878235))
      a0 = math.pi + math.cos(171.276703) + -(math.pi)
      v44 = "qui do ut"
  end
  if a0 ~= -90.805070 then
      a1 = tostring(-25)
      v42 = true == v42 ~= not false
      v40 = 10.180469 - math.pi - -(math.abs(1.410037e+02))
  end
  for i=19,3 do
      a1 = "10"
      a3 = "fugiat aute sit"
      a3 = "in"
  end
  local cond65 = 4
  repeat
      a3 = a3
      v40 = math.sin(39.131992) - -(3.434526e+01)
      cond65 = cond65 + 2
  until cond65 < 24
  return true ~= "laborum consequat" == a1 == false ~= "laborum voluptate" == a3 ~= true ~= v42 == not "aliqua sint ullamco consectetur" ~= v44
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 string
-- @param a3 float
-- @return boolean
function datum11:m21(a0, a1, a2, a3)
  v67, v69, v71, v73 = a3, datum2, "8", "10"
  v75, v77, v79, v81 = true, a3, datum8, "6"
  local cond83 = false
  while cond83 ~= false do
      a1 = true == true == not [[et
officia
reprehenderit]] == a2
      cond83 = true
  end
  local cond84 = false
  repeat
      a3 = math.pi + math.pi - -(math.pi)
      cond84 = true
  until cond84 == true
  for i=5,17,0x2 do
      a2 = "mollit adipiscing"
  end
  return true ~= a1 ~= "et" ~= a2 ~= false ~= false == not false
end

-- @param a0 int
-- @param a1 int
-- @param a2 boolean
-- @return boolean
function datum6:m26(a0, a1, a2)
  local v85, v87, v89, v91 = 93.243770, datum5, 63.428378, datum15
  local v93, v95 = v85, "pariatur aliquip"
  v87 = "4"
  if datum15 ~= "9" then
      a0 = 15 or -(math.floor(29.402729))
      v85 = math.cos(183.519692) + -(math.pi)
      a2 = true == false == not "ut est dolor voluptate" == v87
  else
      v87 = tostring(math.floor(116.666014))
      v85 = math.sin(132.969610) + math.sin(v85) - -(math.pi)
  end
  a1 = math.floor(26.279463) or a1 or - 66
  local cond97 = 0
  while cond97 < 21 do
      a0 = string.len("nisi") - math.floor(197.493676) - - string.len("occaecat")
      v87 = tostring(15)
      a2 = true ~= a2 ~= false == not true
      cond97 = cond97 + 0x2
  end
  return false == true == a2 ~= false == not [[cillum
cupidatat
ex]] ~= v87
end

-- @param a0 int
-- @param a1 int
-- @return string
function datum0:m30(a0, a1)
  local v98, v100, v102, v104 = 0x1.e07e449b43b08p+4, 15.990363, "cupidatat mollit nulla", false
  v106, v108 = 66.586684, a0
  local v110, v112 = -99, "6"
  if a0 >= -52 then
      v98 = math.cos(a1) + math.sin(a0) + -(math.pi)
      v98 = math.tan(v98) - math.abs(a0) + -(51.156398)
  end
  if v100 <= -82.986013 then
      v98 = math.cos(a0) + -(math.cos(-57))
      a0 = math.floor(33.828760) or string.len(v102) - -(48)
      a0 = math.floor(91.933551) + - a1
  end
  for i=13,1 do
      v100 = 27.538958 - math.pi - -(math.abs(-50))
      a0 = math.floor(168.287384) - #("reprehenderit") or -(-3)
      v100 = math.sin(138.129858) + math.pi + -(math.sin(a1))
  end
  v98 = math.pi - math.pi + -(math.cos(v98))
  a0 = 71 + #("ut occaecat consectetur") + -(0x54)
  local cond114 = 10
  while cond114 < 45 do
      v100 = math.abs(v100) + math.abs(156.544797) - -(17.125908)
      cond114 = cond114 + 1
  end
  return tostring(a0)
end

-- @param a0 float
-- @param a1 int
-- @param a2 int
-- @param a3 string
-- @param a4 int
-- @return nil
local func33 = function (a0, a1, a2, a3, a4)
  local v115, v117, v119, v121 = true, a4, datum2, "cillum non quis"
  v123, v125 = "2", a1
  v127, v129, v131, v133 = -68.168123, "labore nulla est occaecat", -4.258762, true
  a3 = "4"
  for _, v in ipairs(datum0) do
      a1 = string.len("sunt Lorem") + a1 + - 39
      a2 = 29 + -62 + - -78
  end
  v117 = math.floor(a0) - v117 or -(a2)
  local cond137 = 1
  while cond137 < 37 do
      a2 = a2 + math.floor(a3 + 2) + - 64
      v117 = math.floor(125.024903) + 0x2E + - #("consectetur consectetur dolore officia")
      v115 = false ~= false ~= false == not "esse qui ea" == "anim elit fugiat consequat"
      cond137 = cond137 + 2
  end
  return false == false ~= true ~= "Duis nostrud consequat" == a3 ~= false == false ~= v115 == false ~= not true
end

-- @return string
local func39 = function ()
  local v138, v140, v142 = "6", 31, datum2
  local v144, v146, v148 = datum2, "dolor", datum15
  local v150, v152, v154, v156 = datum5, v138, true, v140
  v142 = v140 + 0x60 or - tonumber(v138)
  if datum8 ~= "in fugiat pariatur eu" then
      v140 = tonumber(v138) or 92 or - -48
      v140 = math.floor(v138 + 0) + - string.len("laborum velit ullamco")
  else
      v138 = v138
  end
  if datum0 ~= {} then
      v138 = "3"
      v142 = tonumber(v138) or v142 - - -81
  else
      v142 = tonumber(v138) or - v142
  end
  v140 = -74 + -(-70)
  return v138
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m16_a0 = 52.043229
local m16_a1 = "2"
local m16_a2 = 64
local m16_a3 = "non proident id"
local r_m16_0 = datum3:m16(m16_a0, m16_a1, m16_a2, m16_a3)
local m21_a0 = 95.268709
local m21_a1 = false
local m21_a2 = "dolor sit cupidatat"
local m21_a3 = 28.457001
local r_m21_0 = datum11:m21(m21_a0, m21_a1, m21_a2, m21_a3)
local m26_a0 = -31
local m26_a1 = -21
local m26_a2 = true
local r_m26_0 = datum6:m26(m26_a0, m26_a1, m26_a2)
local m30_a0 = 47
local m30_a1 = 98
local r_m30_0 = datum0:m30(m30_a0, m30_a1)
local func33_a0 = 14.853251
local func33_a1 = -46
local func33_a2 = -90
local func33_a3 = "5"
local func33_a4 = -23
local r_func33_0 = func33(func33_a0, func33_a1, func33_a2, func33_a3, func33_a4)
local r_func39_0 = func39()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = datum2
local res_datum3 = ms.table_to_int(datum3)
local res_datum5 = math.floor(datum5 + 2)
local res_datum6 = #(datum6)
local res_datum8 = string.len(datum8)
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = #(datum11)
local res_datum13 = #(datum13)
local res_datum15 = math.floor(datum15 + 1)
local res_r_m16_0 = r_m16_0 and 1 or 0
local res_r_m21_0 = r_m21_0 and 1 or 0
local res_r_m26_0 = r_m26_0 and 1 or 0
local res_r_m30_0 = math.floor(r_m30_0 + 2)
local res_r_func33_0 = 1
local res_r_func39_0 = math.floor(r_func39_0 + 2)
RESULT = res_r_func39_0 + res_r_func33_0 - res_r_m30_0 + res_r_m26_0 - res_r_m21_0 + res_r_m16_0 + res_datum15 + res_datum13 - res_datum11 + res_datum9 + res_datum8 + res_datum6 - res_datum5 + res_datum3 + res_datum2 - res_datum0
print(math.floor(RESULT))