--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            941443904                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
datum0 = {field1 = "voluptate exercitation mollit"}
datum2 = {field3 = true}
local datum4 = {field5 = false}
local datum6 = "1"
datum7 = {field8 = "ullamco irure"}
datum9 = "4"

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 float
-- @return string
function func10(a0, a1)
  local v25, v27, v29 = datum6, datum9, true
  v31, v33 = -6.854306e+01, v25
  local v35, v37, v39, v41 = "1", false, true, true
  a1 = 23.560081 - -(math.tan(a0))
  local cond43 = false
  while cond43 ~= false do
      v27 = "2"
      a0 = a0 or - math.floor(0x1.7a1a137e6280ap+3)
      cond43 = true
  end
  v27 = tostring(math.floor(a1))
  local cond44 = false
  while cond44 ~= false do
      v29 = "officia minim" == [[ullamco
ullamco
consequat]] ~= not [[consequat
Excepteur
reprehenderit
dolor]] ~= "consequat"
      a0 = -77 + 67 or - math.floor(1.099743e+02)
      cond44 = true
  end
  return tostring(a0)
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 int
-- @return string
function func13(a0, a1, a2)
  local v45, v47, v49, v51 = a2, -95, [[sint]], -65.446915
  local v53, v55, v57, v59 = 19, 92.923736, "reprehenderit Duis", a0
  v61, v63, v65, v67 = "in ut non", 90, "4", a0
  if a2 == 41 then
      a0 = "dolor magna" == "Lorem aliqua qui" ~= not false
      a2 = 61 - v47 - -(math.floor(95.307154))
  end
  a2 = math.floor(a1 + 1) - -78 or - -89
  if v47 >= 39 then
      a0 = true ~= true == not false ~= a0
      a0 = false == true ~= not true
  end
  a2 = 35 + - -67
  local cond69 = 0x3
  while cond69 < 43 do
      a0 = false ~= false == "aute non commodo" == "dolore pariatur qui" ~= not true
      cond69 = cond69 + 3
  end
  return "sint minim dolore"
end

-- @param a0 boolean
-- @param a1 int
-- @param a2 boolean
-- @param a3 boolean
-- @return string
function datum4:m17(a0, a1, a2, a3)
  v70, v72, v74, v76 = [[magna
irure]], 68.941954, 77, 5.791384e+01
  local v78, v80 = -73.546479, false
  a3 = false == false == not true
  if v72 >= 89.533577 then
      v70 = "ipsum eiusmod Duis"
      a2 = false ~= not true
      a1 = -51 or 66 + -(87)
  end
  for i, _ in pairs(datum4) do
      a2 = true == true == not false ~= true
      v70 = [[enim
dolor
anim]]
      a2 = true ~= not true
  end
  for i, v in pairs(datum4) do
      v70 = v72
      v70 = 146.998343
  end
  return "dolore aliqua"
end

-- @param a0 float
-- @return function
local func22 = function (a0)
  local v91, v93, v95 = true, "cillum Lorem non", a0
  local v97, v99, v101 = false, v91, v91
  local v103, v105, v107, v109 = v91, "voluptate non", datum9, -52.608599
  v93 = "qui amet occaecat"
  v93 = "amet commodo nostrud"
  local cond112 = false
  while cond112 ~= false do
      v93 = "sint commodo dolor"
      a0 = math.abs(-54) - math.pi - -(28.662612)
      cond112 = true
  end
  for i=4,11 do
      a0 = math.pi + math.pi + -(math.pi)
      v93 = [[non
nostrud
veniam]]
  end
  v95 = 98.291387 + -(30.078931)
  return nil
end

-- @return float
function datum0:m24()
  local v114, v116 = -58, 48
  local v118, v120, v122 = [[cillum
sed
ea
dolor]], 6, datum9
  v124, v126, v128, v130 = datum9, -0x1.61934db037d55p+6, 0x1.2ce4978885aecp+4, true
  if v116 <= 95 then
      v114 = 99 + math.floor(69.942036) - -(v114)
      v114 = math.floor(131.207277) - - math.floor(30.596325)
      v118 = "sunt nulla ea id"
  end
  v116 = 87 - -(math.floor(58.143075))
  v118 = [[sunt]]
  if v114 >= 37 then
      v116 = v114 + - math.floor(4.680371)
      v118 = "ut minim"
      v118 = 192.807152
  end
  if v114 >= -12 then
      v114 = 27 or 39 - -(math.floor(85.494956))
  end
  if v114 < 69 then
      v114 = v114 - 0x24 or - v116
  else
      v118 = "esse"
      v116 = -43 + v114 - -(-8)
      v114 = string.len(v118) + -(-14)
  end
  return math.tan(v114) + math.tan(v116) - -(math.pi)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = 0x2e
local func10_a1 = 61.955973
local r_func10_0 = func10(func10_a0, func10_a1)
local func13_a0 = false
local func13_a1 = "4"
local func13_a2 = 92
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2)
local m17_a0 = false
local m17_a1 = 14
local m17_a2 = true
local m17_a3 = true
local r_m17_0 = datum4:m17(m17_a0, m17_a1, m17_a2, m17_a3)
local func22_a0 = 42.694725
local r_func22_0 = func22(func22_a0)
local r_m24_0 = datum0:m24()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6 + 0)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = tonumber(datum9)
local res_r_func10_0 = math.floor(r_func10_0 + 0x1)
local res_r_func13_0 = string.len(r_func13_0)
local res_r_m17_0 = string.len(r_m17_0)
local res_r_func22_0 = 1
local res_r_m24_0 = math.floor(r_m24_0)
RESULT = res_r_m24_0 + res_r_func22_0 - res_r_m17_0 + res_r_func13_0 - res_r_func10_0 - res_datum9 - res_datum7 + res_datum6 + res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))