--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:           1070592286                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = {field1 = true}
datum2 = -44
datum3 = {field4 = false}
local datum5 = {field6 = -49}
local datum7 = false
local datum8 = 28
local datum9 = {field10 = "id laborum"}
datum11 = {field12 = 65.807649}
local datum13 = 0x45
datum14 = {field15 = -7}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 string
-- @param a2 boolean
-- @param a3 int
-- @return string
function func16(a0, a1, a2, a3)
  local v38, v40, v42, v44 = a2, "elit incididunt ea mollit", -70.377007, [[ad
fugiat]]
  v46, v48, v50, v52 = [[5]], -7.400947e+01, "magna", 89.478737
  local v54, v56, v58, v60 = v40, "Ut eiusmod pariatur", datum13, v40
  a3 = math.floor(0x1.77841d35355e1p+7) or -9 or - 24
  if a1 == "5" then
      a1 = tostring(math.floor(v42))
  else
      v40 = "pariatur ipsum elit"
      a3 = -95 + -(math.floor(v42))
      v40 = "aliqua ad dolore"
  end
  a2 = false == true == not false
  v38 = false ~= not "dolor aute et" ~= a1
  local cond63 = false
  repeat
      a2 = "anim ullamco" ~= a1 ~= true == not false
      v42 = 8.327652e+01 + math.cos(35.315250) + -(70.614093)
      a3 = 15 + -(70)
      cond63 = true
  until cond63 == true
  return "exercitation sunt ullamco"
end

-- @param a0 int
-- @param a1 int
-- @param a2 float
-- @return table
function func21(a0, a1, a2)
  local v65, v67, v69, v71 = "reprehenderit fugiat exercitation", datum8, a0, "7"
  v73, v75, v77 = a0, a2, a2
  local v79, v81, v83 = a2, -0x1.5fd65841af535p+6, v67
  if v67 ~= 0x3E then
      v67 = math.floor(100.634851) or v69 or - math.floor(73.058887)
      a1 = v67 or - a1
  else
      v69 = v67 + -53 or -(37)
      a1 = #("Duis") or -(v69)
  end
  local cond85 = 109
  while cond85 > 0x38 do
      a2 = math.tan(75) + -(math.sin(97))
      a2 = 59.374600 + -(math.cos(0x1.92fd26f73181cp+5))
      v65 = "id mollit aliquip"
      cond85 = cond85 - 2
  end
  for i, v in pairs(datum14) do
      v67 = string.len(v65) - -(93)
      v69 = #(v65) or -(-39)
      v67 = math.floor(1.410887e+02) + #("labore") + - math.floor(130.791914)
  end
  a0 = a1 or -9 + - -24
  return {1}
end

-- @param a0 string
-- @param a1 string
-- @param a2 int
-- @param a3 string
-- @return float
function datum11:m25(a0, a1, a2, a3)
  local v90, v92 = "est esse", 82.801942
  v94, v96, v98 = datum13, a3, 0x1.84e4ebf87b6b2p+6
  local cond100 = false
  while cond100 == true do
      a0 = "aliquip ullamco consequat"
      cond100 = true
  end
  v92 = math.cos(-29) - math.pi - -(math.pi)
  local cond101 = 0x3
  while cond101 < 0x23 do
      a3 = "labore ipsum"
      a0 = [[aliquip
Excepteur]]
      cond101 = cond101 + 0x3
  end
  return math.pi - 14.085552 + math.abs(a2) + 22.402055 + 78.225707 + -(math.abs(v92))
end

-- @param a0 boolean
-- @param a1 float
-- @return table
function datum0:m30(a0, a1)
  v104, v106, v108, v110 = "aliquip do cupidatat", false, 18, a0
  v112, v114, v116 = a1, "1", "exercitation"
  local v118, v120, v122, v124 = 1.417335, -63, "9", 25.426942
  local cond126 = 0x2
  repeat
      a0 = a0 == not false
      cond126 = cond126 + 1
  until cond126 < 39
  a1 = math.sin(47.723627) + -(math.cos(-63))
  a1 = math.cos(14) + math.pi + -(math.tan(1.052395e+01))
  return {2}
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 int
-- @return nil
function datum3:m33(a0, a1, a2, a3)
  local v128, v130, v132, v134 = true, "4", "9", 26.171701
  local v136, v138, v140 = "5", 42.376841, "ad incididunt"
  for _, _ in pairs(datum0) do
      v130 = tostring(a3)
      a3 = -94 + - string.len("in in exercitation")
      v128 = true ~= false ~= not true
  end
  v128 = true ~= "Ut labore" == a2 == not true
  a0 = "cupidatat occaecat ex"
  if datum9 == {} then
      v128 = "quis qui et" == a2 ~= v128 ~= not true
      a3 = 0x1e + -(#(a0))
  else
      v130 = "9"
  end
  return "eu id veniam" ~= a0 ~= "nisi id nulla" ~= a1 == "dolor sit deserunt" ~= a2 == true ~= v128 == not "Ut aliqua voluptate est" == v130
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func16_a0 = 5.993448
local func16_a1 = [[3]]
local func16_a2 = false
local func16_a3 = 28
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3)
local func21_a0 = 63
local func21_a1 = 40
local func21_a2 = 29.184064
local r_func21_0 = func21(func21_a0, func21_a1, func21_a2)
local m25_a0 = "sint sit culpa"
local m25_a1 = "1"
local m25_a2 = -17
local m25_a3 = "velit ad aliquip esse"
local r_m25_0 = datum11:m25(m25_a0, m25_a1, m25_a2, m25_a3)
local m30_a0 = true
local m30_a1 = 1.093894e+01
local r_m30_0 = datum0:m30(m30_a0, m30_a1)
local m33_a0 = "Excepteur eiusmod minim Lorem"
local m33_a1 = "2"
local m33_a2 = "4"
local m33_a3 = -36
local r_m33_0 = datum3:m33(m33_a0, m33_a1, m33_a2, m33_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = datum2
local res_datum3 = ms.table_to_int(datum3)
local res_datum5 = ms.table_to_int(datum5)
local res_datum7 = datum7 and 1 or 0
local res_datum8 = datum8
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = ms.table_to_int(datum11)
local res_datum13 = datum13
local res_datum14 = ms.table_to_int(datum14)
local res_r_func16_0 = #(r_func16_0)
local res_r_func21_0 = ms.table_to_int(r_func21_0)
local res_r_m25_0 = math.floor(r_m25_0)
local res_r_m30_0 = #(r_m30_0)
local res_r_m33_0 = 0x1
RESULT = res_r_m33_0 - res_r_m30_0 - res_r_m25_0 - res_r_func21_0 + res_r_func16_0 - res_datum14 + res_datum13 - res_datum11 - res_datum9 + res_datum8 - res_datum7 - res_datum5 + res_datum3 - res_datum2 + res_datum0
print(math.floor(RESULT))