--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            759836189                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = {field1 = false}
datum2 = 10
datum3 = {field4 = 60.428465}
datum5 = {field6 = 189.724203}
local datum7 = {field8 = true}

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 string
-- @param a2 float
-- @param a3 int
-- @return function
function datum3:m9(a0, a1, a2, a3)
  v39, v41, v43 = datum2, a1, false
  v45, v47 = true, "8"
  local v49, v51 = false, "sed laborum qui"
  a1 = "2"
  a1 = tostring(v39)
  local cond53 = 1
  repeat
      v41 = tostring(a3)
      cond53 = cond53 + 3
  until cond53 < 33
  local cond54 = 111
  while cond54 > 50 do
      v39 = math.floor(49.308680) - #("ullamco cupidatat Ut aliquip") or - -24
      v43 = true ~= true == not true
      cond54 = cond54 - 2
  end
  return nil
end

-- @param a0 string
-- @return function
function func14(a0, ...)
  v55, v57, v59, v61 = a0, "aliqua veniam", "1", a0
  local v63, v65, v67, v69 = true, true, "aute ex", 40.272193
  local v71, v73, v75, v77 = -54.040526, "pariatur ad dolor magna", -68.665705, datum2
  v57 = "occaecat"
  v59 = tostring(math.floor(193.481741))
  v57 = "cupidatat officia occaecat"
  a0 = "5"
  local cond81 = 5
  repeat
      v57 = "laboris dolor ex"
      v55 = v55
      cond81 = cond81 + 0x3
  until cond81 < 37
  return nil
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 boolean
-- @param a3 int
-- @param a4 int
-- @return nil
local func16 = function (a0, a1, a2, a3, a4)
  local v83, v85 = false, "quis"
  local v87, v89, v91, v93 = 48, "2", 22.242381, "5"
  v95, v97, v99, v101 = -93.397422, true, a1, v85
  a0 = 82 - - -73
  v83 = true ~= true ~= false ~= not false
  a1 = "enim in dolore" ~= "non id" == not true
  for i=16,4 do
      v87 = -60 - -33 + -(#("et in"))
      v83 = false == true == not false == a2
      a2 = true == false ~= a2 == not a2
  end
  if datum2 == -67 then
      v87 = a0 + string.len("anim cillum nulla magna") - -(a4)
      v83 = true ~= true ~= not false
      a3 = math.floor(126.103302) + - string.len("dolore id aliquip")
  end
  v85 = "ex cupidatat dolore"
  return false ~= true ~= a1 ~= true == a2 == true ~= false == false == v83 == "occaecat" == v85 ~= not true
end

-- @param a0 string
-- @return function
function datum3:m22(a0)
  v103, v105, v107, v109 = "4", -4.456209e+01, "culpa veniam", a0
  local v111, v113, v115 = -97.762243, 40.829380, "nostrud et"
  local v117, v119, v121, v123 = a0, "7", true, datum2
  if datum2 > 84 then
      a0 = "cupidatat"
      a0 = "minim"
  else
      v103 = "8"
      v105 = math.cos(154.073550) - math.pi - -(math.pi)
  end
  local cond126 = true
  while cond126 ~= true do
      a0 = "quis"
      v105 = math.cos(8.917232e+01) + math.pi - -(math.pi)
      v105 = math.pi - math.pi + -(math.tan(v105))
      cond126 = false
  end
  if v105 ~= 63.040837 then
      v103 = tostring(71)
      v103 = tostring(-97)
      v107 = a0
  else
      a0 = "proident sit nisi"
      v107 = v107
  end
  for _, v in pairs(datum7) do
      v103 = v103
      v105 = 7.860109e+01 - -(math.abs(0x1.35869bcbf1d41p+6))
  end
  return nil
end

-- @param a0 float
-- @param a1 string
-- @return float
local func24 = function (a0, a1)
  v132, v134, v136 = datum2, "9", "minim ullamco"
  v138, v140 = false, true
  local cond142 = 111
  repeat
      a1 = "dolor et qui"
      v132 = math.floor(128.324374) - 31 - - 29
      cond142 = cond142 - 3
  until cond142 > 53
  for i=15,4 do
      v132 = math.floor(0x1.1bcfd3a7ba44dp+5) + -(#("eu Ut laboris"))
      a1 = "cupidatat et"
  end
  if datum2 <= -51 then
      a1 = "Duis pariatur incididunt tempor"
      a1 = "cupidatat dolore sint"
  end
  return math.sin(a0) + 0x1.190fa330a56eep+6 - math.sin(v132) + -(math.pi)
end

-- @param a0 string
-- @param a1 int
-- @param a2 string
-- @param a3 float
-- @param a4 string
-- @return table
function datum7:m27(a0, a1, a2, a3, a4)
  local v145, v147, v149 = a3, [[1]], datum2
  local v151, v153, v155, v157 = v145, "sunt dolor esse non", a1, -82.301189
  if datum0 ~= {} then
      a1 = #(a4) - 77 + - #(a2)
      a4 = 62.127847
  else
      v145 = math.abs(-45) + 94.666944 + -(65.238502)
  end
  if a0 ~= "sed" then
      a0 = [[irure
eu
irure]]
      a4 = a3
  end
  if a0 == "cillum quis reprehenderit" then
      v147 = "10"
      a2 = a2
  else
      a3 = math.tan(v145) - math.cos(a3) - -(math.abs(-20))
  end
  a2 = "esse labore pariatur"
  if datum7 == {} then
      a3 = 79.107844 + -(31.758187)
      a4 = "ea sunt"
      a1 = -2 + - -17
  else
      v145 = math.cos(v145) + math.pi - -(math.tan(118.962625))
      a1 = string.len("Ut voluptate ut") - -44 + -(-39)
  end
  for _, _ in pairs(datum3) do
      a1 = string.len(a4) + -(math.floor(102.597899))
      v147 = tostring(a1)
      a3 = math.sin(178.685952) - math.pi + -(math.sin(29))
  end
  return {t162 = a0}
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 float
-- @param a3 int
-- @param a4 boolean
-- @return table
local func33 = function (a0, a1, a2, a3, a4)
  v163, v165, v167, v169 = a2, "proident eu Excepteur", "4", "culpa"
  local v171, v173, v175, v177 = "nisi Ut sint", a2, "7", -1.450781e+01
  v179, v181, v183, v185 = v163, a0, true, a4
  local cond187 = true
  repeat
      v165 = "in"
      cond187 = false
  until cond187 ~= true
  a3 = math.floor(v163) - -(-84)
  a2 = math.abs(-75) + math.pi - -(27.567342)
  a1 = "tempor" == "enim adipiscing" ~= not [[pariatur
eiusmod]] == [[enim
enim]]
  for _, v in pairs(datum7) do
      v165 = "dolore dolor nulla ea"
      a2 = 10.057921 - math.sin(89.493666) - -(62.451646)
  end
  return {3}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m9_a0 = 96
local m9_a1 = "3"
local m9_a2 = 41.958419
local m9_a3 = -58
local r_m9_0 = datum3:m9(m9_a0, m9_a1, m9_a2, m9_a3)
local func14_a0 = "1"
local func14_vararg0 = -25
local func14_vararg1 = [[nostrud
aliquip
deserunt]]
local r_func14_0 = func14(func14_a0, func14_vararg0, func14_vararg1)
local func16_a0 = -12
local func16_a1 = true
local func16_a2 = false
local func16_a3 = 51
local func16_a4 = -80
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3, func16_a4)
local m22_a0 = "officia consequat ad deserunt"
local r_m22_0 = datum3:m22(m22_a0)
local func24_a0 = 7.012999e+01
local func24_a1 = "deserunt officia proident in"
local r_func24_0 = func24(func24_a0, func24_a1)
local m27_a0 = "ut amet Ut"
local m27_a1 = 23
local m27_a2 = "dolor"
local m27_a3 = 89.670177
local m27_a4 = "dolor cupidatat dolore voluptate"
local r_m27_0 = datum7:m27(m27_a0, m27_a1, m27_a2, m27_a3, m27_a4)
local func33_a0 = "3"
local func33_a1 = false
local func33_a2 = 40.374216
local func33_a3 = -52
local func33_a4 = false
local r_func33_0 = func33(func33_a0, func33_a1, func33_a2, func33_a3, func33_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = datum2
local res_datum3 = #(datum3)
local res_datum5 = #(datum5)
local res_datum7 = #(datum7)
local res_r_m9_0 = 1
local res_r_func14_0 = 1
local res_r_func16_0 = 1
local res_r_m22_0 = 1
local res_r_func24_0 = math.floor(r_func24_0)
local res_r_m27_0 = #(r_m27_0)
local res_r_func33_0 = #(r_func33_0)
RESULT = res_r_func33_0 - res_r_m27_0 - res_r_func24_0 - res_r_m22_0 + res_r_func16_0 - res_r_func14_0 - res_r_m9_0 - res_datum7 - res_datum5 - res_datum3 + res_datum2 + res_datum0
print(math.floor(RESULT))