--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            882752359                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = true
local datum1 = "2"
datum2 = "eiusmod aute"
datum3 = {field4 = true}
datum5 = true
local datum6 = {field7 = 0x25}
datum8 = {field9 = -42}

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 int
-- @param a2 float
-- @return boolean
local func10 = function (a0, a1, a2)
  local v33, v35, v37, v39 = -48, 65, a1, 41.064576
  local v41, v43 = "9", true
  local cond45 = 5
  while cond45 < 0x1d do
      a1 = string.len([[veniam
quis]]) - -60 - - -5
      v33 = -21 - -(a1)
      cond45 = cond45 + 2
  end
  local cond46 = 105
  repeat
      a1 = math.floor(a2) or - 99
      v35 = 66 + 75 or - #("quis cillum dolore aliquip")
      cond46 = cond46 - 0x3
  until cond46 > 73
  local cond47 = 0xa
  repeat
      a1 = #([[occaecat
Ut]]) - v35 - -(-46)
      cond47 = cond47 + 2
  until cond47 <= 46
  return a0 == true ~= false == false == not true
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @param a3 float
-- @return nil
function datum6:m14(a0, a1, a2, a3)
  local v48, v50, v52, v54 = -42, datum2, a0, a3
  v56, v58, v60, v62 = "7", 98.465528, datum1, 96.925670
  if a1 ~= [[2]] then
      v50 = "in sunt"
      v48 = string.len(v50) + -(math.floor(a1 + 0x2))
      v50 = a2
  end
  local cond65 = 10
  while cond65 < 27 do
      a0 = false == false == not "dolore sit non" == v50
      cond65 = cond65 + 1
  end
  v48 = math.floor(6.155062e+01) + - #(a2)
  v50 = a2
  return a0 ~= "tempor enim dolor" ~= a1 ~= "pariatur nisi ea amet" == a2 ~= true == true ~= not "veniam incididunt aute sunt" == v50
end

-- @return string
local func19 = function ()
  v67, v69 = datum5, 91.675572
  v71, v73, v75, v77 = datum1, datum2, true, "tempor in voluptate"
  local v79, v81, v83 = -99, -44, "exercitation Duis Ut consectetur"
  v69 = math.tan(46.673545) + -(math.pi)
  v71 = "1"
  if v71 == "10" then
      v69 = math.cos(-76) - -(math.sin(189.716729))
  end
  v71 = tostring(25)
  local cond85 = false
  repeat
      v71 = tostring(37)
      cond85 = true
  until cond85 ~= false
  return "10"
end

-- @param a0 float
-- @param a1 float
-- @param a2 boolean
-- @return table
function datum8:m20(a0, a1, a2)
  local v86, v88, v90 = 53, a2, 0x2A
  v92, v94 = datum1, 2.088602
  local cond96 = true
  repeat
      a2 = false == false == not false
      cond96 = false
  until cond96 ~= true
  local cond97 = 0
  while cond97 <= 0x18 do
      v88 = false ~= not false
      a2 = false == not true
      cond97 = cond97 + 1
  end
  a0 = math.cos(a0) - math.pi - -(math.pi)
  if a1 >= 21.127614 then
      a1 = 39.444226 - -(math.pi)
  else
      v88 = a2 == true == false == not false
      v88 = false == a2 == true ~= true ~= not true
      a1 = math.cos(67.346763) + math.pi - -(66.227865)
  end
  return {-1}
end

-- @param a0 boolean
-- @param a1 string
-- @return nil
local func24 = function (a0, a1)
  v99, v101, v103 = -4, true, -64.367832
  v105, v107 = -25, -51.056974
  v99 = v99 or - math.floor(88.365253)
  if v101 ~= false then
      a0 = true ~= "ad incididunt irure" ~= "ut proident in" ~= not false
      a0 = false == v101 == true ~= not false == false
      v101 = false ~= "eu sunt ipsum dolore" == "elit magna" ~= not true == true
  end
  v99 = -60 + -4 + -(0x45)
  local cond109 = 4
  while cond109 < 25 do
      a0 = true ~= true ~= true == a0 ~= not true
      cond109 = cond109 + 2
  end
  return a0 ~= "deserunt reprehenderit adipiscing" == a1 == false ~= not true ~= v101
end

-- @param a0 boolean
-- @param a1 string
-- @return boolean
function datum3:m27(a0, a1)
  v110, v112, v114 = a1, datum1, datum2
  v116, v118 = 43.578952, "pariatur proident"
  v120, v122, v124 = 92.721073, datum2, datum0
  for i, v in pairs(datum6) do
      a0 = "Duis cillum" ~= a1 ~= true == not false == a0
      a0 = false == not false
      v114 = "non aliqua proident"
  end
  a1 = "tempor tempor"
  for i=2,20,3 do
      a0 = [[Lorem
fugiat
nostrud
voluptate]] == a1 == a0 == not true == false
      a1 = v114
  end
  for i, _ in ipairs(datum8) do
      a1 = "sunt"
      a0 = "ut cupidatat sunt" == "dolore Duis qui" ~= false ~= not "esse ea aliquip" ~= "ad"
      a0 = "consectetur laboris" == v110 ~= true == not false
  end
  return true ~= a0 == "veniam ut adipiscing" ~= a1 ~= "Excepteur reprehenderit dolore" == v110 == "ut reprehenderit ut enim" == v112 == not "id occaecat non fugiat" == v114
end

-- @param a0 float
-- @param a1 float
-- @return string
function func30(a0, a1)
  v133, v135, v137, v139 = 83.111544, datum1, a0, -71.165351
  v141, v143, v145, v147 = true, 21.798994, false, datum5
  v149, v151 = -62.621227, datum5
  a1 = math.cos(v137) - -(math.sin(135.299411))
  for i, _ in pairs(datum8) do
      a1 = math.cos(80) - math.abs(-27) - -(math.tan(-22))
      v137 = math.tan(v137) + -(0x1.66418ae42e73fp+6)
      a1 = math.pi + -(4.882055)
  end
  a0 = 3.054939e+01 + math.sin(99.772049) - -(19.304208)
  a0 = math.sin(a1) - math.sin(v137) - -(math.pi)
  a1 = math.abs(a0) + -(math.tan(66))
  local cond155 = 119
  repeat
      a0 = 86.815654 - math.pi - -(math.tan(191.983568))
      cond155 = cond155 - 1
  until cond155 >= 75
  return tostring(math.floor(a0))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = false
local func10_a1 = -43
local func10_a2 = 75.494397
local r_func10_0 = func10(func10_a0, func10_a1, func10_a2)
local m14_a0 = true
local m14_a1 = "10"
local m14_a2 = "ad officia"
local m14_a3 = 19.327926
local r_m14_0 = datum6:m14(m14_a0, m14_a1, m14_a2, m14_a3)
local r_func19_0 = func19()
local m20_a0 = 9.974603e+01
local m20_a1 = 13.538039
local m20_a2 = false
local r_m20_0 = datum8:m20(m20_a0, m20_a1, m20_a2)
local func24_a0 = true
local func24_a1 = [[nulla]]
local r_func24_0 = func24(func24_a0, func24_a1)
local m27_a0 = true
local m27_a1 = "eu labore"
local r_m27_0 = datum3:m27(m27_a0, m27_a1)
local func30_a0 = 0x1.4f161367eda2p+4
local func30_a1 = 87.005208
local r_func30_0 = func30(func30_a0, func30_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0 and 1 or 0
local res_datum1 = math.floor(datum1 + 3)
local res_datum2 = #(datum2)
local res_datum3 = #(datum3)
local res_datum5 = datum5 and 0x1 or 0
local res_datum6 = ms.table_to_int(datum6)
local res_datum8 = ms.table_to_int(datum8)
local res_r_func10_0 = r_func10_0 and 0x1 or 0
local res_r_m14_0 = 1
local res_r_func19_0 = tonumber(r_func19_0)
local res_r_m20_0 = ms.table_to_int(r_m20_0)
local res_r_func24_0 = 1
local res_r_m27_0 = r_m27_0 and 1 or 0
local res_r_func30_0 = math.floor(r_func30_0 + 3)
RESULT = res_r_func30_0 - res_r_m27_0 + res_r_func24_0 - res_r_m20_0 + res_r_func19_0 - res_r_m14_0 + res_r_func10_0 + res_datum8 - res_datum6 + res_datum5 - res_datum3 + res_datum2 - res_datum1 + res_datum0
print(math.floor(RESULT))