--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            925525922                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
local datum0 = "officia velit incididunt minim"
local datum1 = {field2 = true}
datum3 = {field4 = true}
local datum5 = [[in
do]]
local datum6 = {field7 = false}
datum8 = {field9 = false}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @param a3 int
-- @param a4 float
-- @return string
function datum6:m10(a0, a1, a2, a3, a4, ...)
  v37, v39, v41 = -46, 33, a3
  local v43, v45, v47, v49 = -18.811656, -80, "9", false
  v37 = v39 or - string.len(a2)
  for i, v in ipairs(datum1) do
      a1 = tostring(math.floor(a4))
  end
  a0 = false ~= true == not false ~= false
  for _, _ in ipairs(datum3) do
      v37 = 15 or - math.floor(139.463827)
  end
  if a4 <= -2.489961 then
      v37 = math.floor(77.106228) or -(string.len("Ut"))
  else
      a4 = 1.671753e+01 - -(math.tan(23.692403))
      a3 = 63 or math.floor(82.581186) or -(string.len(a2))
  end
  if a2 == "quis anim" then
      v37 = #(a2) or -(-92)
  end
  return "non tempor"
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @param a3 string
-- @param a4 string
-- @return boolean
function func16(a0, a1, a2, a3, a4)
  local v56, v58, v60, v62 = 55.385243, a2, "10", 5
  local v64, v66, v68 = -61, -83, true
  a2 = math.pi + -(math.pi)
  local cond70 = false
  repeat
      a1 = "in cupidatat culpa reprehenderit"
      cond70 = true
  until cond70 ~= false
  a3 = [[anim
qui
sint]]
  if a3 == "mollit aute veniam Duis" then
      a0 = tostring(math.floor(41.525231))
      v58 = math.pi - -(71.983566)
      a2 = math.pi - math.tan(144.945400) + -(math.cos(24.086370))
  else
      a1 = 142.053615
  end
  return "reprehenderit" ~= a0 == "Ut do irure" == a1 ~= true ~= "culpa proident cillum" ~= a3 ~= "pariatur tempor" ~= a4 ~= true ~= not false
end

-- @param a0 float
-- @param a1 string
-- @return string
function func22(a0, a1)
  v74, v76, v78, v80 = a1, false, "6", 97.353371
  v82, v84, v86 = 33, -49.992284, a0
  a1 = [[tempor]]
  a0 = 61.745732 - -(math.cos(a0))
  v76 = "ut aute" == "minim anim" == false == not false ~= true
  if v76 ~= true then
      v76 = "tempor sunt" == v74 == not "cillum ipsum" == v74
      v76 = false ~= not true ~= true
  end
  if v74 ~= "elit cupidatat in sunt" then
      v76 = true == true ~= not false ~= false
      a1 = a0
  end
  for i=2,11,2 do
      v76 = true == "Ut tempor" == a1 ~= not true
      v74 = "eiusmod"
  end
  return tostring(math.floor(a0))
end

-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @param a3 string
-- @param a4 int
-- @return float
function datum1:m25(a0, a1, a2, a3, a4)
  local v90, v92 = false, 99.060510
  local v94, v96 = a4, datum0
  v98, v100, v102 = v90, a4, v92
  v90 = "ipsum" == a3 ~= not true
  for i=0x11,0,2 do
      v92 = 0x1.940b66e37a59cp-3 + math.pi - -(55.593189)
      a1 = "sunt exercitation commodo"
  end
  local cond105 = true
  while cond105 == false do
      v94 = math.floor(35.512274) + - string.len("in consectetur magna sed")
      cond105 = false
  end
  return 69.625799 + 86.445215 + 99.269071 - 94.143122 - math.tan(a4) + math.pi + math.cos(v92) - -(math.sin(v94))
end

-- @param a0 int
-- @param a1 string
-- @param a2 boolean
-- @param a3 float
-- @param a4 string
-- @return float
function func31(a0, a1, a2, a3, a4)
  v106, v108, v110, v112 = 90, false, datum5, a1
  local v114, v116, v118 = "3", -3, a1
  local v120, v122, v124, v126 = -51, false, 27.884512, 44
  a3 = math.pi - -(math.pi)
  v110 = [[Lorem
Ut
in
tempor]]
  if datum6 == {} then
      a1 = 174.911986
      a1 = "officia dolore veniam esse"
      v108 = "qui adipiscing" ~= a4 ~= "eiusmod ut cupidatat" ~= a4 == not "aliquip ut" ~= "est sint exercitation"
  else
      a3 = 34.041735 + -(math.pi)
      a1 = a3
  end
  a3 = math.sin(v106) - 55.898406 + -(math.pi)
  a1 = "laboris laboris Lorem"
  return math.abs(a0) + math.pi + 82.597030 - math.abs(a3) - math.pi - math.tan(v106) - 97.574058 - -(3.124209e+00)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m10_a0 = true
local m10_a1 = "10"
local m10_a2 = "deserunt dolor"
local m10_a3 = -77
local m10_a4 = 82.276295
local m10_vararg0 = false
local m10_vararg1 = 65
local r_m10_0 = datum6:m10(m10_a0, m10_a1, m10_a2, m10_a3, m10_a4, m10_vararg0, m10_vararg1)
local func16_a0 = "4"
local func16_a1 = "non esse Excepteur"
local func16_a2 = 56.861138
local func16_a3 = "deserunt ipsum officia ut"
local func16_a4 = "ex dolore amet"
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3, func16_a4)
local func22_a0 = 24.438357
local func22_a1 = "ut magna laboris"
local r_func22_0 = func22(func22_a0, func22_a1)
local m25_a0 = "10"
local m25_a1 = [[sit
quis
aliqua]]
local m25_a2 = false
local m25_a3 = "6"
local m25_a4 = -22
local r_m25_0 = datum1:m25(m25_a0, m25_a1, m25_a2, m25_a3, m25_a4)
local func31_a0 = 34
local func31_a1 = "aliquip sunt"
local func31_a2 = true
local func31_a3 = 97.461698
local func31_a4 = "3"
local r_func31_0 = func31(func31_a0, func31_a1, func31_a2, func31_a3, func31_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = #(datum3)
local res_datum5 = string.len(datum5)
local res_datum6 = #(datum6)
local res_datum8 = ms.table_to_int(datum8)
local res_r_m10_0 = string.len(r_m10_0)
local res_r_func16_0 = r_func16_0 and 1 or 0
local res_r_func22_0 = math.floor(r_func22_0 + 0x3)
local res_r_m25_0 = math.floor(r_m25_0)
local res_r_func31_0 = math.floor(r_func31_0)
RESULT = res_r_func31_0 + res_r_m25_0 - res_r_func22_0 - res_r_func16_0 + res_r_m10_0 + res_datum8 - res_datum6 + res_datum5 - res_datum3 + res_datum1 - res_datum0
print(math.floor(RESULT))