--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            586171516                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
datum0 = -96
local datum1 = {field2 = false}
local datum3 = "fugiat incididunt"
local datum4 = "5"
local datum5 = true
local datum6 = [[7]]
local datum7 = 47.651329
datum8 = {field9 = "sit labore do"}

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 int
-- @return float
local func10 = function (a0, a1, a2, a3)
  local v38, v40 = a3, "6"
  local v42, v44, v46, v48 = datum5, "laboris amet", a1, datum0
  local v50, v52 = a2, a1
  local cond54 = 9
  while cond54 <= 0x2D do
      v38 = 40 + -(91)
      cond54 = cond54 + 1
  end
  v40 = v40
  if a3 >= 74 then
      a0 = "aliqua aliqua sint ut"
      a0 = "nisi irure dolor"
  end
  v38 = string.len("non culpa adipiscing") or math.floor(144.759595) - - 0xC
  v38 = math.floor(v40 + 0) or 30 - - 67
  return 65.555062 + math.sin(a1) - math.pi - math.tan(a3) + math.cos(v38) + math.pi - -(85.338834)
end

-- @return string
function datum1:m15()
  v56, v58, v60, v62 = "1", 15.327130, "4", 69
  local v64, v66 = datum5, "pariatur amet aliquip"
  v58 = math.tan(-28) + -(math.pi)
  v58 = math.cos(v58) - math.pi + -(math.cos(56))
  for i=2,18 do
      v56 = tostring(math.floor(122.563043))
  end
  v56 = tostring(math.floor(0x1.83a412d84fdb7p+7))
  for i, _ in ipairs(datum8) do
      v56 = tostring(57)
  end
  v56 = tostring(math.floor(0x1.538c1bbe4eea3p+7))
  return v56
end

-- @return nil
function func16()
  v70, v72 = 84.504109, [[3]]
  v74, v76, v78, v80 = false, true, datum7, datum0
  v82, v84 = false, v72
  for i=5,20,3 do
      v72 = "4"
      v70 = math.pi + math.tan(v70) + -(math.pi)
      v74 = false ~= not false
  end
  for i=18,2,0x3 do
      v72 = tostring(86)
      v72 = "10"
      v72 = "2"
  end
  local cond86 = 118
  while cond86 > 0x3B do
      v74 = false == not false
      v74 = false == "et eiusmod enim laboris" == v72 == not false
      cond86 = cond86 - 2
  end
  v70 = math.abs(v70) - -(math.tan(v70))
  for i=5,14 do
      v70 = 51.232575 - 91.525583 - -(math.pi)
  end
  return false == "consequat sunt tempor" ~= v72 == not false == v74
end

-- @param a0 string
-- @param a1 string
-- @param a2 int
-- @param a3 int
-- @param a4 int
-- @return float
local func17 = function (a0, a1, a2, a3, a4)
  v87, v89, v91 = datum5, true, a1
  local v93, v95, v97, v99 = a3, -36.491745, [[dolor
Lorem
ea
in]], a0
  v87 = false ~= false == not "Lorem minim quis" ~= "in"
  if a1 == "veniam eu consectetur" then
      a0 = "5"
      a2 = string.len("id non") - - math.floor(a0 + 2)
  end
  a2 = tonumber(a0) or - 39
  local cond101 = false
  while cond101 ~= false do
      v89 = true ~= v87 == not true == true
      a3 = #("nisi ullamco") or -(-28)
      cond101 = true
  end
  return math.pi + math.pi - math.tan(a2) - math.tan(a3) - math.cos(a4) + 90.871185 - -(math.pi)
end

-- @param a0 string
-- @param a1 float
-- @return nil
function func23(a0, a1)
  v102, v104 = "3", false
  local v106, v108, v110 = datum4, datum0, datum3
  local cond112 = true
  repeat
      v104 = "sunt cillum est" == [[Ut
nulla
exercitation
Excepteur]] ~= false == not false
      v104 = "fugiat adipiscing ut Ut" == v102 == [[ut]] == v102 == not "officia" == a0
      cond112 = false
  until cond112 == false
  v104 = "esse cillum proident" == a0 ~= true ~= true == not true
  v102 = tostring(0x7)
  if v102 == "6" then
      a0 = "incididunt"
  else
      v104 = true == "ullamco nulla" ~= v102 == not true == true
  end
  return "ut non enim ipsum" ~= a0 == true == "et adipiscing" ~= v102 == not false == v104
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 string
-- @param a3 boolean
-- @param a4 boolean
-- @return function
function datum8:m26(a0, a1, a2, a3, a4)
  local v114, v116, v118 = datum7, datum3, datum5
  v120, v122, v124 = 0x38, datum0, datum5
  if v114 < 49.242739 then
      v116 = "in quis anim"
  end
  a1 = math.pi - math.pi + -(math.cos(a1))
  if v114 < 85.049873 then
      a3 = true == true == not true
      v116 = "sunt ut"
  end
  if a0 ~= false then
      a4 = [[cupidatat
in]] == v116 == true ~= not "incididunt velit deserunt" ~= "consequat non consectetur nostrud"
      a1 = math.abs(21.489147) - -(math.abs(-36))
      v114 = math.abs(-34) + -(math.tan(a1))
  else
      a0 = "consequat proident" ~= "in ipsum" ~= "Excepteur cupidatat ullamco" ~= v116 ~= not "minim quis" ~= "enim adipiscing id"
  end
  for i=3,0x10,3 do
      a0 = a0 ~= not true ~= a4
      a0 = "anim" == "irure" == not true == a0
      a1 = math.pi + math.tan(a1) - -(math.abs(1))
  end
  return nil
end

-- @param a0 int
-- @return string
local func32 = function (a0)
  local v127, v129, v131 = true, "7", "2"
  v133, v135, v137 = datum5, -92.834389, datum0
  local v139, v141, v143 = "7", -22.168279, datum3
  local cond145 = 8
  repeat
      v127 = false ~= false ~= false == true == not false
      v129 = "10"
      cond145 = cond145 + 1
  until cond145 < 41
  for i, _ in ipairs(datum8) do
      a0 = -38 + - math.floor(130.349515)
      a0 = a0 or string.len("ut in officia ad") - - -10
      v129 = "7"
  end
  if v127 == false then
      v127 = "occaecat pariatur nostrud amet" ~= v129 == false == false == not true
      a0 = 38 or string.len("in proident") - -(0x3E)
      v127 = false == true ~= not false
  else
      a0 = math.floor(94.650453) + string.len("adipiscing") + -(a0)
      v131 = v129
      v131 = "2"
  end
  for i, v in ipairs(datum1) do
      a0 = -23 - - -55
      a0 = 48 + math.floor(104.573881) or -(76)
      v127 = false == not true
  end
  return "id reprehenderit Lorem"
end

-- @param a0 string
-- @param a1 int
-- @param a2 boolean
-- @return string
function datum1:m34(a0, a1, a2)
  local v151, v153 = -26, -0x1.9bf650d64ddp+3
  v155, v157 = datum7, "enim consectetur ut commodo"
  v153 = 36.493332 + -(math.abs(v151))
  if a0 ~= "4" then
      v151 = a1 - 28 or - math.floor(7.048199e+01)
  else
      v151 = 37 + 52 + -(math.floor(96.090169))
      v151 = #("veniam") + -(math.floor(v153))
  end
  local cond159 = 0
  repeat
      a2 = true ~= not true
      cond159 = cond159 + 3
  until cond159 < 47
  a2 = false ~= false ~= not "qui laborum" == a0
  for i=1,15,3 do
      a2 = true == not false == a2
  end
  return "laborum sint commodo"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = "sunt tempor"
local func10_a1 = 0x1.3f8738284933dp+6
local func10_a2 = "Ut"
local func10_a3 = -14
local r_func10_0 = func10(func10_a0, func10_a1, func10_a2, func10_a3)
local r_m15_0 = datum1:m15()
local r_func16_0 = func16()
local func17_a0 = "6"
local func17_a1 = "amet minim"
local func17_a2 = 89
local func17_a3 = -77
local func17_a4 = 97
local r_func17_0 = func17(func17_a0, func17_a1, func17_a2, func17_a3, func17_a4)
local func23_a0 = "Lorem ut ipsum et"
local func23_a1 = 8.686537e+01
local r_func23_0 = func23(func23_a0, func23_a1)
local m26_a0 = false
local m26_a1 = 0x1.6e66e4fff9f9p+5
local m26_a2 = "incididunt amet nisi"
local m26_a3 = true
local m26_a4 = false
local r_m26_0 = datum8:m26(m26_a0, m26_a1, m26_a2, m26_a3, m26_a4)
local func32_a0 = 51
local r_func32_0 = func32(func32_a0)
local m34_a0 = "10"
local m34_a1 = 47
local m34_a2 = true
local r_m34_0 = datum1:m34(m34_a0, m34_a1, m34_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0
local res_datum1 = #(datum1)
local res_datum3 = #(datum3)
local res_datum4 = math.floor(datum4 + 0)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = math.floor(datum6 + 3)
local res_datum7 = math.floor(datum7)
local res_datum8 = ms.table_to_int(datum8)
local res_r_func10_0 = math.floor(r_func10_0)
local res_r_m15_0 = math.floor(r_m15_0 + 0)
local res_r_func16_0 = 1
local res_r_func17_0 = math.floor(r_func17_0)
local res_r_func23_0 = 1
local res_r_m26_0 = 1
local res_r_func32_0 = #(r_func32_0)
local res_r_m34_0 = string.len(r_m34_0)
RESULT = res_r_m34_0 - res_r_func32_0 + res_r_m26_0 - res_r_func23_0 - res_r_func17_0 + res_r_func16_0 + res_r_m15_0 + res_r_func10_0 + res_datum8 + res_datum7 - res_datum6 + res_datum5 - res_datum4 + res_datum3 - res_datum1 + res_datum0
print(math.floor(RESULT))