--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:           1042427330                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = "irure sunt"
local datum1 = -29
local datum2 = {field3 = true}
datum4 = {field5 = "eu"}
datum6 = "2"

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @return nil
local func7 = function (a0)
  local v23, v25, v27, v29 = true, a0, datum1, true
  v31, v33, v35 = "6", true, datum6
  v37, v39, v41, v43 = datum1, 98.608825, "4", "quis do"
  v27 = -4 or - -27
  if v27 >= -55 then
      v27 = #("minim adipiscing") + -(math.floor(26.639317))
  else
      a0 = false == true ~= not true ~= v23
  end
  if datum0 ~= [[ea
Lorem]] then
      a0 = a0 ~= not "ullamco pariatur" ~= "adipiscing consectetur"
      v23 = false ~= true == true ~= not "labore velit anim" ~= "culpa amet"
      v23 = v25 == not true
  else
      a0 = false ~= v25 == false == not true
      v27 = v27 or math.floor(53.171503) or - 71
  end
  local cond45 = true
  while cond45 ~= true do
      a0 = false == false == not v25
      v23 = false == not true
      cond45 = false
  end
  local cond46 = false
  while cond46 ~= false do
      v23 = "sunt non aliqua Duis" ~= "exercitation fugiat" == not "qui nisi" ~= "cupidatat non laboris"
      cond46 = true
  end
  return a0 ~= false ~= v23 ~= false ~= v25 ~= not false
end

-- @param a0 string
-- @return nil
local func9 = function (a0)
  v47, v49 = true, datum0
  v51, v53 = v47, true
  if v49 ~= "ullamco aute commodo" then
      v49 = "fugiat irure"
      v47 = v47 ~= false == v47 == not false
  end
  v49 = "minim ex"
  local cond55 = 3
  repeat
      v47 = false ~= not "cupidatat fugiat elit irure" ~= "officia"
      cond55 = cond55 + 1
  until cond55 < 33
  v47 = false == not true
  return "culpa tempor laboris" ~= a0 ~= v47 ~= not [[in
cupidatat
do]] == v49
end

-- @param a0 string
-- @param a1 boolean
-- @return string
function datum2:m11(a0, a1)
  v56, v58, v60 = datum0, datum6, -93.646831
  v62, v64 = a1, 49.199925
  local v66, v68, v70, v72 = "in sit", 15.762474, -27, "irure nostrud"
  v58 = "4"
  local cond74 = 117
  repeat
      v58 = "4"
      a1 = false == true ~= false ~= not true
      v58 = tostring(math.floor(1.195750e+02))
      cond74 = cond74 - 0x2
  until cond74 >= 55
  a1 = "ea eiusmod" ~= v58 ~= "Ut ex" ~= a0 == not "aliquip" == "irure"
  return "aliqua exercitation proident"
end

-- @param a0 string
-- @param a1 int
-- @return float
function datum2:m14(a0, a1)
  v75, v77, v79 = 49.537127, true, datum6
  v81, v83 = a1, "5"
  v85, v87 = -9.869380, false
  a0 = "non minim pariatur sint"
  v79 = tostring(math.floor(111.667094))
  a0 = "dolore"
  v79 = tostring(91)
  return math.pi - math.cos(a1) - math.abs(v75) - math.pi - -(58.665564)
end

-- @param a0 int
-- @param a1 int
-- @return int
function datum2:m17(a0, a1)
  local v89, v91, v93 = "sunt", false, "9"
  v95, v97, v99, v101 = datum0, "7", -82.116931, true
  local cond103 = 3
  repeat
      v91 = false ~= not false
      a0 = a1 + 67 + -(a1)
      a1 = math.floor(98.832719) or -45 + -(0x15)
      cond103 = cond103 + 3
  until cond103 < 27
  if datum2 == {} then
      a0 = a0 + -(81)
      a1 = #(v89) or #(v89) or - a0
  else
      a0 = #(v89) or -(89)
      v89 = "pariatur ullamco laborum"
      a1 = 74 or a0 or - a1
  end
  if a0 <= 22 then
      v91 = true == not true
      v91 = true == "qui fugiat" ~= "aute anim ad in" == not [[do
dolor
nulla
proident]] == "proident et"
  else
      v89 = "laboris ipsum quis"
      a0 = string.len(v89) - math.floor(147.871780) or - 44
      a1 = math.floor(105.749842) + - -43
  end
  for i=0x3,16,0x2 do
      a0 = 0x5A or -(0x46)
      a1 = -62 + 62 - - 14
  end
  a0 = #(v89) - - a0
  return a0 + a1 - string.len(v89) - -(-66)
end

-- @param a0 boolean
-- @param a1 int
-- @return string
function datum4:m20(a0, a1)
  v106, v108, v110 = a1, 16.264436, -0x1.cca615b273d6p+3
  local v112, v114, v116 = datum6, datum6, datum1
  if v106 < 0x40 then
      v106 = 70 or - -22
      a1 = 10 or - -49
  end
  local cond118 = 7
  while cond118 < 27 do
      a1 = 0x29 + - -28
      cond118 = cond118 + 1
  end
  a0 = false == not true
  return "7"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func7_a0 = true
local r_func7_0 = func7(func7_a0)
local func9_a0 = "4"
local r_func9_0 = func9(func9_a0)
local m11_a0 = "1"
local m11_a1 = false
local r_m11_0 = datum2:m11(m11_a0, m11_a1)
local m14_a0 = "minim"
local m14_a1 = -25
local r_m14_0 = datum2:m14(m14_a0, m14_a1)
local m17_a0 = -61
local m17_a1 = -37
local r_m17_0 = datum2:m17(m17_a0, m17_a1)
local m20_a0 = false
local m20_a1 = -13
local r_m20_0 = datum4:m20(m20_a0, m20_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = datum1
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6 + 0)
local res_r_func7_0 = 1
local res_r_func9_0 = 1
local res_r_m11_0 = string.len(r_m11_0)
local res_r_m14_0 = math.floor(r_m14_0)
local res_r_m17_0 = r_m17_0
local res_r_m20_0 = math.floor(r_m20_0 + 0)
RESULT = res_r_m20_0 - res_r_m17_0 + res_r_m14_0 + res_r_m11_0 - res_r_func9_0 - res_r_func7_0 - res_datum6 - res_datum4 - res_datum2 - res_datum1 + res_datum0
print(math.floor(RESULT))