--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            907812160                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = "laborum nostrud in"}
local datum2 = "10"
local datum3 = 64.349522
datum4 = 28
datum5 = "9"
datum6 = {field7 = "qui veniam"}
local datum8 = -9

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 float
-- @return boolean
function func9(a0, a1)
  local v29, v31, v33 = true, true, "sunt amet"
  local v35, v37, v39 = a1, datum4, "non"
  v41, v43 = "velit ad", a1
  for i=2,10,0x2 do
      v31 = "mollit tempor enim" == [[officia
sit
commodo]] ~= true == not false ~= true
  end
  local cond45 = true
  while cond45 == false do
      v29 = true ~= true == not false
      v29 = true == not "sunt" == "eu consectetur irure sed"
      cond45 = false
  end
  for i=4,19 do
      a0 = string.len("exercitation mollit ea") or 83 + - -34
  end
  v29 = true ~= not true == v31
  a0 = -84 or math.floor(192.440554) + - a0
  return false == false ~= true == v29 == v31 ~= not "eiusmod" == v33
end

-- @param a0 int
-- @param a1 int
-- @param a2 string
-- @param a3 int
-- @param a4 boolean
-- @return string
function datum6:m12(a0, a1, a2, a3, a4)
  v46, v48, v50, v52 = -60.739332, "laboris laborum", false, true
  v54, v56, v58, v60 = -18, datum4, 25.874039, "3"
  v48 = "consequat Ut ipsum anim"
  a1 = 1 + 0 + - -63
  if datum3 ~= 78.736388 then
      v48 = [[cupidatat
ut
deserunt]]
  end
  if datum3 <= 5.252520 then
      v46 = math.pi + math.pi - -(math.pi)
  end
  return "commodo elit minim"
end

-- @param a0 float
-- @param a1 string
-- @param a2 int
-- @param a3 string
-- @return boolean
function datum0:m18(a0, a1, a2, a3)
  v63, v65 = -40, datum4
  local v67, v69 = datum3, -56
  v71, v73 = true, true
  a3 = "8"
  v65 = 2 or 45 or -(v65)
  a1 = [[Excepteur
in]]
  v67 = math.sin(v63) + math.pi + -(8.877287)
  return true == "adipiscing aute reprehenderit" ~= a1 == false == "nulla est et occaecat" == a3 ~= true == false == not false
end

-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @param a3 boolean
-- @param a4 boolean
-- @return boolean
function func23(a0, a1, a2, a3, a4)
  local v76, v78, v80, v82 = 24.167135, "aliqua ullamco", a4, datum8
  local v84, v86 = a3, true
  v88, v90, v92 = a2, 0x4C, "aliqua fugiat"
  v78 = "id nisi"
  v80 = false == not "et minim" == "ut ipsum fugiat"
  if a1 ~= [[exercitation
ea
tempor]] then
      v80 = "anim fugiat eiusmod irure" == "in" ~= true == true ~= not "Ut qui fugiat" == a0
      v78 = "enim esse"
  end
  local cond96 = 112
  while cond96 > 64 do
      a0 = "9"
      cond96 = cond96 - 3
  end
  return [[fugiat
fugiat
non
non]] == a0 ~= [[quis
quis
Duis
nostrud]] == a1 ~= a2 ~= a3 ~= a4 == false == "dolor culpa labore" ~= v78 == not v80
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func9_a0 = 25
local func9_a1 = 87.562172
local r_func9_0 = func9(func9_a0, func9_a1)
local m12_a0 = 0xE
local m12_a1 = -22
local m12_a2 = "nulla culpa"
local m12_a3 = -65
local m12_a4 = false
local r_m12_0 = datum6:m12(m12_a0, m12_a1, m12_a2, m12_a3, m12_a4)
local m18_a0 = 38.512237
local m18_a1 = "mollit cillum"
local m18_a2 = 16
local m18_a3 = "8"
local r_m18_0 = datum0:m18(m18_a0, m18_a1, m18_a2, m18_a3)
local func23_a0 = "7"
local func23_a1 = "officia"
local func23_a2 = true
local func23_a3 = true
local func23_a4 = false
local r_func23_0 = func23(func23_a0, func23_a1, func23_a2, func23_a3, func23_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = math.floor(datum2 + 0)
local res_datum3 = math.floor(datum3)
local res_datum4 = datum4
local res_datum5 = tonumber(datum5)
local res_datum6 = ms.table_to_int(datum6)
local res_datum8 = datum8
local res_r_func9_0 = r_func9_0 and 1 or 0
local res_r_m12_0 = string.len(r_m12_0)
local res_r_m18_0 = r_m18_0 and 1 or 0
local res_r_func23_0 = r_func23_0 and 1 or 0
RESULT = res_r_func23_0 + res_r_m18_0 - res_r_m12_0 + res_r_func9_0 - res_datum8 - res_datum6 + res_datum5 + res_datum4 + res_datum3 - res_datum2 + res_datum0
print(math.floor(RESULT))