--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            807711179                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = false}
local datum2 = 2.121975
local datum3 = {field4 = 88.614782}
local datum5 = -87
local datum6 = true
datum7 = "8"
datum8 = {field9 = "ut deserunt dolore"}

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @return int
local func10 = function (a0, a1, a2, ...)
  v23, v25 = datum5, datum2
  local v27, v29 = a1, a1
  v31, v33 = -8.929276, -47
  for i, v in pairs(datum0) do
      a2 = "laborum incididunt"
  end
  for i, v in ipairs(datum3) do
      a0 = [[ut
et]]
      v27 = "1"
      a1 = tostring(math.floor(147.546517))
  end
  a1 = "1"
  local cond42 = 8
  repeat
      a2 = [[adipiscing
sed
adipiscing]]
      v27 = tostring(math.floor(32.882323))
      v25 = 72.508275 - math.abs(-19) + -(math.tan(121.298766))
      cond42 = cond42 + 2
  until cond42 <= 42
  a0 = "esse exercitation cupidatat id"
  return #(a0) + math.floor(a1 + 1) + string.len(a2) + v23 + math.floor(v25) + - math.floor(v27 + 0)
end

-- @param a0 int
-- @param a1 string
-- @return float
function datum3:m14(a0, a1)
  v44, v46, v48 = a0, "fugiat ea tempor ut", "1"
  v50, v52 = datum2, datum6
  v54, v56, v58 = "ea Ut ex", true, 26.570490
  v44 = a0 + math.floor(0x1.d932cdf668b14p+6) + - -17
  v44 = -1 or -(string.len(v46))
  v44 = math.floor(84.836496) - -(string.len("aute"))
  local cond60 = true
  while cond60 == false do
      v48 = tostring(-5)
      cond60 = false
  end
  return math.sin(a0) - math.pi + math.abs(v44) - math.pi - -(math.pi)
end

-- @return int
function func17(...)
  v61, v63 = 93.544795, "5"
  v65, v67, v69 = -75, datum6, "1"
  v71, v73, v75 = -90.951169, "adipiscing", false
  if datum3 ~= {} then
      v61 = 12.383218 + -(46.437441)
      v63 = "5"
      v65 = string.len("dolor qui eiusmod") + -(string.len("incididunt aliquip"))
  end
  v63 = "10"
  for _, v in ipairs(datum0) do
      v61 = math.pi - math.sin(-17) - -(math.tan(v61))
      v63 = tostring(math.floor(v61))
  end
  if v63 == "4" then
      v65 = math.floor(v63 + 3) + -(math.floor(5.339323e+01))
      v65 = -57 or math.floor(v61) or - math.floor(v61)
  end
  return math.floor(v61) + math.floor(v63 + 1) - - v65
end

-- @param a0 string
-- @return nil
function datum0:m18(a0)
  local v79, v81, v83, v85 = -47, "voluptate", datum6, "Duis irure ullamco aute"
  v87, v89 = v79, a0
  a0 = tostring(v79)
  local cond91 = 118
  while cond91 > 66 do
      v81 = "ut Excepteur"
      v79 = -61 + tonumber(a0) or - #("commodo in ad magna")
      a0 = "3"
      cond91 = cond91 - 1
  end
  v81 = [[proident
nostrud]]
  for i, v in pairs(datum0) do
      v81 = "elit qui"
      a0 = "10"
  end
  return "veniam aliqua Excepteur eu" == a0 == true ~= not "culpa aliqua exercitation" ~= v81
end

-- @return float
function datum3:m20()
  v97, v99, v101, v103 = datum2, 2.981609e+01, "sed aliquip culpa", false
  v105, v107 = datum2, false
  v109, v111 = datum5, -37
  v97 = 3.882375e+01 - math.pi - -(math.sin(6.681897e+00))
  local cond113 = false
  repeat
      v99 = 1.894129 + math.sin(-54) + -(math.pi)
      cond113 = true
  until cond113 ~= false
  for i=0x1,10,2 do
      v101 = v97
      v99 = math.pi + -(math.abs(v99))
  end
  return math.tan(v97) - math.sin(v99) - -(math.pi)
end

-- @param a0 float
-- @return float
local func21 = function (a0)
  v114, v116, v118, v120 = -28.314201, a0, "9", datum2
  local v122, v124 = -50, "ex mollit mollit ullamco"
  for i, _ in pairs(datum8) do
      a0 = 75.971169 + -(math.cos(v114))
      a0 = math.cos(v114) + -(math.pi)
  end
  a0 = 97.383120 - -(math.cos(a0))
  v114 = math.tan(6.808840) - -(math.sin(v114))
  for _, _ in ipairs(datum3) do
      v114 = 0x1.e675f787b61f7p+4 + math.tan(a0) + -(math.abs(v114))
      v114 = 4.620168e+01 + math.sin(v114) + -(math.sin(1.447187e+02))
      v114 = math.cos(0x1.0e773c416edbcp+6) - math.abs(a0) - -(math.abs(v114))
  end
  return math.abs(a0) - math.sin(v114) + -(math.cos(v116))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = "sed aliqua"
local func10_a1 = "10"
local func10_a2 = "culpa nulla"
local func10_vararg0 = 41
local func10_vararg1 = 98.081568
local r_func10_0 = func10(func10_a0, func10_a1, func10_a2, func10_vararg0, func10_vararg1)
local m14_a0 = 0x36
local m14_a1 = "3"
local r_m14_0 = datum3:m14(m14_a0, m14_a1)
local r_func17_0 = func17()
local m18_a0 = [[5]]
local r_m18_0 = datum0:m18(m18_a0)
local r_m20_0 = datum3:m20()
local func21_a0 = 81.257081
local r_func21_0 = func21(func21_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = #(datum3)
local res_datum5 = datum5
local res_datum6 = datum6 and 0x1 or 0
local res_datum7 = math.floor(datum7 + 0)
local res_datum8 = #(datum8)
local res_r_func10_0 = r_func10_0
local res_r_m14_0 = math.floor(r_m14_0)
local res_r_func17_0 = r_func17_0
local res_r_m18_0 = 0x1
local res_r_m20_0 = math.floor(r_m20_0)
local res_r_func21_0 = math.floor(r_func21_0)
RESULT = res_r_func21_0 - res_r_m20_0 - res_r_m18_0 - res_r_func17_0 - res_r_m14_0 + res_r_func10_0 + res_datum8 + res_datum7 + res_datum6 + res_datum5 + res_datum3 - res_datum2 - res_datum0
print(math.floor(RESULT))