--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            977254445                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = [[laborum
minim
non]]
local datum1 = {field2 = 100.998807}
local datum3 = -68
local datum4 = {field5 = "velit Excepteur"}
local datum6 = "1"

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @return function
function datum4:m7()
  local v32, v34 = datum3, "ipsum ipsum"
  v36, v38, v40 = -74.250929, -62, datum6
  v34 = "fugiat officia"
  v34 = v34
  v34 = "irure"
  local cond43 = 2
  while cond43 <= 40 do
      v32 = math.floor(101.775783) or -(-16)
      v34 = "ipsum ullamco nostrud"
      v32 = math.floor(82.530908) or -(93)
      cond43 = cond43 + 1
  end
  return nil
end

-- @param a0 int
-- @param a1 string
-- @param a2 int
-- @param a3 float
-- @return float
function datum1:m8(a0, a1, a2, a3)
  v44, v46, v48 = 68.446063, false, true
  local v50, v52, v54, v56 = true, datum3, datum3, -9.816868
  for i=11,1,3 do
      a2 = 16 - - math.floor(165.482070)
  end
  local cond58 = true
  while cond58 ~= true do
      a2 = #("pariatur labore") - -(math.floor(a3))
      a0 = math.floor(26.441647) or -7 - - tonumber(a1)
      a2 = a2 + #("ea culpa elit nostrud") or - math.floor(a1 + 0)
      cond58 = false
  end
  a2 = a0 or - a0
  local cond59 = 104
  while cond59 > 72 do
      a3 = math.sin(v44) - -(math.pi)
      v44 = math.sin(-6) + -(math.pi)
      cond59 = cond59 - 1
  end
  return math.tan(a0) + 23.267423 - math.abs(a2) - math.abs(a3) - math.cos(v44) + -(55.505405)
end

-- @param a0 float
-- @param a1 int
-- @param a2 int
-- @param a3 string
-- @return float
local func13 = function (a0, a1, a2, a3)
  local v60, v62 = 59.168358, true
  local v64, v66, v68 = 89.042741, v60, a1
  for i, v in ipairs(datum4) do
      a3 = string.gsub(a3, "%z", "")
      a3 = "incididunt ut"
      a0 = math.sin(20) - math.cos(34.838357) + -(math.tan(-38))
  end
  local cond75 = true
  while cond75 ~= true do
      v62 = true ~= not false
      a1 = a1 or -(#(a3))
      a2 = a1 + - -65
      cond75 = false
  end
  for i, v in ipairs(datum1) do
      a0 = math.abs(v60) + -(59.825121)
  end
  v60 = math.sin(0x1.283f4d889a039p+7) - 70.130227 + -(math.pi)
  for _, _ in ipairs(datum4) do
      a2 = math.floor(8.239490e+01) + math.floor(v60) - - 8
  end
  return math.tan(a0) + math.abs(a1) + math.cos(a2) + math.pi - math.cos(v60) + -(0x1.f861987179e8dp+4)
end

-- @return float
function datum4:m18()
  local v80, v82 = datum0, false
  v84, v86, v88, v90 = "10", false, datum3, datum0
  v92, v94 = -64, true
  v80 = "reprehenderit sit elit"
  if v84 ~= "7" then
      v82 = [[veniam
irure]] ~= v80 ~= not false
      v84 = "5"
      v84 = "5"
  else
      v82 = false ~= not "exercitation qui tempor" ~= v84
      v84 = "10"
  end
  v82 = "Duis velit" ~= v84 == not true == true
  if v80 == "sit sint" then
      v82 = v82 == "cillum irure non" == v80 ~= not v82
      v84 = "5"
      v84 = "8"
  end
  return math.pi - 77.964776 + -(8.802957e+01)
end

-- @param a0 float
-- @param a1 string
-- @param a2 float
-- @return table
function datum4:m19(a0, a1, a2)
  local v96, v98, v100 = a1, -46, true
  v102, v104, v106 = 35, a2, a2
  v108, v110 = v96, "10"
  for i, _ in pairs(datum1) do
      a0 = 83.640658 - -(math.pi)
      v100 = false ~= not false
      v100 = [[ea
cupidatat
esse]] ~= a1 == false ~= false == not true ~= false
  end
  v96 = tostring(math.floor(129.120807))
  for i, _ in pairs(datum4) do
      v100 = false == not "Excepteur sunt" == "et consectetur Excepteur"
      v96 = tostring(v98)
      v100 = true == true ~= not "deserunt" ~= "enim mollit veniam incididunt"
  end
  a0 = 8.293394 + -(math.pi)
  local cond116 = 122
  repeat
      v100 = "sit officia" == v96 ~= true ~= not true
      cond116 = cond116 - 0x1
  until cond116 >= 67
  return {a0}
end

-- @param a0 string
-- @param a1 int
-- @param a2 float
-- @param a3 boolean
-- @return float
function func23(a0, a1, a2, a3)
  v118, v120, v122, v124 = -26, a0, 0, a3
  local v126, v128, v130 = -12, "dolor", -20.959603
  local v132, v134, v136 = a1, a3, a0
  for _, v in pairs(datum4) do
      a2 = math.pi + -(81.673631)
  end
  v120 = "exercitation irure in esse"
  if v122 ~= -52 then
      v118 = -33 or string.len("do commodo eiusmod") - -(math.floor(191.093720))
      v120 = "cillum id"
  else
      a1 = 0x3C or -(#(v120))
  end
  v122 = v118 or -(v118)
  return math.pi + math.tan(a1) - math.sin(a2) + math.pi - math.sin(v118) - 90.444015 + -(math.tan(v122))
end

-- @param a0 string
-- @param a1 int
-- @param a2 string
-- @return function
local func28 = function (a0, a1, a2)
  v142, v144, v146 = -45.780658, false, datum3
  v148, v150, v152 = 2.182693, false, datum6
  a2 = a2
  a1 = -81 + - string.len("aute consectetur esse")
  local cond154 = 6
  while cond154 <= 0x18 do
      a2 = "8"
      v142 = 0x1.9e593b9e2ed6ep+1 + -(17.742678)
      cond154 = cond154 + 1
  end
  if datum4 == {} then
      a0 = tostring(-41)
      v144 = "fugiat et Lorem ea" ~= a0 == not true
      a2 = tostring(math.floor(131.232359))
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_m7_0 = datum4:m7()
local m8_a0 = 70
local m8_a1 = "3"
local m8_a2 = -6
local m8_a3 = 93.966755
local r_m8_0 = datum1:m8(m8_a0, m8_a1, m8_a2, m8_a3)
local func13_a0 = 58.387599
local func13_a1 = 26
local func13_a2 = -39
local func13_a3 = "eu laboris minim cillum"
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2, func13_a3)
local r_m18_0 = datum4:m18()
local m19_a0 = 67.858615
local m19_a1 = "3"
local m19_a2 = 33.091627
local r_m19_0 = datum4:m19(m19_a0, m19_a1, m19_a2)
local func23_a0 = "ullamco consectetur commodo"
local func23_a1 = -69
local func23_a2 = 84.072351
local func23_a3 = false
local r_func23_0 = func23(func23_a0, func23_a1, func23_a2, func23_a3)
local func28_a0 = "3"
local func28_a1 = 18
local func28_a2 = "4"
local r_func28_0 = func28(func28_a0, func28_a1, func28_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = datum3
local res_datum4 = #(datum4)
local res_datum6 = math.floor(datum6 + 1)
local res_r_m7_0 = 1
local res_r_m8_0 = math.floor(r_m8_0)
local res_r_func13_0 = math.floor(r_func13_0)
local res_r_m18_0 = math.floor(r_m18_0)
local res_r_m19_0 = ms.table_to_int(r_m19_0)
local res_r_func23_0 = math.floor(r_func23_0)
local res_r_func28_0 = 0x1
RESULT = res_r_func28_0 + res_r_func23_0 + res_r_m19_0 + res_r_m18_0 + res_r_func13_0 - res_r_m8_0 - res_r_m7_0 + res_datum6 - res_datum4 + res_datum3 - res_datum1 - res_datum0
print(math.floor(RESULT))