--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            518280735                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = "4"
datum1 = 78
datum2 = {field3 = false}
datum4 = "1"
local datum5 = "6"
datum6 = {field7 = 0x35}
datum8 = false

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 float
-- @return float
local func9 = function (a0, a1)
  local v35, v37, v39, v41 = a0, "labore", "et adipiscing", datum1
  v43, v45, v47 = -81.791359, v35, "5"
  local v49, v51, v53 = datum8, datum4, "eu labore"
  for i, v in pairs(datum2) do
      v35 = "2"
      a0 = "3"
      v39 = "in"
  end
  a1 = 8.611033e+01 - math.tan(149.485197) + -(5.838036)
  for i, v in pairs(datum2) do
      v37 = "nostrud aute"
  end
  v39 = "cillum esse Excepteur"
  a1 = 99.415053 - -(math.sin(-100))
  for i=2,17 do
      v37 = "nulla"
  end
  return math.pi + math.tan(a1) - 49.632321 - 40.033237 - -(math.pi)
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @return table
function datum2:m12(a0, a1, a2)
  local v62, v64, v66, v68 = datum8, -17, "esse irure", true
  v70, v72 = v62, "mollit ex commodo commodo"
  v74, v76 = datum4, -72.349922
  if a1 == "1" then
      v66 = a2
      v64 = tonumber(a1) - - -69
  end
  v62 = "id" == a2 == not [[ipsum
officia]] ~= v66
  a0 = "Duis magna incididunt"
  a0 = "voluptate"
  return {t80 = a0}
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 float
-- @param a3 int
-- @param a4 int
-- @return boolean
local func16 = function (a0, a1, a2, a3, a4)
  local v82, v84 = a3, datum8
  local v86, v88 = a1, "est dolore"
  local cond90 = false
  repeat
      a2 = math.pi - 49.277299 - -(math.tan(0x29))
      a4 = math.floor(a2) - -(-29)
      a3 = 69 or 97 or - -32
      cond90 = true
  until cond90 ~= false
  a0 = "sit nisi qui" == "in" == not false
  local cond91 = 0x68
  repeat
      v82 = -27 + #([[ipsum
esse
velit]]) - -(math.floor(0x1.464104cfa2e63p+7))
      a2 = math.sin(156.386460) + 0x1.93533fe80dedp+5 - -(math.abs(133.051717))
      cond91 = cond91 - 3
  until cond91 >= 65
  return a0 == "sit velit sit" ~= a1 == true == false ~= true ~= false == not false ~= v84
end

-- @return table
function func22(...)
  v92, v94 = datum4, 12
  v96, v98 = datum4, datum1
  local v100, v102, v104 = true, 31.220349, -68
  v94 = tonumber(v96) or -(#("tempor"))
  v96 = tostring(math.floor(96.434878))
  v94 = 34 + -(#("nisi Duis adipiscing"))
  v94 = -50 + math.floor(198.148930) or - tonumber(v92)
  return {t106 = v92}
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @return nil
function datum6:m23(a0, a1, a2)
  v108, v110 = true, -90
  local v112, v114 = -5.326325e+01, "1"
  local v116, v118, v120, v122 = true, v110, datum4, "dolore qui in"
  local cond124 = false
  while cond124 == true do
      a2 = tostring(math.floor(81.048282))
      v110 = v110 - math.floor(115.441943) + - 89
      v110 = #("enim ad eu") + -19 + - 13
      cond124 = true
  end
  for i=0,13,0x3 do
      v110 = math.floor(a0) + math.floor(v112) or -(math.floor(a0))
      a1 = "6"
      v108 = true ~= not true
  end
  for i, v in ipairs(datum6) do
      a1 = "2"
      a0 = math.cos(v110) + math.sin(v110) + -(math.abs(v112))
      a1 = "2"
  end
  if datum1 ~= 45 then
      v112 = math.tan(v110) - 30.221060 - -(math.cos(171.395704))
      a2 = "2"
  end
  return true ~= "incididunt" ~= a1 == "eu et" == a2 == v108 ~= true == not true
end

-- @return table
function func27()
  local v128, v130 = "ea cupidatat officia", -68.266320
  local v132, v134, v136 = datum8, 81.158448, 70.536301
  for i=0,14,3 do
      v130 = math.cos(150.500502) - -(math.sin(v130))
      v130 = math.pi - math.cos(43) - -(83.868152)
      v130 = math.pi - 83.547571 - -(math.sin(v130))
  end
  v128 = 104.019477
  if v128 == "laboris ex voluptate do" then
      v128 = "magna"
      v130 = math.pi - -(math.pi)
      v130 = math.abs(v130) - 53.201714 + -(math.cos(v130))
  else
      v128 = "eu ullamco magna"
      v128 = "exercitation ut sit"
  end
  v130 = 14.405951 + -(math.cos(v130))
  v128 = "Duis"
  return {-7}
end

-- @param a0 float
-- @return table
function func28(a0)
  v142, v144, v146, v148 = "sint amet eiusmod", 26, true, true
  local v150, v152, v154, v156 = [[7]], false, "dolore occaecat", a0
  v158, v160 = a0, 45.318485
  if v146 ~= true then
      v146 = v146 ~= not false
      v146 = false == true == not true
      v144 = string.len("consequat est consequat qui") or -(-31)
  end
  v144 = v144 + - math.floor(a0)
  local cond162 = 7
  while cond162 < 0x16 do
      v144 = -3 - - v144
      a0 = math.cos(v144) + -(math.sin(v144))
      v142 = v142
      cond162 = cond162 + 2
  end
  local cond163 = 5
  while cond163 <= 0x16 do
      v142 = "nulla in exercitation Duis"
      v144 = -34 - -(v144)
      cond163 = cond163 + 0x2
  end
  return {-8}
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 float
-- @param a3 string
-- @return int
local func30 = function (a0, a1, a2, a3)
  v164, v166, v168 = a1, datum1, a2
  local v170, v172 = datum8, datum5
  v174, v176 = datum8, datum1
  local cond178 = 111
  while cond178 >= 0x40 do
      a0 = math.floor(2.805568) or -4 + -(-22)
      cond178 = cond178 - 1
  end
  a1 = false ~= true == false == not true
  v164 = "incididunt sit nulla" ~= "aliqua consequat" == not true == a1
  v166 = 61 or 98 or -(string.len(a3))
  local cond179 = 4
  repeat
      v164 = true == not true
      a1 = false == true ~= a1 == not false == false
      a1 = true ~= true ~= true == not "Ut nulla" ~= "magna do"
      cond179 = cond179 + 0x2
  until cond179 < 42
  return a0 + 69 + math.floor(a2) + #(a3) or 43 or v166 or -(math.floor(v168))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func9_a0 = "4"
local func9_a1 = 0.010197
local r_func9_0 = func9(func9_a0, func9_a1)
local m12_a0 = "cupidatat anim"
local m12_a1 = "3"
local m12_a2 = "tempor eiusmod sed"
local r_m12_0 = datum2:m12(m12_a0, m12_a1, m12_a2)
local func16_a0 = true
local func16_a1 = "laboris"
local func16_a2 = 46.234494
local func16_a3 = -3
local func16_a4 = -17
local r_func16_0 = func16(func16_a0, func16_a1, func16_a2, func16_a3, func16_a4)
local r_func22_0 = func22()
local m23_a0 = 14.639421
local m23_a1 = "5"
local m23_a2 = "9"
local r_m23_0 = datum6:m23(m23_a0, m23_a1, m23_a2)
local r_func27_0 = func27()
local func28_a0 = 84.570163
local r_func28_0 = func28(func28_a0)
local func30_a0 = 0x48
local func30_a1 = false
local func30_a2 = 57.665357
local func30_a3 = "Lorem nisi ullamco"
local r_func30_0 = func30(func30_a0, func30_a1, func30_a2, func30_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = datum1
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = math.floor(datum4 + 1)
local res_datum5 = math.floor(datum5 + 3)
local res_datum6 = ms.table_to_int(datum6)
local res_datum8 = datum8 and 0x1 or 0
local res_r_func9_0 = math.floor(r_func9_0)
local res_r_m12_0 = ms.table_to_int(r_m12_0)
local res_r_func16_0 = r_func16_0 and 1 or 0
local res_r_func22_0 = ms.table_to_int(r_func22_0)
local res_r_m23_0 = 1
local res_r_func27_0 = #(r_func27_0)
local res_r_func28_0 = ms.table_to_int(r_func28_0)
local res_r_func30_0 = r_func30_0
RESULT = res_r_func30_0 + res_r_func28_0 - res_r_func27_0 - res_r_m23_0 + res_r_func22_0 + res_r_func16_0 - res_r_m12_0 + res_r_func9_0 - res_datum8 + res_datum6 - res_datum5 - res_datum4 - res_datum2 - res_datum1 - res_datum0
print(math.floor(RESULT))