--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            853521728                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = true
datum1 = {field2 = 94.224400}
local datum3 = {field4 = 1}
datum5 = {field6 = "nostrud ipsum labore culpa"}
datum7 = 74.295779

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 int
-- @param a2 string
-- @param a3 boolean
-- @param a4 float
-- @return int
function func8(a0, a1, a2, a3, a4, ...)
  local v27, v29, v31 = -71, "esse veniam", datum7
  local v33, v35 = "3", v27
  local v37, v39 = 72, a3
  if a2 ~= "sunt nostrud" then
      a1 = a1 or a1 or -(#(v29))
      v29 = "laboris cupidatat pariatur labore"
  end
  for _, _ in pairs(datum1) do
      v31 = 53.396722 + math.sin(1.508339e-02) + -(math.pi)
      a3 = true == true == not false == true
  end
  a1 = math.floor(25.094498) - - -1
  a2 = "do in sint ea"
  for i, v in ipairs(datum1) do
      v31 = math.tan(a1) + math.pi - -(math.abs(v27))
  end
  return #(a0) - a1 or #(a2) or 8 + math.floor(a4) + v27 or #(v29) or -(math.floor(v31))
end

-- @param a0 float
-- @return float
function datum1:m14(a0)
  v47, v49, v51, v53 = datum7, "laboris veniam", datum7, 1
  local v55, v57, v59 = a0, "velit sint irure sint", datum0
  v61, v63, v65, v67 = "aliqua dolor", "officia veniam ad", -62, v47
  a0 = math.sin(v51) - math.cos(v51) - -(93.203122)
  local cond69 = 101
  while cond69 >= 0x3D do
      v49 = "enim anim velit"
      cond69 = cond69 - 3
  end
  for i, _ in ipairs(datum3) do
      a0 = math.tan(126.405072) + math.abs(24.266835) - -(83.683960)
      a0 = math.sin(41) - math.pi + -(math.pi)
  end
  return math.tan(a0) - math.sin(v47) - math.pi + -(math.sin(v51))
end

-- @return string
function datum3:m16()
  v73, v75, v77, v79 = 53, -98, false, 0xf
  local v81, v83 = -81, [[sed]]
  if v75 == -20 then
      v73 = #("eu") or -(0x5c)
  else
      v73 = string.len("nulla") or -(v75)
      v75 = 73 + string.len("consequat ipsum est") + -(v75)
      v75 = -46 or math.floor(199.001704) or - math.floor(108.715236)
  end
  local cond85 = 1
  repeat
      v75 = #("aliquip Ut adipiscing") + 48 - - 90
      v73 = math.floor(95.103279) or - 92
      v75 = 0x15 + - math.floor(184.694635)
      cond85 = cond85 + 3
  until cond85 < 0x29
  local cond86 = false
  repeat
      v75 = -36 or -(v73)
      cond86 = true
  until cond86 ~= false
  return tostring(v73)
end

-- @param a0 string
-- @return string
function datum5:m17(a0)
  v87, v89, v91, v93 = -38, 0x4A, "mollit mollit ad", "2"
  local v95, v97, v99, v101 = "incididunt ut nisi", -28, "proident et", datum7
  local v103, v105 = 57.097668, "2"
  for i=11,0,3 do
      v87 = tonumber(a0) or -76 + - 0xD
      a0 = tostring(v87)
  end
  v91 = "aliquip laborum minim"
  local cond108 = 107
  while cond108 > 58 do
      v91 = "ullamco"
      v89 = math.floor(170.256627) + -(math.floor(164.731954))
      cond108 = cond108 - 2
  end
  local cond110 = true
  repeat
      a0 = tostring(-23)
      v89 = -74 - math.floor(24.748164) - -(#(v91))
      cond110 = false
  until cond110 ~= true
  return [[occaecat
non]]
end

-- @param a0 boolean
-- @param a1 int
-- @return table
function datum3:m19(a0, a1)
  local v112, v114 = datum7, "laboris dolor eiusmod"
  v116, v118 = -89, 43.515763
  local v120, v122 = datum0, "8"
  v114 = [[eiusmod
consectetur
quis]]
  if v116 == 51 then
      a0 = "dolore adipiscing Excepteur dolor" ~= "Duis aliqua sed" ~= false == true == not "in pariatur labore" ~= v114
      v116 = -26 + 91 or -(-86)
  else
      a0 = false ~= true == not false == false
      a0 = "quis" ~= "consectetur" ~= not true
      v116 = math.floor(v112) or v116 + - 0x25
  end
  a0 = a0 == true ~= true ~= not false
  if datum7 < 92.637023 then
      v114 = "magna cupidatat"
      v112 = math.pi - -(math.tan(47.872298))
  end
  if a1 == -98 then
      v114 = "laborum laboris et"
  else
      v116 = -43 + - -2
      a0 = true == not true
      v114 = "labore voluptate"
  end
  return {-3}
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 float
-- @param a3 string
-- @return int
function datum5:m22(a0, a1, a2, a3)
  v127, v129, v131, v133 = "laborum in", datum7, a0, 51
  v135, v137, v139, v141 = a1, "7", a3, "6"
  v143, v145, v147 = "8", v129, datum0
  for i=1,15,3 do
      a2 = math.cos(0x1.23060c233800bp+7) - math.abs(0x1.4f4be77118f3cp+6) + -(math.pi)
      a3 = "esse ad eiusmod"
  end
  if v129 < 37.086817 then
      v127 = "non pariatur"
      a3 = 179.653499
  else
      v131 = true ~= false ~= not true
      a2 = 26.687295 - 18.738460 - -(math.pi)
      a1 = "cupidatat aliqua"
  end
  if a2 ~= -50.278621 then
      a1 = "tempor esse"
      a2 = 98.558126 + -(59.366524)
      v129 = 81.995272 - 37.209569 + -(math.sin(v129))
  end
  v127 = 172.894011
  return -76 - string.len(a1) or math.floor(a2) + #(a3) or #(v127) + math.floor(v129) + -(0x35)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = "ut"
local func8_a1 = -79
local func8_a2 = "in in"
local func8_a3 = true
local func8_a4 = 80.784241
local func8_vararg0 = 61.994011
local r_func8_0 = func8(func8_a0, func8_a1, func8_a2, func8_a3, func8_a4, func8_vararg0)
local m14_a0 = 1.408369e-01
local r_m14_0 = datum1:m14(m14_a0)
local r_m16_0 = datum3:m16()
local m17_a0 = "6"
local r_m17_0 = datum5:m17(m17_a0)
local m19_a0 = false
local m19_a1 = -31
local r_m19_0 = datum3:m19(m19_a0, m19_a1)
local m22_a0 = false
local m22_a1 = "mollit dolor esse"
local m22_a2 = 55.725923
local m22_a3 = "Duis"
local r_m22_0 = datum5:m22(m22_a0, m22_a1, m22_a2, m22_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0 and 1 or 0
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = ms.table_to_int(datum3)
local res_datum5 = #(datum5)
local res_datum7 = math.floor(datum7)
local res_r_func8_0 = r_func8_0
local res_r_m14_0 = math.floor(r_m14_0)
local res_r_m16_0 = math.floor(r_m16_0 + 3)
local res_r_m17_0 = #(r_m17_0)
local res_r_m19_0 = #(r_m19_0)
local res_r_m22_0 = r_m22_0
RESULT = res_r_m22_0 + res_r_m19_0 - res_r_m17_0 - res_r_m16_0 - res_r_m14_0 + res_r_func8_0 + res_datum7 - res_datum5 + res_datum3 - res_datum1 + res_datum0
print(math.floor(RESULT))