--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            755106038                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = {field1 = 107.327020}
datum2 = 12.691652
local datum3 = {field4 = true}
local datum5 = -72
local datum6 = "10"
datum7 = {field8 = 11}
datum9 = {field10 = false}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 float
-- @param a2 string
-- @return string
function func11(a0, a1, a2)
  local v24, v26 = -88, 84
  v28, v30 = v24, false
  local cond32 = 1
  while cond32 < 0x2F do
      v26 = string.len(a2) or - #("dolor")
      v26 = 22 or -23 or -(string.len("veniam aute et dolor"))
      cond32 = cond32 + 3
  end
  for i, v in ipairs(datum0) do
      v26 = -52 or v26 or -(string.len("ut eiusmod occaecat"))
      a2 = "sed incididunt"
      a2 = "anim"
  end
  local cond37 = 116
  while cond37 >= 60 do
      a2 = "Excepteur anim dolor et"
      a2 = "veniam ex"
      cond37 = cond37 - 2
  end
  return "5"
end

-- @return string
local func15 = function ()
  v39, v41, v43 = 73, 1.347002e+01, "ea qui minim"
  v45, v47, v49, v51 = false, 9.119245, "fugiat ipsum non ullamco", -59.522051
  local v53, v55, v57 = v39, v41, true
  local cond59 = true
  repeat
      v39 = -77 or v39 or -(-50)
      v39 = math.floor(159.872570) + - -56
      cond59 = false
  until cond59 ~= true
  v39 = string.len("consequat nostrud") + -(75)
  for i, _ in pairs(datum7) do
      v39 = string.len("esse") - - -70
      v41 = math.abs(v41) + math.sin(v41) + -(85.771611)
      v39 = math.floor(18.009979) + -13 + - #(v43)
  end
  if datum5 < -1 then
      v43 = "sed"
      v43 = "culpa laborum"
  end
  v39 = #([[quis
minim
Lorem
qui]]) or #(v43) or -(49)
  return "dolor sunt laboris"
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 int
-- @return table
function datum0:m16(a0, a1, a2)
  v65, v67 = a2, "veniam irure"
  v69, v71, v73, v75 = a1, datum5, "amet veniam in", false
  for i, _ in pairs(datum0) do
      v65 = -18 or -48 or -(v65)
  end
  a0 = "5"
  for _, v in pairs(datum3) do
      v65 = #("in aute eiusmod") - 58 + -(math.floor(a0 + 1))
      v67 = "ullamco dolor Ut culpa"
      a0 = [[9]]
  end
  for i=1,19,2 do
      a2 = #("mollit fugiat") + math.floor(132.043843) + - math.floor(82.748512)
      a0 = "4"
  end
  return {t81 = a0}
end

-- @param a0 string
-- @param a1 int
-- @param a2 boolean
-- @return int
function func20(a0, a1, a2)
  v83, v85, v87, v89 = datum5, "dolor", datum6, true
  v91, v93, v95 = v83, a1, "enim"
  local v97, v99 = -79, "sint deserunt sint"
  if v87 == "1" then
      v85 = "aliqua laboris"
  else
      a2 = "deserunt irure ex dolor" ~= v87 == not false
  end
  if datum2 >= -39.041334 then
      v83 = string.len(v85) + math.floor(0x1.a76f6e4dd8081p+6) or -(a1)
      v83 = 61 or - 49
  end
  if a2 ~= false then
      a0 = "10"
  end
  v83 = math.floor(133.525484) + - math.floor(42.462106)
  return math.floor(a0 + 3) - a1 or 26 or v83 + string.len(v85) + - tonumber(v87)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func11_a0 = true
local func11_a1 = 4.214144e+01
local func11_a2 = "anim"
local r_func11_0 = func11(func11_a0, func11_a1, func11_a2)
local r_func15_0 = func15()
local m16_a0 = "1"
local m16_a1 = true
local m16_a2 = 79
local r_m16_0 = datum0:m16(m16_a0, m16_a1, m16_a2)
local func20_a0 = "2"
local func20_a1 = 73
local func20_a2 = true
local r_func20_0 = func20(func20_a0, func20_a1, func20_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = #(datum3)
local res_datum5 = datum5
local res_datum6 = tonumber(datum6)
local res_datum7 = #(datum7)
local res_datum9 = #(datum9)
local res_r_func11_0 = math.floor(r_func11_0 + 2)
local res_r_func15_0 = string.len(r_func15_0)
local res_r_m16_0 = #(r_m16_0)
local res_r_func20_0 = r_func20_0
RESULT = res_r_func20_0 - res_r_m16_0 + res_r_func15_0 + res_r_func11_0 + res_datum9 + res_datum7 - res_datum6 + res_datum5 - res_datum3 - res_datum2 + res_datum0
print(math.floor(RESULT))