--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            371535770                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = [[10]]
local datum1 = {field2 = 114.769008}
datum3 = "esse eiusmod labore"
local datum4 = {field5 = true}
datum6 = 1
datum7 = {field8 = 0xB}
local datum9 = {field10 = false}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @return nil
function func11(a0)
  local v20, v22, v24, v26 = -85, -87.355676, -3.447537e+01, "7"
  v28, v30, v32, v34 = true, 5.192389, 45.596399, v20
  v22 = 6.961987e+01 + math.tan(28.943618) - -(math.abs(v20))
  if datum1 == {} then
      v20 = math.floor(v22) or v20 + - math.floor(142.290942)
      v22 = math.tan(v22) - math.pi - -(math.pi)
  end
  for i=0x1,15,2 do
      v20 = 63 - 50 + -(v20)
  end
  if datum7 ~= {} then
      v20 = math.floor(115.582661) - 0xd - -(-87)
  else
      a0 = true == true ~= not false == true
      a0 = false == true ~= not true
  end
  return false == a0 ~= true ~= not true
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 float
-- @param a3 string
-- @return nil
function func13(a0, a1, a2, a3, ...)
  v36, v38 = true, -96
  v40, v42, v44 = -83, datum3, a3
  a0 = [[9]]
  if a3 ~= [[ea
eiusmod
cupidatat
nulla]] then
      a2 = math.pi - math.pi + -(math.cos(171.589770))
      a2 = math.sin(a2) + math.cos(v38) - -(83.051930)
  end
  for _, v in pairs(datum1) do
      a2 = math.tan(v38) - math.cos(0x28) - -(8.051534)
  end
  a2 = math.pi + -(73.563597)
  return "in id" ~= a0 == true ~= a1 == true == "dolor laboris" == a3 ~= false == v36 == not true
end

-- @return function
local func18 = function ()
  v48, v50 = "ea laborum", -93.083819
  v52, v54, v56, v58 = "5", "1", datum6, datum3
  v48 = "sunt dolore"
  if v48 == "ut eiusmod adipiscing Ut" then
      v48 = 132.987457
  end
  if v48 == "est laboris" then
      v48 = "aute nisi"
      v48 = "pariatur esse eiusmod"
  else
      v48 = "dolore cillum anim consectetur"
      v50 = math.abs(0x35) + math.pi - -(math.tan(49.940625))
      v48 = "enim do"
  end
  v48 = "aute Excepteur Ut"
  v50 = math.pi + math.pi - -(math.pi)
  local cond64 = 109
  while cond64 > 71 do
      v50 = math.pi + math.cos(94.067304) + -(math.sin(103.884224))
      v50 = 46.969682 - math.pi - -(math.sin(7.276535))
      v48 = "irure"
      cond64 = cond64 - 1
  end
  return nil
end

-- @return function
function func19()
  local v65, v67, v69 = "nisi eiusmod sed Excepteur", -23.263844, 15
  v71, v73, v75, v77 = 59, "6", "labore Excepteur", -46
  local cond79 = 104
  repeat
      v67 = math.pi - math.cos(5) + -(math.tan(v67))
      v65 = "laboris enim"
      v65 = v67
      cond79 = cond79 - 1
  until cond79 > 54
  if v67 >= -95.443241 then
      v67 = math.tan(21) - -(99.124100)
  else
      v65 = 1.965037e+02
  end
  if v65 ~= "enim id" then
      v67 = math.abs(v67) + -(math.pi)
      v65 = v65
  else
      v65 = "est tempor"
      v67 = math.tan(48.074930) - -(math.tan(v67))
      v65 = "labore id aliqua laborum"
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func11_a0 = false
local r_func11_0 = func11(func11_a0)
local func13_a0 = "2"
local func13_a1 = true
local func13_a2 = 44.380741
local func13_a3 = "dolor mollit est"
local func13_vararg0 = false
local func13_vararg1 = "pariatur laboris"
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2, func13_a3, func13_vararg0, func13_vararg1)
local r_func18_0 = func18()
local r_func19_0 = func19()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = #(datum1)
local res_datum3 = string.len(datum3)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = datum6
local res_datum7 = #(datum7)
local res_datum9 = #(datum9)
local res_r_func11_0 = 1
local res_r_func13_0 = 1
local res_r_func18_0 = 0x1
local res_r_func19_0 = 1
RESULT = res_r_func19_0 + res_r_func18_0 + res_r_func13_0 + res_r_func11_0 + res_datum9 + res_datum7 - res_datum6 - res_datum4 + res_datum3 + res_datum1 + res_datum0
print(math.floor(RESULT))