--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            930709708                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
local datum0 = {field1 = true}
local datum2 = true
local datum3 = {field4 = true}
datum5 = false
local datum6 = {field7 = true}
datum8 = {field9 = 45.151047}
local datum10 = {field11 = "enim"}
local datum12 = {field13 = [[deserunt
quis]]}

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @return string
local func14 = function (a0)
  local v29, v31, v33, v35 = "10", "eiusmod velit eu", "4", "dolore dolor proident commodo"
  local v37, v39 = "7", "9"
  a0 = "8"
  a0 = "7"
  v31 = "adipiscing eiusmod"
  v31 = [[irure
Ut
do]]
  return "cillum"
end

-- @param a0 float
-- @return string
function func16(a0)
  v41, v43, v45, v47 = "voluptate est minim", a0, 66, datum5
  v49, v51, v53 = -60, [[8]], a0
  local cond55 = 6
  while cond55 < 0x17 do
      v41 = "pariatur"
      cond55 = cond55 + 3
  end
  local cond56 = true
  repeat
      v43 = math.sin(190.624079) + -(52.733288)
      a0 = 51.424998 - -(math.sin(v43))
      cond56 = false
  until cond56 ~= true
  local cond57 = true
  repeat
      a0 = math.sin(a0) - 48.166036 - -(97.486659)
      cond57 = false
  until cond57 ~= true
  return "dolor consectetur"
end

-- @return string
function datum6:m18()
  v58, v60, v62 = datum5, "fugiat reprehenderit in est", 42
  local v64, v66, v68, v70 = -45, 13.703010, "2", -7.500680e+01
  v58 = false ~= true ~= false == not true
  local cond72 = false
  repeat
      v60 = "cupidatat esse elit"
      cond72 = true
  until cond72 == true
  v60 = "dolore irure"
  if v60 == "laborum Ut" then
      v60 = [[minim
consectetur
Duis]]
      v58 = true == false == "est consequat" == "ut" == not "eu consequat fugiat" ~= v60
  end
  for _, v in pairs(datum6) do
      v58 = false ~= true == false == not false
      v58 = v58 == not "ipsum voluptate non" == v60
  end
  return "officia nulla"
end

-- @param a0 boolean
-- @param a1 int
-- @param a2 int
-- @param a3 int
-- @return int
function func19(a0, a1, a2, a3)
  v77, v79, v81, v83 = datum5, 0x1.f7eb174876c3p+3, false, "nisi ipsum"
  local v85, v87, v89 = "5", 0x36, "aliqua"
  a3 = #("incididunt anim non proident") + math.floor(v79) or -(string.len("fugiat occaecat reprehenderit"))
  local cond91 = true
  repeat
      a2 = -78 + math.floor(184.285723) - -(a1)
      a1 = 22 - 59 - -(34)
      cond91 = false
  until cond91 ~= true
  if v77 ~= true then
      a0 = true == false ~= not true
      v77 = false == not true
      a2 = math.floor(162.761366) or 0x4a + - #([[labore
aute]])
  else
      a2 = -40 + -(a3)
  end
  return -9 + a1 or a2 + a3 + -71 - -(math.floor(v79))
end

-- @param a0 int
-- @param a1 string
-- @param a2 int
-- @return string
function datum6:m24(a0, a1, a2)
  v92, v94, v96, v98 = "10", 54.725339, "2", "esse quis"
  local v100, v102, v104 = "1", v92, datum2
  local v106, v108, v110, v112 = v92, -89.708812, true, v94
  v92 = v92
  local cond114 = 104
  repeat
      v96 = tostring(36)
      a2 = math.floor(v94) or -(tonumber(v92))
      cond114 = cond114 - 0x1
  until cond114 > 57
  v94 = math.pi - -(math.abs(61))
  if a0 >= 12 then
      a0 = math.floor(131.537027) - - -80
  end
  return tostring(a0)
end

-- @return int
function func28()
  local v115, v117 = datum2, "dolor ea ipsum"
  local v119, v121, v123 = v115, [[in
in
id
Lorem]], "1"
  local cond125 = 103
  repeat
      v115 = "nisi dolor" ~= "exercitation cillum" == not "esse laboris" ~= v117
      v117 = "tempor quis"
      cond125 = cond125 - 1
  until cond125 > 51
  v115 = true ~= v115 == not "dolor ullamco ut tempor" ~= "enim"
  local cond127 = true
  repeat
      v115 = "dolore veniam labore veniam" == v117 ~= "quis dolor" ~= v117 == not true == v115
      v115 = "cupidatat reprehenderit" == v117 ~= not false
      cond127 = false
  until cond127 == false
  return 0x18 + - string.len(v117)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func14_a0 = "2"
local r_func14_0 = func14(func14_a0)
local func16_a0 = 22.471881
local r_func16_0 = func16(func16_a0)
local r_m18_0 = datum6:m18()
local func19_a0 = true
local func19_a1 = 50
local func19_a2 = 86
local func19_a3 = 54
local r_func19_0 = func19(func19_a0, func19_a1, func19_a2, func19_a3)
local m24_a0 = -90
local m24_a1 = [[ipsum
commodo
do
do]]
local m24_a2 = -27
local r_m24_0 = datum6:m24(m24_a0, m24_a1, m24_a2)
local r_func28_0 = func28()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = datum2 and 1 or 0
local res_datum3 = #(datum3)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = ms.table_to_int(datum6)
local res_datum8 = #(datum8)
local res_datum10 = #(datum10)
local res_datum12 = #(datum12)
local res_r_func14_0 = #(r_func14_0)
local res_r_func16_0 = #(r_func16_0)
local res_r_m18_0 = #(r_m18_0)
local res_r_func19_0 = r_func19_0
local res_r_m24_0 = tonumber(r_m24_0)
local res_r_func28_0 = r_func28_0
RESULT = res_r_func28_0 - res_r_m24_0 + res_r_func19_0 - res_r_m18_0 - res_r_func16_0 - res_r_func14_0 + res_datum12 + res_datum10 + res_datum8 - res_datum6 - res_datum5 - res_datum3 - res_datum2 - res_datum0
print(math.floor(RESULT))