--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            793782703                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
local datum0 = {field1 = -1}
datum2 = {field3 = false}
local datum4 = {field5 = -43}
datum6 = "ex ut irure"
local datum7 = 9.605835
datum8 = {field9 = true}
local datum10 = {field11 = "sunt occaecat aliqua nostrud"}
datum12 = -2

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 float
-- @return string
function datum4:m13(a0, a1)
  local v38, v40, v42 = false, "nulla ea", datum12
  local v44, v46, v48 = datum6, v38, "10"
  a1 = math.sin(a0) + math.abs(99.137685) + -(math.cos(57.518296))
  if v40 == "pariatur nostrud dolore" then
      v40 = "sunt reprehenderit"
      a0 = math.abs(-71) - math.tan(a0) + -(math.pi)
  end
  a0 = math.pi - -(math.cos(147.873137))
  if datum6 ~= "veniam qui veniam velit" then
      v38 = "proident non dolor" == v40 == true ~= not "Ut non" ~= v40
      a0 = math.pi + -(math.tan(a0))
      a0 = math.pi - 8.976790e+01 - -(math.tan(a0))
  else
      a1 = 19.261266 + 62.255367 + -(98.205841)
      a1 = math.pi - 90.385918 - -(math.cos(a1))
  end
  if v40 == "qui elit nisi" then
      v40 = "eu sed"
  end
  if v38 ~= true then
      v38 = false == not false
  end
  return "commodo velit"
end

-- @param a0 int
-- @param a1 string
-- @param a2 int
-- @param a3 float
-- @param a4 float
-- @return string
function datum8:m16(a0, a1, a2, a3, a4)
  v52, v54 = -90.411150, false
  v56, v58, v60, v62 = datum6, a1, "4", "id laborum eiusmod"
  v64, v66, v68 = datum7, 2.748163e+01, a1
  local cond70 = 7
  repeat
      v56 = 0x1.042b02702da0bp+5
      cond70 = cond70 + 3
  until cond70 <= 0x1F
  local cond72 = false
  repeat
      a3 = math.pi - 43.595862 + -(72.131164)
      a2 = string.len(v56) - a0 or - -97
      cond72 = true
  until cond72 == true
  local cond73 = false
  while cond73 ~= false do
      v52 = math.pi + -(math.abs(a2))
      a2 = string.len("ut id") - -(-69)
      v52 = math.tan(a0) + -(0x1.a42dcd38f63f9p+5)
      cond73 = true
  end
  return "mollit esse ullamco"
end

-- @param a0 int
-- @param a1 int
-- @param a2 int
-- @return string
local func22 = function (a0, a1, a2)
  v74, v76, v78, v80 = -41.319748, "et", datum12, "5"
  local v82, v84, v86, v88 = "7", false, datum12, datum12
  local v90, v92 = 0x1E, 0x1.7685a1701d748p+5
  v76 = "qui anim dolore"
  for i, v in pairs(datum4) do
      a2 = v78 or math.floor(138.423692) + -(-2)
  end
  local cond97 = 9
  while cond97 < 40 do
      v76 = [[aliqua]]
      a0 = -21 or -(#("sed id aliqua"))
      cond97 = cond97 + 0x2
  end
  return "dolore voluptate"
end

-- @param a0 string
-- @return boolean
function func26(a0)
  v100, v102, v104, v106 = "anim cupidatat", false, -33, datum7
  v108, v110, v112, v114 = datum12, datum6, -51, datum12
  v102 = "sit ad ad" == "Ut id" ~= false == not false == v102
  v102 = false == true ~= not true
  v100 = "dolor cillum minim"
  for _, _ in pairs(datum0) do
      v100 = "Ut Excepteur eiusmod"
  end
  local cond118 = false
  while cond118 == true do
      v102 = false ~= "nisi voluptate sit" == v100 == not "quis ea" ~= a0
      a0 = "nostrud nisi"
      a0 = a0
      cond118 = true
  end
  return "nisi velit aliquip" ~= a0 == "consectetur incididunt ex" == v100 == not true ~= v102
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 boolean
-- @param a3 boolean
-- @param a4 float
-- @return nil
function func28(a0, a1, a2, a3, a4)
  v120, v122, v124, v126 = "1", 19, true, a3
  v128, v130 = datum12, v120
  local v132, v134, v136 = a1, "culpa in nisi", a0
  a0 = false ~= a2 == not false == true
  a1 = 5.590770
  for i, v in pairs(datum4) do
      a0 = "in" == a1 ~= true == not true
      v122 = 62 or -72 or - 38
      v124 = true ~= a2 == false ~= not "qui" ~= v120
  end
  a3 = true ~= a2 ~= true ~= not false
  a0 = false ~= [[nulla
nisi
aliqua]] ~= "ut aute" ~= not a0
  return a0 == "culpa eu sint" ~= a1 ~= true ~= a2 ~= a3 ~= false == "in aliquip do pariatur" == v120 ~= false ~= not v124
end

-- @return string
function func34(...)
  local v142, v144, v146 = 7.866480, "1", -68.996657
  local v148, v150, v152, v154 = -56, "8", false, "4"
  v156, v158, v160, v162 = "10", "culpa elit labore et", "velit ut tempor", "5"
  if v142 >= -87.612185 then
      v144 = "9"
      v144 = tostring(math.floor(v146))
      v142 = math.pi + -(math.abs(-63))
  end
  if datum6 == "et ipsum" then
      v142 = math.pi - math.pi - -(15.625638)
  else
      v142 = math.sin(36.237186) - math.pi - -(6.509632)
  end
  v142 = math.abs(79.741396) + -(math.tan(0x19))
  local cond164 = true
  repeat
      v144 = tostring(math.floor(v146))
      cond164 = false
  until cond164 == false
  v144 = tostring(math.floor(v142))
  return tostring(math.floor(v142))
end

-- @param a0 string
-- @param a1 string
-- @return function
function func35(a0, a1)
  v165, v167 = -46, datum7
  v169, v171, v173 = false, datum12, false
  local cond175 = 6
  repeat
      v165 = #("enim elit deserunt") or v165 + - 88
      a0 = "dolor magna tempor"
      v165 = #("elit tempor") or -(75)
      cond175 = cond175 + 2
  until cond175 < 47
  a0 = "commodo sed aliquip aliquip"
  for i=1,15,3 do
      a1 = v167
      a0 = v167
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m13_a0 = 50.017260
local m13_a1 = 79.629243
local r_m13_0 = datum4:m13(m13_a0, m13_a1)
local m16_a0 = 0x36
local m16_a1 = "4"
local m16_a2 = -85
local m16_a3 = 82.872273
local m16_a4 = 0x1.e75cc4fcf09a5p+5
local r_m16_0 = datum8:m16(m16_a0, m16_a1, m16_a2, m16_a3, m16_a4)
local func22_a0 = -53
local func22_a1 = 0xd
local func22_a2 = -20
local r_func22_0 = func22(func22_a0, func22_a1, func22_a2)
local func26_a0 = "consectetur sed"
local r_func26_0 = func26(func26_a0)
local func28_a0 = false
local func28_a1 = "occaecat velit"
local func28_a2 = false
local func28_a3 = false
local func28_a4 = 24.566294
local r_func28_0 = func28(func28_a0, func28_a1, func28_a2, func28_a3, func28_a4)
local func34_vararg0 = "laboris"
local func34_vararg1 = "sunt deserunt"
local func34_vararg2 = false
local r_func34_0 = func34(func34_vararg0, func34_vararg1, func34_vararg2)
local func35_a0 = "ex pariatur non"
local func35_a1 = "veniam est"
local r_func35_0 = func35(func35_a0, func35_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = ms.table_to_int(datum4)
local res_datum6 = string.len(datum6)
local res_datum7 = math.floor(datum7)
local res_datum8 = ms.table_to_int(datum8)
local res_datum10 = #(datum10)
local res_datum12 = datum12
local res_r_m13_0 = string.len(r_m13_0)
local res_r_m16_0 = string.len(r_m16_0)
local res_r_func22_0 = string.len(r_func22_0)
local res_r_func26_0 = r_func26_0 and 1 or 0
local res_r_func28_0 = 1
local res_r_func34_0 = math.floor(r_func34_0 + 0x3)
local res_r_func35_0 = 1
RESULT = res_r_func35_0 + res_r_func34_0 + res_r_func28_0 - res_r_func26_0 - res_r_func22_0 + res_r_m16_0 - res_r_m13_0 - res_datum12 + res_datum10 - res_datum8 + res_datum7 - res_datum6 + res_datum4 + res_datum2 - res_datum0
print(math.floor(RESULT))