--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             98910192                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
local datum0 = [[anim
do]]
local datum1 = {field2 = false}
datum3 = {field4 = true}
local datum5 = "ex"
local datum6 = {field7 = true}
datum8 = {field9 = 146.777201}

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @return string
function datum8:m10()
  v26, v28 = 30, 9.065829
  local v30, v32, v34 = datum0, "5", true
  if datum3 ~= {} then
      v26 = math.floor(73.580597) + -(v26)
      v26 = 5 or 8 - - 0x49
  else
      v28 = math.cos(v28) - math.tan(-99) - -(math.tan(v26))
      v26 = -15 + math.floor(59.246403) - - 14
  end
  for i, v in ipairs(datum1) do
      v28 = 44.340575 - -(math.abs(48))
      v26 = string.len("anim") - -(54)
      v28 = math.pi - -(39.273678)
  end
  local cond39 = false
  while cond39 ~= false do
      v26 = math.floor(v28) or - 0x11
      cond39 = true
  end
  return tostring(v26)
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 float
-- @param a3 float
-- @return string
function datum1:m11(a0, a1, a2, a3)
  v40, v42, v44 = a1, -73, -6
  v46, v48 = "10", -17
  if a0 == true then
      a2 = math.cos(a2) + -(math.sin(a1))
  end
  local cond50 = 0x7C
  repeat
      a2 = math.pi + -(math.pi)
      a0 = true ~= false == not "magna sunt" ~= "sunt in exercitation Ut"
      cond50 = cond50 - 3
  until cond50 > 0x3b
  for i=11,4,0x3 do
      a1 = math.tan(v42) + -(math.tan(-56))
      a3 = math.abs(84) + math.abs(v42) - -(math.pi)
  end
  return "ea aliquip"
end

-- @param a0 string
-- @return function
function datum1:m16(a0)
  local v51, v53, v55 = -58, true, datum0
  v57, v59, v61, v63 = "ullamco amet", 35, v51, -83.056099
  for _, _ in ipairs(datum6) do
      v53 = false ~= not false
      v53 = true == true ~= false ~= not false == false
  end
  v51 = #(a0) - -(-38)
  if a0 ~= [[commodo
Excepteur
eiusmod
anim]] then
      v53 = true ~= true == false ~= not true
      v53 = true ~= false == not "dolore in" ~= "aute labore"
  end
  a0 = "culpa sint"
  v51 = 0x48 + -(math.floor(0x1.16970cec8d41ap+7))
  v51 = 32 - -(-27)
  return nil
end

-- @param a0 string
-- @return string
function datum6:m18(a0)
  v67, v69, v71, v73 = 4, -99, 58.131568, -24
  v75, v77, v79 = "occaecat ut", -70.982823, -58
  local v81, v83, v85, v87 = -22.151164, "3", true, -83
  local cond89 = true
  repeat
      a0 = [[ea
dolor
cupidatat]]
      v67 = v69 or - math.floor(89.007396)
      a0 = "irure in ipsum minim"
      cond89 = false
  until cond89 == false
  a0 = "id irure elit"
  if datum1 ~= {} then
      v71 = math.cos(v67) + math.pi - -(math.sin(-38))
      a0 = 57.579710
      v67 = -100 + -76 or - math.floor(v71)
  else
      v71 = 48.945129 + math.cos(-98) + -(math.abs(v69))
  end
  for i=4,20,2 do
      a0 = "exercitation"
      v71 = math.pi + -(math.abs(57.766754))
      v69 = math.floor(148.751891) + v67 or - v67
  end
  return a0
end

-- @param a0 boolean
-- @return nil
function func20(a0)
  v94, v96, v98 = 10, false, "culpa tempor"
  local v100, v102, v104 = v94, 54, a0
  if datum5 ~= "ut id cupidatat" then
      v96 = a0 == not true == true
  else
      v96 = true ~= not false ~= false
  end
  v94 = 0x10 - - -45
  for i, v in pairs(datum8) do
      a0 = false ~= false == not false
      a0 = a0 ~= false == not false
  end
  local cond109 = false
  repeat
      a0 = true == false == false == not false
      v94 = 100 - -(-73)
      cond109 = true
  until cond109 ~= false
  local cond110 = true
  repeat
      v96 = true ~= a0 ~= not true
      cond110 = false
  until cond110 ~= true
  return false ~= a0 == true ~= not v96
end

-- @param a0 float
-- @return string
function datum1:m22(a0)
  local v111, v113 = datum0, a0
  v115, v117, v119 = 61, -62, "in"
  v121, v123 = true, "6"
  local cond125 = 108
  repeat
      v115 = #(v111) or 46 or - 62
      v115 = math.floor(v113) or math.floor(a0) + -(math.floor(a0))
      v113 = 8.453479e+01 - -(3.200091e+01)
      cond125 = cond125 - 1
  until cond125 >= 0x39
  for i=2,19 do
      a0 = math.tan(v115) + -(math.pi)
      v113 = math.pi + -(math.pi)
      a0 = math.sin(v115) + 4.701715 + -(math.tan(121.227324))
  end
  v111 = v111
  return tostring(math.floor(a0))
end

-- @param a0 boolean
-- @return string
local func24 = function (a0, ...)
  v127, v129, v131 = 7.581725, a0, 69
  v133, v135, v137, v139 = datum5, "4", 22, "est non dolore"
  local v141, v143 = -37, [[7]]
  if v129 == true then
      v131 = -22 - -(math.floor(v127))
      v129 = true == true ~= not true
      v131 = #("sit consectetur") + -95 or -(-74)
  else
      v127 = math.tan(191.142386) + 4.648587e+01 - -(math.pi)
      v127 = math.pi + -(math.pi)
  end
  v129 = v129 ~= not true
  v127 = math.cos(v127) + math.cos(10.810197) - -(24.430758)
  v131 = #("ipsum laboris") or math.floor(137.168940) or -(3)
  local cond145 = true
  repeat
      v129 = true == true ~= not true
      v129 = false ~= not false
      v129 = true == v129 == a0 ~= not false == true
      cond145 = false
  until cond145 == false
  return "10"
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_m10_0 = datum8:m10()
local m11_a0 = false
local m11_a1 = 17.765217
local m11_a2 = 34.124982
local m11_a3 = 78.913272
local r_m11_0 = datum1:m11(m11_a0, m11_a1, m11_a2, m11_a3)
local m16_a0 = [[qui
Lorem
magna]]
local r_m16_0 = datum1:m16(m16_a0)
local m18_a0 = "dolor labore"
local r_m18_0 = datum6:m18(m18_a0)
local func20_a0 = true
local r_func20_0 = func20(func20_a0)
local m22_a0 = 52.248187
local r_m22_0 = datum1:m22(m22_a0)
local func24_a0 = false
local r_func24_0 = func24(func24_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum1 = #(datum1)
local res_datum3 = ms.table_to_int(datum3)
local res_datum5 = #(datum5)
local res_datum6 = #(datum6)
local res_datum8 = #(datum8)
local res_r_m10_0 = tonumber(r_m10_0)
local res_r_m11_0 = #(r_m11_0)
local res_r_m16_0 = 1
local res_r_m18_0 = #(r_m18_0)
local res_r_func20_0 = 1
local res_r_m22_0 = math.floor(r_m22_0 + 3)
local res_r_func24_0 = math.floor(r_func24_0 + 2)
RESULT = res_r_func24_0 + res_r_m22_0 + res_r_func20_0 - res_r_m18_0 + res_r_m16_0 + res_r_m11_0 - res_r_m10_0 - res_datum8 - res_datum6 - res_datum5 - res_datum3 + res_datum1 - res_datum0
print(math.floor(RESULT))