--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            118186301                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = {field1 = "nulla labore"}
datum2 = 0x1.205bc4f368c17p+6
local datum3 = 46
local datum4 = 31.665978
local datum5 = 83.868056

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 string
-- @return string
function datum0:m6(a0, a1)
  local v29, v31, v33, v35 = "occaecat irure", datum3, true, "10"
  v37, v39, v41 = a0, true, "10"
  local v43, v45 = [[4]], "proident fugiat amet"
  for i=0,10 do
      a0 = true ~= "in exercitation fugiat" ~= v29 ~= not true
      a0 = false == true ~= not true
  end
  local cond47 = true
  repeat
      v31 = string.len([[Duis
fugiat]]) - #(v29) or - -18
      v31 = 0x5B + #("ut do") + - math.floor(129.510985)
      cond47 = false
  until cond47 == false
  if a1 ~= "nulla et sint" then
      v33 = "esse qui" ~= a1 ~= not false
      a0 = true ~= not true
  else
      a1 = "proident mollit Ut"
  end
  return "10"
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @param a4 float
-- @return string
function func9(a0, a1, a2, a3, a4)
  local v49, v51, v53 = 26, a4, false
  v55, v57 = 47.538850, datum4
  v59, v61, v63, v65 = false, v51, datum4, true
  v51 = math.pi + -(math.cos(-49))
  local cond67 = true
  while cond67 == false do
      a3 = [[magna
est
nulla
quis]]
      a2 = "1"
      cond67 = false
  end
  local cond68 = true
  while cond68 ~= true do
      v51 = math.pi + math.abs(v49) + -(math.pi)
      cond68 = false
  end
  if datum3 > 36 then
      v53 = false ~= not false
      a3 = "id aliqua eiusmod in"
      v51 = 8.061436 + math.sin(v51) - -(73.270209)
  else
      a3 = "cillum quis"
  end
  return "7"
end

-- @param a0 string
-- @return string
local func15 = function (a0)
  v70, v72, v74, v76 = -98, true, 79, "anim"
  v78, v80, v82, v84 = "proident do", -20, false, 50
  local v86, v88, v90, v92 = v70, datum3, -22, datum3
  local cond94 = true
  while cond94 == false do
      a0 = "aute nulla adipiscing occaecat"
      v74 = string.len("ea ut") or 13 + -(48)
      v74 = -55 + #("dolor magna anim") - - 90
      cond94 = false
  end
  local cond95 = true
  repeat
      v70 = v70 or math.floor(1.389827e+02) or -(math.floor(171.050992))
      a0 = "consequat nostrud dolor"
      v70 = 0xc or v70 + - v70
      cond95 = false
  until cond95 ~= true
  return a0
end

-- @param a0 boolean
-- @return float
local func17 = function (a0)
  v96, v98, v100 = "8", datum4, "esse dolore qui"
  local v102, v104, v106, v108 = -98, datum3, -26, "nostrud labore dolor"
  local v110, v112, v114 = true, datum3, "reprehenderit aute nisi"
  local cond116 = 9
  repeat
      v96 = "10"
      cond116 = cond116 + 1
  until cond116 < 25
  local cond117 = 100
  while cond117 > 68 do
      v98 = math.abs(v98) + math.pi - -(math.pi)
      v98 = math.tan(27) - math.cos(192.885442) - -(85.376071)
      cond117 = cond117 - 1
  end
  return math.pi - 36.497950 - math.sin(v98) - -(91.722590)
end

-- @return string
local func19 = function ()
  v118, v120, v122, v124 = 79.738785, "quis commodo", datum3, true
  local v126, v128, v130, v132 = "laborum dolor reprehenderit ut", "enim nisi adipiscing", true, "7"
  for _, v in ipairs(datum0) do
      v120 = 63.728213
      v120 = v120
  end
  for i=11,5 do
      v120 = "velit"
      v120 = "elit dolor"
      v120 = 197.196803
  end
  if v118 >= 2.406370e+01 then
      v120 = v118
      v120 = v118
  end
  v118 = math.sin(v118) + 80.409646 - -(math.sin(27.381238))
  return "mollit laborum aliquip"
end

-- @param a0 boolean
-- @return function
local func20 = function (a0)
  v140, v142 = a0, "exercitation in"
  local v144, v146 = datum3, datum3
  v140 = true ~= true ~= true == true ~= not false == true
  for _, _ in pairs(datum0) do
      a0 = true ~= true == not true
      a0 = a0 == false ~= not true ~= false
  end
  v142 = "occaecat Excepteur cupidatat"
  v140 = true == true ~= not false
  return nil
end

-- @param a0 boolean
-- @param a1 float
-- @return string
function func22(a0, a1)
  v150, v152, v154 = true, true, a0
  local v156, v158, v160, v162 = "6", datum3, true, datum3
  local v164, v166, v168 = true, -62.566040, a1
  v150 = true ~= true == true == not v154
  for _, v in ipairs(datum0) do
      a0 = true == false == not false
      a0 = true ~= false == not a0
      v152 = false ~= v152 ~= not true ~= true
  end
  local cond172 = 0x6
  while cond172 < 23 do
      v150 = false == not true
      v150 = v154 ~= true ~= not "sit nisi proident qui" ~= "exercitation ut ut"
      cond172 = cond172 + 0x3
  end
  return "tempor"
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 string
-- @return nil
local func25 = function (a0, a1, a2)
  local v174, v176, v178 = true, "9", a0
  local v180, v182 = 0x1.dd7c07f5fab9cp+5, a2
  v184, v186, v188, v190 = "dolor qui", "9", a1, 46.456402
  v174 = true ~= not "consectetur nisi" ~= "in voluptate consequat"
  for i=0x14,1,3 do
      v174 = "et irure" == "minim" == not true == false
      a2 = "ipsum aliqua ullamco enim"
      v176 = [[3]]
  end
  a1 = [[2]]
  if v178 ~= true then
      a1 = "4"
      v176 = tostring(math.floor(5.005714))
  end
  return true == a0 ~= "voluptate aliquip" == a1 == "deserunt ut" ~= a2 == v174 == "ad labore esse" == v176 == not v178
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m6_a0 = true
local m6_a1 = "consectetur ipsum minim"
local r_m6_0 = datum0:m6(m6_a0, m6_a1)
local func9_a0 = false
local func9_a1 = true
local func9_a2 = "7"
local func9_a3 = "pariatur mollit nostrud"
local func9_a4 = 34.956393
local r_func9_0 = func9(func9_a0, func9_a1, func9_a2, func9_a3, func9_a4)
local func15_a0 = "est aliquip Duis"
local r_func15_0 = func15(func15_a0)
local func17_a0 = false
local r_func17_0 = func17(func17_a0)
local r_func19_0 = func19()
local func20_a0 = true
local r_func20_0 = func20(func20_a0)
local func22_a0 = true
local func22_a1 = 4.324213e+01
local r_func22_0 = func22(func22_a0, func22_a1)
local func25_a0 = false
local func25_a1 = "3"
local func25_a2 = "ut ad do"
local r_func25_0 = func25(func25_a0, func25_a1, func25_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = datum3
local res_datum4 = math.floor(datum4)
local res_datum5 = math.floor(datum5)
local res_r_m6_0 = tonumber(r_m6_0)
local res_r_func9_0 = tonumber(r_func9_0)
local res_r_func15_0 = #(r_func15_0)
local res_r_func17_0 = math.floor(r_func17_0)
local res_r_func19_0 = string.len(r_func19_0)
local res_r_func20_0 = 1
local res_r_func22_0 = #(r_func22_0)
local res_r_func25_0 = 0x1
RESULT = res_r_func25_0 + res_r_func22_0 + res_r_func20_0 + res_r_func19_0 - res_r_func17_0 + res_r_func15_0 + res_r_func9_0 - res_r_m6_0 - res_datum5 - res_datum4 + res_datum3 + res_datum2 + res_datum0
print(math.floor(RESULT))