--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            287161230                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = [[5]]
datum1 = {field2 = true}
local datum3 = "ipsum Duis"
local datum4 = false
local datum5 = 83

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 string
-- @param a2 boolean
-- @param a3 boolean
-- @param a4 string
-- @return nil
function datum1:m6(a0, a1, a2, a3, a4, ...)
  v31, v33, v35, v37 = datum3, "4", -3, datum3
  v39, v41 = 83.316092, datum0
  local cond43 = true
  repeat
      v33 = tostring(math.floor(156.799290))
      cond43 = false
  until cond43 == false
  for _, _ in ipairs(datum1) do
      v31 = "culpa nisi"
      v31 = "eu"
  end
  local cond45 = true
  while cond45 ~= true do
      v31 = "dolore ea"
      v31 = "sit sint magna"
      v33 = tostring(math.floor(106.497513))
      cond45 = false
  end
  v31 = "Ut adipiscing"
  return a0 ~= "Ut proident veniam" ~= a1 ~= true ~= a2 ~= a3 == "deserunt dolore officia" ~= a4 == "cillum" ~= v31 == not "ullamco" == v33
end

-- @param a0 string
-- @param a1 int
-- @param a2 boolean
-- @param a3 string
-- @return boolean
function datum1:m12(a0, a1, a2, a3, ...)
  v49, v51, v53, v55 = 80.796321, -29.108014, 10.347586, -72
  v57, v59, v61 = v49, a3, 76
  v51 = math.tan(a1) - -(68.251819)
  if datum5 >= -49 then
      v51 = math.sin(a1) + math.pi + -(math.sin(175.766378))
      a1 = string.len("velit fugiat proident eiusmod") or -84 or - -2
  end
  local cond63 = false
  while cond63 == true do
      a3 = "in deserunt sed"
      a3 = "esse Excepteur Excepteur"
      a0 = a0
      cond63 = true
  end
  local cond66 = 0x1
  repeat
      v51 = 94.922342 - -(math.pi)
      v49 = 57.181914 - -(math.cos(a1))
      a1 = 22 - -(-93)
      cond66 = cond66 + 1
  until cond66 < 38
  return "sit" ~= a0 ~= false == true == a2 == "elit eiusmod pariatur" ~= a3 ~= true == not true
end

-- @param a0 float
-- @return string
function datum1:m17(a0)
  local v67, v69, v71, v73 = -0x1.cf3bfc835536p+2, "5", datum5, datum3
  local v75, v77, v79, v81 = a0, false, v67, "elit"
  local cond83 = 119
  while cond83 > 74 do
      v69 = "8"
      v67 = math.abs(v67) - -(math.abs(v67))
      v69 = "2"
      cond83 = cond83 - 3
  end
  v67 = math.abs(0x1.7f65ee759b829p+7) + -(math.abs(v67))
  if a0 >= 53.907892 then
      a0 = math.tan(a0) - math.cos(5) + -(38.844183)
  end
  v69 = tostring(0x58)
  return tostring(math.floor(a0))
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 string
-- @return string
function func19(a0, a1, a2, a3)
  local v84, v86, v88 = datum0, datum5, true
  local v90, v92, v94 = true, "4", -41.787701
  v96, v98 = false, datum4
  v88 = [[esse
irure
labore]] == a3 == true == true == not false == v88
  if v86 >= 16 then
      a3 = "5"
  else
      a2 = math.sin(0x19) + 72.202755 - -(math.tan(v86))
      a0 = math.tan(-15) - math.tan(0x1.74e08ce207b8ep+6) - -(math.abs(-63))
      a0 = 11.266060 - -(math.pi)
  end
  a3 = tostring(v86)
  v88 = true ~= a1 ~= not "dolore irure" ~= a3
  v88 = true == false ~= not false
  return tostring(math.floor(a0))
end

-- @return function
function datum1:m24()
  local v100, v102, v104, v106 = "10", datum3, 71.632836, false
  local v108, v110, v112, v114 = "irure deserunt", -16.319387, datum3, "7"
  v116, v118, v120, v122 = v102, v102, false, datum3
  v104 = 55.024375 + -(math.cos(0x55))
  v100 = v100
  if datum0 ~= "3" then
      v100 = tostring(math.floor(81.810195))
      v102 = v102
      v100 = [[2]]
  else
      v102 = v102
      v102 = v102
  end
  local cond126 = false
  while cond126 ~= false do
      v102 = "nisi exercitation minim amet"
      cond126 = true
  end
  return nil
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 int
-- @return function
local func25 = function (a0, a1, a2, a3)
  local v128, v130, v132 = datum5, 37.708422, "est Duis dolor"
  v134, v136 = 41.378922, datum3
  local v138, v140, v142 = datum0, datum0, datum4
  v128 = 92 + a3 or -(#("esse incididunt qui"))
  a2 = math.pi - math.abs(a3) + -(73.604917)
  a3 = math.floor(32.758044) or math.floor(a0) or -(math.floor(0x1.fe44e476b7f0cp+6))
  if a2 > 17.017848 then
      a1 = true ~= false == not true
      a0 = 11.910860 + math.sin(v128) - -(math.pi)
  else
      v128 = 0x64 or -(57)
  end
  a0 = math.cos(v130) - 54.698790 - -(math.sin(a3))
  return nil
end

-- @return string
local func30 = function ()
  v144, v146, v148, v150 = true, datum5, -20, 26.533359
  v152, v154, v156, v158 = "enim laboris", datum5, datum0, -87.006582
  if datum5 > 48 then
      v144 = v144 == false ~= not true
      v146 = 18 - -(65)
      v144 = false ~= not false
  end
  local cond160 = 7
  repeat
      v146 = -95 + - 80
      v146 = -71 or -47 + - v146
      v144 = false == v144 ~= not false == v144
      cond160 = cond160 + 2
  until cond160 <= 39
  v146 = math.floor(180.714417) or -(0x25)
  return [[ad
sunt]]
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m6_a0 = false
local m6_a1 = "exercitation cupidatat sunt"
local m6_a2 = false
local m6_a3 = false
local m6_a4 = "proident ullamco qui"
local m6_vararg0 = 32.662323
local m6_vararg1 = 45.702993
local r_m6_0 = datum1:m6(m6_a0, m6_a1, m6_a2, m6_a3, m6_a4, m6_vararg0, m6_vararg1)
local m12_a0 = "6"
local m12_a1 = -20
local m12_a2 = true
local m12_a3 = "ipsum quis"
local m12_vararg0 = 9.630239
local m12_vararg1 = "est sit"
local m12_vararg2 = 4
local r_m12_0 = datum1:m12(m12_a0, m12_a1, m12_a2, m12_a3, m12_vararg0, m12_vararg1, m12_vararg2)
local m17_a0 = 94.489673
local r_m17_0 = datum1:m17(m17_a0)
local func19_a0 = 8.421508e+01
local func19_a1 = false
local func19_a2 = 79.686081
local func19_a3 = "3"
local r_func19_0 = func19(func19_a0, func19_a1, func19_a2, func19_a3)
local r_m24_0 = datum1:m24()
local func25_a0 = 69.565730
local func25_a1 = true
local func25_a2 = 30.660139
local func25_a3 = -49
local r_func25_0 = func25(func25_a0, func25_a1, func25_a2, func25_a3)
local r_func30_0 = func30()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = #(datum1)
local res_datum3 = #(datum3)
local res_datum4 = datum4 and 0x1 or 0
local res_datum5 = datum5
local res_r_m6_0 = 1
local res_r_m12_0 = r_m12_0 and 1 or 0
local res_r_m17_0 = tonumber(r_m17_0)
local res_r_func19_0 = tonumber(r_func19_0)
local res_r_m24_0 = 1
local res_r_func25_0 = 1
local res_r_func30_0 = #(r_func30_0)
RESULT = res_r_func30_0 + res_r_func25_0 - res_r_m24_0 - res_r_func19_0 - res_r_m17_0 - res_r_m12_0 + res_r_m6_0 + res_datum5 + res_datum4 + res_datum3 + res_datum1 + res_datum0
print(math.floor(RESULT))