--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            320903444                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
local datum0 = {field1 = 172.354442}
datum2 = 20.690926
datum3 = {field4 = 1.656141e+02}
local datum5 = {field6 = 87}
datum7 = {field8 = 14}
local datum9 = {field10 = 86.105171}
local datum11 = 59
datum12 = {field13 = 137.801812}

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 int
-- @param a2 float
-- @return function
function func14(a0, a1, a2)
  v29, v31, v33, v35 = "nulla aliqua", 98.817674, true, false
  local v37, v39, v41 = -6.811674e+01, 51, 39.948826
  local cond43 = false
  while cond43 == true do
      v29 = "sit culpa deserunt"
      v31 = math.pi + math.pi - -(math.abs(20))
      cond43 = true
  end
  a1 = math.floor(48.212934) + 38 or - 0x32
  a0 = a0 ~= not false
  v29 = "sed irure mollit"
  local cond46 = 1
  repeat
      v31 = math.abs(a1) - math.tan(83.262788) - -(99.190597)
      a0 = a0 ~= not true
      cond46 = cond46 + 2
  until cond46 <= 27
  return nil
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return string
function datum12:m18(a0, a1, a2, a3)
  local v47, v49, v51 = -19.266522, true, -36
  local v53, v55, v57, v59 = false, a1, 5, false
  for i=0x1,17 do
      a3 = a1
      a3 = tostring(math.floor(138.720347))
      a1 = "1"
  end
  local cond61 = true
  while cond61 ~= true do
      a1 = "8"
      a1 = "4"
      cond61 = false
  end
  for i=2,16 do
      v49 = "sunt ea officia non" ~= "fugiat esse Duis" ~= true == not true
      a0 = "8"
      a0 = a0
  end
  for _, _ in pairs(datum3) do
      a2 = "eu laboris"
      a0 = "1"
  end
  v49 = true == not "ut labore occaecat esse" == a2
  return "dolore adipiscing laboris incididunt"
end

-- @param a0 string
-- @return string
local func23 = function (a0)
  local v65, v67, v69, v71 = datum11, false, -35.564929, "3"
  v73, v75 = [[9]], -56.218879
  v77, v79, v81 = -51, v67, "2"
  v69 = 73.394947 - -(math.cos(160.425440))
  if v65 >= -10 then
      v67 = "voluptate" ~= a0 ~= not true
      v69 = math.abs(v69) + -(math.sin(v69))
  else
      v69 = math.abs(-9) + -(math.cos(35))
  end
  for i, _ in pairs(datum9) do
      a0 = "culpa laborum aliqua in"
  end
  if a0 ~= "deserunt mollit Lorem" then
      a0 = "tempor non in eu"
  end
  for i=0,16 do
      v65 = math.floor(18.813671) or 84 + -(-14)
      a0 = "proident in eu"
  end
  v69 = math.cos(v69) - -(math.pi)
  return a0
end

-- @param a0 string
-- @param a1 float
-- @param a2 float
-- @return function
function datum7:m25(a0, a1, a2)
  local v87, v89 = "deserunt exercitation", false
  v91, v93 = true, "2"
  v95, v97 = v87, v89
  for i=0x14,0,0x2 do
      a0 = a0
      v87 = "magna tempor dolore aute"
  end
  local cond99 = false
  while cond99 == true do
      a2 = math.cos(32) - 3.352092 - -(10.557697)
      v87 = v87
      a0 = "8"
      cond99 = true
  end
  local cond100 = 112
  while cond100 > 0x38 do
      v91 = true ~= "anim in culpa aute" == a0 == not true
      a0 = tostring(math.floor(a1))
      cond100 = cond100 - 3
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func14_a0 = false
local func14_a1 = -76
local func14_a2 = 55.763548
local r_func14_0 = func14(func14_a0, func14_a1, func14_a2)
local m18_a0 = [[6]]
local m18_a1 = "9"
local m18_a2 = "adipiscing ut"
local m18_a3 = "5"
local r_m18_0 = datum12:m18(m18_a0, m18_a1, m18_a2, m18_a3)
local func23_a0 = "sint"
local r_func23_0 = func23(func23_a0)
local m25_a0 = "3"
local m25_a1 = 0x1.0007adeb2cb03p+0
local m25_a2 = 0x1.47f1fcf9cf02p+6
local r_m25_0 = datum7:m25(m25_a0, m25_a1, m25_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = math.floor(datum2)
local res_datum3 = #(datum3)
local res_datum5 = #(datum5)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = datum11
local res_datum12 = ms.table_to_int(datum12)
local res_r_func14_0 = 1
local res_r_m18_0 = string.len(r_m18_0)
local res_r_func23_0 = #(r_func23_0)
local res_r_m25_0 = 0x1
RESULT = res_r_m25_0 + res_r_func23_0 - res_r_m18_0 + res_r_func14_0 - res_datum12 + res_datum11 - res_datum9 + res_datum7 - res_datum5 - res_datum3 - res_datum2 - res_datum0
print(math.floor(RESULT))