--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            867709076                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
local datum0 = 57.265306
datum1 = {field2 = 8.786685e+01}
datum3 = -38
local datum4 = "9"
local datum5 = {field6 = false}
datum7 = {field8 = 1.248641}
local datum9 = [[6]]

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @return string
local func10 = function ()
  v32, v34 = "sit cupidatat deserunt", "7"
  v36, v38, v40 = true, 20.091827, datum3
  local v42, v44, v46 = "mollit culpa", "et mollit", datum9
  v32 = "mollit nisi sit Lorem"
  local cond49 = 4
  while cond49 < 42 do
      v34 = v34
      v32 = "ea Ut"
      v34 = "3"
      cond49 = cond49 + 3
  end
  v34 = v34
  if v36 == false then
      v34 = "4"
  else
      v36 = "nisi Excepteur officia" == "in" ~= not "in" ~= v32
  end
  local cond50 = 0x69
  while cond50 > 71 do
      v32 = "irure"
      v34 = "2"
      cond50 = cond50 - 2
  end
  return "7"
end

-- @param a0 float
-- @param a1 string
-- @return nil
local func11 = function (a0, a1)
  v51, v53 = "occaecat", 43
  local v55, v57, v59, v61 = true, datum0, "1", false
  v63, v65 = a1, v53
  local cond67 = 8
  while cond67 <= 28 do
      v55 = "id" == "ad ut" == not "in sit" == "irure Duis ex nulla"
      v55 = "fugiat minim Duis" == v51 == true == true ~= not true
      cond67 = cond67 + 3
  end
  if datum5 ~= {} then
      v55 = false ~= true ~= not "quis ullamco dolor quis" == a1
      v55 = false ~= not true
      v55 = true == not false
  end
  for _, _ in ipairs(datum7) do
      v51 = "deserunt irure exercitation"
      a0 = math.pi - 95.858165 - -(math.tan(a0))
      v55 = true ~= true == not false
  end
  v51 = v51
  return false ~= "in pariatur in sed" == a1 == "cupidatat tempor" ~= v51 == true == not v55
end

-- @return function
function datum1:m14()
  local v71, v73 = -3.172675, "Ut laboris occaecat"
  v75, v77, v79, v81 = "10", datum0, datum0, [[id]]
  if v71 <= -82.870480 then
      v71 = 83.426628 - math.sin(57.769372) - -(math.cos(v71))
      v73 = "cupidatat voluptate fugiat"
      v73 = v71
  else
      v73 = v71
      v73 = v73
  end
  local cond86 = 105
  repeat
      v71 = math.abs(-49) - -(6.160287e+01)
      cond86 = cond86 - 1
  until cond86 >= 73
  if v71 == -81.309051 then
      v71 = math.pi - math.pi - -(0x1.23124981ac183p+5)
  else
      v73 = 0x1.611b576476145p+7
      v71 = math.pi + -(math.tan(140.335263))
      v71 = math.abs(0x1.64347a3a168a6p+7) - math.sin(96) + -(math.pi)
  end
  local cond87 = 110
  while cond87 >= 60 do
      v71 = math.cos(v71) + -(74.668872)
      v73 = "veniam"
      v73 = v73
      cond87 = cond87 - 1
  end
  return nil
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @param a3 float
-- @param a4 boolean
-- @return function
function datum5:m15(a0, a1, a2, a3, a4)
  v90, v92, v94, v96 = -13, datum0, datum0, "commodo ullamco in"
  v98, v100 = datum3, datum9
  local v102, v104, v106, v108 = v90, a1, "9", datum0
  local cond110 = false
  while cond110 ~= false do
      v90 = math.floor(80.753599) - math.floor(v92) - -(#(a0))
      cond110 = true
  end
  a4 = true ~= false == not "nisi pariatur" ~= "Excepteur nulla"
  if datum0 <= 25.733857 then
      v90 = math.floor(0x1.34d8b8706a5a6p+7) or -8 or -(math.floor(186.740284))
  else
      v94 = math.cos(103.693536) - -(math.pi)
      a2 = "ad non adipiscing sunt"
      a1 = false ~= not false
  end
  v90 = -71 or -30 - -(-46)
  for i=4,12 do
      v94 = math.tan(v94) - math.pi + -(math.sin(85.880643))
      a2 = "qui reprehenderit anim"
      a0 = "sint"
  end
  return nil
end

-- @param a0 float
-- @param a1 string
-- @param a2 float
-- @param a3 int
-- @param a4 string
-- @return table
function func21(a0, a1, a2, a3, a4)
  v112, v114, v116 = a0, datum3, datum4
  local v118, v120, v122, v124 = false, 58.002112, [[sunt
ex]], a4
  if v114 <= -26 then
      a0 = math.tan(5) - math.sin(a0) + -(math.sin(137.489630))
  end
  v112 = math.cos(a2) + math.abs(a0) - -(math.abs(32))
  if datum3 < -99 then
      a4 = tostring(math.floor(v112))
      a2 = math.pi + -(85.045827)
      a4 = "7"
  else
      a3 = v114 or math.floor(a0) + - math.floor(a4 + 0x1)
      a0 = math.cos(a3) + math.pi - -(math.cos(a0))
      a2 = math.pi - -(84.426745)
  end
  if a4 ~= "10" then
      a4 = "10"
      v114 = 63 or -(a3)
  else
      a1 = "ullamco"
      a3 = -16 or - string.len("qui minim sit")
      a1 = "tempor reprehenderit in"
  end
  for i, _ in pairs(datum7) do
      a0 = math.sin(0x1.27b4b99ae66bdp+6) + -(90.606599)
      a4 = tostring(math.floor(a2))
  end
  v112 = math.abs(-39) - math.abs(-25) + -(math.abs(a3))
  return {a0}
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 float
-- @param a3 string
-- @return float
function datum7:m27(a0, a1, a2, a3)
  v128, v130, v132, v134 = 72.696155, 77.641791, a3, "irure Lorem dolore"
  v136, v138 = datum4, "proident anim"
  v140, v142, v144, v146 = datum3, datum0, -23, a2
  for i=5,0xf do
      v132 = "ex"
      v132 = "commodo"
      a0 = true ~= true ~= not true
  end
  v128 = 8.074587e+01 + 92.795936 - -(math.pi)
  v130 = math.cos(127.264448) + math.sin(95.958322) - -(math.tan(58.543410))
  if a2 >= 4.415204 then
      v132 = v128
      a1 = 99.258620 - 98.284380 + -(0x1.1c808af4b2558p+6)
  else
      a1 = math.pi + -(math.tan(a1))
      v130 = 73.446528 + -(43.981698)
  end
  return 6.233475e+01 - math.tan(a1) + math.tan(a2) - math.pi - math.cos(v128) - math.sin(v130) - -(0x1.304eaff013009p+4)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_func10_0 = func10()
local func11_a0 = 30.878419
local func11_a1 = "officia ut dolor"
local r_func11_0 = func11(func11_a0, func11_a1)
local r_m14_0 = datum1:m14()
local m15_a0 = "non occaecat"
local m15_a1 = false
local m15_a2 = "culpa ullamco"
local m15_a3 = 21.663361
local m15_a4 = true
local r_m15_0 = datum5:m15(m15_a0, m15_a1, m15_a2, m15_a3, m15_a4)
local func21_a0 = 50.608633
local func21_a1 = [[cupidatat
amet]]
local func21_a2 = 2.893883e+01
local func21_a3 = 69
local func21_a4 = "5"
local r_func21_0 = func21(func21_a0, func21_a1, func21_a2, func21_a3, func21_a4)
local m27_a0 = true
local m27_a1 = 10.331659
local m27_a2 = 30.834618
local m27_a3 = "id enim"
local r_m27_0 = datum7:m27(m27_a0, m27_a1, m27_a2, m27_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = math.floor(datum0)
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = datum3
local res_datum4 = math.floor(datum4 + 0x2)
local res_datum5 = #(datum5)
local res_datum7 = #(datum7)
local res_datum9 = tonumber(datum9)
local res_r_func10_0 = math.floor(r_func10_0 + 0)
local res_r_func11_0 = 1
local res_r_m14_0 = 0x1
local res_r_m15_0 = 1
local res_r_func21_0 = ms.table_to_int(r_func21_0)
local res_r_m27_0 = math.floor(r_m27_0)
RESULT = res_r_m27_0 - res_r_func21_0 - res_r_m15_0 + res_r_m14_0 + res_r_func11_0 + res_r_func10_0 + res_datum9 - res_datum7 + res_datum5 + res_datum4 - res_datum3 + res_datum1 - res_datum0
print(math.floor(RESULT))