--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            273301540                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
local datum0 = {field1 = "pariatur"}
datum2 = {field3 = false}
datum4 = 75.277094
local datum5 = {field6 = -70}
datum7 = "2"

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 boolean
-- @return nil
local func8 = function (a0, a1)
  v35, v37, v39 = 13.105646, false, false
  local v41, v43, v45 = "aliqua nisi esse", -83.326519, -92
  local cond47 = true
  while cond47 ~= true do
      a1 = true ~= false ~= not false
      cond47 = false
  end
  for i=2,0x11,3 do
      v35 = math.sin(v35) - -(97.421855)
      v35 = math.pi + -(math.pi)
  end
  v37 = false ~= true == not true ~= true
  for i=3,15,0x2 do
      v35 = math.pi - math.pi - -(math.pi)
  end
  return true == a1 == true == not true ~= v37
end

-- @param a0 int
-- @param a1 float
-- @param a2 int
-- @param a3 float
-- @return boolean
function func11(a0, a1, a2, a3)
  local v48, v50, v52, v54 = "9", "2", 70, false
  v56, v58, v60 = datum7, -46, 73.995077
  local cond62 = 0x7
  repeat
      v50 = "1"
      a3 = 13.070192 - -(math.pi)
      a1 = math.sin(44.457151) + -(55.538339)
      cond62 = cond62 + 3
  until cond62 < 22
  v48 = v48
  v48 = tostring(math.floor(a1))
  return true == false ~= true == true == "laboris mollit" == v48 == not "adipiscing dolore" ~= v50
end

-- @param a0 string
-- @param a1 boolean
-- @return table
function datum2:m16(a0, a1)
  local v63, v65 = -13, 48
  v67, v69 = datum7, v63
  if a1 ~= true then
      v63 = 40 + - 43
      v65 = 0x3c or - string.len(a0)
  else
      a1 = false == not a1
      a1 = true == not false
  end
  local cond71 = false
  repeat
      a1 = true ~= true == not false
      cond71 = true
  until cond71 ~= false
  if v63 < 9 then
      a1 = false == not true ~= false
      v65 = 89 + math.floor(1.594079e+02) + - -5
  else
      a1 = false ~= true ~= not true
  end
  v63 = 12 or -11 or - #([[qui
cillum]])
  return {t72 = a0}
end

-- @return boolean
local func19 = function ()
  v74, v76, v78 = false, "veniam in minim", "elit ipsum"
  v80, v82, v84, v86 = false, true, "ea ex in dolore", 88
  if v76 == "reprehenderit" then
      v76 = "Lorem incididunt"
  else
      v74 = false == not true ~= false
  end
  if v76 ~= "nulla" then
      v74 = true == v74 == not true ~= true
      v76 = "cillum tempor magna"
  else
      v76 = "sint amet commodo"
  end
  local cond90 = 124
  while cond90 >= 69 do
      v76 = v76
      cond90 = cond90 - 2
  end
  v74 = false ~= not "adipiscing ullamco dolore dolore" ~= "id consectetur"
  return v74 ~= not "dolore voluptate amet minim" == v76
end

-- @param a0 boolean
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @return nil
function func20(a0, a1, a2, a3)
  v92, v94, v96 = "aliqua fugiat ut", true, "mollit consequat aliquip"
  v98, v100 = datum7, false
  v102, v104, v106, v108 = "quis nisi aute", datum7, v94, "adipiscing eiusmod"
  v92 = v92
  v94 = "sint voluptate" == a3 ~= not false
  v92 = "minim dolore in"
  v94 = false == false ~= true ~= not true ~= false
  if datum0 == {} then
      a3 = "laborum enim voluptate"
      a3 = v92
      a3 = [[sint
dolore]]
  end
  a1 = math.pi - math.abs(81) + -(math.pi)
  return false == a0 ~= false == "proident" == a2 == "magna nulla mollit" ~= a3 ~= "sit fugiat dolore" ~= v92 ~= v94 ~= not [[eu
exercitation]] == v96
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @return int
function datum5:m25(a0, a1, a2, a3, ...)
  v113, v115 = a0, datum7
  v117, v119 = 92.871850, 60
  local cond121 = true
  while cond121 ~= true do
      a0 = false ~= true ~= "eiusmod irure esse aliqua" == a2 == not true
      a3 = "quis Ut dolor"
      cond121 = false
  end
  v115 = "10"
  if a2 ~= "nulla tempor aute amet" then
      v113 = "velit" == "ut ea exercitation amet" ~= not true
  end
  local cond122 = 8
  while cond122 < 31 do
      a0 = "aliquip anim esse" ~= "dolore dolor" == false ~= not "eu magna aliquip" == "irure sint aliqua culpa"
      a0 = "Duis nisi" ~= "esse nisi incididunt" ~= not true
      cond122 = cond122 + 0x3
  end
  return -35 or 58 - string.len(a2) or #(a3) or -76 or -(tonumber(v115))
end

-- @param a0 int
-- @param a1 string
-- @param a2 boolean
-- @param a3 int
-- @return int
function datum0:m30(a0, a1, a2, a3)
  local v123, v125, v127 = "velit labore cupidatat sed", [[fugiat
est]], "in enim"
  local v129, v131 = -89.325979, v123
  a1 = "3"
  if v125 ~= "Duis quis" then
      a2 = true == false ~= not false
      a3 = a3 + 22 - -(#("sint"))
  else
      a3 = math.floor(145.940839) + - string.len("dolore eiusmod")
  end
  for i=2,0xb,3 do
      a2 = true == not "Duis cillum" == "anim dolore mollit do"
  end
  for i=4,11,2 do
      a3 = a0 + -(math.floor(118.075582))
      v123 = "consectetur"
  end
  a0 = string.len("dolore magna commodo ut") + -(math.floor(173.343690))
  for i=0x10,1,2 do
      a0 = math.floor(a1 + 0x1) - -96 + -(#("laboris"))
      a2 = a2 ~= true ~= false ~= not "sunt magna" ~= "in"
  end
  return a0 or tonumber(a1) or -60 + a3 + string.len(v123) or -(string.len(v125))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = 0x3c
local func8_a1 = false
local r_func8_0 = func8(func8_a0, func8_a1)
local func11_a0 = 64
local func11_a1 = 68.116863
local func11_a2 = -65
local func11_a3 = 3.311616
local r_func11_0 = func11(func11_a0, func11_a1, func11_a2, func11_a3)
local m16_a0 = "ut proident"
local m16_a1 = false
local r_m16_0 = datum2:m16(m16_a0, m16_a1)
local r_func19_0 = func19()
local func20_a0 = false
local func20_a1 = 91.003524
local func20_a2 = "9"
local func20_a3 = "exercitation sunt dolor proident"
local r_func20_0 = func20(func20_a0, func20_a1, func20_a2, func20_a3)
local m25_a0 = true
local m25_a1 = false
local m25_a2 = "cupidatat dolore"
local m25_a3 = "sed do elit"
local m25_vararg0 = 61.715563
local m25_vararg1 = true
local m25_vararg2 = false
local r_m25_0 = datum5:m25(m25_a0, m25_a1, m25_a2, m25_a3, m25_vararg0, m25_vararg1, m25_vararg2)
local m30_a0 = -26
local m30_a1 = [[5]]
local m30_a2 = true
local m30_a3 = -66
local r_m30_0 = datum0:m30(m30_a0, m30_a1, m30_a2, m30_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = math.floor(datum4)
local res_datum5 = #(datum5)
local res_datum7 = tonumber(datum7)
local res_r_func8_0 = 1
local res_r_func11_0 = r_func11_0 and 1 or 0
local res_r_m16_0 = #(r_m16_0)
local res_r_func19_0 = r_func19_0 and 1 or 0
local res_r_func20_0 = 1
local res_r_m25_0 = r_m25_0
local res_r_m30_0 = r_m30_0
RESULT = res_r_m30_0 + res_r_m25_0 - res_r_func20_0 - res_r_func19_0 + res_r_m16_0 - res_r_func11_0 + res_r_func8_0 - res_datum7 - res_datum5 + res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))