--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            699517774                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = 66.727932
local datum1 = 38.886524
local datum2 = {field3 = "magna veniam minim"}
datum4 = {field5 = false}
local datum6 = {field7 = true}

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @return int
function func8(a0)
  local v32, v34 = true, "1"
  v36, v38 = datum1, a0
  local cond40 = false
  repeat
      v32 = false == not true
      a0 = true == true == not false ~= a0
      a0 = v32 ~= false == not v32
      cond40 = true
  until cond40 == true
  for i=13,0x2 do
      a0 = v32 == not true == true
      v32 = true ~= a0 ~= not false
      v34 = tostring(22)
  end
  if datum1 > -84.216678 then
      v34 = tostring(math.floor(164.975411))
      a0 = "Duis qui labore velit" ~= "dolore id ut" ~= true == false ~= not false
  else
      v34 = "5"
      v34 = tostring(math.floor(162.854977))
  end
  return 41 or 8 or -(math.floor(v34 + 2))
end

-- @param a0 float
-- @param a1 string
-- @param a2 boolean
-- @param a3 string
-- @return table
local func10 = function (a0, a1, a2, a3)
  local v41, v43, v45, v47 = 16, a0, "nulla fugiat", 0x55
  v49, v51, v53, v55 = v41, -44, 0, a2
  local cond57 = 5
  repeat
      a3 = "6"
      cond57 = cond57 + 3
  until cond57 < 47
  local cond58 = false
  repeat
      v41 = math.floor(v43) - -(33)
      a0 = math.abs(0x1.83d14982b3bedp+4) - -(math.cos(81))
      v41 = -65 - -(#("anim sint"))
      cond58 = true
  until cond58 == true
  local cond59 = false
  repeat
      a1 = tostring(math.floor(a0))
      a0 = math.pi + -(math.cos(v43))
      a3 = tostring(math.floor(152.495677))
      cond59 = true
  until cond59 == true
  return {1}
end

-- @param a0 string
-- @param a1 float
-- @param a2 float
-- @return nil
function datum2:m15(a0, a1, a2)
  local v63, v65, v67, v69 = true, a2, -45.005844, -10.419304
  local v71, v73, v75 = 16, "esse in", "8"
  v77, v79, v81, v83 = true, 88, "culpa commodo", a1
  a0 = tostring(math.floor(a2))
  if v67 == 5.795051 then
      v65 = math.pi + math.cos(a2) - -(14.845989)
  else
      a2 = math.cos(a2) - math.pi - -(math.pi)
      v67 = 48.127165 + -(math.abs(47.642972))
  end
  if a2 <= -94.908372 then
      v67 = 25.914787 + -(math.pi)
  end
  for _, v in pairs(datum6) do
      a1 = math.pi - -(6.170007)
      a1 = math.tan(a2) + 84.257484 - -(math.pi)
  end
  if datum4 == {} then
      v63 = true == not "sit" ~= "proident Excepteur sed officia"
  end
  return "exercitation dolor minim do" == a0 == false == true ~= v63 ~= false == not false
end

-- @param a0 string
-- @param a1 int
-- @param a2 boolean
-- @param a3 boolean
-- @param a4 string
-- @return nil
local func19 = function (a0, a1, a2, a3, a4)
  local v87, v89, v91, v93 = 80, "velit", datum0, a1
  local v95, v97, v99 = "3", true, a0
  v87 = math.floor(96.622429) - -(2)
  local cond101 = 5
  while cond101 <= 47 do
      a2 = "occaecat" == v89 == not "laborum culpa" ~= "in est in"
      a2 = false == not true
      cond101 = cond101 + 3
  end
  if a0 ~= "1" then
      v89 = "dolor exercitation incididunt"
  end
  return "culpa Ut dolor sit" ~= a0 ~= false == a2 ~= true ~= a3 ~= "incididunt dolore enim Ut" == a4 == true == not "nisi voluptate" ~= v89
end

-- @param a0 int
-- @return string
function func25(a0)
  v103, v105, v107 = datum0, "eiusmod in officia", -7.291885
  v109, v111 = false, "9"
  v113, v115, v117, v119 = -18.827357, true, false, 19
  v107 = math.sin(16.772073) + -(math.pi)
  local cond121 = 101
  while cond121 >= 70 do
      v105 = "labore anim sunt labore"
      v105 = "magna"
      a0 = #("anim dolore sint") + 25 or -(math.floor(7.560194e+00))
      cond121 = cond121 - 3
  end
  v105 = v107
  v107 = math.sin(v103) - math.sin(83) - -(math.pi)
  return tostring(a0)
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 boolean
-- @return boolean
function func27(a0, a1, a2)
  local v124, v126, v128 = datum1, false, "8"
  local v130, v132 = a2, "2"
  local cond134 = false
  repeat
      v124 = math.pi + math.pi - -(math.pi)
      a1 = a1 ~= not true
      cond134 = true
  until cond134 ~= false
  v124 = math.pi - 19.009357 - -(math.pi)
  local cond135 = 9
  repeat
      a2 = true ~= not "consequat" == "pariatur sed sed"
      cond135 = cond135 + 0x2
  until cond135 <= 28
  return [[enim]] == a0 ~= a1 ~= a2 == true ~= not true ~= v126
end

-- @return function
function func31()
  v136, v138, v140, v142 = "3", "7", 69, 12
  v144, v146, v148 = 66.850422, 78, "proident Duis labore et"
  local v150, v152, v154 = 74.231584, false, "3"
  v136 = tostring(math.floor(109.518023))
  local cond156 = 4
  repeat
      v136 = v136
      v136 = tostring(math.floor(41.184833))
      cond156 = cond156 + 2
  until cond156 <= 34
  local cond157 = true
  repeat
      v136 = "2"
      cond157 = false
  until cond157 ~= true
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func8_a0 = true
local r_func8_0 = func8(func8_a0)
local func10_a0 = 97.160301
local func10_a1 = "5"
local func10_a2 = true
local func10_a3 = "6"
local r_func10_0 = func10(func10_a0, func10_a1, func10_a2, func10_a3)
local m15_a0 = [[1]]
local m15_a1 = 47.652147
local m15_a2 = 23.413723
local r_m15_0 = datum2:m15(m15_a0, m15_a1, m15_a2)
local func19_a0 = "3"
local func19_a1 = 0x10
local func19_a2 = false
local func19_a3 = false
local func19_a4 = "10"
local r_func19_0 = func19(func19_a0, func19_a1, func19_a2, func19_a3, func19_a4)
local func25_a0 = -54
local r_func25_0 = func25(func25_a0)
local func27_a0 = "ullamco elit"
local func27_a1 = true
local func27_a2 = false
local r_func27_0 = func27(func27_a0, func27_a1, func27_a2)
local r_func31_0 = func31()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = math.floor(datum0)
local res_datum1 = math.floor(datum1)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = ms.table_to_int(datum6)
local res_r_func8_0 = r_func8_0
local res_r_func10_0 = #(r_func10_0)
local res_r_m15_0 = 0x1
local res_r_func19_0 = 1
local res_r_func25_0 = math.floor(r_func25_0 + 0x2)
local res_r_func27_0 = r_func27_0 and 0x1 or 0
local res_r_func31_0 = 1
RESULT = res_r_func31_0 - res_r_func27_0 - res_r_func25_0 + res_r_func19_0 + res_r_m15_0 - res_r_func10_0 - res_r_func8_0 + res_datum6 + res_datum4 + res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))