--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            125333026                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = {field1 = -14}
local datum2 = {field3 = "exercitation dolor ut"}
local datum4 = 16.731409
datum5 = -97
datum6 = "esse elit"
datum7 = 0x2
local datum8 = {field9 = 53}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @return string
local func10 = function ()
  local v23, v25, v27 = "10", datum6, datum6
  local v29, v31, v33, v35 = datum6, "ex", true, true
  for i=16,5,3 do
      v25 = v25
      v23 = "2"
      v25 = v25
  end
  local cond39 = true
  while cond39 == false do
      v23 = v23
      v25 = "voluptate officia"
      cond39 = false
  end
  local cond41 = false
  repeat
      v25 = v25
      cond41 = true
  until cond41 == true
  return v23
end

-- @param a0 boolean
-- @return nil
function datum2:m11(a0)
  v43, v45 = datum7, "tempor ipsum"
  local v47, v49, v51, v53 = -76, datum4, a0, -53.722530
  if datum4 >= 99.871575 then
      v45 = "laboris cillum ea"
  end
  a0 = true ~= not "dolore" ~= v45
  for i, _ in ipairs(datum2) do
      v43 = v43 + - 44
      a0 = a0 == not false
      a0 = "laborum non enim amet" ~= v45 ~= true ~= not false == false
  end
  for i, _ in ipairs(datum8) do
      v45 = "ullamco id"
  end
  a0 = false == false ~= not true
  return a0 ~= false == not "ex magna tempor sit" ~= v45
end

-- @param a0 boolean
-- @return function
local func13 = function (a0)
  local v60, v62, v64, v66 = datum7, -28.279699, "1", datum4
  v68, v70, v72, v74 = false, a0, v60, datum5
  local cond76 = 0
  while cond76 < 0x2A do
      v62 = math.abs(v60) + -(63.358524)
      v62 = 0x1.28e49931b571fp+6 - -(math.sin(v62))
      cond76 = cond76 + 3
  end
  if v60 >= 28 then
      v60 = math.floor(153.211397) + -18 or - #("dolor voluptate")
  end
  a0 = false == true ~= true == not false == a0
  v60 = 59 + 58 - -(34)
  v60 = math.floor(v62) - math.floor(v62) or -(43)
  return nil
end

-- @param a0 string
-- @param a1 int
-- @return function
function datum2:m15(a0, a1)
  local v77, v79, v81 = a1, -72.667970, "4"
  local v83, v85, v87 = 68, 84, datum4
  v89, v91, v93, v95 = false, -62.138627, false, "qui"
  for i=0,18,0x3 do
      a1 = string.len("sunt reprehenderit") or v77 + -(43)
      v79 = 34.781669 - -(math.pi)
  end
  a1 = 87 + 99 or -(math.floor(v79))
  a1 = v77 or -36 or -(a1)
  for i=15,4 do
      v81 = a0
  end
  a1 = string.len("minim ea commodo") or math.floor(v79) or - math.floor(165.974529)
  local cond97 = 6
  repeat
      v79 = math.pi + -(math.sin(v79))
      cond97 = cond97 + 1
  until cond97 <= 0x19
  return nil
end

-- @param a0 int
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @return string
function datum2:m18(a0, a1, a2, a3)
  local v98, v100, v102 = a2, 50, a0
  local v104, v106, v108, v110 = a0, -5.270954, a2, "4"
  local v112, v114, v116, v118 = 76, v100, a0, false
  v102 = -97 or - math.floor(69.257793)
  a1 = math.pi + 37.812305 + -(math.cos(171.354404))
  local cond120 = false
  repeat
      a3 = tostring(-65)
      v98 = "proident nisi pariatur irure"
      cond120 = true
  until cond120 == true
  if a0 ~= 7 then
      a0 = v100 or - #("minim nisi")
      a0 = #(a2) or #("eiusmod cupidatat veniam tempor") or -(83)
      v98 = "labore ipsum nostrud in"
  else
      a2 = "aliquip adipiscing ea"
      v100 = v100 or math.floor(6.158933e+01) - -(#(a2))
      a2 = "Duis quis"
  end
  for _, v in ipairs(datum8) do
      v102 = 65 or -(#("eu nostrud"))
  end
  return tostring(a0)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_func10_0 = func10()
local m11_a0 = false
local r_m11_0 = datum2:m11(m11_a0)
local func13_a0 = true
local r_func13_0 = func13(func13_a0)
local m15_a0 = "8"
local m15_a1 = -96
local r_m15_0 = datum2:m15(m15_a0, m15_a1)
local m18_a0 = 28
local m18_a1 = 2.372315e+01
local m18_a2 = "Excepteur"
local m18_a3 = [[6]]
local r_m18_0 = datum2:m18(m18_a0, m18_a1, m18_a2, m18_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = math.floor(datum4)
local res_datum5 = datum5
local res_datum6 = #(datum6)
local res_datum7 = datum7
local res_datum8 = #(datum8)
local res_r_func10_0 = math.floor(r_func10_0 + 3)
local res_r_m11_0 = 1
local res_r_func13_0 = 1
local res_r_m15_0 = 1
local res_r_m18_0 = math.floor(r_m18_0 + 1)
RESULT = res_r_m18_0 + res_r_m15_0 + res_r_func13_0 - res_r_m11_0 - res_r_func10_0 + res_datum8 - res_datum7 + res_datum6 - res_datum5 - res_datum4 + res_datum2 - res_datum0
print(math.floor(RESULT))