--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            908668602                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = [[id]]
local datum1 = {field2 = "eu magna nostrud amet"}
datum3 = 55.194102
datum4 = {field5 = false}
local datum6 = {field7 = 112.949080}
datum8 = {field9 = "ipsum magna"}
datum10 = false
datum11 = {field12 = true}
local datum13 = {field14 = 34.558116}
local datum15 = {field16 = 68}

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 boolean
-- @param a1 boolean
-- @param a2 string
-- @return function
local func17 = function (a0, a1, a2)
  local v56, v58, v60, v62 = 0x1.ed7af8ee7cdbp+4, "Duis minim", "8", 66
  local v64, v66 = false, datum0
  local cond68 = 122
  repeat
      v56 = math.pi + -(math.abs(182.261549))
      a0 = false ~= not "amet et cupidatat" == "minim ullamco dolore"
      v58 = "esse ut reprehenderit"
      cond68 = cond68 - 1
  until cond68 >= 52
  for _, _ in ipairs(datum11) do
      a1 = "adipiscing nisi adipiscing" == a2 == false ~= not true
      v56 = math.abs(v56) - -(math.sin(v56))
      a2 = "10"
  end
  v58 = "nisi sit"
  return nil
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return float
function datum11:m21(a0, a1, a2, a3)
  local v71, v73, v75 = [[9]], a0, a2
  v77, v79, v81 = false, "mollit minim do", 83
  v73 = math.sin(22.622836) - math.abs(a0) - -(math.sin(a0))
  local cond83 = true
  repeat
      a1 = "9"
      cond83 = false
  until cond83 ~= true
  for _, v in pairs(datum11) do
      a1 = "2"
      a1 = a1
  end
  if v71 ~= "7" then
      a1 = v71
      v71 = tostring(math.floor(0x1.966ebb298fe0dp+4))
      v71 = tostring(math.floor(v73))
  end
  return math.abs(a0) - math.pi - 42.369222 + 1.804478e+01 + math.pi + -(math.abs(v73))
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 int
-- @return boolean
local func26 = function (a0, a1, a2, ...)
  v86, v88 = "in sunt ea", "fugiat labore"
  local v90, v92, v94 = v86, "10", "2"
  local v96, v98, v100 = a1, "2", -67
  if v88 ~= "consequat" then
      a2 = string.len("cupidatat") + string.len("Lorem voluptate") + - #(v86)
  end
  for i, _ in ipairs(datum4) do
      a2 = #("esse voluptate") or -(string.len("in"))
      a2 = #(v90) + - string.len(v90)
      a2 = string.len(v88) or 60 + -(string.len(v88))
  end
  a1 = true == not false
  a0 = math.tan(14) + -(92.951358)
  v86 = "dolore Ut ad"
  return false == true ~= a1 ~= true == "aute esse esse aliquip" == v86 == [[Excepteur
irure
in]] == v88 ~= not [[Excepteur
Duis
laboris
laboris]] ~= v90
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @return float
function datum13:m30(a0, a1, a2)
  local v105, v107, v109 = "anim nostrud in", datum3, "4"
  v111, v113, v115, v117 = 0x1.ac92c289f4cd4p+5, 32.381621, false, "voluptate aliqua amet"
  a2 = a2
  for i=17,3,3 do
      a0 = a0
  end
  a2 = "laborum"
  local cond120 = 0x76
  repeat
      a2 = "culpa anim"
      a2 = "ad"
      a1 = tostring(math.floor(v107))
      cond120 = cond120 - 3
  until cond120 >= 0x3d
  return math.pi - math.pi - math.pi - math.pi + -(math.cos(v107))
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 float
-- @param a3 boolean
-- @param a4 boolean
-- @return nil
function func34(a0, a1, a2, a3, a4)
  local v121, v123 = 17, "ea occaecat"
  v125, v127, v129, v131 = "8", a0, -93, "6"
  local v133, v135, v137 = false, datum3, "1"
  if v123 ~= "adipiscing aliquip" then
      a0 = tostring(51)
      v121 = 1 + 16 or - string.len("dolore pariatur")
      v121 = -92 - - string.len("qui eiusmod")
  else
      a2 = 7.495168e+01 + -(math.sin(a2))
  end
  for _, v in pairs(datum8) do
      v125 = tostring(41)
      a3 = "ut nostrud" ~= v123 ~= false == not [[cupidatat
mollit]] ~= "proident id aute non"
      a3 = a1 ~= not false == a3
  end
  a0 = tostring(v121)
  for i, v in pairs(datum15) do
      a4 = false == true == not false
  end
  a3 = "aliquip laboris anim incididunt" == a0 ~= "Excepteur" ~= "id dolor officia dolor" ~= not false
  return "deserunt" ~= a0 ~= false ~= a1 == true == false == a3 == true ~= a4 == false == "esse ipsum nulla" == v123 ~= not "ex minim" == v125
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 float
-- @return float
function datum11:m40(a0, a1, a2, a3, ...)
  local v144, v146, v148, v150 = 37, "5", "exercitation", 64.614691
  v152, v154 = "sit elit dolore", 17
  v156, v158, v160, v162 = a3, v144, a0, datum0
  local cond164 = true
  while cond164 == false do
      v148 = "ea"
      v148 = "enim aliquip adipiscing"
      v144 = -83 + - -90
      cond164 = false
  end
  a2 = math.pi - 7.378103 - -(5.805651e+01)
  a3 = math.cos(v144) + math.pi + -(math.tan(a3))
  if a3 >= -88.814587 then
      v146 = tostring(math.floor(a3))
      v144 = #(v148) + string.len([[deserunt
sit
do]]) or - 0x21
  else
      a3 = 31.262561 - -(math.cos(114.000657))
  end
  if v146 == "10" then
      a1 = false == "deserunt in in" ~= "ea deserunt incididunt" == not false
  else
      v146 = "4"
  end
  return math.sin(a0) + math.pi + math.tan(a2) + math.tan(a3) - math.abs(v144) - 69.481305 + -(math.pi)
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 boolean
-- @param a4 float
-- @return string
function datum4:m45(a0, a1, a2, a3, a4)
  v166, v168, v170, v172 = a0, datum3, a0, false
  local v174, v176, v178, v180 = datum0, a4, datum10, [[5]]
  local cond182 = false
  while cond182 ~= false do
      a1 = "4"
      a2 = tostring(math.floor(v168))
      a1 = "2"
      cond182 = true
  end
  v168 = math.pi - -(21.844743)
  if datum8 == {} then
      v166 = "velit sunt laboris dolore"
      a4 = math.cos(a4) - math.pi + -(51.916574)
      a0 = "labore"
  else
      v168 = math.pi - -(math.cos(58))
      a1 = "4"
      v168 = math.pi - 79.799297 + -(math.sin(76))
  end
  return "9"
end

-- @param a0 int
-- @param a1 string
-- @param a2 boolean
-- @param a3 float
-- @return boolean
function func51(a0, a1, a2, a3)
  local v184, v186 = "5", a3
  local v188, v190 = a3, v184
  if datum6 == {} then
      a1 = "voluptate"
  else
      v184 = v184
      a3 = math.pi + math.pi + -(math.abs(-90))
  end
  if a0 <= 8 then
      a1 = "labore dolor"
      a0 = math.floor(1.673893e+02) - -2 + - math.floor(173.017404)
  end
  v184 = tostring(math.floor(a3))
  if a3 >= 72.712338 then
      v186 = math.tan(61) + 17.760891 + -(math.pi)
      a2 = false ~= true == not true
      a1 = 196.755857
  else
      a0 = tonumber(v184) or -(#(a1))
  end
  return false ~= "minim" == a1 == true ~= a2 ~= true ~= "mollit" == v184 ~= not false
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func17_a0 = false
local func17_a1 = false
local func17_a2 = "2"
local r_func17_0 = func17(func17_a0, func17_a1, func17_a2)
local m21_a0 = 59.133704
local m21_a1 = "8"
local m21_a2 = [[7]]
local m21_a3 = "ut irure"
local r_m21_0 = datum11:m21(m21_a0, m21_a1, m21_a2, m21_a3)
local func26_a0 = 0x1.820b244c349d2p+3
local func26_a1 = true
local func26_a2 = 6
local func26_vararg0 = 0x1
local r_func26_0 = func26(func26_a0, func26_a1, func26_a2, func26_vararg0)
local m30_a0 = "8"
local m30_a1 = "6"
local m30_a2 = "consectetur sed eu"
local r_m30_0 = datum13:m30(m30_a0, m30_a1, m30_a2)
local func34_a0 = "3"
local func34_a1 = true
local func34_a2 = 48.264993
local func34_a3 = true
local func34_a4 = true
local r_func34_0 = func34(func34_a0, func34_a1, func34_a2, func34_a3, func34_a4)
local m40_a0 = 82.433387
local m40_a1 = true
local m40_a2 = 67.963443
local m40_a3 = 7.999050
local m40_vararg0 = [[exercitation
enim
nulla
do]]
local m40_vararg1 = -93
local r_m40_0 = datum11:m40(m40_a0, m40_a1, m40_a2, m40_a3, m40_vararg0, m40_vararg1)
local m45_a0 = "adipiscing in consectetur voluptate"
local m45_a1 = "9"
local m45_a2 = "5"
local m45_a3 = false
local m45_a4 = 27.903799
local r_m45_0 = datum4:m45(m45_a0, m45_a1, m45_a2, m45_a3, m45_a4)
local func51_a0 = 4
local func51_a1 = "ut sint"
local func51_a2 = true
local func51_a3 = 17.323254
local r_func51_0 = func51(func51_a0, func51_a1, func51_a2, func51_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = string.len(datum0)
local res_datum1 = #(datum1)
local res_datum3 = math.floor(datum3)
local res_datum4 = #(datum4)
local res_datum6 = #(datum6)
local res_datum8 = #(datum8)
local res_datum10 = datum10 and 1 or 0
local res_datum11 = ms.table_to_int(datum11)
local res_datum13 = ms.table_to_int(datum13)
local res_datum15 = ms.table_to_int(datum15)
local res_r_func17_0 = 0x1
local res_r_m21_0 = math.floor(r_m21_0)
local res_r_func26_0 = r_func26_0 and 1 or 0
local res_r_m30_0 = math.floor(r_m30_0)
local res_r_func34_0 = 1
local res_r_m40_0 = math.floor(r_m40_0)
local res_r_m45_0 = math.floor(r_m45_0 + 3)
local res_r_func51_0 = r_func51_0 and 1 or 0
RESULT = res_r_func51_0 - res_r_m45_0 + res_r_m40_0 + res_r_func34_0 + res_r_m30_0 + res_r_func26_0 - res_r_m21_0 + res_r_func17_0 + res_datum15 + res_datum13 + res_datum11 + res_datum10 + res_datum8 + res_datum6 + res_datum4 - res_datum3 - res_datum1 - res_datum0
print(math.floor(RESULT))