--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            966922494                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  9 statements)         --
--------------------------------------------------------
datum0 = "4"
datum1 = true
datum2 = "6"
local datum3 = 41.553156
datum4 = {field5 = 179.355746}
local datum6 = false
datum7 = "enim adipiscing do"
datum8 = {field9 = "consequat magna Duis"}
datum10 = "7"

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @return string
function datum4:m11(a0)
  v44, v46 = "cupidatat", datum7
  local v48, v50, v52 = v44, datum0, datum7
  local v54, v56, v58 = true, true, a0
  a0 = "8"
  v48 = "laboris"
  a0 = "10"
  v48 = "incididunt consequat anim"
  if datum7 == "esse" then
      v48 = [[tempor]]
  else
      v44 = "Excepteur pariatur"
  end
  return a0
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @param a3 int
-- @param a4 string
-- @return int
local func13 = function (a0, a1, a2, a3, a4)
  local v62, v64, v66, v68 = 0.107511, "id in", a3, a2
  v70, v72, v74, v76 = "1", false, a2, datum10
  local cond78 = 111
  while cond78 > 72 do
      v62 = math.tan(0x27) - -(math.abs(83))
      a4 = tostring(-89)
      cond78 = cond78 - 1
  end
  if a1 == "6" then
      a2 = math.pi + 0x1.1a18914e476b5p+3 - -(0x1.266fa154f4a04p+6)
      a3 = math.floor(v62) or math.floor(0x1.5cf418fd0b927p+6) + -(math.floor(a2))
      a3 = math.floor(a2) + -70 or -(-22)
  else
      a1 = tostring(math.floor(105.768266))
      v64 = 0x1.4089866d0d5acp+6
      a3 = -69 + -(math.floor(a2))
  end
  v62 = math.abs(0x29) - -(math.tan(-35))
  local cond79 = false
  repeat
      a0 = "in"
      cond79 = true
  until cond79 ~= false
  return string.len(a0) or tonumber(a1) + math.floor(a2) - a3 + tonumber(a4) + math.floor(v62) + - string.len(v64)
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 string
-- @return string
function func19(a0, a1, a2)
  v81, v83 = -91.564165, datum1
  local v85, v87 = true, 0x4f
  a2 = a2
  local cond89 = false
  repeat
      a2 = "10"
      a0 = -47 or -(95)
      v83 = v83 == not true
      cond89 = true
  until cond89 == true
  v81 = math.abs(74.406539) - math.pi - -(math.cos(77.995928))
  return tostring(a0)
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 string
-- @return string
function datum4:m23(a0, a1, a2)
  v90, v92 = a0, a2
  local v94, v96 = v90, a0
  local cond98 = true
  while cond98 ~= true do
      a1 = false == not false
      a1 = false ~= "commodo ipsum laboris" ~= "culpa in" == not false
      a1 = false ~= true ~= true ~= not "Ut dolore esse" ~= a2
      cond98 = false
  end
  for i=1,12 do
      v90 = 15.262962 - -(math.abs(57))
      v90 = 2.334040e+01 - math.pi - -(35.178828)
      v92 = "exercitation"
  end
  local cond99 = 0x79
  while cond99 >= 73 do
      v92 = "cillum"
      cond99 = cond99 - 0x2
  end
  return "quis"
end

-- @return boolean
function datum4:m27()
  local v102, v104, v106 = datum10, datum1, datum3
  local v108, v110, v112, v114 = true, [[qui
incididunt]], datum7, 68.090257
  local cond116 = 6
  repeat
      v104 = false == not false
      v104 = true ~= not "cillum" == v102
      v102 = "10"
      cond116 = cond116 + 1
  until cond116 < 0x1c
  v104 = true == false == not "culpa minim irure" ~= v102
  v104 = true ~= "consequat sed non ullamco" == v102 ~= not true == true
  return "dolor adipiscing tempor" == v102 == not true ~= v104
end

-- @param a0 float
-- @param a1 string
-- @param a2 boolean
-- @param a3 int
-- @param a4 string
-- @return table
function datum4:m28(a0, a1, a2, a3, a4, ...)
  v117, v119 = datum7, "7"
  local v121, v123 = -65, a3
  v125, v127, v129, v131 = datum2, a3, "aute in id", a0
  a2 = true == not true == false
  if a2 ~= true then
      a4 = "consequat"
      v117 = "aliquip Excepteur in occaecat"
      v121 = 12 + v121 or -(-2)
  else
      a0 = math.pi + -(85.501411)
      a4 = 133.620584
  end
  v117 = "nostrud amet eu"
  a1 = "1"
  v121 = string.len(v117) + 60 + -(56)
  return {a0}
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 boolean
-- @return float
function func34(a0, a1, a2)
  v140, v142, v144, v146 = datum2, 8, -53, "10"
  v148, v150, v152, v154 = datum0, -65, "dolor fugiat sunt", v140
  a0 = "enim dolore"
  if a0 == "veniam pariatur eiusmod Excepteur" then
      a2 = true == false == a2 ~= not true
  end
  local cond157 = 7
  while cond157 <= 50 do
      a0 = [[esse
cupidatat
commodo
fugiat]]
      a2 = a2 ~= true ~= not false == a1
      a0 = "cillum nisi incididunt nostrud"
      cond157 = cond157 + 3
  end
  v142 = 79 + -(41)
  return math.pi - 13.995637 + math.pi + 0x1.e617feb1da0c8p+5 - -(math.sin(v142))
end

-- @param a0 float
-- @param a1 int
-- @param a2 int
-- @param a3 boolean
-- @param a4 string
-- @return nil
function datum8:m38(a0, a1, a2, a3, a4)
  local v159, v161, v163, v165 = a1, [[8]], "10", datum7
  v167, v169 = a2, -13
  v171, v173, v175 = a3, datum7, -30.596212
  local cond177 = 0x5
  while cond177 <= 26 do
      a1 = 65 + - math.floor(v161 + 1)
      a1 = 65 or -(#([[dolore
eiusmod
sed
cupidatat]]))
      cond177 = cond177 + 0x3
  end
  for _, _ in pairs(datum4) do
      a4 = "Lorem"
      v161 = "5"
      a2 = a2 - - #("occaecat nostrud nulla")
  end
  a0 = math.pi + math.pi - -(math.tan(a1))
  return true == true == false ~= a3 ~= "est proident cupidatat" ~= a4 ~= false ~= "veniam dolore sint" == v161 == not "incididunt in" ~= v163
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m11_a0 = "3"
local r_m11_0 = datum4:m11(m11_a0)
local func13_a0 = "minim ut sit ea"
local func13_a1 = "3"
local func13_a2 = 17.658750
local func13_a3 = -56
local func13_a4 = "9"
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2, func13_a3, func13_a4)
local func19_a0 = -52
local func19_a1 = false
local func19_a2 = "10"
local r_func19_0 = func19(func19_a0, func19_a1, func19_a2)
local m23_a0 = 88.362538
local m23_a1 = true
local m23_a2 = "laboris"
local r_m23_0 = datum4:m23(m23_a0, m23_a1, m23_a2)
local r_m27_0 = datum4:m27()
local m28_a0 = 0x1.208fce4af1e0cp+4
local m28_a1 = [[7]]
local m28_a2 = true
local m28_a3 = 59
local m28_a4 = "pariatur elit nulla aliquip"
local m28_vararg0 = true
local m28_vararg1 = false
local r_m28_0 = datum4:m28(m28_a0, m28_a1, m28_a2, m28_a3, m28_a4, m28_vararg0, m28_vararg1)
local func34_a0 = "ut"
local func34_a1 = true
local func34_a2 = false
local r_func34_0 = func34(func34_a0, func34_a1, func34_a2)
local m38_a0 = 89.765467
local m38_a1 = 25
local m38_a2 = 0
local m38_a3 = false
local m38_a4 = "dolore"
local r_m38_0 = datum8:m38(m38_a0, m38_a1, m38_a2, m38_a3, m38_a4)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = datum1 and 0x1 or 0
local res_datum2 = math.floor(datum2 + 2)
local res_datum3 = math.floor(datum3)
local res_datum4 = #(datum4)
local res_datum6 = datum6 and 1 or 0
local res_datum7 = #(datum7)
local res_datum8 = ms.table_to_int(datum8)
local res_datum10 = tonumber(datum10)
local res_r_m11_0 = math.floor(r_m11_0 + 2)
local res_r_func13_0 = r_func13_0
local res_r_func19_0 = math.floor(r_func19_0 + 2)
local res_r_m23_0 = #(r_m23_0)
local res_r_m27_0 = r_m27_0 and 1 or 0
local res_r_m28_0 = ms.table_to_int(r_m28_0)
local res_r_func34_0 = math.floor(r_func34_0)
local res_r_m38_0 = 1
RESULT = res_r_m38_0 - res_r_func34_0 + res_r_m28_0 + res_r_m27_0 + res_r_m23_0 - res_r_func19_0 + res_r_func13_0 + res_r_m11_0 + res_datum10 + res_datum8 - res_datum7 + res_datum6 - res_datum4 - res_datum3 + res_datum2 - res_datum1 + res_datum0
print(math.floor(RESULT))