--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:           1062088380                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
datum0 = "aliqua aliquip incididunt"
local datum1 = {field2 = true}
local datum3 = "nisi"
datum4 = "Lorem sint exercitation veniam"
datum5 = false
datum6 = 76
local datum7 = -6
local datum8 = 30
datum9 = {field10 = "sed nostrud"}
datum11 = {field12 = 16.085668}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 string
-- @param a4 string
-- @return boolean
function datum11:m13(a0, a1, a2, a3, a4)
  local v29, v31 = a1, true
  v33, v35, v37, v39 = 0x1, a0, -21, false
  a4 = tostring(35)
  for i=5,12,2 do
      a2 = "ex proident eiusmod enim"
  end
  a4 = "6"
  a0 = "aute consequat laboris tempor"
  local cond43 = false
  while cond43 ~= false do
      a0 = "irure qui consequat cupidatat"
      cond43 = true
  end
  return "minim enim" ~= a0 == false ~= "magna mollit" == a2 ~= "tempor ea dolore" ~= a3 ~= "aute velit dolore laborum" ~= a4 ~= false == not v31
end

-- @param a0 float
-- @param a1 float
-- @return boolean
function datum9:m19(a0, a1)
  v45, v47, v49 = datum8, "9", true
  local v51, v53 = "non ad", "elit culpa"
  v55, v57, v59, v61 = -50.488148, false, -10, "3"
  if datum3 ~= "ex Excepteur" then
      a1 = 32.737486 - math.tan(a1) - -(84.376825)
      v45 = math.floor(v47 + 1) + math.floor(82.186457) or - 49
      v49 = "est id esse" ~= [[Excepteur]] ~= "nulla officia" ~= v47 == not true
  end
  local cond63 = false
  while cond63 == true do
      a0 = math.pi - math.abs(a0) - -(math.abs(a0))
      v47 = tostring(math.floor(a0))
      cond63 = true
  end
  a0 = 95.829392 + math.cos(v45) - -(math.pi)
  v49 = v49 ~= not true == v49
  return true == true == true == "nulla laboris voluptate" == v47 ~= not true ~= v49
end

-- @return float
function datum9:m22()
  v64, v66, v68, v70 = -31.553319, -36.788132, "eu eu laborum", datum5
  local v72, v74, v76, v78 = "ullamco", 0x43, false, "in cillum"
  if v66 > 52.615132 then
      v66 = 0x1.679cf2ad45bc1p+5 + -(math.tan(v64))
      v64 = math.pi + -(math.pi)
      v66 = 56.495909 - -(51.899858)
  else
      v66 = math.sin(v66) - math.abs(v66) - -(math.pi)
      v66 = math.tan(43) - math.cos(-6) + -(math.abs(6))
      v66 = 0x1.75eada764995bp+4 + -(math.abs(v64))
  end
  v66 = math.tan(-70) - -(math.cos(v64))
  if v66 >= -98.182000 then
      v66 = math.sin(-40) - 12.353768 - -(67.437448)
  else
      v66 = 18.000413 - math.pi + -(math.pi)
  end
  v64 = math.pi + -(math.tan(v66))
  return math.sin(v64) + -(math.cos(v66))
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 float
-- @return table
function datum1:m23(a0, a1, a2)
  local v80, v82, v84, v86 = true, false, a1, [[2]]
  v88, v90 = [[commodo
fugiat
adipiscing
sed]], "6"
  a0 = true == true == not true
  a1 = true ~= true == not "in consequat ad" == "nostrud sint eu tempor"
  a1 = false == false ~= not a1
  v82 = false == v82 == true == true ~= not true ~= a0
  a2 = 91.834313 - 87.926574 + -(math.cos(28))
  return {t92 = a0}
end

-- @param a0 string
-- @return string
function datum1:m27(a0)
  v94, v96, v98 = datum3, "7", a0
  local v100, v102 = datum3, -6
  if v96 == "3" then
      v96 = tostring(math.floor(32.187980))
  else
      a0 = "8"
      v94 = "deserunt eiusmod"
  end
  v96 = "5"
  local cond105 = true
  while cond105 == false do
      a0 = a0
      cond105 = false
  end
  return [[dolore
ex
in]]
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m13_a0 = "enim exercitation"
local m13_a1 = 99.943688
local m13_a2 = "dolore aute"
local m13_a3 = "exercitation"
local m13_a4 = "5"
local r_m13_0 = datum11:m13(m13_a0, m13_a1, m13_a2, m13_a3, m13_a4)
local m19_a0 = 70.229203
local m19_a1 = 0x1.74308f43e33a8p+2
local r_m19_0 = datum9:m19(m19_a0, m19_a1)
local r_m22_0 = datum9:m22()
local m23_a0 = true
local m23_a1 = true
local m23_a2 = 67.943696
local r_m23_0 = datum1:m23(m23_a0, m23_a1, m23_a2)
local m27_a0 = "10"
local r_m27_0 = datum1:m27(m27_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = string.len(datum0)
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = string.len(datum3)
local res_datum4 = string.len(datum4)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = datum6
local res_datum7 = datum7
local res_datum8 = datum8
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = #(datum11)
local res_r_m13_0 = r_m13_0 and 1 or 0
local res_r_m19_0 = r_m19_0 and 1 or 0
local res_r_m22_0 = math.floor(r_m22_0)
local res_r_m23_0 = ms.table_to_int(r_m23_0)
local res_r_m27_0 = #(r_m27_0)
RESULT = res_r_m27_0 - res_r_m23_0 - res_r_m22_0 + res_r_m19_0 - res_r_m13_0 + res_datum11 + res_datum9 - res_datum8 - res_datum7 - res_datum6 - res_datum5 + res_datum4 - res_datum3 + res_datum1 - res_datum0
print(math.floor(RESULT))