--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            422537261                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  9 statements)         --
--------------------------------------------------------
local datum0 = {field1 = true}
datum2 = {field3 = -4}
local datum4 = "4"
local datum5 = false
datum6 = {field7 = false}
local datum8 = "consequat proident tempor dolor"
datum9 = {field10 = -44}
local datum11 = true
datum12 = {field13 = true}

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @param a1 string
-- @return table
function datum12:m14(a0, a1)
  local v28, v30 = "7", -92
  v32, v34 = datum11, 0x1F
  a1 = tostring(v30)
  local cond36 = true
  while cond36 == false do
      v28 = v28
      cond36 = false
  end
  local cond37 = 119
  while cond37 >= 57 do
      a1 = "7"
      cond37 = cond37 - 3
  end
  return {a0}
end

-- @return boolean
function datum6:m17()
  v39, v41 = -33.156119, "deserunt reprehenderit eu adipiscing"
  v43, v45 = "dolore magna", "voluptate culpa incididunt nisi"
  v39 = math.pi + 5.738080e+01 + -(math.pi)
  for _, _ in pairs(datum12) do
      v39 = math.cos(v39) - math.pi - -(math.pi)
      v39 = math.pi + -(31.073581)
  end
  for i=11,1,2 do
      v39 = math.tan(v39) + 46.082573 - -(math.pi)
      v41 = "qui aliqua"
      v41 = "dolor"
  end
  for i=5,13 do
      v41 = "aute sed"
      v39 = math.pi - -(math.abs(0x1.a17fbf60747b8p+5))
      v41 = "ut enim exercitation aute"
  end
  return false == not "dolor laborum ea nisi" == v41
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 boolean
-- @param a4 string
-- @return string
function func18(a0, a1, a2, a3, a4)
  local v50, v52 = -16, datum5
  v54, v56 = 97, v50
  v58, v60 = 0x4b, [[commodo
qui
velit
veniam]]
  local cond62 = true
  repeat
      a2 = tostring(math.floor(4.698574))
      a1 = tostring(math.floor(9.556425e+01))
      a3 = "Excepteur" == "Lorem labore enim" == not "qui aute" ~= "ut dolor tempor"
      cond62 = false
  until cond62 ~= true
  local cond63 = true
  repeat
      a2 = "3"
      v52 = false == false == not true
      a4 = "nisi est"
      cond63 = false
  until cond63 == false
  return "8"
end

-- @param a0 boolean
-- @param a1 boolean
-- @return int
function datum9:m24(a0, a1)
  v65, v67 = -81.570392, 22
  local v69, v71 = 44, datum4
  v73, v75, v77, v79 = -55.936504, "8", -42.663000, 17.967735
  v69 = math.floor(36.654199) + -(-49)
  for _, _ in ipairs(datum0) do
      a1 = "ut consequat aliquip deserunt" ~= "cillum" == not a1
  end
  v67 = v67 + - #("quis commodo eu")
  v69 = -23 or 54 - - 57
  return 78 or 49 - math.floor(v65) + v67 + - v69
end

-- @return int
function func27()
  local v82, v84, v86, v88 = datum8, datum11, -92, -58
  local v90, v92 = [[consequat
fugiat
ut]], v82
  v94, v96 = true, 77.258593
  local cond98 = 120
  while cond98 >= 58 do
      v82 = "tempor ea"
      cond98 = cond98 - 3
  end
  v84 = true == false ~= false ~= not false ~= true
  for i=3,16,3 do
      v86 = 62 - -33 or - -64
      v82 = "Lorem sunt irure"
  end
  if v84 == false then
      v86 = -31 or - #("id labore")
      v86 = 0x23 or - string.len("aliquip veniam veniam")
      v86 = v86 - v86 + - -6
  end
  for _, v in ipairs(datum12) do
      v84 = false == not true ~= true
  end
  return #(v82) or 64 - -(v86)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m14_a0 = 9
local m14_a1 = "9"
local r_m14_0 = datum12:m14(m14_a0, m14_a1)
local r_m17_0 = datum6:m17()
local func18_a0 = "nulla minim"
local func18_a1 = "10"
local func18_a2 = "6"
local func18_a3 = true
local func18_a4 = "ullamco Excepteur"
local r_func18_0 = func18(func18_a0, func18_a1, func18_a2, func18_a3, func18_a4)
local m24_a0 = true
local m24_a1 = true
local r_m24_0 = datum9:m24(m24_a0, m24_a1)
local r_func27_0 = func27()

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = #(datum2)
local res_datum4 = math.floor(datum4 + 3)
local res_datum5 = datum5 and 1 or 0
local res_datum6 = ms.table_to_int(datum6)
local res_datum8 = string.len(datum8)
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = datum11 and 1 or 0
local res_datum12 = ms.table_to_int(datum12)
local res_r_m14_0 = #(r_m14_0)
local res_r_m17_0 = r_m17_0 and 1 or 0
local res_r_func18_0 = tonumber(r_func18_0)
local res_r_m24_0 = r_m24_0
local res_r_func27_0 = r_func27_0
RESULT = res_r_func27_0 + res_r_m24_0 + res_r_func18_0 + res_r_m17_0 + res_r_m14_0 + res_datum12 + res_datum11 + res_datum9 - res_datum8 - res_datum6 - res_datum5 + res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))