--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            707662564                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  5 statements)         --
--------------------------------------------------------
datum0 = -9
datum1 = {field2 = 0x1b}
local datum3 = 97.734899
local datum4 = "7"
datum5 = {field6 = 146.093232}

--------------------------------------------------------
-- Function definitions (  6 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 int
-- @param a2 float
-- @param a3 boolean
-- @return string
local func7 = function (a0, a1, a2, a3)
  v25, v27, v29 = datum3, [[8]], "mollit minim est"
  local v31, v33 = datum3, a3
  a1 = math.floor(61.702227) - -1 or -(math.floor(a2))
  a0 = "proident eu"
  local cond36 = 2
  while cond36 < 44 do
      a3 = true ~= "non" == v27 ~= not false
      v25 = 0x1.e5c1e29c45b2p+5 + -(math.cos(-9))
      a2 = math.sin(86.210784) - math.pi + -(math.pi)
      cond36 = cond36 + 3
  end
  return a0
end

-- @return int
local func12 = function ()
  v38, v40 = datum0, 7.921913
  v42, v44 = "proident ullamco Excepteur quis", -41.320366
  local cond46 = 0x79
  repeat
      v40 = math.sin(v40) - -(65.846296)
      cond46 = cond46 - 1
  until cond46 > 68
  v38 = -32 + -(math.floor(82.246089))
  v38 = math.floor(v40) or math.floor(v40) or - -24
  v40 = math.cos(69.909375) + -(34.789895)
  if datum0 < 38 then
      v38 = string.len("elit dolor veniam") or -(17)
      v38 = -77 + -44 or - math.floor(188.221403)
      v38 = math.floor(v40) + -57 or - math.floor(v40)
  end
  return v38 + - math.floor(v40)
end

-- @param a0 int
-- @param a1 string
-- @param a2 float
-- @return string
local func13 = function (a0, a1, a2)
  v47, v49 = a0, -24.274994
  v51, v53, v55 = "culpa enim", datum0, -52
  local v57, v59, v61, v63 = datum4, -29, "quis deserunt", "8"
  local cond65 = 3
  while cond65 <= 43 do
      v47 = math.floor(52.406954) + -(#([[do
deserunt]]))
      v47 = #(v51) - - -98
      a1 = [[esse]]
      cond65 = cond65 + 1
  end
  a2 = math.sin(a2) - math.pi - -(76.424169)
  for i, _ in ipairs(datum5) do
      a1 = 66.837762
      a0 = a0 + 88 + -(math.floor(70.902461))
  end
  return tostring(a0)
end

-- @param a0 string
-- @return boolean
function datum5:m17(a0)
  local v69, v71, v73 = [[consectetur
sed
voluptate]], "1", datum0
  v75, v77, v79 = true, datum4, -91
  a0 = a0
  if v69 ~= "proident dolore consectetur" then
      a0 = "4"
  end
  a0 = "4"
  a0 = tostring(-89)
  if datum4 == "1" then
      a0 = [[9]]
  else
      v69 = "est reprehenderit"
  end
  if datum1 == {} then
      v69 = "velit adipiscing amet exercitation"
      v69 = "dolore"
  else
      a0 = "2"
      v71 = tostring(math.floor(161.468089))
      a0 = v71
  end
  return "sunt reprehenderit labore" == a0 == "minim occaecat" ~= v69 == not "exercitation labore" ~= v71
end

-- @param a0 int
-- @return float
function func19(a0)
  local v83, v85 = true, datum0
  v87, v89, v91 = datum0, true, true
  v93, v95, v97 = "laboris anim ea eu", "amet quis", "cillum in in"
  v87 = -78 or 0x3A or -(math.floor(73.492679))
  v85 = 62 or - v87
  local cond99 = true
  repeat
      v87 = -6 or -42 or -(-15)
      a0 = -71 + 0x1e or - math.floor(182.099891)
      v87 = 75 + -(#("aliquip aute in"))
      cond99 = false
  until cond99 ~= true
  return math.abs(a0) - 83.379352 + math.tan(v85) + -(math.cos(v87))
end

-- @param a0 string
-- @param a1 boolean
-- @param a2 boolean
-- @return float
function datum1:m21(a0, a1, a2)
  local v100, v102, v104 = true, "4", "7"
  local v106, v108 = false, "9"
  local cond110 = 0x6F
  repeat
      a0 = 39.533392
      cond110 = cond110 - 3
  until cond110 > 62
  v100 = "ipsum reprehenderit enim" == v102 == false == false ~= not true
  a2 = "cillum nulla" ~= a0 ~= not true
  v100 = false == not "fugiat et" ~= a0
  for i, _ in pairs(datum1) do
      a1 = "enim" ~= a0 == true == not false == false
      v102 = "9"
      a0 = a0
  end
  return 7.983421e+01 - math.pi - math.pi + 0.611309 + -(93.420522)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func7_a0 = "ex sed"
local func7_a1 = 54
local func7_a2 = 58.455593
local func7_a3 = false
local r_func7_0 = func7(func7_a0, func7_a1, func7_a2, func7_a3)
local r_func12_0 = func12()
local func13_a0 = -84
local func13_a1 = "dolore ipsum"
local func13_a2 = 28.271167
local r_func13_0 = func13(func13_a0, func13_a1, func13_a2)
local m17_a0 = "9"
local r_m17_0 = datum5:m17(m17_a0)
local func19_a0 = 0x8
local r_func19_0 = func19(func19_a0)
local m21_a0 = "consequat dolor proident"
local m21_a1 = false
local m21_a2 = true
local r_m21_0 = datum1:m21(m21_a0, m21_a1, m21_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0
local res_datum1 = ms.table_to_int(datum1)
local res_datum3 = math.floor(datum3)
local res_datum4 = math.floor(datum4 + 0x1)
local res_datum5 = ms.table_to_int(datum5)
local res_r_func7_0 = string.len(r_func7_0)
local res_r_func12_0 = r_func12_0
local res_r_func13_0 = math.floor(r_func13_0 + 2)
local res_r_m17_0 = r_m17_0 and 1 or 0
local res_r_func19_0 = math.floor(r_func19_0)
local res_r_m21_0 = math.floor(r_m21_0)
RESULT = res_r_m21_0 + res_r_func19_0 + res_r_m17_0 - res_r_func13_0 + res_r_func12_0 + res_r_func7_0 - res_datum5 - res_datum4 - res_datum3 - res_datum1 - res_datum0
print(math.floor(RESULT))