--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             72452877                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  8 statements)         --
--------------------------------------------------------
datum0 = true
datum1 = false
datum2 = {field3 = false}
datum4 = "in"
datum5 = {field6 = "deserunt Duis"}
datum7 = true
datum8 = "Duis"
local datum9 = false

--------------------------------------------------------
-- Function definitions (  4 functions)               --
--------------------------------------------------------
-- @param a0 int
-- @return int
function func10(a0)
  local v25, v27, v29, v31 = "1", "1", 0x1.6e2809f1f7b2p+6, a0
  local v33, v35, v37 = -91.201214, false, a0
  v39, v41, v43 = "2", datum8, datum8
  local cond45 = 0x70
  while cond45 > 0x41 do
      v29 = math.pi - math.pi - -(math.pi)
      v25 = tostring(a0)
      v29 = math.cos(122.368802) + 38.165167 + -(math.sin(86))
      cond45 = cond45 - 3
  end
  v29 = 36.152743 + -(math.sin(-70))
  a0 = math.floor(v29) + - math.floor(v25 + 3)
  local cond46 = 5
  while cond46 < 21 do
      a0 = a0 - -(math.floor(v27 + 3))
      cond46 = cond46 + 0x2
  end
  return a0 or tonumber(v25) or tonumber(v27) + - math.floor(v29)
end

-- @param a0 float
-- @param a1 float
-- @param a2 float
-- @param a3 string
-- @param a4 boolean
-- @return table
function datum5:m12(a0, a1, a2, a3, a4)
  local v47, v49 = 92, "eiusmod Ut Duis"
  v51, v53 = false, datum4
  v55, v57, v59 = v49, 30.310166, datum7
  a4 = "Lorem velit est" == "Ut consequat dolor qui" ~= false == not true
  a1 = math.cos(0x1.25b27570660fep+5) - -(math.tan(a1))
  a1 = math.pi - -(math.pi)
  local cond61 = 5
  while cond61 < 32 do
      a3 = "4"
      a0 = math.pi - math.abs(111.785933) - -(math.cos(23))
      a4 = true == not false
      cond61 = cond61 + 3
  end
  return {0x7}
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 float
-- @return string
function datum2:m18(a0, a1, a2)
  v63, v65, v67, v69 = -17, a1, datum8, "7"
  v71, v73 = v63, -12
  for i=15,4,0x2 do
      a0 = false == true == not false
      a2 = math.abs(v63) - -(67.921737)
      a2 = math.pi + math.pi + -(49.427497)
  end
  if a2 == -38.531488 then
      v65 = v65
      a1 = tostring(math.floor(a2))
      a0 = false ~= a0 == not false ~= false
  end
  local cond75 = 10
  repeat
      a0 = true ~= false ~= "sit officia cillum" == v65 ~= not "id pariatur" ~= "elit"
      a0 = a0 ~= false == not true
      cond75 = cond75 + 2
  until cond75 < 47
  for i, v in pairs(datum5) do
      a2 = 17.336548 + -(math.abs(-53))
  end
  return "8"
end

-- @param a0 string
-- @param a1 string
-- @return function
function func22(a0, a1)
  local v79, v81 = datum8, 96.855864
  v83, v85 = -82.599975, a1
  local v87, v89, v91 = datum7, a0, datum1
  v81 = 3.483094e+01 - 74.947009 + -(63.565519)
  a0 = "ullamco nisi"
  if v81 >= 36.677794 then
      v79 = "voluptate cillum aliquip"
      a1 = v83
      v81 = math.pi - math.tan(v83) + -(0x1.1c1b027ff64a5p+6)
  else
      a1 = "pariatur dolore labore aliquip"
      v79 = v79
      v81 = math.cos(v81) + -(math.pi)
  end
  local cond97 = 0x64
  while cond97 >= 72 do
      v83 = math.pi + -(38.588998)
      cond97 = cond97 - 3
  end
  if datum5 ~= {} then
      a1 = "dolore labore minim"
      v79 = "fugiat"
      a1 = "irure anim officia"
  end
  return nil
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func10_a0 = 96
local r_func10_0 = func10(func10_a0)
local m12_a0 = 83.652886
local m12_a1 = 74.654282
local m12_a2 = 57.678327
local m12_a3 = "6"
local m12_a4 = true
local r_m12_0 = datum5:m12(m12_a0, m12_a1, m12_a2, m12_a3, m12_a4)
local m18_a0 = false
local m18_a1 = "7"
local m18_a2 = 90.701510
local r_m18_0 = datum2:m18(m18_a0, m18_a1, m18_a2)
local func22_a0 = "dolor nulla"
local func22_a1 = "laborum anim elit"
local r_func22_0 = func22(func22_a0, func22_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = datum0 and 1 or 0
local res_datum1 = datum1 and 1 or 0
local res_datum2 = #(datum2)
local res_datum4 = string.len(datum4)
local res_datum5 = #(datum5)
local res_datum7 = datum7 and 1 or 0
local res_datum8 = #(datum8)
local res_datum9 = datum9 and 1 or 0
local res_r_func10_0 = r_func10_0
local res_r_m12_0 = ms.table_to_int(r_m12_0)
local res_r_m18_0 = tonumber(r_m18_0)
local res_r_func22_0 = 1
RESULT = res_r_func22_0 + res_r_m18_0 + res_r_m12_0 + res_r_func10_0 - res_datum9 - res_datum8 - res_datum7 + res_datum5 - res_datum4 - res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))