--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            181442153                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
local datum0 = "6"
datum1 = "3"
datum2 = false
local datum3 = 97
local datum4 = {field5 = 87}
datum6 = 0x2a
datum7 = 76.588142
datum8 = false
datum9 = {field10 = false}
datum11 = 26

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @return boolean
local func12 = function (a0)
  local v38, v40, v42 = 0x2A, datum8, false
  v44, v46, v48 = 50.865912, datum6, datum3
  v50, v52 = "7", v38
  for i=2,20,0x3 do
      a0 = math.pi + -(math.pi)
      v38 = math.floor(a0) or - math.floor(50.662179)
  end
  a0 = math.tan(-84) - -(math.tan(134.914251))
  for i=0x4,0xF do
      v42 = false == false == not true
      v42 = false ~= not false
  end
  v40 = true ~= true == not false
  for i=0x2,14 do
      a0 = math.abs(33.962174) - -(math.tan(v38))
      v42 = false == true == v40 == not true == v40
  end
  return true ~= false == false == v40 == not v42
end

-- @param a0 string
-- @return float
function datum9:m14(a0)
  local v54, v56, v58, v60 = 71, datum1, a0, true
  local v62, v64, v66 = datum0, datum7, [[1]]
  v56 = a0
  for i=0xb,4,2 do
      v56 = tostring(v54)
  end
  for i, _ in ipairs(datum9) do
      v54 = #("culpa") + -13 + -(math.floor(a0 + 1))
      v54 = 66 + 60 - -(math.floor(97.758457))
      v54 = v54 - - v54
  end
  local cond70 = false
  while cond70 == true do
      v56 = tostring(math.floor(64.798088))
      v54 = -88 + 15 or - tonumber(v56)
      v54 = math.floor(104.123097) - - math.floor(a0 + 0)
      cond70 = true
  end
  if v56 == "9" then
      v56 = tostring(math.floor(182.114407))
  else
      v56 = "9"
  end
  return math.pi - math.tan(v54) + -(math.pi)
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @param a3 boolean
-- @param a4 string
-- @return table
function datum9:m16(a0, a1, a2, a3, a4)
  v71, v73, v75, v77 = true, 75.917952, datum2, 72.236078
  v79, v81 = 4, a4
  v83, v85, v87 = a3, "2", datum2
  for i=1,15,2 do
      a1 = "sint irure"
  end
  a2 = 21.056494 + -(80.195858)
  v75 = false ~= not a3
  local cond90 = 103
  while cond90 > 75 do
      a0 = "5"
      a3 = true ~= v71 == not false
      cond90 = cond90 - 1
  end
  return {t91 = a0}
end

-- @param a0 float
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return function
function func22(a0, a1, a2, a3)
  local v95, v97, v99, v101 = datum0, "5", -22, -58
  local v103, v105, v107 = a3, true, -91
  for i, v in ipairs(datum9) do
      v95 = "10"
      v97 = "5"
      a0 = math.sin(43) - math.pi - -(7.448005e+01)
  end
  if a3 == "labore magna pariatur minim" then
      v97 = v97
      a0 = 21.441210 + -(math.cos(26))
      v95 = "1"
  else
      a1 = "proident velit consequat"
      a0 = math.tan(180.477779) + -(math.tan(78.859423))
      a1 = "culpa pariatur esse cillum"
  end
  local cond114 = true
  repeat
      a3 = "in velit ipsum"
      a3 = [[velit
do]]
      a1 = "sunt"
      cond114 = false
  until cond114 == false
  v97 = v95
  if datum9 ~= {} then
      a1 = "Lorem tempor nisi"
  end
  return nil
end

-- @return float
local func27 = function ()
  v119, v121, v123 = "Lorem cupidatat consequat", 39.060356, "7"
  v125, v127, v129 = true, datum7, datum11
  local cond131 = false
  while cond131 == true do
      v119 = v119
      v121 = math.cos(-41) + math.pi + -(math.pi)
      v121 = math.tan(v121) - -(math.pi)
      cond131 = true
  end
  v121 = 20.450275 + -(10.025686)
  v119 = "do ullamco ut"
  return 66.193851 - -(math.cos(v121))
end

-- @param a0 int
-- @param a1 string
-- @return table
function datum4:m28(a0, a1)
  local v133, v135 = "cupidatat", "ipsum ipsum"
  local v137, v139, v141, v143 = -86.058078, -40.844104, 42.345717, v133
  a1 = "culpa veniam deserunt laboris"
  a0 = #("ullamco culpa esse") or -84 or - #("sit")
  if v135 == "esse Lorem qui fugiat" then
      a0 = string.len(a1) + string.len(a1) or -(-73)
      v135 = v135
  end
  a0 = math.floor(76.320836) - 0x1C - -(9)
  v135 = 1.195698e+02
  return {a0}
end

-- @param a0 string
-- @param a1 float
-- @param a2 boolean
-- @return function
local func31 = function (a0, a1, a2)
  v150, v152 = a2, 33
  v154, v156 = datum2, "velit"
  local v158, v160, v162, v164 = "fugiat sunt", "8", "est", datum2
  a2 = true ~= not v154
  for i, v in ipairs(datum4) do
      v152 = -15 - -(string.len("eiusmod in"))
  end
  for i, v in pairs(datum9) do
      a0 = "2"
      a1 = 82.724176 + math.pi + -(math.pi)
      a0 = tostring(math.floor(0x1.d3b6f56f90d63p+6))
  end
  for i=0x13,4 do
      a0 = "6"
  end
  return nil
end

-- @param a0 boolean
-- @param a1 string
-- @return table
local func35 = function (a0, a1)
  v172, v174, v176, v178 = a0, "exercitation in officia", a1, a0
  v180, v182, v184 = 94.003236, v172, "cillum aliquip ut"
  local cond186 = 3
  repeat
      v174 = "velit velit"
      a0 = "dolore voluptate" ~= "consectetur deserunt" ~= false ~= not true
      v174 = "eu anim esse non"
      cond186 = cond186 + 3
  until cond186 < 44
  for i, v in ipairs(datum9) do
      a1 = "2"
      v172 = false ~= true == "elit magna officia" ~= a1 == not "anim do magna" == v174
  end
  for i, _ in pairs(datum9) do
      v174 = "ea irure"
  end
  v174 = "laboris Duis"
  return {t195 = a0}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local func12_a0 = 56.920558
local r_func12_0 = func12(func12_a0)
local m14_a0 = "9"
local r_m14_0 = datum9:m14(m14_a0)
local m16_a0 = "2"
local m16_a1 = "do"
local m16_a2 = 23.056278
local m16_a3 = true
local m16_a4 = "aliquip aliquip ipsum"
local r_m16_0 = datum9:m16(m16_a0, m16_a1, m16_a2, m16_a3, m16_a4)
local func22_a0 = 89.380140
local func22_a1 = "in"
local func22_a2 = "sunt do officia"
local func22_a3 = "ea"
local r_func22_0 = func22(func22_a0, func22_a1, func22_a2, func22_a3)
local r_func27_0 = func27()
local m28_a0 = -98
local m28_a1 = "reprehenderit laborum"
local r_m28_0 = datum4:m28(m28_a0, m28_a1)
local func31_a0 = [[4]]
local func31_a1 = 68.367639
local func31_a2 = true
local r_func31_0 = func31(func31_a0, func31_a1, func31_a2)
local func35_a0 = true
local func35_a1 = "1"
local r_func35_0 = func35(func35_a0, func35_a1)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = math.floor(datum0 + 1)
local res_datum1 = tonumber(datum1)
local res_datum2 = datum2 and 1 or 0
local res_datum3 = datum3
local res_datum4 = #(datum4)
local res_datum6 = datum6
local res_datum7 = math.floor(datum7)
local res_datum8 = datum8 and 1 or 0
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = datum11
local res_r_func12_0 = r_func12_0 and 1 or 0
local res_r_m14_0 = math.floor(r_m14_0)
local res_r_m16_0 = ms.table_to_int(r_m16_0)
local res_r_func22_0 = 1
local res_r_func27_0 = math.floor(r_func27_0)
local res_r_m28_0 = ms.table_to_int(r_m28_0)
local res_r_func31_0 = 1
local res_r_func35_0 = ms.table_to_int(r_func35_0)
RESULT = res_r_func35_0 + res_r_func31_0 + res_r_m28_0 - res_r_func27_0 + res_r_func22_0 - res_r_m16_0 - res_r_m14_0 - res_r_func12_0 - res_datum11 - res_datum9 + res_datum8 - res_datum7 + res_datum6 - res_datum4 - res_datum3 + res_datum2 + res_datum1 + res_datum0
print(math.floor(RESULT))