--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             85073536                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
datum0 = "nulla fugiat sint id"
local datum1 = "8"
datum2 = false
datum3 = "aliqua"
datum4 = {field5 = false}
datum6 = {field7 = 12}

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @return int
function datum4:m8()
  v27, v29, v31 = "5", 0x3f, 24
  local v33, v35 = v27, true
  local v37, v39, v41, v43 = "9", 43, 99.744631, datum2
  v29 = -9 - 9 + - v31
  v27 = tostring(v31)
  v31 = 61 or - math.floor(v27 + 2)
  if v27 ~= "7" then
      v29 = math.floor(v27 + 0) + string.len("eu Ut minim consectetur") + -(math.floor(v27 + 3))
      v29 = -32 - 78 or - -32
  end
  return math.floor(v27 + 1) + v29 or - v31
end

-- @param a0 boolean
-- @param a1 int
-- @param a2 float
-- @param a3 int
-- @param a4 int
-- @return table
function func9(a0, a1, a2, a3, a4)
  local v45, v47 = a2, a2
  v49, v51 = datum1, a0
  local v53, v55, v57, v59 = a0, "anim fugiat", "incididunt minim officia", true
  a4 = #([[dolor
consequat
aute]]) + -(math.floor(164.515172))
  for i=0xc,3,3 do
      a0 = true == "proident magna eiusmod" ~= "eiusmod dolor" == not true
  end
  for i=0,10,2 do
      a0 = true ~= not false
  end
  for i=3,19,2 do
      a0 = "voluptate" ~= v49 ~= not true
      a3 = math.floor(77.492194) or string.len("labore ipsum sit aute") or - 53
      a2 = 70.495939 + math.tan(1.770219e+02) - -(math.abs(v47))
  end
  for _, _ in pairs(datum6) do
      a0 = true ~= false == true ~= not false
  end
  if datum3 == "eiusmod adipiscing voluptate" then
      a0 = false == not false
      a4 = math.floor(v49 + 0) + 92 + - math.floor(v45)
  end
  return {t62 = a0}
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 int
-- @return float
local func15 = function (a0, a1, a2)
  local v64, v66 = 0x38, -1
  local v68, v70, v72 = 43.289447, "dolor", a1
  local v74, v76, v78 = v66, "elit", datum2
  local cond80 = true
  while cond80 == false do
      v68 = 10.104564 + -(math.pi)
      v64 = -1 - - -75
      v68 = math.pi + math.pi + -(math.pi)
      cond80 = false
  end
  a2 = #("ex consequat laboris") or - math.floor(1.717274e+02)
  for _, v in pairs(datum6) do
      a0 = math.pi + -(math.tan(a0))
  end
  local cond83 = 2
  while cond83 <= 0x2B do
      a2 = #("sint velit") + - 33
      cond83 = cond83 + 2
  end
  return math.tan(a0) + 64.833960 + math.sin(a2) + math.abs(v64) - math.sin(v66) - -(math.cos(v68))
end

-- @return string
function datum6:m19()
  local v84, v86, v88 = [[non
cupidatat
non]], -35.536661, "1"
  local v90, v92 = -64, datum1
  v94, v96, v98, v100 = v84, v86, "5", [[4]]
  v84 = "occaecat id ut"
  local cond102 = 122
  while cond102 > 63 do
      v84 = v84
      v88 = "3"
      v84 = "ipsum ex commodo"
      cond102 = cond102 - 1
  end
  if datum0 ~= "ut ex Excepteur proident" then
      v84 = string.reverse(v84)
  else
      v86 = math.pi + 92.275429 + -(math.pi)
      v86 = 85.503097 + math.pi + -(math.sin(37))
      v86 = math.cos(64) - -(math.pi)
  end
  v86 = 19.370890 - -(16.609853)
  local cond105 = true
  repeat
      v88 = "4"
      v88 = tostring(math.floor(155.548247))
      cond105 = false
  until cond105 ~= true
  return "10"
end

-- @return boolean
local func20 = function ()
  local v106, v108 = 18.753684, "nostrud do"
  local v110, v112 = 55, datum3
  local v114, v116 = -0x1.062a772fae102p+6, false
  if v108 ~= [[Ut
consectetur
dolore
in]] then
      v106 = 67.780793 - -(math.abs(39))
      v110 = 0x19 - - string.len("commodo aute Excepteur dolor")
      v106 = math.pi + math.abs(v106) - -(92.487679)
  else
      v110 = v110 or -(-31)
      v110 = -68 - -(math.floor(8.579528e+01))
      v106 = 21.793553 + math.pi + -(math.sin(0x1.0b8e84fbca194p+3))
  end
  if v110 > 0x2e then
      v108 = [[fugiat
sint]]
      v106 = math.sin(67.547397) + math.abs(86) + -(90.401985)
  end
  for i=1,13,3 do
      v106 = math.pi - -(math.pi)
      v106 = math.pi - math.sin(v106) + -(math.tan(118.298779))
      v110 = math.floor(v106) + - math.floor(141.260901)
  end
  v106 = math.tan(-55) - math.sin(83) + -(math.pi)
  v108 = "sint fugiat commodo reprehenderit"
  return true ~= "eiusmod incididunt mollit laborum" ~= v108 ~= not false
end

-- @param a0 float
-- @return int
function func21(a0)
  v119, v121, v123, v125 = "dolore deserunt consequat", 90, datum1, "10"
  local v127, v129, v131, v133 = "5", datum0, a0, "1"
  local v135, v137, v139, v141 = datum3, -20.517878, true, datum0
  a0 = math.tan(v121) + math.sin(a0) - -(math.pi)
  if a0 == -0x1.18f3ddcab7efcp+6 then
      v123 = v123
  end
  for i, v in pairs(datum4) do
      v119 = "amet consectetur"
  end
  v123 = tostring(v121)
  for i=15,1 do
      v123 = "2"
      v123 = "10"
  end
  return math.floor(a0) or string.len(v119) + v121 + - tonumber(v123)
end

-- @param a0 int
-- @param a1 string
-- @param a2 float
-- @return string
function datum4:m23(a0, a1, a2)
  v146, v148 = a1, -40
  v150, v152, v154, v156 = datum0, -65, datum2, -70
  local v158, v160, v162, v164 = a2, "deserunt ad Lorem", "id ad", a2
  if a0 == 0x5d then
      a1 = "minim sed id"
      v148 = #([[ipsum
Ut
elit
laboris]]) + -(math.floor(a2))
      a1 = "nisi quis sed"
  end
  local cond168 = 0
  repeat
      a0 = 46 - math.floor(192.844146) + - string.len("aute ex")
      v150 = "aliqua laborum dolore"
      a0 = 17 - -(15)
      cond168 = cond168 + 1
  until cond168 < 29
  if v150 ~= [[eu]] then
      v148 = 0x39 + string.len(v150) + - -57
      a0 = 29 + math.floor(a2) + -(-25)
      a1 = "aute enim ipsum"
  end
  for i=16,5,3 do
      a0 = -67 or string.len([[quis]]) + - #(a1)
      a0 = string.len(a1) or #("Duis anim nostrud") or -(string.len("aliquip aute"))
      v146 = "Ut"
  end
  for i=1,18,2 do
      a0 = -9 - -(#(a1))
      v148 = -28 - 43 + - #("aute adipiscing sit ipsum")
      v150 = "qui dolor culpa"
  end
  return tostring(a0)
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_m8_0 = datum4:m8()
local func9_a0 = false
local func9_a1 = -87
local func9_a2 = 4.832463
local func9_a3 = -17
local func9_a4 = 59
local r_func9_0 = func9(func9_a0, func9_a1, func9_a2, func9_a3, func9_a4)
local func15_a0 = 10.552563
local func15_a1 = false
local func15_a2 = -99
local r_func15_0 = func15(func15_a0, func15_a1, func15_a2)
local r_m19_0 = datum6:m19()
local r_func20_0 = func20()
local func21_a0 = 83.326849
local r_func21_0 = func21(func21_a0)
local m23_a0 = 0x8
local m23_a1 = "reprehenderit pariatur"
local m23_a2 = 8.357692
local r_m23_0 = datum4:m23(m23_a0, m23_a1, m23_a2)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = string.len(datum0)
local res_datum1 = math.floor(datum1 + 3)
local res_datum2 = datum2 and 1 or 0
local res_datum3 = string.len(datum3)
local res_datum4 = #(datum4)
local res_datum6 = #(datum6)
local res_r_m8_0 = r_m8_0
local res_r_func9_0 = ms.table_to_int(r_func9_0)
local res_r_func15_0 = math.floor(r_func15_0)
local res_r_m19_0 = math.floor(r_m19_0 + 2)
local res_r_func20_0 = r_func20_0 and 1 or 0
local res_r_func21_0 = r_func21_0
local res_r_m23_0 = math.floor(r_m23_0 + 3)
RESULT = res_r_m23_0 - res_r_func21_0 - res_r_func20_0 + res_r_m19_0 + res_r_func15_0 - res_r_func9_0 - res_r_m8_0 - res_datum6 + res_datum4 + res_datum3 - res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))