--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            672387193                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = "9"
datum1 = 8.472263
local datum2 = {field3 = 27}
local datum4 = "4"
local datum5 = {field6 = 31}
datum7 = {field8 = false}
local datum9 = 8.797429

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @param a4 string
-- @return int
function datum5:m10(a0, a1, a2, a3, a4)
  v38, v40, v42, v44 = 23, 3, 76.779022, "8"
  v46, v48, v50 = datum1, "1", a0
  local v52, v54, v56, v58 = "ipsum Lorem", v38, v38, v38
  if datum9 == -0x1.c665b9fc9d3d4p+4 then
      v38 = -17 or string.len(a2) - -(0)
      v42 = 79.521290 + -(math.tan(193.553053))
      a4 = tostring(math.floor(v42))
  end
  v40 = string.len(a3) or -(97)
  v42 = math.sin(0x1.a167c44412b57p+5) - math.pi - -(math.pi)
  local cond60 = false
  while cond60 == true do
      v38 = math.floor(0x1.85a2fd7394beep+5) + -(string.len(a3))
      a3 = [[sunt
sed
Excepteur]]
      v42 = 60.964286 + -(math.sin(5))
      cond60 = true
  end
  return #(a0) + 47 or string.len(a2) + string.len(a3) - math.floor(a4 + 1) + v38 or v40 or - math.floor(v42)
end

-- @param a0 boolean
-- @param a1 float
-- @return table
function datum7:m16(a0, a1)
  v62, v64 = "id voluptate minim tempor", 68
  v66, v68, v70, v72 = datum1, v62, "6", v62
  for i, v in pairs(datum5) do
      a1 = math.abs(-10) - 81.592693 - -(39.067127)
      v62 = "quis in irure"
      a1 = 82.628796 - -(57.939826)
  end
  for _, v in pairs(datum7) do
      v64 = string.len([[velit
laboris]]) or -(2)
      a1 = math.cos(20) + 0x1.a6e5779bb046ap+5 + -(78.355159)
      v62 = [[amet]]
  end
  local cond81 = false
  repeat
      a1 = math.sin(158.701233) + math.sin(14) - -(math.pi)
      a1 = 0x1.728c304fc078cp+6 + -(math.abs(119.054548))
      v64 = #("et ut Lorem id") + - #("aute non laborum")
      cond81 = true
  until cond81 ~= false
  return {t82 = a0}
end

-- @param a0 string
-- @return string
local func19 = function (a0)
  local v83, v85 = false, 100
  local v87, v89 = a0, 6
  for i=3,20,2 do
      v83 = "sed" == a0 ~= false ~= not true == false
      v83 = true ~= not false
  end
  v85 = -45 + math.floor(115.549456) + -(string.len("incididunt amet dolor"))
  for i, v in ipairs(datum5) do
      v83 = "aliquip ut" ~= a0 ~= not true ~= v83
      a0 = "aliqua Duis"
      v85 = string.len("aliquip ipsum incididunt") - - -43
  end
  if datum9 >= 95.155608 then
      v85 = 66 + 72 or - -94
      v85 = 33 + v85 - - v85
      v83 = true == true == false ~= not true == false
  else
      a0 = [[ut
labore
laborum
Ut]]
      a0 = "veniam fugiat"
      v83 = true == false ~= not false
  end
  for i, v in ipairs(datum2) do
      v83 = false ~= true ~= not false == true
      v83 = false ~= v83 ~= not [[enim
minim
enim]] == a0
      v85 = math.floor(89.622592) + -(#("eu eu ullamco esse"))
  end
  v83 = false == true == true ~= v83 == not false
  return a0
end

-- @param a0 string
-- @return table
function func21(a0)
  local v100, v102, v104 = true, false, 0x1.3d04d19de9f18p+3
  v106, v108 = a0, 75
  local v110, v112, v114, v116 = "amet quis sit", "sit qui anim", 69, datum4
  if datum7 == {} then
      v100 = "ex ea minim" ~= [[veniam
ut
enim]] ~= false ~= true ~= not v102
      v104 = math.tan(5.912922) - -(math.pi)
      v104 = math.cos(v104) + 93.035576 - -(37.706092)
  else
      v104 = math.pi - -(22.159888)
  end
  v104 = 74.421732 - math.pi + -(math.pi)
  if a0 == "10" then
      v102 = false ~= false == not true
      a0 = a0
      v100 = false ~= false == "laboris et" == [[adipiscing]] == not "laboris ut est" ~= "aliquip nisi cillum officia"
  end
  v100 = false == not false == false
  return {t118 = a0}
end

-- @param a0 boolean
-- @return int
function datum5:m23(a0)
  local v119, v121, v123 = true, "mollit ea", -13
  local v125, v127 = 74.611782, 62.146396
  v129, v131, v133 = datum9, 84, datum9
  for i=4,18,2 do
      v121 = "id Duis veniam ipsum"
      v123 = string.len(v121) + -(math.floor(0x1.4fb9e9cea4632p+5))
      v121 = "dolor sunt"
  end
  v119 = "fugiat" == v121 ~= false == v119 == not false
  a0 = false ~= not true
  a0 = false == "cupidatat deserunt et tempor" ~= "cupidatat non ad" ~= not "irure magna pariatur" ~= "ea tempor deserunt aliquip"
  a0 = "laborum occaecat ex" ~= v121 == "incididunt exercitation dolore" == "sed occaecat" == not true ~= true
  return 0x40 + 23 or string.len(v121) - -(v123)
end

-- @param a0 int
-- @param a1 int
-- @param a2 string
-- @param a3 string
-- @return int
function func25(a0, a1, a2, a3)
  v137, v139 = 7.957310e+01, -56.866118
  local v141, v143 = -23.383730, datum4
  local cond145 = 120
  while cond145 >= 74 do
      a2 = "3"
      v139 = 15.782113 + -(math.tan(v139))
      a2 = tostring(a0)
      cond145 = cond145 - 2
  end
  v139 = math.sin(92.406226) + math.tan(1.058493e+02) + -(math.abs(a1))
  local cond146 = 7
  while cond146 < 33 do
      a3 = "incididunt tempor velit"
      a1 = string.len("magna") + -(#("ad"))
      a1 = string.len(a3) - -(a0)
      cond146 = cond146 + 2
  end
  for i=5,11,3 do
      a2 = "8"
  end
  return a0 + a1 + math.floor(a2 + 0) + string.len(a3) + math.floor(v137) + -(math.floor(v139))
end

-- @param a0 int
-- @param a1 float
-- @return function
function datum2:m30(a0, a1)
  v148, v150, v152, v154 = a0, true, "Lorem sunt consequat", "7"
  local v156, v158 = false, datum0
  local cond160 = true
  while cond160 ~= true do
      a1 = math.abs(v148) - math.sin(v148) - -(math.sin(94.950447))
      cond160 = false
  end
  local cond161 = false
  while cond161 ~= false do
      v148 = math.floor(a1) + 6 or -(math.floor(a1))
      cond161 = true
  end
  return nil
end

-- @param a0 int
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return table
function datum5:m33(a0, a1, a2, a3)
  v162, v164 = datum9, a2
  local v166, v168, v170, v172 = true, v162, datum0, false
  local cond174 = 8
  repeat
      a0 = #("culpa cupidatat exercitation") + string.len("exercitation ullamco dolore") + - tonumber(a1)
      cond174 = cond174 + 1
  until cond174 < 47
  a1 = tostring(-23)
  for i=20,2 do
      a1 = "5"
      v162 = 64.792042 - -(77.703463)
  end
  a0 = #("exercitation") + math.floor(0x1.817b340833bd7p+6) - -(8)
  v162 = math.pi - -(math.pi)
  return {a0}
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m10_a0 = "incididunt id quis sit"
local m10_a1 = true
local m10_a2 = "ea eu dolore esse"
local m10_a3 = "id ad"
local m10_a4 = "6"
local r_m10_0 = datum5:m10(m10_a0, m10_a1, m10_a2, m10_a3, m10_a4)
local m16_a0 = false
local m16_a1 = 79.224857
local r_m16_0 = datum7:m16(m16_a0, m16_a1)
local func19_a0 = "Duis culpa ex pariatur"
local r_func19_0 = func19(func19_a0)
local func21_a0 = "9"
local r_func21_0 = func21(func21_a0)
local m23_a0 = false
local r_m23_0 = datum5:m23(m23_a0)
local func25_a0 = 0x44
local func25_a1 = 0x1f
local func25_a2 = "8"
local func25_a3 = "sunt mollit dolor"
local r_func25_0 = func25(func25_a0, func25_a1, func25_a2, func25_a3)
local m30_a0 = 96
local m30_a1 = 28.469246
local r_m30_0 = datum2:m30(m30_a0, m30_a1)
local m33_a0 = -16
local m33_a1 = [[8]]
local m33_a2 = "exercitation qui"
local m33_a3 = "4"
local r_m33_0 = datum5:m33(m33_a0, m33_a1, m33_a2, m33_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = math.floor(datum0 + 2)
local res_datum1 = math.floor(datum1)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = math.floor(datum4 + 2)
local res_datum5 = ms.table_to_int(datum5)
local res_datum7 = ms.table_to_int(datum7)
local res_datum9 = math.floor(datum9)
local res_r_m10_0 = r_m10_0
local res_r_m16_0 = #(r_m16_0)
local res_r_func19_0 = string.len(r_func19_0)
local res_r_func21_0 = #(r_func21_0)
local res_r_m23_0 = r_m23_0
local res_r_func25_0 = r_func25_0
local res_r_m30_0 = 1
local res_r_m33_0 = ms.table_to_int(r_m33_0)
RESULT = res_r_m33_0 - res_r_m30_0 - res_r_func25_0 + res_r_m23_0 - res_r_func21_0 - res_r_func19_0 + res_r_m16_0 + res_r_m10_0 + res_datum9 + res_datum7 - res_datum5 + res_datum4 + res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))