--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:             70846779                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions ( 10 statements)         --
--------------------------------------------------------
local datum0 = "10"
datum1 = "9"
datum2 = {field3 = false}
datum4 = {field5 = false}
local datum6 = {field7 = 49.123490}
local datum8 = -48
local datum9 = {field10 = -37}
datum11 = {field12 = false}
local datum13 = {field14 = false}
datum15 = -4

--------------------------------------------------------
-- Function definitions (  7 functions)               --
--------------------------------------------------------
-- @return int
function datum11:m16()
  v47, v49, v51, v53 = datum0, true, false, "6"
  v55, v57, v59, v61 = 65, "2", true, "occaecat Excepteur nostrud"
  v47 = v47
  local cond63 = true
  while cond63 ~= true do
      v49 = true == false == not v49
      cond63 = false
  end
  if v49 ~= false then
      v49 = "sint culpa ex magna" == v47 ~= true ~= true == not false
  end
  for i=2,18,3 do
      v49 = "anim fugiat" == "amet incididunt non" == not false
      v47 = tostring(math.floor(9.484628e+01))
  end
  v47 = [[9]]
  return math.floor(v47 + 2) or - 53
end

-- @param a0 string
-- @param a1 int
-- @param a2 float
-- @param a3 boolean
-- @param a4 int
-- @return table
function datum4:m17(a0, a1, a2, a3, a4)
  local v64, v66, v68 = a0, "Ut", a4
  local v70, v72 = "tempor", "3"
  v74, v76 = a2, a3
  local cond78 = false
  repeat
      a0 = tostring(a1)
      cond78 = true
  until cond78 == true
  a0 = [[9]]
  for i, v in pairs(datum13) do
      a4 = -17 + -(#("nostrud occaecat do incididunt"))
      a2 = math.tan(8.348870e+01) + math.sin(0) - -(math.tan(48))
      a2 = math.abs(33) + math.abs(a1) - -(math.tan(135.288947))
  end
  if a2 >= -41.105909 then
      a2 = 5.244268e-01 + -(math.pi)
      v66 = "nostrud proident do"
  end
  return {t82 = a0}
end

-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @return function
function func23(a0, a1, a2)
  local v86, v88, v90, v92 = datum0, datum0, a2, a2
  local v94, v96, v98 = -5.250376, a1, a0
  for i=5,16,2 do
      v86 = tostring(-85)
      a0 = [[proident
non
magna]]
  end
  v86 = "5"
  for i, _ in ipairs(datum11) do
      a0 = "Lorem in dolore"
      v86 = a1
      v86 = tostring(math.floor(91.683218))
  end
  v86 = tostring(math.floor(66.585207))
  a1 = tostring(math.floor(1.015440))
  v88 = "5"
  return nil
end

-- @param a0 string
-- @param a1 string
-- @param a2 float
-- @param a3 float
-- @param a4 int
-- @return boolean
function datum13:m27(a0, a1, a2, a3, a4)
  local v102, v104 = 78.927550, -80
  v106, v108, v110, v112 = false, a2, true, "veniam irure aliquip"
  local cond114 = 122
  repeat
      v102 = math.sin(a2) + -(math.pi)
      cond114 = cond114 - 0x1
  until cond114 > 70
  a4 = -27 or -(#([[non]]))
  for i=16,0 do
      v102 = math.abs(a4) - math.cos(-9) + -(math.pi)
      v102 = math.pi - -(math.pi)
  end
  if a0 == [[culpa
nisi]] then
      a3 = math.pi + 99.276579 + -(math.tan(v104))
  else
      a4 = math.floor(19.952662) + -(string.len([[in
nostrud
voluptate]]))
  end
  local cond115 = true
  repeat
      a0 = "dolor fugiat"
      v102 = math.tan(a2) + math.pi - -(math.abs(v102))
      v102 = math.pi + math.pi + -(83.509281)
      cond115 = false
  until cond115 ~= true
  return "amet" == a0 == "minim velit" == a1 ~= true ~= false ~= true ~= false == not true
end

-- @param a0 string
-- @param a1 string
-- @return nil
function datum11:m33(a0, a1)
  local v116, v118, v120, v122 = true, [[laboris
ea]], 58, 17
  v124, v126, v128 = [[3]], 64.742385, -0x1.a6f958d719c31p+5
  local v130, v132 = v118, 43.944131
  if a0 == "irure et" then
      a1 = "ipsum"
  end
  v118 = "voluptate ea consequat"
  if a0 ~= "nulla nisi sunt" then
      v118 = a0
      v118 = "anim"
  end
  local cond138 = 105
  repeat
      v118 = "ullamco dolore cillum magna"
      a1 = v118
      cond138 = cond138 - 1
  until cond138 >= 51
  return "eu in" == a0 == "quis" ~= a1 ~= false ~= v116 ~= "pariatur eu culpa" == v118 ~= not true
end

-- @param a0 boolean
-- @param a1 boolean
-- @param a2 string
-- @param a3 string
-- @param a4 float
-- @return int
function func36(a0, a1, a2, a3, a4)
  local v141, v143, v145 = datum8, datum8, datum15
  v147, v149, v151, v153 = "Ut mollit ipsum occaecat", a4, datum8, -0x1.ace4bce351eb4p+5
  v155, v157 = -82.408000, a3
  a0 = true == not false
  for i, v in ipairs(datum4) do
      a2 = tostring(v141)
      a1 = true ~= not "ex pariatur tempor tempor" == a3
  end
  a2 = "6"
  a3 = a3
  if datum6 ~= {} then
      v143 = -9 - #("ex ut dolore") or - math.floor(37.599065)
      a1 = true ~= true == true ~= not true
  end
  a3 = "10"
  return 97 + -27 or math.floor(a2 + 2) or math.floor(a3 + 1) + math.floor(a4) + v141 or v143 + -(v145)
end

-- @param a0 string
-- @param a1 string
-- @param a2 string
-- @param a3 string
-- @return int
function func42(a0, a1, a2, a3)
  v162, v164 = datum15, true
  local v166, v168, v170 = a0, "Excepteur ipsum", v162
  local v172, v174, v176, v178 = true, false, "reprehenderit tempor dolore", true
  a2 = a2
  if v162 ~= 0x19 then
      a0 = [[5]]
  end
  a2 = "ea"
  a2 = a2
  return tonumber(a0) or string.len(a1) + string.len(a2) or #(a3) or v162 or 70 or -(tonumber(v166))
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local r_m16_0 = datum11:m16()
local m17_a0 = "1"
local m17_a1 = -33
local m17_a2 = 19.970027
local m17_a3 = false
local m17_a4 = -93
local r_m17_0 = datum4:m17(m17_a0, m17_a1, m17_a2, m17_a3, m17_a4)
local func23_a0 = "commodo Ut"
local func23_a1 = "9"
local func23_a2 = false
local r_func23_0 = func23(func23_a0, func23_a1, func23_a2)
local m27_a0 = "occaecat amet"
local m27_a1 = "2"
local m27_a2 = 1.439235e+01
local m27_a3 = 80.181673
local m27_a4 = 45
local r_m27_0 = datum13:m27(m27_a0, m27_a1, m27_a2, m27_a3, m27_a4)
local m33_a0 = "fugiat"
local m33_a1 = "Excepteur in in Excepteur"
local r_m33_0 = datum11:m33(m33_a0, m33_a1)
local func36_a0 = true
local func36_a1 = false
local func36_a2 = "2"
local func36_a3 = "2"
local func36_a4 = 30.352181
local r_func36_0 = func36(func36_a0, func36_a1, func36_a2, func36_a3, func36_a4)
local func42_a0 = "8"
local func42_a1 = "Excepteur ex in"
local func42_a2 = "dolore"
local func42_a3 = "quis officia voluptate"
local r_func42_0 = func42(func42_a0, func42_a1, func42_a2, func42_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = tonumber(datum0)
local res_datum1 = tonumber(datum1)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = #(datum6)
local res_datum8 = datum8
local res_datum9 = ms.table_to_int(datum9)
local res_datum11 = ms.table_to_int(datum11)
local res_datum13 = ms.table_to_int(datum13)
local res_datum15 = datum15
local res_r_m16_0 = r_m16_0
local res_r_m17_0 = ms.table_to_int(r_m17_0)
local res_r_func23_0 = 1
local res_r_m27_0 = r_m27_0 and 1 or 0
local res_r_m33_0 = 1
local res_r_func36_0 = r_func36_0
local res_r_func42_0 = r_func42_0
RESULT = res_r_func42_0 - res_r_func36_0 + res_r_m33_0 - res_r_m27_0 + res_r_func23_0 + res_r_m17_0 - res_r_m16_0 + res_datum15 + res_datum13 + res_datum11 + res_datum9 + res_datum8 - res_datum6 - res_datum4 - res_datum2 + res_datum1 - res_datum0
print(math.floor(RESULT))