--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            554809689                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  7 statements)         --
--------------------------------------------------------
datum0 = {field1 = 3.023374e+01}
local datum2 = {field3 = 145.322235}
local datum4 = 14
datum5 = {field6 = -82}
datum7 = true
datum8 = 81.425811
local datum9 = 47

--------------------------------------------------------
-- Function definitions (  8 functions)               --
--------------------------------------------------------
-- @param a0 string
-- @param a1 string
-- @return function
function datum2:m10(a0, a1)
  local v48, v50, v52 = datum9, "8", "officia sunt id"
  local v54, v56, v58 = -72.891729, datum4, "6"
  local v60, v62, v64 = "1", datum8, 76
  local cond66 = false
  repeat
      v52 = "cillum pariatur"
      v50 = [[3]]
      cond66 = true
  until cond66 ~= false
  a0 = "5"
  v50 = a0
  for i, v in pairs(datum0) do
      a1 = "7"
      a0 = "4"
      a0 = "3"
  end
  local cond71 = 106
  repeat
      a1 = "9"
      cond71 = cond71 - 2
  until cond71 > 0x49
  return nil
end

-- @param a0 string
-- @return boolean
function datum2:m13(a0)
  local v72, v74 = -11.593839, 95
  v76, v78, v80 = v72, datum4, datum8
  for _, v in pairs(datum0) do
      a0 = "6"
      a0 = "4"
      v72 = 86.780154 + -(math.pi)
  end
  if v74 >= -34 then
      v74 = 59 - -(0x4)
      v72 = math.sin(v74) + math.pi - -(math.pi)
  else
      v74 = 86 or tonumber(a0) or - 12
  end
  for i=1,0xD do
      v72 = math.tan(-62) + 7.932676 - -(math.pi)
  end
  local cond84 = 3
  while cond84 < 23 do
      v74 = math.floor(v72) + -(-87)
      a0 = tostring(math.floor(146.983471))
      cond84 = cond84 + 3
  end
  return "non consequat Ut" == a0 ~= true ~= not false
end

-- @param a0 float
-- @param a1 boolean
-- @param a2 float
-- @param a3 int
-- @param a4 boolean
-- @return string
function datum2:m15(a0, a1, a2, a3, a4)
  local v85, v87, v89, v91 = false, -0x1.a82f497dcb35p+3, a4, "2"
  local v93, v95, v97, v99 = 1, datum4, a3, a0
  local v101, v103, v105 = -43.204911, "ut mollit", v85
  for i=0,12 do
      a1 = false ~= false ~= false ~= not true ~= false
      v89 = true ~= false == true ~= true == not false
  end
  local cond107 = false
  while cond107 == true do
      a2 = math.abs(a2) - -(math.sin(29.720657))
      cond107 = true
  end
  a0 = math.tan(-41) - math.cos(68.805652) + -(0x1.7f3d02fe09aebp+5)
  if a2 <= -0x1.69d53c81b0fcp+5 then
      a2 = math.sin(a3) - -(math.pi)
  end
  return tostring(math.floor(a0))
end

-- @param a0 int
-- @param a1 int
-- @param a2 boolean
-- @param a3 boolean
-- @param a4 float
-- @return function
function func21(a0, a1, a2, a3, a4)
  local v108, v110, v112, v114 = "3", a0, "2", 19
  v116, v118, v120 = a1, datum9, "3"
  local v122, v124 = false, "1"
  if a1 > 0x47 then
      v108 = tostring(a0)
  else
      a1 = 40 + math.floor(v112 + 0x2) or -(math.floor(v112 + 3))
  end
  a1 = math.floor(103.089346) or a0 or - 4
  for i=10,5,2 do
      a3 = true ~= "amet sunt" ~= "sunt" == not true
      a2 = false == a3 ~= not true
      a1 = -33 - -(-95)
  end
  v110 = 96 or string.len("eu voluptate exercitation ex") - - v110
  return nil
end

-- @param a0 int
-- @param a1 string
-- @param a2 boolean
-- @param a3 string
-- @return boolean
function func27(a0, a1, a2, a3)
  local v126, v128 = datum7, "8"
  v130, v132, v134 = 38.029785, "velit do in", datum8
  v136, v138, v140 = datum7, true, a0
  for i=0x11,3,3 do
      a3 = "4"
      v130 = 3.494822e+01 + math.pi - -(23.227196)
  end
  local cond142 = false
  repeat
      a1 = "irure"
      a2 = "ex deserunt nulla sed" ~= "laborum consectetur qui" ~= false ~= not true
      cond142 = true
  until cond142 ~= false
  v128 = tostring(math.floor(v130))
  local cond144 = 0x7d
  repeat
      a0 = -24 or 12 - -(#("et magna officia"))
      a3 = "1"
      cond144 = cond144 - 0x2
  until cond144 > 74
  return true == "sint" == a1 ~= a2 == "velit occaecat officia" == a3 == true ~= v126 ~= "in non in" ~= v128 ~= not true
end

-- @param a0 string
-- @param a1 string
-- @param a2 boolean
-- @param a3 float
-- @param a4 string
-- @return string
function func32(a0, a1, a2, a3, a4)
  local v145, v147 = a3, datum9
  v149, v151 = "1", datum8
  for i, _ in pairs(datum5) do
      v147 = 55 or tonumber(a1) + -(string.len("velit"))
  end
  for i=4,13,0x2 do
      a3 = 9.634033e+00 - -(math.sin(192.602960))
      a2 = false ~= false == not false
  end
  v147 = math.floor(v145) + -24 + - tonumber(a0)
  v145 = 0x1.d8d8dbe7053f8p+5 + math.abs(-75) + -(math.abs(v147))
  if a0 == "4" then
      a1 = tostring(math.floor(a3))
      v147 = math.floor(104.893158) - tonumber(a1) or - math.floor(8.591486e+00)
  else
      a2 = a2 == false == not false
      a0 = "1"
      a3 = 29.147266 - -(math.pi)
  end
  if a4 ~= [[quis]] then
      a4 = [[voluptate
irure
dolore]]
      v145 = math.pi - -(math.pi)
  end
  return "in consectetur"
end

-- @param a0 boolean
-- @param a1 string
-- @param a2 int
-- @param a3 int
-- @return table
function datum0:m38(a0, a1, a2, a3)
  v156, v158 = "6", -7
  v160, v162 = "dolore Lorem nostrud", "3"
  for i, _ in ipairs(datum0) do
      a2 = math.floor(53.878815) or -(#("aliquip culpa"))
      v156 = tostring(math.floor(89.775287))
  end
  a1 = "7"
  v156 = "9"
  for i=0,16,0x3 do
      v156 = tostring(v158)
  end
  for _, _ in pairs(datum2) do
      a2 = 91 + string.len("irure sint nostrud") or -(a3)
  end
  a2 = 37 + -(math.floor(18.534363))
  return {t167 = a0}
end

-- @param a0 string
-- @param a1 float
-- @param a2 string
-- @param a3 boolean
-- @return string
function func43(a0, a1, a2, a3)
  v169, v171, v173, v175 = datum9, datum7, true, a2
  v177, v179 = [[cupidatat
occaecat
ea]], "1"
  local v181, v183 = v169, datum9
  if datum2 == {} then
      a3 = false == "incididunt adipiscing" ~= "esse est ea" == not "adipiscing eu et" == "non enim"
  end
  a2 = [[ex
consectetur
veniam
fugiat]]
  for i=0x5,14 do
      a1 = math.sin(-90) - -(math.tan(85.311025))
      a1 = math.pi + -(0.756857)
      a3 = false ~= true ~= "in qui" ~= a2 == not true
  end
  v173 = "reprehenderit nulla commodo" == a0 ~= not true
  local cond186 = 111
  while cond186 > 0x45 do
      a1 = math.abs(27.112789) - math.pi + -(math.pi)
      a2 = "Excepteur labore laborum dolore"
      cond186 = cond186 - 1
  end
  return a0
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m10_a0 = "10"
local m10_a1 = "4"
local r_m10_0 = datum2:m10(m10_a0, m10_a1)
local m13_a0 = "1"
local r_m13_0 = datum2:m13(m13_a0)
local m15_a0 = 0x1.89b142910158fp+6
local m15_a1 = true
local m15_a2 = 48.772381
local m15_a3 = -95
local m15_a4 = false
local r_m15_0 = datum2:m15(m15_a0, m15_a1, m15_a2, m15_a3, m15_a4)
local func21_a0 = 62
local func21_a1 = 0x26
local func21_a2 = true
local func21_a3 = true
local func21_a4 = 25.500678
local r_func21_0 = func21(func21_a0, func21_a1, func21_a2, func21_a3, func21_a4)
local func27_a0 = 73
local func27_a1 = "ut amet ea enim"
local func27_a2 = false
local func27_a3 = "8"
local r_func27_0 = func27(func27_a0, func27_a1, func27_a2, func27_a3)
local func32_a0 = "3"
local func32_a1 = "6"
local func32_a2 = true
local func32_a3 = 58.838274
local func32_a4 = "amet sint"
local r_func32_0 = func32(func32_a0, func32_a1, func32_a2, func32_a3, func32_a4)
local m38_a0 = false
local m38_a1 = "7"
local m38_a2 = -35
local m38_a3 = 13
local r_m38_0 = datum0:m38(m38_a0, m38_a1, m38_a2, m38_a3)
local func43_a0 = "10"
local func43_a1 = 77.612290
local func43_a2 = "incididunt labore"
local func43_a3 = true
local r_func43_0 = func43(func43_a0, func43_a1, func43_a2, func43_a3)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = #(datum0)
local res_datum2 = ms.table_to_int(datum2)
local res_datum4 = datum4
local res_datum5 = ms.table_to_int(datum5)
local res_datum7 = datum7 and 1 or 0
local res_datum8 = math.floor(datum8)
local res_datum9 = datum9
local res_r_m10_0 = 1
local res_r_m13_0 = r_m13_0 and 1 or 0
local res_r_m15_0 = tonumber(r_m15_0)
local res_r_func21_0 = 1
local res_r_func27_0 = r_func27_0 and 1 or 0
local res_r_func32_0 = string.len(r_func32_0)
local res_r_m38_0 = ms.table_to_int(r_m38_0)
local res_r_func43_0 = tonumber(r_func43_0)
RESULT = res_r_func43_0 + res_r_m38_0 + res_r_func32_0 - res_r_func27_0 - res_r_func21_0 - res_r_m15_0 - res_r_m13_0 + res_r_m10_0 + res_datum9 - res_datum8 + res_datum7 + res_datum5 + res_datum4 + res_datum2 + res_datum0
print(math.floor(RESULT))