--------------------------------------------------------
-- This code was automatically generated by moonsmith --
-- https://github.com/jubnzv/moonsmith                --
--                                                    --
-- Seed:            850903026                         --
--------------------------------------------------------

--------------------------------------------------------
-- Utility functions.                                 --
--------------------------------------------------------
ms = {}

-- Generates a random integer for an arbitrary table.
-- @param t table
function ms.table_to_int(t)
  acc = 0
  for i, v in ipairs(t) do
    if type(v) == "number" then
      acc = acc + v
    else
      acc = acc - i
    end
  end
  return acc + #t
end

--------------------------------------------------------
-- Global datums definitions (  6 statements)         --
--------------------------------------------------------
local datum0 = {field1 = false}
datum2 = {field3 = "adipiscing nostrud deserunt"}
local datum4 = {field5 = [[occaecat
sed
exercitation]]}
local datum6 = {field7 = 19.713947}
local datum8 = 1.649450
datum9 = false

--------------------------------------------------------
-- Function definitions (  5 functions)               --
--------------------------------------------------------
-- @param a0 float
-- @param a1 int
-- @return float
function datum6:m10(a0, a1)
  v24, v26 = datum9, a1
  v28, v30, v32 = true, 0x2f, "4"
  local v34, v36 = "nostrud Duis", "1"
  for _, _ in ipairs(datum2) do
      a0 = math.cos(-97) - -(math.pi)
      v28 = false == not false
  end
  for i=14,5,3 do
      v24 = true ~= not false
  end
  local cond39 = false
  repeat
      v26 = 93 or - 0xA
      a1 = #("in reprehenderit officia adipiscing") or -(string.len("voluptate cupidatat nostrud"))
      v24 = false ~= true == not false
      cond39 = true
  until cond39 == true
  return math.tan(a0) - math.sin(a1) + math.pi + math.tan(v26) + -(math.pi)
end

-- @return string
function func13()
  local v40, v42 = -57, -96.669361
  local v44, v46, v48 = "2", datum9, 60
  local v50, v52, v54 = "3", "3", "3"
  local cond56 = 117
  repeat
      v42 = math.abs(v40) - 0x1.37a803b1b9a59p+6 - -(56.582338)
      v44 = tostring(math.floor(1.577120))
      cond56 = cond56 - 1
  until cond56 >= 71
  local cond57 = 1
  while cond57 < 0x26 do
      v44 = v44
      cond57 = cond57 + 2
  end
  for _, _ in ipairs(datum4) do
      v44 = "6"
      v40 = -82 + 16 or -(tonumber(v44))
      v44 = v44
  end
  return tostring(v40)
end

-- @param a0 int
-- @param a1 boolean
-- @param a2 float
-- @param a3 float
-- @return int
local func14 = function (a0, a1, a2, a3)
  v59, v61, v63, v65 = "5", "Ut", a1, "4"
  local v67, v69, v71 = v59, "1", "8"
  for i, _ in pairs(datum4) do
      a1 = false == true ~= not a1
  end
  for _, v in ipairs(datum2) do
      a2 = 25.711084 - -(math.sin(0x1.3a934560acefbp+6))
  end
  if a3 <= -54.786180 then
      v59 = tostring(math.floor(a3))
      a2 = math.pi - -(math.tan(112.670996))
  end
  for i=18,1,2 do
      a3 = math.pi + math.sin(197.460634) + -(math.sin(a0))
      v61 = [[enim
in
consequat]]
      a3 = math.cos(0x4B) + math.pi - -(math.pi)
  end
  return a0 + -80 - math.floor(a2) + math.floor(a3) - math.floor(v59 + 2) + - string.len(v61)
end

-- @param a0 string
-- @param a1 int
-- @return string
local func19 = function (a0, a1)
  local v77, v79 = false, true
  local v81, v83, v85, v87 = 8.649859e+01, v77, "in", "Ut labore"
  local v89, v91 = -29, datum9
  v81 = 85.124518 - math.cos(0x1.7c9d6e4922588p+7) - -(0x1.43e80d64f9c43p+6)
  local cond93 = 8
  repeat
      v79 = true ~= not true == v77
      v77 = "proident" ~= "eu ipsum commodo" == not false ~= v79
      a0 = a0
      cond93 = cond93 + 2
  until cond93 <= 36
  v81 = 24.161216 - -(math.pi)
  for i=0x1,0x11,2 do
      a1 = math.floor(v81) or 84 + - math.floor(4.996004e+01)
  end
  return a0
end

-- @param a0 string
-- @return nil
function datum2:m22(a0)
  v94, v96, v98 = "Excepteur consequat magna nisi", -90, true
  local v100, v102 = -13.947473, datum9
  local v104, v106, v108, v110 = -73.878473, "5", "10", datum9
  v98 = "anim laboris" == [[labore
mollit
ad]] == not true
  v96 = math.floor(a0 + 3) or - v96
  if a0 == "3" then
      a0 = tostring(math.floor(84.727137))
      v96 = v96 + 0x49 + - v96
      v98 = false == not true
  end
  local cond112 = 9
  while cond112 < 39 do
      v96 = v96 - -(math.floor(1.488768e+01))
      cond112 = cond112 + 1
  end
  return [[dolor
est
culpa
in]] == a0 ~= "dolor quis nulla" == v94 ~= true ~= not true ~= v98
end

--------------------------------------------------------
-- Calling functions                                  --
--------------------------------------------------------
local m10_a0 = 60.302729
local m10_a1 = -63
local r_m10_0 = datum6:m10(m10_a0, m10_a1)
local r_func13_0 = func13()
local func14_a0 = 0x46
local func14_a1 = false
local func14_a2 = 8.825376
local func14_a3 = 0x1.0810a18c56c3ep-1
local r_func14_0 = func14(func14_a0, func14_a1, func14_a2, func14_a3)
local func19_a0 = "4"
local func19_a1 = -52
local r_func19_0 = func19(func19_a0, func19_a1)
local m22_a0 = "4"
local r_m22_0 = datum2:m22(m22_a0)

--------------------------------------------------------
-- Combining and printing result                      --
--------------------------------------------------------
local res_datum0 = ms.table_to_int(datum0)
local res_datum2 = #(datum2)
local res_datum4 = #(datum4)
local res_datum6 = #(datum6)
local res_datum8 = math.floor(datum8)
local res_datum9 = datum9 and 1 or 0
local res_r_m10_0 = math.floor(r_m10_0)
local res_r_func13_0 = tonumber(r_func13_0)
local res_r_func14_0 = r_func14_0
local res_r_func19_0 = math.floor(r_func19_0 + 2)
local res_r_m22_0 = 0x1
RESULT = res_r_m22_0 - res_r_func19_0 - res_r_func14_0 + res_r_func13_0 + res_r_m10_0 - res_datum9 + res_datum8 + res_datum6 + res_datum4 - res_datum2 + res_datum0
print(math.floor(RESULT))